### ISSUE TITLE
Documentation clarification for "Run Bosch Scan from Command Line" Section Arch

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#102]
**Describe the bug**
Section Arch does not work as described due to pacman not being installed

**To Reproduce**
1. Fresh install of WSL on Windows 11 with Ubuntu 20.04 LTS
2. Follow instructions to install software common, deadsnakes and VENV for UBUNTU
3. In section Arch, there is the command pacman -S python. This leads to return  "Command 'pacman' not found, but can be installed with:"

**Version**
- Windows 11 WSL, Ubuntu 20.04 LTS
- 
**Additional context**
Is the section Arch only applicable, if Arch Linux is used? 

As the documentation refers to Ubuntu as basis for the documentation, I'd suggest to remove it or place it with an explicit statement that the Arch section is needed for Arch Linux only.

**Comment by pszafer** [comment]
Yes, it's Arch Linux only. Added extra info to section.
