### ISSUE TITLE
"pip3.8 install bosch-thermostat-client" fails to build aioxmpp pyaes aioopenssl aiosasl 

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#103]
**Describe the bug**
Following  the installation guide "Run Bosch Scan from Command Line" the packages  aioxmpp pyaes aioopenssl aiosasl fail to build during "pip3.8 install bosch-thermostat-client"

**To Reproduce**
1. Fresh WSL and VENV environment created
2. Run pip3.8 install bosch-thermostat-client

**Expected behavior**
No errors are reported

**Error log (short)**
Building wheels for collected packages: aioxmpp, pyaes, aioopenssl, aiosasl
 ... more details below ...
Failed to build aioxmpp pyaes aioopenssl aiosasl

**Version**
  - HA version?  Not Applicable
  - HA Bosch component version? Not applicable
  - Python Bosch HTTP client version? bosch_thermostat_client-0.16.2-py3-none-any.whl
  - Windows 11 WSL with Ubuntu 20.04 LTS

**Additional Comments**
bosch_cli scan runs however, but reports several errors namely: 
INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /recordings
INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 400 Bad Request', 'Seq-No: 0', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']

######################################################
** Install log output**
######################################################

(venv) webeling@Base:~/bosch$ pip3.8 install bosch-thermostat-client
Collecting bosch-thermostat-client
  Downloading bosch_thermostat_client-0.16.2-py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 1.8 MB/s
Collecting aioxmpp>=0.12.2
  Downloading aioxmpp-0.12.2.tar.gz (386 kB)
     |████████████████████████████████| 386 kB 12.7 MB/s
Collecting click>=8
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 6.3 MB/s
Collecting colorlog
  Downloading colorlog-6.5.0-py2.py3-none-any.whl (11 kB)
Collecting pyaes>=1.6.1
  Downloading pyaes-1.6.1.tar.gz (28 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 11.6 MB/s
Collecting aioopenssl>=0.1
  Downloading aioopenssl-0.6.0.tar.gz (15 kB)
Collecting aiosasl>=0.3
  Downloading aiosasl-0.5.0.tar.gz (28 kB)
Collecting babel~=2.3
  Downloading Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 10.8 MB/s
Collecting dnspython<3.0,>=1.0
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 9.6 MB/s
Collecting lxml~=4.0
  Downloading lxml-4.6.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 11.2 MB/s
Collecting multidict<6,>=2.0
  Downloading multidict-5.2.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (187 kB)
     |████████████████████████████████| 187 kB 10.7 MB/s
Collecting pyOpenSSL
  Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.1 MB/s
Collecting pyasn1
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 6.5 MB/s
Collecting pyasn1_modules
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 12.2 MB/s
Collecting sortedcollections~=2.1
  Downloading sortedcollections-2.1.0-py3-none-any.whl (9.5 kB)
Collecting tzlocal<3,>=1.2
  Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.0-py3-none-any.whl (6.1 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.2.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (210 kB)
     |████████████████████████████████| 210 kB 11.1 MB/s
Collecting attrs>=17.3.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.9 MB/s
Collecting charset-normalizer<3.0,>=2.0
  Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)
     |████████████████████████████████| 308 kB 12.7 MB/s
Collecting pytz>=2015.7
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 14.7 MB/s
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cryptography>=3.3
  Downloading cryptography-35.0.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 11.6 MB/s
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting idna>=2.0
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 6.6 MB/s
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
     |████████████████████████████████| 446 kB 12.9 MB/s
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 12.0 MB/s
Building wheels for collected packages: aioxmpp, pyaes, aioopenssl, aiosasl
  Building wheel for aioxmpp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webeling/bosch/venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tjc566de/aioxmpp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tjc566de/aioxmpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4swspr_4
       cwd: /tmp/pip-install-tjc566de/aioxmpp/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for aioxmpp
  Running setup.py clean for aioxmpp
  Building wheel for pyaes (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webeling/bosch/venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tjc566de/pyaes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tjc566de/pyaes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-eue986eu
       cwd: /tmp/pip-install-tjc566de/pyaes/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyaes
  Running setup.py clean for pyaes
  Building wheel for aioopenssl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webeling/bosch/venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tjc566de/aioopenssl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tjc566de/aioopenssl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m6ar_5ro
       cwd: /tmp/pip-install-tjc566de/aioopenssl/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for aioopenssl
  Running setup.py clean for aioopenssl
  Building wheel for aiosasl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/webeling/bosch/venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tjc566de/aiosasl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tjc566de/aiosasl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m5b55l7e
       cwd: /tmp/pip-install-tjc566de/aiosasl/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for aiosasl
  Running setup.py clean for aiosasl
Failed to build aioxmpp pyaes aioopenssl aiosasl
Installing collected packages: six, pycparser, cffi, cryptography, pyOpenSSL, aioopenssl, aiosasl, pytz, babel, dnspython, lxml, multidict, pyasn1, pyasn1-modules, sortedcontainers, sortedcollections, tzlocal, aioxmpp, click, colorlog, pyaes, frozenlist, aiosignal, typing-extensions, async-timeout, attrs, charset-normalizer, idna, yarl, aiohttp, bosch-thermostat-client
    Running setup.py install for aioopenssl ... done
    Running setup.py install for aiosasl ... done
    Running setup.py install for aioxmpp ... done
    Running setup.py install for pyaes ... done
Successfully installed aiohttp-3.8.0 aioopenssl-0.6.0 aiosasl-0.5.0 aiosignal-1.2.0 aioxmpp-0.12.2 async-timeout-4.0.0 attrs-21.2.0 babel-2.9.1 bosch-thermostat-client-0.16.2 cffi-1.15.0 charset-normalizer-2.0.7 click-8.0.3 colorlog-6.5.0 cryptography-35.0.0 dnspython-2.1.0 frozenlist-1.2.0 idna-3.3 lxml-4.6.4 multidict-5.2.0 pyOpenSSL-21.0.0 pyaes-1.6.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pytz-2021.3 six-1.16.0 sortedcollections-2.1.0 sortedcontainers-2.4.0 typing-extensions-3.10.0.2 tzlocal-2.1 yarl-1.7.2

**Comment by pszafer** [comment]
can you try installing this in your venv before run:
```
pip3 install wheel
```

**Comment by webeling67** [comment]
That worked, I'll update the wiki page accordingly
