### ISSUE TITLE
Special character $ in EasyControl password breaks integration in HA

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#104]
**Describe the bug**
Using a EasyControl password with the special character $ prevents the detection of the sensors connected to the CT200

**To Reproduce**
1. Set EasyControl password to something$
2. Add integration to HA and enter UUID, Token and the something$ password
3. HA will report the CT200 but will not show the sensors

**Expected behavior**
Sensors should be visible

**Screenshots**

**Version**
  - HA version: 2021.11.1
  - HA Bosch component version? unknown
  - Python Bosch HTTP client version? unknown

** Debug SCAN **
Not available

**Additional context**
Needs additional debug data, but I would need guidance who to fetch it

**Comment by pszafer** [comment]
I don't know why for some users special character is deal breaker and for some password longer than >8 chars make Bosch XMPP server to return empty json responses. I'm closing this issue. If you want to further test it and get some meaningful info for other (which we can put in README/wiki) it would be great.
