### ISSUE TITLE
Document Raw Scan from within Home Assistant

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#106]
**Is your feature request related to a problem? Please describe.**
Provide a guide how to do raw scan within HA

**Describe the solution you'd like**
Extend the current raw scan documentation

**Describe alternatives you've considered**
Create a new page, decided against it as I would like to reduce clutter in the Wiki navigator

PIctures to be used for the documentation
<img width="836" alt="Rawscan14" src="https://user-images.githubusercontent.com/61348455/141646672-55a8c1d6-86d1-47ce-99dc-0fd666784d31.png">
<img width="832" alt="Rawscan15" src="https://user-images.githubusercontent.com/61348455/141646673-e04da082-55ff-460b-bdf6-b4453a095ecb.png">
<img width="822" alt="Rawscan16" src="https://user-images.githubusercontent.com/61348455/141646675-3f01514f-84ea-49ff-8d10-6a8d4f94c047.png">
<img width="821" alt="Rawscan10" src="https://user-images.githubusercontent.com/61348455/141646676-5c99548c-0037-41ca-987d-83a26d3266ab.png">
<img width="835" alt="Rawscan11" src="https://user-images.githubusercontent.com/61348455/141646677-77814481-58f9-41a3-a69b-95a1aa7c2427.png">
<img width="835" alt="Rawscan12" src="https://user-images.githubusercontent.com/61348455/141646678-8267c413-82af-421e-a5ae-1a2f1f917ee2.png">
<img width="811" alt="Rawscan13" src="https://user-images.githubusercontent.com/61348455/141646680-4527c349-2696-423c-82fb-2c3c78f43dab.png">
<img width="840" alt="Rawscan17" src="https://user-images.githubusercontent.com/61348455/141647289-a39051c7-4271-4c37-be70-6a3a277f8446.png">
.

**Comment by webeling67** [comment]
Done within https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices

**Comment by pszafer** [comment]
Nice, thanks!
