### ISSUE TITLE
No Custom Bosch Integration in the HA integration list

### ISSUE THREAD

**Issue by damiano75** [bosch-thermostat/home-assistant-bosch-custom-component#109]
**Describe the bug**
Even if I have installed the custom integration by HACS, in the add integration list in HA there is only the BOSCH SHC integration

**Screenshots**

![image](https://user-images.githubusercontent.com/47896789/141765381-e2b53519-6b8a-47e1-b0c9-fa73316c6731.png)
![image](https://user-images.githubusercontent.com/47896789/141765458-b34ca9d9-aa31-4aea-a0d3-a90cfac63bbf.png)

**Version**
  - HA version core-2021.11.3
  - HA Bosch component version v0.16.4

**Comment by webeling67** [comment]
Please clear the cache in the browser and restart the core. https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Installation-Guide#install-integration

**Comment by damiano75** [comment]
Solved, thank you
