### ISSUE TITLE
Wiki documentation on the use of the services

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#110]
**Is your feature request related to a problem? Please describe.**
The integration provides some services, but they are not completely documented

**Describe the solution you'd like**
Create a wiki page to document the usage as Home Assistant Services

**Additional context**
Pictures for the documentation will follow

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Bosch-Services-in-Home-Assistant
