### ISSUE TITLE
Buderus u052-28 with external boiler and Buderus TC100

### ISSUE THREAD

**Issue by pr0phe** [bosch-thermostat/home-assistant-bosch-custom-component#111]
Hi there, thanks for yr work, its really great.
Its almost all that i want from my buderus.
At all i need to set a temp (to turn on and turn off the heaters) - it done, and also i need to turn on|off hotwater and two binary sensors: hotwater heatin on|off, flame is on|off.
That functions exist in buderus easy controll mobile app, but non in intergration.
Ive made two scans as per yr instructions. Could you help with that?

[scans.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7610589/scans.zip)

**Comment by pszafer** [comment]
I assume you don't see heating water in water heater entity attributes?
If no, I need more scans unfortunately. 2 scans for each function would be ideal.

For hot water, and hot water heating:
- 1st scan when hot water is offf
- 2nd scan when hot water is on

Flame is on:
- 1st scan when flame is off
- 2nd scan when flame is on.

**Comment by pr0phe** [comment]
[bosch_2.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7613550/bosch_2.zip)

**Comment by pszafer** [comment]
so my thoughts about those scans:
- hot water on/off -> water_heater - if `dhwOperationState` is off then show operation mode of heater as off (not eco as read by `dhwOperationMode`)
- for flame off/on -> I think you can turn on sensor `/system/appliance/actualPower` and make template sensor of it. Something like this (I can't find flame status anywhere):
```
    - name: "Flame status"
      unique_id: bosch_flame_status
      state: >
        {% if states('sensor.actualPower') | float(default=0) > 0 %}
           {% if  state_attr('sensor.actualPower, 'reason') == "CH" %}
               flame for central heating
            {% else %}
                flame for hot water %}
           {% endif %}
         {% endif %}
```
- I could add merged sensors: `/system/appliance/causecode`, `/system/appliance/displaycode` and show display status, but somebody would need to translate this file for me to English - https://github.com/robertklep/nefit-easy-commands/blob/a007360b4885c555a28dc04b729bfe954a13f0a5/lib/data/display-codes.json

**Comment by pr0phe** [comment]
with flame status - it logic =) i think about after post an issue,
but in total - im not able to turn on and off that hot water. its the most problem, cause Water heater dhwA group doesnt have switch or toggle for that function.

**Comment by pr0phe** [comment]
[display-codes.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7639789/display-codes.txt)
Guys from bbqkees helped with translate

**Comment by pr0phe** [comment]
How to add toggle switch to turn dhwA on and off?

**Comment by pszafer** [comment]
sorry, I haven't had enough time to work on it yet

**Comment by przemoc86** [comment]
Hello @pszafer - I'm also patiently wait for hot water switch :) Thanks in advance ;)
Donation will be made in few minutes BTW :)

**Comment by pszafer** [comment]
@przemoc86 can you describe your setup?
Do you have tank for hot water?

**Comment by pr0phe** [comment]
> sorry, I haven't had enough time to work on it yet

Upto now?) Pls help me to make an on/off toggle for hw.

**Comment by pszafer** [comment]
in progress https://github.com/orgs/bosch-thermostat/projects/1 . I have to fix some issues in HA Core to push new version forward :/

**Comment by pr0phe** [comment]
Great news

**Comment by przemoc86** [comment]
> can you make one scan when you are in `ON mode` and switch to `auto`?

In attachment JSON with ON and JSON with AUTO
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8500744/bosch_scan.zip)

it seems that there are 3 differences beside timestamps and temp values etc.

**Comment by pszafer** [comment]
if you choose manual in HA then is manual set to `on` in interface?

**Comment by pr0phe** [comment]
Ive checked, if i change dwha to clock, sensor states "off" andd in a few minutes became manual again, i tryed to switch modes manual|clock and nothing happens with dwha. 
In easycontrol there are two possible ways to control hw, front panel has basic switch manual|clock switch, and also via options menu which has a little more options: manual mode has on|off switch when active, clock mode has a few preinstalled programs and user program.

**Comment by pszafer** [comment]
can you make 2 more scans in that case. Both in manual mode -> one with switch `off`, one with `on`

**Comment by pr0phe** [comment]
shure, but not today, im in city for few days, ill make it on saturday
