### ISSUE TITLE
Entities not available after HA restart

### ISSUE THREAD

**Issue by itepe** [bosch-thermostat/home-assistant-bosch-custom-component#112]
**Describe the bug**
After HA restarting Bosch sensor entities unavailable. This problem occurring always after  restart. Not possible re-read integration, only adding integration again resolve problem.

**To Reproduce**
1. Add Bosch integration to HA
2. Set entities tab
3.  check data values in entities
4. Restart Home Assistant
5. Entities not available

**Expected behavior**
After HA restart, entities will available again.

**Screenshots**
![image](https://user-images.githubusercontent.com/29843317/143844667-5755897f-fb47-4f53-861f-26123f927799.png)

**Version**
  - core-2021.11.5
  - HA Bosch component version - latest
  - Bosch module RC300 04.07.07

**Comment by pszafer** [comment]
Provide some debug logs from HA. After restart of HA can you ping address of your gateway, is it available?

**Comment by itepe** [comment]
> Provide some debug logs from HA. After restart of HA can you ping address of your gateway, is it available?

Yes, device is available from HA device (docker), ping answer normally.
I've log, but I don't want to publish with my device and HA sensitive data ;)

**Comment by pszafer** [comment]
so filter out sensitive data. Without logs it's impossible to even try to help you resolve problem with your HA.

**Comment by itepe** [comment]
> Provide some debug logs from HA. After restart of HA can you ping address of your gateway, is it available
Ok, attached debug_scan.
[debug_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7618524/debug_scan.txt)

**Comment by pszafer** [comment]
scan won't help here. I need to see logs while component is starting and maybe I can find what's wrong.

**Comment by itepe** [comment]
OK, which exactly log you need? I have not more than debug_scan or screenshot like 1st post :(

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#home-assistant-debugging-log

**Comment by itepe** [comment]
Let me check ;)
[Bosch_RC300_debug_log.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7624337/Bosch_RC300_debug_log.txt)
)

**Comment by pszafer** [comment]
what is your hardware for HA? I think there is something wrong with your network/HA.
I'd run HA in some regular PC with docker/python venv and check if problem exists in other hardware.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices#using-linux

**Comment by itepe** [comment]
I've HP T520, 4GB RAM with Ubuntu 20.04 LTS on docker. Additionally I'm use some other docker applications (UNIFI, UNMS), but it have not influence to HA (nothing changes after stopping).
OK, let's summarize:
- component (integration) not started after HA restart automatically
- component starts correct after disable/enable integration
It is OK for me, but a little cumbersome ;)

Thank you for support!

**Comment by itepe** [comment]
Case closed.
