### ISSUE TITLE
Integration don’t work | RC300

### ISSUE THREAD

**Issue by bitdevil007** [bosch-thermostat/home-assistant-bosch-custom-component#113]
The integration doesn‘t work  :-(

Home Assistant Version: 2021.11.5
Bosch thermostat: 0.16.06

IVT
RC300
Firmware: 04.07.07

——————————————————

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:258 
Integration: Bosch thermostat (documentation, issues) 
First occurred: 18:01:32 (1 occurrences) 
Last logged: 18:01:32

Cannot connect to Bosch gateway, host 192.168.1.191 with UUID: 306071522

——————————————————

Logger: bosch_thermostat_client.gateway.ivt
Source: /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/ivt.py:98 
First occurred: 18:01:32 (1 occurrences) 
Last logged: 18:01:32

I cannot find supported device. Your devices: null

**Comment by pszafer** [comment]
can you make bosch scan?

**Comment by bitdevil007** [comment]
How can i do it?
