### ISSUE TITLE
Documentation Update for Installation

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#115]
**Describe the bug**
Missing steps in the installation documentation, namely the need to download the repo in HACS.

**To Reproduce**
Support request in Discord identified the incompleteness

**Expected behavior**
Installation guide works also for fresh installs

**Version**
  - Wiki as published on Dec 14th 2021

**Comment by webeling67** [comment]
First fix is in. Need to add screenshots and follow up screens that changed in 2021.12

**Comment by webeling67** [comment]
![Hacs About](https://user-images.githubusercontent.com/61348455/146352621-ed5a66cd-6727-469e-b98d-e583861a3e97.png)

**Comment by webeling67** [comment]
![Hacs Find Integration](https://user-images.githubusercontent.com/61348455/146353616-a8be0ce2-ff96-41bd-bee5-2e3bf8957421.png)

**Comment by webeling67** [comment]
![HACS Download Repo](https://user-images.githubusercontent.com/61348455/146354235-3ba34b74-e979-4ffb-b0f0-589789cbe618.png)

**Comment by webeling67** [comment]
![install integration](https://user-images.githubusercontent.com/61348455/146355118-83245bdf-ba17-4d59-a71f-5a251f4c14a2.png)
![ha search Bosch](https://user-images.githubusercontent.com/61348455/146355123-d90700b7-f63d-4047-8e46-08246f800b97.png)

**Comment by webeling67** [comment]
Updated completed

**Comment by pszafer** [comment]
great 👍
