### ISSUE TITLE
energy consumption miscalculation

### ISSUE THREAD

**Issue by bmaciag** [bosch-thermostat/home-assistant-bosch-custom-component#116]
**Describe the bug**
I use the solution with HA and my Junkers heater. First of all thank you for the greak work to bring it to live. But the value shown in energy consumption must be wrong. Its way to high and does not match to any value which my Junkers does show. Any Idea what this could be?

**Expected behavior**
Show one value from the Screenshots below.

**Screenshots**
Value in HA:
![image](https://user-images.githubusercontent.com/26123384/146510026-ec0901a4-6837-4c36-aece-f5cdf546a59c.png)
Values on the Junkers:
![image](https://user-images.githubusercontent.com/26123384/146510209-cfceb525-d695-4e57-bc94-2391cba81733.png)
![image](https://user-images.githubusercontent.com/26123384/146510238-4aa4a61a-cfd4-41ff-b2c5-09e491b1cb92.png)
![image](https://user-images.githubusercontent.com/26123384/146510272-3d69b48e-9489-4834-b04b-b6f814e3813d.png)

**Version**
  - HA version?
    - core-2021.12.2
    - supervisor-2021.12.2
    - Home Assistant OS 7.0
  - HA Bosch component version? v0.16.7
  - Python Bosch HTTP client version? python3.9

** Debug SCAN **
[http://jsonblob.com/922406607120515072](http://jsonblob.com/922406607120515072)

**Comment by pszafer** [comment]
Please provide versions of all components you are using. Latest is not good enough.
And I need your bosch scan as well

**Comment by bmaciag** [comment]
Hi @pszafer
how to get the "Python Bosch HTTP client version"?
I'm running the debug_scan for "sensor.energy_consumption" but nothing happens.

**Comment by pszafer** [comment]
look into logs.
For client version it will show at HA startup in logs.
Same for debug scan, logs will show a link to it after minut or two.

**Comment by webeling67** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices might help to get the raw-scan

**Comment by bmaciag** [comment]
Hi guys, thanks for your support, I updated my issue.

**Comment by pszafer** [comment]
@bmaciag I don't know why device is showing such values, but component is displaying properly
```json
{
      "id": "/heatSources/energyMonitoring/consumption",
      "type": "floatValue",
      "writeable": 1,
      "recordable": 0,
      "value": 58663304,
      "unitOfMeasure": "kWh",
      "minValue": 0,
      "maxValue": 135780000
    },
```

I have same issue and I switched to "observe" recordings sensors only as those are still pretty reliable but one hour shifted.
