### ISSUE TITLE
CT200: unsuported firmware version 03.10.00

### ISSUE THREAD

**Issue by dukicn** [bosch-thermostat/home-assistant-bosch-custom-component#117]
My CT200 upgraded the firmware to 03.10.00 and integration with home assistant doesn't work anymore with the error: 

There are problems with config of your thermostat.
You might have unsupported firmware version 03.10.00.

Home Assistant Version:  2022.2.0.dev20211223

[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7771431/bosch_scan.txt)

**Comment by incama** [comment]
Same here.

**Comment by tomvanswam** [comment]
Same here
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7772973/bosch_scan.json.txt)

What do you have to do to update the component to the new firmware (in this or the bosch-thermostat-client-python repo)? As I wouldn't mind creating a PR to help when I have the time.

**Comment by motechsolutions** [comment]
Same here

**Comment by olesj33** [comment]
Same here

**Comment by robsnoek** [comment]
same here

**Comment by damiano75** [comment]
Same here

[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7773888/bosch_scan.zip)

**Comment by SteGe88** [comment]
Same here unfortunately

**Comment by pszafer** [comment]
Check pre-release - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.16.8
I haven't checked it as I don't have time during Christmas preparation, so hope it would work. Let me know

**Comment by webeling67** [comment]
Pre Release https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.16.8 is done for Christmas. Works on my installation. You need to reload the repository in HACS and enable beta releases, if you want to try.

**Comment by robsnoek** [comment]
pre release works for me
thanks

**Comment by incama** [comment]
Yes it works! Thanks a lot!

**Comment by motechsolutions** [comment]
Works for me as well, thank you for the fast update

**Comment by pszafer** [comment]
ok, released as stable.

**Comment by dukicn** [comment]
Works for me as well. Thanks for a very fast update.

**Comment by olesj33** [comment]
Works here, thanks for quick response

**Comment by SteGe88** [comment]
Wouw, what a stunning fast solution! Thanks @pszafer! Have a merry Christmas!
