### ISSUE TITLE
Could you make this an official integration?

### ISSUE THREAD

**Issue by HAuser2019** [bosch-thermostat/home-assistant-bosch-custom-component#118]
**Is your feature request related to a problem? Please describe.**
Yes we want this intergration to be officially supported by Home Assistant.

**Describe the solution you'd like**
Could you please make this an official integration. So more people can enjoy.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**

**Comment by pszafer** [comment]
So not really. There are several problems to convert this integration to official.
- first one is time, I'd need at least 100-200 hours to make this good enough to make PR to HA and I don't have enough time to work on that
- fast response for bosch updates - bosch push updates once in a while, I have to manually see scan of the device and analyze what they changed, it takes time, but recently it takes about 2-3 hours per update, so let's say one day. With official integration it would take 2-3 hours, review and you'd need for next update of HA (it could be day, it could be a week). I'm thinking how to provide "device description" via internet so if bosch push update then you don't need to update integration and restart HA, but just would need to fetch new "device description". But again I doubt HA Core devs would allow for such feature.

If there is someone who is willing to help me with polishing integration then I could consider to make this official integration.

**Comment by HAuser2019** [comment]
Geeze does it take so much time to make it official! Well HACS it is then for now.
