### ISSUE TITLE
KM200 - Your device is unknown null

### ISSUE THREAD

**Issue by Unimatrix8472** [bosch-thermostat/home-assistant-bosch-custom-component#119]
Hey,

I wanted to integrate my KM200 (firmware 1.10.03) into the Home Assistant. Unfortunately I always get an error message that the device is unknown.

> (homeassistant) homeassistant@raspberrypi:/srv/homeassistant $ bosch_cli scan --host=BuderusKM200.fritz.box --token=.....--password=.....--protocol=HTTP --device=IVT
> 2021-12-28 10:44:48 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: [{"Tok": "8", "Id": "64", "Ver": "02.07", "No": "3630302E3333334143303533303031363900000000000000000000"}, {"Tok": "16", "Id": "67", "Ver": "NF02.08", "No": "630240671152090160060000000000000000000000000000000000"}]
> Traceback (most recent call last):
>   File "/srv/homeassistant/bin/bosch_cli", line 8, in <module>
>     sys.exit(cli())
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/srv/homeassistant/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/srv/homeassistant/lib/python3.9/site-packages/bosch_thermostat_client/bosch_cli.py", line 79, in wrapper
>     return asyncio.run(f(*args, **kwargs))
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/srv/homeassistant/lib/python3.9/site-packages/bosch_thermostat_client/bosch_cli.py", line 234, in scan
>     connected = True if ignore_unknown else await gateway.check_connection()
>   File "/srv/homeassistant/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 307, in check_connection
>     await self.initialize()
>   File "/srv/homeassistant/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 90, in initialize
>     raise UnknownDevice("Your device is unknown %s" % json.dumps(self._device))
> bosch_thermostat_client.exceptions.UnknownDevice: Your device is unknown null

The KM200 is connected to a Buderus Logamax plus GB132 heater with an RC30 controller. With ioBroker everything works fine.

Attached you will find the raw scan file.
`bosch_cli scan -i --host=BuderusKM200.fritz.box --token=..... --password=..... --protocol=HTTP --device=IVT`

Thank you for your support!
Eric

[rawscan_None.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7784097/rawscan_None.zip)

**Comment by pszafer** [comment]
Fixed with https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.16.9

**Comment by Unimatrix8472** [comment]
Thanks a lot!
