### ISSUE TITLE
"Temperature" shows up in Home Assistant as degrees. Should be kWh

### ISSUE THREAD

**Issue by jan11011977** [bosch-thermostat/home-assistant-bosch-custom-component#121]
The EasyControl integration has three 'energy' stats: 'Energy', 'Energy Temperature' and 'Energy Hot Water'.

The 'Energy Temperature' stat has the unit set to 'degrees' whereas it should be 'kWh' like the other two energy stats.

**Comment by pszafer** [comment]
Ok, I'm recognizing units in easy control by guessing if temperature in name then Celsius.
I'll let you know when I release the fix

**Comment by jan11011977** [comment]
Thank you so much!

**Comment by jan11011977** [comment]
Actually I'm sorry but Celcius is the correct unit for this measurement.

This value represents the average outside temperature, as recorded in the energy stats in the app.

Sorry for the false alarm, and thank you for writing this HASS plugin, you have done an amazing job with it.
