### ISSUE TITLE
Hydraulic balancing entity state is always OFF

### ISSUE THREAD

**Issue by gralin** [bosch-thermostat/home-assistant-bosch-custom-component#122]
**Describe the bug**

I have enabled Hydraulic balancing in Bosch app but it's still being reported in HA as OFF. I tried toggling the value in the app, restarting HA, but nothing changes - it's always OFF.

**Expected behavior**

Hydraulic balancing entity state should be ON when Hydraulic balancing is enabled in Bosch app.

**Screenshots**

![image](https://user-images.githubusercontent.com/3457048/148040452-f2df53bc-593b-4d2e-841b-955167968d39.png)

![tempFileForShare_20220104-104742](https://user-images.githubusercontent.com/3457048/148041344-ffa0a4ae-4d95-4e3e-af3d-fb26791ce69c.jpg)

**Version**
  - HA version 2021.12.7
  - HA Bosch component version v0.16.9

**Debug SCAN**
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7806714/bosch_scan.json.txt)

**Comment by pszafer** [comment]
Forgot to mention, fixed in 0.17.0
