### ISSUE TITLE
Hotwater trigger for manual load not supported in rc35 and km200

### ISSUE THREAD

**Issue by johannes281** [bosch-thermostat/home-assistant-bosch-custom-component#123]
Hi,

I saw in an earlier Issue #95 that the hotwater manual load is supported by your integration with a switch. I have a GB172 with BC25 and RC35 and KM200 as webgateway. But the described functionality isn't available in my HA installation. There are also no disabled entities in Water heater dhw1. Do you have any idea why the entities are missing in my installation? Is it a rc35 problem so i need to upgrade to rc310?

![water](https://user-images.githubusercontent.com/75601385/148351572-9219e281-f2ba-4c5a-9953-3a5399a49931.png)

![water1](https://user-images.githubusercontent.com/75601385/148351894-1362fd52-0792-4c5b-a736-492eca6bf320.png)

Thanks for checking.
Johannes

**Comment by pszafer** [comment]
Attach Bosch scan

**Comment by johannes281** [comment]
[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7826999/bosch_scan.txt)

**Comment by pszafer** [comment]
Hi, RC35 doesn't have this functionality. But I think that you can do automation to simulate same behaviour and it will work.
Currently you're working according to schedule:
```
{
            "id": "/dhwCircuits/dhw1/operationMode",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 0,
            "value": "auto",
            "allowedValues": [
                "auto",
                "on",
                "off"
            ]
        },
```

Just switch operationMode to on and it should heat, after 1 hour switch back to auto.
