### ISSUE TITLE
Homekit integration doesn't work for any of the sensors

### ISSUE THREAD

**Issue by happymeal99** [bosch-thermostat/home-assistant-bosch-custom-component#124]
Using a IVT, KM200 integration everything works fine in Home assistant.

Once integration with homekit is enabled, non of the sensor information is going across to apple devices. Homekit doesn't even see those entities. They are correctly added to config. Climate and water_heater are correctly working in homekit but no sensors.

This issue only hits sensor type information. Those sensors are enabled in settings, and are properly displaying on HA dashboard. I tried variety of sensors.

homekit:
    filter:
      include_entities:       
        - sensor.komfovent_outdoor_temperature_c
        - sensor.bosch_outdoor_temperature
        - sensor.system_pressure
        - switch.komfovent_eco_mode
        - climate.hc1
        - climate.hc2
        - water_heater.dhw1

**Comment by pszafer** [comment]
I don't know what might be issue with homekit as I never used it.
Can you send screenshot of developer tools states of this sensor `sensor.bosch_outdoor_temperature`?

**Comment by happymeal99** [comment]
![image](https://user-images.githubusercontent.com/96337055/148931502-10d6eac6-b0d1-4897-bfd4-c74e7ee6bea2.png)

There you go!

**Comment by pszafer** [comment]
ok, so I don't know. Units and device class are properly set.

**Comment by happymeal99** [comment]
@pszafer  for future reference, after removing two properties from the sensor the homekit integration correctly transfered it into apple home.

state_class: measurement and device_class temperature.

**Comment by pszafer** [comment]
So I think it's bug in Homekit integration as documentation of HomeKit (and many integration) requires device_class temperature
![image](https://user-images.githubusercontent.com/690510/149084025-3ed13845-d2e4-439d-927f-913416da6654.png)

`state_class: measurement` it's also recommended for such sensors (at least I followed developer docs 2/3 months ago when they introduced those state classes.
