### ISSUE TITLE
Trying to set up Buderus TC 100

### ISSUE THREAD

**Issue by taert79** [bosch-thermostat/home-assistant-bosch-custom-component#127]
**Describe the bug**
I'm trying to set up Buderus TC 100, without success.
- When I choose "Easycontrol" as device type, it complains that my credentials are wrong. Already tried a simpler and shorter password, but no luck...
- When I choose "Nefit" as device type, something happens: an (unknown) device is created, with no entities. The debug scan attached is created after setting up with Nefit device type.

**Version**
  - HA version?  2021.12.9
  - HA Bosch component version? 0.16.9
  - Python Bosch HTTP client version? unknown

** Debug SCAN **
http://www.jsonblob.com/930835681056669696

**Comment by pszafer** [comment]
It's NEFIT, I have to add your device to my library. What country are you from?

**Comment by taert79** [comment]
Hi there @pszafer ,

Thanks so much for your reply! I live in Belgium.

**Comment by taert79** [comment]
Just installed 0.17.0, works perfectly now!
