### ISSUE TITLE
Home Assistant Restart: Bosch service unavailable

### ISSUE THREAD

**Issue by M4v3r1cK87** [bosch-thermostat/home-assistant-bosch-custom-component#128]
**Describe the bug**
When I restart Home Assistant, if the Bosch device is unknown or unavailable, also the bosch service are unavailable. So, if I try to invoke the bosch.debug_scan service, Home Assistant return the error message "Unable to find bosch.debug_scan service"

**To Reproduce**
1. Restart HA with the Bosch device unavailable
2. Goto under DeveloperTools/Service
3. Invoke the bosch.debug_scan service

**Version**
  - HA version? 2021.12.9
  - HA Bosch component version? 0.16.9

**Comment by pszafer** [comment]
Yes, it's proper behavior. What's the purpose to have service if there is no device to scan.

**Comment by M4v3r1cK87** [comment]
Mmmm and if is unavailable for HA, but is available into the network? If the service is unavailable I cannot scan the device for checking errors or compatibility issues from the device and HA. How can I run the bosch.scan service?

**Comment by pszafer** [comment]
Services in HA are designed to be working with devices which are connected to HA. If it's available in network but something else is wrong (eg credentials) then scan wouldn't work anyway. If you need to scan device which is not in HA then you can scan with docker or install lib manually.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Run-lib-with-Docker
