### ISSUE TITLE
Startup error: firmware_version is None

### ISSUE THREAD

**Issue by DavidMStraub** [bosch-thermostat/home-assistant-bosch-custom-component#129]
Thanks for this great component! I've been using it for quite a long time and am finding it very useful. I am continuously upgrading, but some time ago (not sure exactly when), it stopped working for me with the following error on HA startup:

```
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bosch/__init__.py", line 124, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 206, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 253, in async_init_bosch
    await self.gateway.check_connection()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 307, in check_connection
    await self.initialize()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 75, in initialize
    self._db = get_db_of_firmware(self._device[TYPE], self._firmware_version)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/db/__init__.py", line 44, in get_db_of_firmware
    filename = DEVICE_TYPES[device_type].format(firmware_version.replace(".", ""))
AttributeError: 'NoneType' object has no attribute 'replace'
```

Do you know what could be the reason?

**Version**
  - HA version: 2021.12.8
  - HA Bosch component version: current master (1d612cc2a433ed7fdb8525c15ec6c1d4f98fc032)
  - Python Bosch HTTP client version: 0.17.0

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`

Unfortunately I can't do it since the service is not registered due to the startup error.

Thanks!

**Comment by pszafer** [comment]
Hard to say. Was it working like week ago?
Can you try downgrade to 0.16.9? Maybe I made mistake somewhere...
or maybe you changed password?

**Comment by DavidMStraub** [comment]
I am sure had the error already before 0.16.9; upgraded to current master only today to see if it helps.

**Comment by DavidMStraub** [comment]
If that helps: using the library version 0.17.0 I was able to run

```
bosch_cli scan --host *** --token ***  --password *** --protocol HTTP --device IVT --stdout -d
```

and the output is here:

https://gist.github.com/DavidMStraub/e839452d8dfd22be2da57c1f866cd500

**Comment by DavidMStraub** [comment]
Thanks! Upgrading did not solve the issue, I got the log error

> Cannot connect to Bosch gateway, host 192.168.178.42 with UUID: 854420148 

But then I tried deleting and re-adding the integration, and it worked. It's a bit tedious manually re-enabling all the entities that are all disabled by default, what's the rationale for this?

Anyway, very happy that this is working now, thanks for the support!

**Comment by pszafer** [comment]
too many requests to API might freeze your thermostat so most sensors are disabled by default and you should enable only those you need.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Sensors-Configuration
