### ISSUE TITLE
Buderus KM50 supported? Integration don't start up...

### ISSUE THREAD

**Issue by medicus07** [bosch-thermostat/home-assistant-bosch-custom-component#130]
I select IVT/XMPP config type and put in the serial number, the access token and my Bosch id password...

There is a success message, but I can't see any entities.

I use HA OS on a RP4

Versions:
  - HA 2021.12.10
  - HA Python 3.9.7
  - HA Bosch component v0.17.0
  - Python Bosch HTTP client version?

Here is a log file from core log:
[Log.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7903707/Log.log)

**Comment by pszafer** [comment]
According to logs either you provided wrong credentials to decrypt message or it uses differenct encryption algorithm.
You can try to retrieve data with different methods: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Run-lib-with-Docker

**Comment by medicus07** [comment]
I did not make it to run the dev docker... tried on new installed RP3.

The access token on device label has the syntax: xxxx-xxxx-xxxx-xxxx

Is it with "-" or without "-" in credentials?

**Comment by pszafer** [comment]
without -

**Comment by medicus07** [comment]
I managed it... I checked the device in the MyBuderus app and after delete readded it.

I recognized my fault: the device password is not the password of the mybosch login! 

Thanks for your input! :-)
