### ISSUE TITLE
Buderus Logamax plus GB192i + KM100 / RC300 only some entities show up

### ISSUE THREAD

**Issue by AndyHeinz** [bosch-thermostat/home-assistant-bosch-custom-component#131]
Hi,

I finally found your component which is awesome :) 
It works partially for me. I'm not sure where the issue is.
This is what the scan gets: 
![grafik](https://user-images.githubusercontent.com/5164872/151126241-9d795d3e-863e-439b-b765-623333bcb091.png)

bosch_cli scan -i --host 111.111.111.111 --token zzzzzzzzzz --password xxxxx --protocol HTTP --device IVT
All other (device/protocol) scans fail.

I think the json holds all the relevant informations.
http://jsonblob.com/935811748674682880

Thanks for looking into!

**Comment by pszafer** [comment]
What's not working for you?

**Comment by AndyHeinz** [comment]
Hi 
I got only three working entities out of 54 - the rest is dead. The json states there should be more. Is the mapping faulted?
Thanks!

**Comment by pszafer** [comment]
Did you read wiki? https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Sensors-Configuration

Most things are disabled by default so you can enable those you want. I have 30 entities enabled and everything is fine for me

**Comment by AndyHeinz** [comment]
great - I was to impatient!
Thanks
