### ISSUE TITLE
How to access dhw current temperature entity

### ISSUE THREAD

**Issue by vdg1** [bosch-thermostat/home-assistant-bosch-custom-component#132]
Hi,

I am not sure this is an actual bug, more a technical question from my side when it comes to use the integration in HA: In HA I see the entity of the hot water system of my heat pump (IVT Geo 500). Its entity id is water_heater.dhw1 which actually contains 2 entities (set point and actual temperature). I added the entity to a graph element in Lovelace and it shows both temperatures just fine. Now I'd like to access the actual temperature sensor for statistical evaluation. So I set up a statistics sensor in HA's configuration yaml:

- platform: statistics
    name: "Hot water change over 5 minutes"
    entity_id: water_heater.dhw1
    state_characteristic: change
    max_age:
      minutes: 5
    sampling_size: 50
    precision: 1

However the statistics sensor remain empty. I assume I need to reference the actual temperature sensor entity id in the statistics sensor, but I don't know how to retrieve its entity id.

Any help would be appreciated!

**Comment by pszafer** [comment]
You need to create template sensor first which extracts attribute you want. Use this entity in statistics platform.

**Comment by vdg1** [comment]
Hi,

thanks for the tip. I am not that used to HA yet....

I was just about to test this, but ran into the same problem as described in [this issue](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/133).

**Comment by pszafer** [comment]
Fox example:
```
    - unique_id: 1floor_temperature                                                                                    
      name: "First floor temperature"               
      unit_of_measurement: "°C"                
      state: >-                                                                                                        
        {{ state_attr('climate.hc1', 'current_temperature') }} 
```
