### ISSUE TITLE
Home Assistant Bosch Thermostat "unknown model"

### ISSUE THREAD

**Issue by MarkRoks** [bosch-thermostat/home-assistant-bosch-custom-component#134]
Hello,

I've installed the Bosch thermostat integration with Hacs in my Home Assistant. Home Assistant runs on a Raspberry Pi 4 and works fine. But the Bosch thermostat integration won't connect with my Bosch EasyControl (CT200) thermostat. He says after installation "unknown model".

If I look in the Home Assistant files, I see that Python 3.9 is installed and the firmware of the Home Assistant himself is 2022.2.0b4 (beta-version).

The logfiles are like this:

**_**_2022-01-31 14:45:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-31 14:45:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-31 14:45:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration bosch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-31 14:48:45 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-01-31 14:49:15 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-01-31 14:49:15 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2022-01-31 14:49:15 ERROR (MainThread) [custom_components.bosch] Cannot connect to Bosch gateway, host 101260615 with UUID: None
2022-01-31 15:06:32 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-01-31 15:06:32 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2022-01-31 15:06:32 ERROR (MainThread) [custom_components.bosch] Cannot connect to Bosch gateway, host 101260615 with UUID: None_**_**

What could I try to change/do to get a working integration in the Home Assitant for the Bosch Thermostat?

Greetings,

Mark

**Comment by pszafer** [comment]
I need scan of your device. https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices

**Comment by MarkRoks** [comment]
Hello,

It's not possible to scan the device. Because the Bosch Thermostat is not set correctly and won't be available in the scan service.

I only can see the logbook of the instllation, which failed:

![image](https://user-images.githubusercontent.com/78249637/151866669-af8333f7-0dd9-40b3-b258-160381e0afb1.png)

And by the integration it looks like:

![image](https://user-images.githubusercontent.com/78249637/151866909-6d3b2443-db74-4764-b71d-e1fe8441f650.png)

The Bosch EasyControl thermostat has firmware 03.02.00. At this moment there is no option to update these firmware to 03.10.00, because Bosch is doing maintenance at their server.

Can I try something else, to get wright data?

Greetings,

Mark

**Comment by pszafer** [comment]
Although minimal version my component support is 03.04.01. Yours is very old. It would be better to update first :)

**Comment by MarkRoks** [comment]
Oké, thank you!

Bosch told me that in the beginning of april it will be possible to update again. That's a pretty long time, I thought. But there is no alternative, I think so.

Other question: in which steps is it possible to manipulate the setpoint of the termostat with this integration? In the past I was able to set it by steps of 0.1 with the open API, by firmware 01.04.00 . But now are the steps only possible in 0.5, even the manual operation on the thermostat, with firmware 03.02.00.

I like to hear you!

Greetings,

Mark

**Comment by pszafer** [comment]
So try to do the scan some of attached ways and I can try to add support for your current firmware.

0.1 step is too low for those temperature sensors IMO so it's logical they changed it for something more realistic

**Comment by aBaDDoNNL** [comment]
I actually am facing the same problem. I got my new EasyControl thermostat a week ago also with firmware 03.02.00. So maybe here in The Netherlands we have some old stash lying around ;)

I ran the bosch_cli scan and got the following: 

`2022-02-01 16:46:48 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/uuid
2022-02-01 16:46:54 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
2022-02-01 16:47:00 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/versionFirmware
2022-02-01 16:47:06 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/productID
2022-02-01 16:47:12 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/DateTime
2022-02-01 16:47:12 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
Traceback (most recent call last):
  File "./bosch_cli", line 8, in <module>
    sys.exit(cli())
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/bosch_cli.py", line 79, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/bosch_cli.py", line 234, in scan
    connected = True if ignore_unknown else await gateway.check_connection()
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base.py", line 307, in check_connection
    await self.initialize()
  File "/home/abaddon/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base.py", line 90, in initialize
    raise UnknownDevice("Your device is unknown %s" % json.dumps(self._device))
bosch_thermostat_client.exceptions.UnknownDevice: Your device is unknown null`

Didn't see any options in the bosch_cli tool to go more verbose than this so hopefully, it is sufficient but it boils down to the same error I see in HA which is what Mark is reporting.

Cheers,

Ramon

**Comment by pszafer** [comment]
Can you sniff to what xmpp server your device is connected to?

**Comment by aBaDDoNNL** [comment]
Sorry, I had a quick look, but I just moved and I am currently using a very basic router which doesn't allow me to even look at logs to just check simple things like DNS queries or such. As the traffic of the thermostat is going straight through that router I cannot see it's destination. Maybe if I have some time I could try to force it through some other router. But I don't think I will be able to do that soon.

**Comment by Westerbroek** [comment]
Hi, here the same problem. Firmware version 03.02.00
I have tried portforwarding 5222 and 5223 from my router to my Easycontrol. But no traffic is detected in my firewall that try an connection.

**Comment by MarkRoks** [comment]
Hello,

For me isn't possible to run any scan for the Bosch Thermostat, meanwhile the firmware is 03.02.00. 

I hope Bosch today it will fix it up to 03.10.00, by which it must be possible to run the integration correctly. I'll be curious what happens, after the update.

I'll keep you up to date.

**Comment by pszafer** [comment]
@Westerbroek it's other way around, your CT200 connects to some bosch XMPP server and somebody have to find what server is it.
@aBaDDoNNL year ago with new firmware they changed XMPP server to new one.
Old servers were different and I think that such "old" firmware as 03.02.00 it can connect to one of these old servers. Everything is about finding which server it is...

**Comment by MarkRoks** [comment]
Hello,

Some days later then expected, Bosch has just updated my Bosch CT200 to firmware 03.10.00. After that I run again the installation procedure of Bosch Thermostat integration. After that I get again the same error: "unknown model".

Despite I see Python 3.9 in the files, but of this works....? If I re-install Python 3.9, I receive some errors. Something about: "existing files not found". It look likes the problem arises from the version of Python which runs in Python. 

I've sought on the internet to a solution, but nothing found what solves the problem.

Any other suggestion what could be the cause to a working integration?

Greetings,

Mark

**Comment by pszafer** [comment]
Are you talking about HA or Windows installation?

**Comment by MarkRoks** [comment]
Hello,

Home Assistant is installed on my Raspberry Pi 4.

**Comment by pszafer** [comment]
Provide some logs https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#home-assistant-debugging-log

**Comment by MarkRoks** [comment]
Hello,

Here are the received logs, after debugging;

22-02-04 12:20:58 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-04 12:50:36 INFO (MainThread) [supervisor.resoluti**on.check] Starting system checks with state CoreState.RUNNING
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-02-04 12:50:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 12:50:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 12:50:37 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-02-04 12:50:37 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-02-04 12:50:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-04 13:06:46 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 13:06:54 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 13:07:01 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 13:07:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 13:07:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 13:08:57 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 13:09:05 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 13:09:12 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 13:09:12 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 13:09:23 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 13:11:27 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 13:11:35 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 13:11:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 13:11:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 13:11:54 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 13:20:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-02-04 13:50:37 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-02-04 13:50:58 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
22-02-04 13:51:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-04 13:57:38 INFO (MainThread) [supervisor.host.info] Updating local host information
22-02-04 13:57:38 INFO (MainThread) [supervisor.host.services] Updating service information
22-02-04 13:57:38 INFO (MainThread) [supervisor.host.network] Updating local network information
22-02-04 13:57:39 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-02-04 13:57:39 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-02-04 14:10:38 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_configurator
22-02-04 14:10:38 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/armv7-addon-configurator with tag 5.3.3.
22-02-04 14:10:57 INFO (MainThread) [supervisor.addons] Add-on 'core_configurator' successfully installed
22-02-04 14:11:32 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_configurator
22-02-04 14:11:51 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 14:11:58 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 14:12:04 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 14:12:05 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 14:12:15 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 14:13:47 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-configurator with version 5.3.3
22-02-04 14:16:20 INFO (SyncWorker_6) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 14:16:27 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 14:16:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 14:16:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 14:16:44 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 14:17:48 INFO (SyncWorker_7) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 14:17:55 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 14:18:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 14:18:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-04 14:18:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-02-04 14:19:25 INFO (MainThread) [supervisor.backups.manager] Found 45 backup files
22-02-04 14:19:25 INFO (MainThread) [supervisor.backups.manager] Found 45 backup files
22-02-04 14:19:29 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-homeassistant
22-02-04 14:19:36 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-02-04 14:19:43 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-04 14:19:43 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete

Hopefully it is enough to see something of the Bosch integration, which is installed, but gives the error: "unknown model"._**

Greetings,

Mark

**Comment by MarkRoks** [comment]
Here I have some error logs of the integration self;

2022-02-04 14:19:41 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-04 14:19:41 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-04 14:19:41 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration bosch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-04 14:19:41 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-04 14:19:47 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.17.3.
2022-02-04 14:19:47 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2022-02-04 14:19:47 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 101168494.
2022-02-04 14:19:50 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-02-04 14:19:50 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2022-02-04 14:19:50 ERROR (MainThread) [custom_components.bosch] Cannot connect to Bosch gateway, host 101168494 with UUID: None

**Comment by pszafer** [comment]
Most likely you provided wrong password

**Comment by MarkRoks** [comment]
Hello,

You're right! I've changed the password in the same I thought it was. After that de integration her-installed. And it works!

Strange I thought the password was the right one.

Thank you a lot!

Greetings,

Mark

**Comment by aBaDDoNNL** [comment]
> Hello,
> 
> For me isn't possible to run any scan for the Bosch Thermostat, meanwhile the firmware is 03.02.00.
> 
> I hope Bosch today it will fix it up to 03.10.00, by which it must be possible to run the integration correctly. I'll be curious what happens, after the update.
> 
> I'll keep you up to date.

Hi Mark,

Out of curiosity how were you able to get the firmware update? Did you call/reached out to them to ask them to push it, because you mentioned the server maintenance. Mine remains on 3.02.

Cheers,

Ramon

**Comment by MarkRoks** [comment]
Hello Ramon,

That was a long story. I've contacted the Nefit Bosch customer support, because my Bosch EasyControl had firmware 01.04 and won't update (automatic). 

First they say, they couldn't help me and it would take to the beginning of april, when the updates become available. Because their server was under construcion.

I won't agree. After that, I received a document, which I had to reply to them. After that it took a week to update from 01.04 to 03.10 in little steps. 

But finally it works and has firmware 03.10 on it.

Greetings,

Mark

**Comment by Todor2025** [comment]
> Hello Ramon,
> 
> That was a long story. I've contacted the Nefit Bosch customer support, because my Bosch EasyControl had firmware 01.04 and won't update (automatic).
> 
> First they say, they couldn't help me and it would take to the beginning of april, when an possible update becomes available. This was because their server was under construcion.
> 
> I won't agree and had contacted them again and again. After that, I received a document, which I had to reply to them. After that it took a week to update from 01.04 to 03.10 in little steps. They pushed them forward to my Bosch EasyControl.
> 
> But finally it works and it has firmware 03.10.
> 
> Greetings,
> 
> Mark

Hi Mark,

Is it possible to share the steps you took to upgrade EasyControl CT200 firmware from version 01.04 to 03.10?

My EasyControl CT200 thermostat is running with 01.04 firmware and cannot connect to the boiler (Bosch GC2300i W 24/30). I've contacted the local dealer/support for Bosch and they told me that the problem is the old CT200 firmware (which cannot "speak" to (recognize) the boiler software). They tried to update CT200 firmware, but after a few attempts they gave up. 

In EasyControl as of 13 May 2025 it is not possible to automatically update the firmware. 

Thank you. 

Regards,
Todor
