### ISSUE TITLE
total system uptime incorrect name/unit

### ISSUE THREAD

**Issue by pswid** [bosch-thermostat/home-assistant-bosch-custom-component#136]
"**total system uptime mins**" should be renamed to "**total system uptime**" (or "**total system working time**"?) because it doesn't report minutes but seconds. Proper `unit_of_measurement` should be added to the entity as well. However, in my opinion, the better option would be showing it in format days, hours, minutes (skip the seconds?) and leave original value in seconds as an attribute only. What do you think?

![image](https://user-images.githubusercontent.com/78219494/151961404-c7ff3628-e798-4887-979a-43f3d0ecd053.png)

**Comment by pszafer** [comment]
They changed it... It was mins, now some devices have seconds, some minutes... I have to retrieve unit and show it as it is.

**Comment by nobthenob** [comment]
Hi,
In my HA system the "total system update mins" sensor has device class timestamp. I believe this is not correct, as it is basically just a number, in my case it seems to be minutes (Buderus RC 310 Control unit).
Thank you for looking into!

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0
