### ISSUE TITLE
Monthly/yearly consumption statistics 

### ISSUE THREAD

**Issue by dimkin-eu** [bosch-thermostat/home-assistant-bosch-custom-component#137]
Bosch control App ( android ) has statistics for monthly consumption ( over current and previous years )
Is there a possibility to retrieve that to HA?
I'm having `CT 100` ( fw 02.22.00 ) + Bosch `Condens 9000i W` if that matters :)
 
![image](https://user-images.githubusercontent.com/7899764/152238040-8f0977a7-d1dc-4b7e-a4e1-5bc63b3ea4ae.png)

**Comment by pszafer** [comment]
Currently HA doesn't allow to put past data into sensor statistics only present data, so it's impossible AFAIK

**Comment by dimkin-eu** [comment]
could it be fetched per se? not from sensor history, but from the same place app does?
like hawing some raw data.

**Comment by pszafer** [comment]
yes, it could be fetched and put to influx db do example

**Comment by pszafer** [comment]
Done for Nefit and CT200 in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0
