### ISSUE TITLE
sensor.recording_ractualtemp has unit °C which is unsupported for device_class energy

### ISSUE THREAD

**Issue by spaetz** [bosch-thermostat/home-assistant-bosch-custom-component#138]
**Describe the bug**
On a current installation
```
bosch-thermostat-client==0.17.3
boschshcpy==0.2.19
```

I get the following in the logs

`sensor.recording_ractualtemp has unit °C which is unsupported for device_class energy
`
which makes sense, since this actually measures the (averaged) water temperature and no energy consumption. So does this need to be put into a different category?

Thanks for the integration, I works great!

**Comment by PeterHolgersson** [comment]
Adding "actualtemp" on row 42 in sensors.py fixed the issue for me.
if any(x in uri for x in ["temp", "outdoor", "actualTemp"]):

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0
