### ISSUE TITLE
There are problems with config of your thermostat.

### ISSUE THREAD

**Issue by josbeir** [bosch-thermostat/home-assistant-bosch-custom-component#140]
Hi! Since a few days i am seeing this notification in the notifications panel:

![image](https://user-images.githubusercontent.com/26058/152538893-aded98f8-899e-4bfa-8426-67c6dd8483b3.png)

I think i didn't do anything special in particular, am using your plugin a few months whiteout any issues. So maybe something changed in a recent version that broke something?

I have a Buderus installation with KM200 module (RC310). Scan log attached.

[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8003466/bosch_scan.json.zip)

In HASS logs i'm seeing this

```
Logger: bosch_thermostat_client.helper
Source: /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/helper.py:266
First occurred: January 22, 2022, 8:27:35 AM (1006 occurrences)
Last logged: 2:47:56 AM

    Can't update data for Current Summer Winter Mode. Trying uri: /heatingCircuits/hc2/currentSuWiMode. Error message: URI /heatingCircuits/hc2/currentSuWiMode doesn not exist: 404, message='Not Found', url=URL('http://192.168.1.22/heatingCircuits/hc2/currentSuWiMode')
    Can't update data for Health status. Trying uri: /system/healthStatus. Error message: Connection timed out for /system/healthStatus.
    Can't update data for Actual Power. Trying uri: /heatSources/actualPower. Error message: Connection timed out for /heatSources/actualPower.
    Can't update data for Actual Supply temperature. Trying uri: /system/appliance/actualSupplyTemperature. Error message: Connection timed out for /system/appliance/actualSupplyTemperature.
    Can't update data for Current Summer Winter Mode. Trying uri: /heatingCircuits/hc1/currentSuWiMode. Error message: Connection timed out for /heatingCircuits/hc1/currentSuWiMode.
```

Hope the this information helps?

**Comment by pszafer** [comment]
What component version do you use? 0.17.3 was provided to handle the newest firmware

**Comment by josbeir** [comment]
I just discovered that i was still in 0.16.8. Updated it now and the notification is gone. Was convinced HACS did auto updates :-)

Stupid! sorry ;-)
