### ISSUE TITLE
Conflicting dependencies in 2022.3 release

### ISSUE THREAD

**Issue by rgerbranda** [bosch-thermostat/home-assistant-bosch-custom-component#146]
**Describe the bug**
Today I installed `core-2022.3.0b5` of Home Assistant

**To Reproduce**
Update to `core-2022.3.0b5`

**Expected behavior**
Bosch component should still work

**Screenshots**

**Version**
  - HA version? core-2022.3.0b5
  - HA Bosch component version? 0.17.3
  - Python Bosch HTTP client version?

** Debug SCAN **
```
2022-03-01 22:00:15 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package bosch-thermostat-client==0.17.3: ERROR: Cannot install bosch-thermostat-client because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-01 22:00:29 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package bosch-thermostat-client==0.17.3: ERROR: Cannot install bosch-thermostat-client because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-01 22:00:50 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package bosch-thermostat-client==0.17.3: ERROR: Cannot install bosch-thermostat-client because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-01 22:00:50 ERROR (MainThread) [homeassistant.setup] Setup failed for bosch: Requirements for bosch not found: ['bosch-thermostat-client==0.17.3'].
```

**Comment by DoDoENT** [comment]
Today `core-2022.3.0` came out of beta and into stable and this issue remains.

**Comment by narfotic** [comment]
Update today to core-2022.3.0. Stopped working.

`Unable to install package bosch-thermostat-client==0.17.3: ERROR: Cannot install bosch-thermostat-client because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

`Setup failed for bosch: Requirements for bosch not found: ['bosch-thermostat-client==0.17.3'].`

**Comment by pszafer** [comment]
Issue is in one of the dependencies: https://github.com/horazont/aioxmpp/issues/380

**Comment by kirelam** [comment]
What way is there, to find out what other package it has a conflict with?

**Comment by pszafer** [comment]
Install each dependency one by one with package-constraint.txt and find out which won't install.

**Comment by kirelam** [comment]
My knowledge is too small to know what packages belong to this integration and how to install these

**Comment by kirelam** [comment]
Does this mean there must first come a bugfix FR m the core to solve this issue.? Otherwise i Will roll back to a previous backup!

**Comment by pszafer** [comment]
We wait for possible update of `aioxmpp` library.

**Comment by kantorbalazs** [comment]
> We wait for possible update of `aioxmpp` library.

Is that going to come in HA update or in the Bosch component?

**Comment by christophgasser** [comment]
Waiting for that update too as I got stuck installing the component because of the dependencies problem. BR C

**Comment by aleksandersmolowik** [comment]
Now after restart it is working again!

**Comment by pszafer** [comment]
Fixed with https://github.com/horazont/aioxmpp/pull/381

**Comment by motechsolutions** [comment]
I can also confirm now working after reboot

**Comment by tomekswx** [comment]
Working with 2022.3.3.
