### ISSUE TITLE
bug since core HA update

### ISSUE THREAD

**Issue by lilouane** [bosch-thermostat/home-assistant-bosch-custom-component#147]
hi,

Since the last update of the HA core the boch integration does not want to start anymore, I am attaching the message from the boot log.
I cannot generate the debug because it is not found in the services.
waiting for a update on your side.

greeting

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 13:23:19 (3 occurrences)
Last logged: 13:23:32

Unable to install package bosch-thermostat-client==0.17.3: ERROR: Cannot install bosch-thermostat-client because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by filipole** [comment]
same here

**Comment by pszafer** [comment]
duplicate https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/146
