### ISSUE TITLE
Add sensors to nsc icom 040802

### ISSUE THREAD

**Issue by PeterHolgersson** [bosch-thermostat/home-assistant-bosch-custom-component#149]
**Is your feature request related to a problem? Please describe.**
Yes and No, some of the sensors are lacking the state class and device class attributes so they can not be used in statistics.

**Describe the solution you'd like**
I want to add the following sensors:

HC
- /heatingCircuits/hc1/holidayMode/activated
- /heatingCircuits/hc1/status
- /heatingCircuits/hc1/operationMode

DHW
- /dhwCircuits/dhw1/actualTemp
- /dhwCircuits/dhw1/temperatureLevels/low
- /dhwCircuits/dhw1/temperatureLevels/eco
- /dhwCircuits/dhw1/temperatureLevels/high
- /dhwCircuits/dhw1/holidayMode/activated
- /dhwCircuits/dhw1/status
- /dhwCircuits/dhw1/

Sensors
- /gateway/DateTime
- /gateway/update/status
- /system/holidayModes/hm1/startStop
- /heatSources/applianceSupplyTemperature
- /heatSources/powerSetpoint

And also add the state class and device class attributes to the following sensors:
- /heatingCircuits/hc1/suWiThreshold
- /heatingCircuits/hc1/pumpModulation
- /system/sensors/temperatures/supply_t1_setpoint
- /system/sensors/temperatures/supply_t1
- /system/sensors/temperatures/return
- /system/sensors/temperatures/switch
- 

**Describe alternatives you've considered**

**Additional context**

As github does not accept *.json files I renamed the attached files to .txt the content is however still JSON
The suggested solution:
[040802.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8239381/040802.txt)
Raw scan of my device (IVT GEO508):
[rawscan_174431120 20220313T10_49.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8239390/rawscan_174431120.20220313T10_49.txt)

**Comment by pszafer** [comment]
So most of the uri's are already in component:
|Uri|status|
|---|---|
| /heatingCircuits/hc1/holidayMode/activated | to be added |
| /heatingCircuits/hc1/status | present in climate |
| /heatingCircuits/hc1/operationMode | present in climate |
| /dhwCircuits/dhw1/actualTemp | present in dhw |
| /dhwCircuits/dhw1/temperatureLevels/low | present in dhw |
| /dhwCircuits/dhw1/temperatureLevels/eco | present in dhw |
| /dhwCircuits/dhw1/temperatureLevels/high | present in dhw |
| /dhwCircuits/dhw1/holidayMode/activated | to be added |
| /dhwCircuits/dhw1/status | present in dhw |
| /gateway/DateTime | is there any reason to add it? |
| /gateway/update/status |  is there any reason to add it? |
| /system/holidayModes/hm1/startStop | can't be added |
| /heatSources/applianceSupplyTemperature | to be added |
| /heatSources/powerSetpoint | | to be added |

```
And also add the state class and device class attributes to the following sensors:
/heatingCircuits/hc1/suWiThreshold
/heatingCircuits/hc1/pumpModulation
/system/sensors/temperatures/supply_t1_setpoint
/system/sensors/temperatures/supply_t1
/system/sensors/temperatures/return
/system/sensors/temperatures/switch
```

What are proper device and state classes for above?

**Comment by PeterHolgersson** [comment]
Hi @pszafer 
Thank you for taking the time to look at this!
I have put some comments in the comment column below:
<html><body>


Uri | status | Comment
-- | -- | --
/heatingCircuits/hc1/holidayMode/activated | to be added |
/heatingCircuits/hc1/status | present in climate | The reason for adding this is to get one sensor entity to easier show it in HA, but I can extract the attribute
/heatingCircuits/hc1/operationMode | present in climate | The reason for adding this is to get one sensor entity to easier show it in HA, but I can extract the attribute
/dhwCircuits/dhw1/actualTemp | present in dhw | The reason to add this is to get one entity that can be used for statistics and it's present for HC1 as a single entity
/dhwCircuits/dhw1/temperatureLevels/low | present in dhw | The reason for adding low/eco/high is to see the setpoint without changing the mode, as it is now you need to change the mode before you see the setpoint of that mode
/dhwCircuits/dhw1/temperatureLevels/eco | present in dhw | see above
/dhwCircuits/dhw1/temperatureLevels/high | present in dhw | see above
/dhwCircuits/dhw1/holidayMode/activated | to be added |
/dhwCircuits/dhw1/status | present in dhw | ok
/gateway/DateTime | is there any reason to add it? | The only reason to add this is to see if there are any drift in the internal  clock of the heat pump, so I can live without it
/gateway/update/status | is there any reason to add it? | A thought here was to create a notification in HA if the firmware have been updated as it have the states "inprogress", "completed", "interrupted" 
/system/holidayModes/hm1/startStop | can't be added | ok
/heatSources/applianceSupplyTemperature | to be added | state class: measurement  device class: temperature
/heatSources/powerSetpoint |   | Is this to be added?, in case you add it the state class is measurement and device class is frequency


</body>
</html>

See below for state class and device class

<html><body>


Uri | State class | Device class
-- | -- | --
/heatingCircuits/hc1/suWiThreshold | measurement  | temperature
/heatingCircuits/hc1/pumpModulation | measurement  | frequency
/system/sensors/temperatures/supply_t1_setpoint | measurement  | temperature
/system/sensors/temperatures/supply_t1 | measurement  | temperature
/system/sensors/temperatures/return | measurement  | temperature
/system/sensors/temperatures/switch | measurement  | temperature

</body>
</html>

**Comment by pszafer** [comment]
the best is to extract as much attributes manually because I don't know if there are some API limits to call Bosch device. There were some people in the past blocked by bosch device (but component fetched then all enabled uris in single loop).

I will try to add some of those sensors for next release

**Comment by PeterHolgersson** [comment]
Aha, I see but is this when you are connected through the cloud? I have tried the setup in the attached file (040802.txt) locally without any problems. But I understand that different bosch devices and the fact that if you connect local or through the cloud could create problems in certain cases.

Perfect! Thanks!

**Comment by pszafer** [comment]
It doesn't matter if you connect locally or via cloud. After some number of request users were blocked by device for several hours for cloud and till device restart if locally.
