### ISSUE TITLE
Data going in the negatives

### ISSUE THREAD

**Issue by massamino** [bosch-thermostat/home-assistant-bosch-custom-component#154]
**Describe the bug**
An auto "reload?" happened and my usage went in the negatives.
The problem also happens when removing and reinstall the integration (but is normal behavior in this case?).

**Expected behavior**
Keep counting upwards.

**Screenshots**
![Gas](https://user-images.githubusercontent.com/52240756/160199590-30157e08-1a85-4c96-86ba-dd25b840e191.png)
![Gas2](https://user-images.githubusercontent.com/52240756/160202942-e7f8ae7c-fde8-4d5f-89e8-6ac840ffa692.png)

**Version**
  - HA version? 2022.3
  - HA Bosch component version? 0.17.3
  - Python Bosch HTTP client version? dunno

**Debug SCAN**
**IMPORTANT**
[gas.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8353881/gas.json.txt)

**Comment by pszafer** [comment]
In HA 2022.4 you should be able to manually fix such issues. If your device is not available for longer than one hour in current version it will look like this... (next version when released shouldn't have such issues)
