### ISSUE TITLE
Holiday Mode

### ISSUE THREAD

**Issue by Schopenhauer178** [bosch-thermostat/home-assistant-bosch-custom-component#155]
Hi,

thanks a lot for this integration. I use it to connect my Bosch MBLani module (connected to the EMS port on the central heating: https://www.bosch-smarthome.com/de/de/produkte/weitere-bosch-produkte/mb-lani/) to connect to homeassistant. It works fine so far. 

Regarding the hot water temperature my Bosch HomeCom app offers me the possibility to switch it to off or alternatively to off with thermic desinfection. It is located in the holiday mode of the app.

Is there any chance to set the parameter  "off with thermic desinfection"?

Thank you and best regards
Sven

**Comment by pszafer** [comment]
I'd need bosch scan to check for it.

**Comment by Schopenhauer178** [comment]
Hi, I did the Raw Scan. Do I need do remove any passwords or anything like that from the file before uploading?

**Comment by pszafer** [comment]
all sensitive data should be cut automatically by scan tool

**Comment by Schopenhauer178** [comment]
here you go. May you find some further sensors that could be of interest. The used MB Lani module is the current official Bosch interface, so may be others would benefit as well. Thanks a lot!

[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8655011/bosch_scan.json.zip)

**Comment by pszafer** [comment]
I'm on holiday till next week so I'll check it next week

**Comment by pszafer** [comment]
can you turn on this mode `off with thermic desinfection`, so I can check how is it look like when it's enabled?

**Comment by Schopenhauer178** [comment]
Hi, I added to files:

1. Manual Disinfection turned. -> seems it just raises the temperature to 70 degree for a certain time. But I didn't figure out where the time is set
2. Holiday mode turned on from today til 24th with hot water off and thermal disinfection. The system sets the value td_off. 

So this means:

Auto_sat = Temperature like Saturdays
off= Hot water off
td_off= Hot water off with thermic disinfection

here's the part of the code:

            "id": "/system/holidayModes/hm1/dhwMode",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 0,
            "value": "TD_OFF",
            "allowedValues": [
                "AUTO_SAT",
                "OFF",
                "TD_OFF"

Thanks a lot!

Sven


[Archiv.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8711449/Archiv.zip)

**Comment by pszafer** [comment]
I see that 2 actions happen:
- switch `"/system/holidayModes/hm1/dhwMode"` from OFF to TD_OFF
- set `/system/holidayModes/hm1/assignedTo` to dhw1.

Only way I can think of to implement it is to use 3 select entities https://developers.home-assistant.io/docs/core/entity/select

- add sensor with holidayModes available,
- add option in integration options to choose which holidayMode you want to use (based on sensor or user knowledge),
- add select entities for `hcMode`
- add select entities for `dhwMode`
- add select entities for `assignedTo`
Eventually allow to use only `hm1`.

**Comment by pszafer** [comment]
As HA doesn't have any date utility for that I'd add service `send_custom_put` and you can just push parsed value to it.

**Comment by Schopenhauer178** [comment]
perfect !

**Comment by pszafer** [comment]
Does it look good for you?
![image](https://user-images.githubusercontent.com/690510/172652468-a68c7320-0bf7-4020-bf80-ebb21f93e656.png)

![image](https://user-images.githubusercontent.com/690510/172652755-76d96ed9-9f18-4fd2-a96d-c8e6f041fa21.png)

**Comment by Schopenhauer178** [comment]
looks great! Thank you! Let me know when its ready for testing :)

**Comment by pszafer** [comment]
ready for testing: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0.dev2

**Comment by Schopenhauer178** [comment]
Hi, I am struggling how to fill in start and end date of the holiday mode. I would expect to parse the value like "2022-05-17/2022-05-24". but I that doesn't work. If I load the example data I see the screenshot (attachment).

What do I have to fill in? :) 


<img width="1005" alt="Bildschirmfoto 2022-06-11 um 22 57 30" src="https://user-images.githubusercontent.com/83306880/173204718-4aacd3d3-b453-4f0b-ad4b-c08bb24ef9b6.png">

**Comment by Schopenhauer178** [comment]
just found out that also some recording sensors that worked before are not working now:

<img width="1005" alt="ho errors" src="https://user-images.githubusercontent.com/83306880/173205019-29740006-f97f-406c-9baf-f14463f55d2f.png">

**Comment by pszafer** [comment]
about first I don't know, I'd think that "2022-06-13/2022-06-14" should work.
about second open new issue and paste some logs. Screenshot doesn't say anything

**Comment by Schopenhauer178** [comment]
Hi,

thank's it's working in general. I filled in

service: bosch.send_custom_put
data: 
  uuid: "111111" --> ID that can be seen in the Bosch Homecomputer App
  path: "/system/holidayModes/hm1/startStop"
  value: "2022-06-14/2022-06-15"

results:

Hot Water: 
like Saturday: working
off: not working (eco is set)
eco: working

heating: 
like Saturday: working
eco: working
off: not working

holiday mode assigned to:
hc1: not working
dhw1: working
-> it should be possible to activate either one of both or both.

deletion of holiday mode:
setting value to   value: "" doesn't delete the mode. Any idea?

Best regards 

Sven

**Comment by Niki206cc** [comment]
Hi, with the command
"/system/holidayModes/hm1/startStop"
i can correctly set in holiday mode the heating....but what is the command to set in holiday the hot water?
I tried with  "/system/holidayModes/dhw1/startStop" but doesn't work.

Thanks!
