### ISSUE TITLE
CT-200 - sensor actual power not showing up

### ISSUE THREAD

**Issue by jmlt** [bosch-thermostat/home-assistant-bosch-custom-component#156]
![ha1](https://user-images.githubusercontent.com/17306923/164214758-e0f40b6b-83d4-4307-94e9-c0a93a4924ff.png)
I have a CT-200 linked to HA through this component on HACS, according to Wiki there should be a sensor actual power I could add to Energy dashboard but I can't find it somehow.
Am I doing something wrong or there's a trick?

Thank you.

**Comment by jmlt** [comment]
Well... meanwhile I removed integration from HA and HACS in order to reinstall, restarted everything but now I can't add back CT200, it says "Unknown error occurred".

**Comment by pszafer** [comment]
Please, attach bosch_scan.

**Comment by jmlt** [comment]
> Please, attach bosch_scan.
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8595232/bosch_scan.zip)
There it is. Thank you for your time.

**Comment by pszafer** [comment]
Actual power for energy dashboard will land in v0.18.0 of component. Stay tuned!
