### ISSUE TITLE
buderus gb-072 with Logamatic TC100

### ISSUE THREAD

**Issue by pszafer** [bosch-thermostat/home-assistant-bosch-custom-component#159]
Hello @pszafer . I have buderus gb-072 with Logamatic TC100 regulator. I have external water tank. From application, I'm able to choose 3 options: Switch off, Auto, On. Auto means that water is being heated according to set schedule.
Currently in integration I can see dwh1 but with only 2 positions: off and High Demand (which is setting up "On" visible for TC100).
![buderus](https://user-images.githubusercontent.com/62384501/155995792-88fdc3ef-087d-4873-82f7-fe89569fe65f.jpg)
![buderus_ha](https://user-images.githubusercontent.com/62384501/155995872-8b0180c3-4483-4d54-9a32-07938fa7f9c0.png)

_Originally posted by @przemoc86 in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/111#issuecomment-1054285291_

**Comment by pszafer** [comment]
I moved this to separate issue as this is Easycontrol feature request.

**Comment by przemoc86** [comment]
Thanks :) Waiting for this feature :)

**Comment by pszafer** [comment]
> can you make one scan when you are in `ON mode` and switch to `auto`?

In attachment JSON with ON and JSON with AUTO
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8500744/bosch_scan.zip)

it seems that there are 3 differences beside timestamps and temp values etc.

**Comment by pszafer** [comment]
Ready in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0

**Comment by przemoc86** [comment]
Not working unfortunately. Switching into performance and coming back to the last set up

![2022-06-29 14_43_03-Settings – Home Assistant – Opera](https://user-images.githubusercontent.com/62384501/176439183-41a8ea2c-9110-4e5d-b2e2-111c5f40fde8.png)

**Comment by przemoc86** [comment]
Hello @pszafer - any progress maybe? I really appreciate to use this feature ;)

**Comment by pszafer** [comment]
@przemoc86 it has to work now :) Install 0.19.2

**Comment by przemoc86** [comment]
I can confirm that is working! Thanks!
