### ISSUE TITLE
Integration uses deprecated `async_get_registry` to access device registry, use async_get instead

### ISSUE THREAD

**Issue by SmilyHM** [bosch-thermostat/home-assistant-bosch-custom-component#160]
**Describe the bug**
Log-entry:
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for bosch using this method at custom_components/bosch/__init__.py, line 220: await self.hass.helpers.device_registry.async_get_registry()

**To Reproduce**
Use this integration :-)

**Expected behavior**
from Log: use async_get instead. At custom_components/bosch/__init__.py, line 220: await self.hass.helpers.device_registry.async_get_registry()

**Version**
  - HA version
    - Core 2022.06.01
    - Supervisor: 2022.05.3
    - OS: 8.1
  - HA Bosch component version: latest (I guess v0.17.3)
  - Python Bosch HTTP client version: ? (where to find?)

Best regards
Sascha

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0
