### ISSUE TITLE
error "Can't update data for Summer Winter Threshold"

### ISSUE THREAD

**Issue by pswid** [bosch-thermostat/home-assistant-bosch-custom-component#162]
My Buderus heatpump has a IP gateway with firmware: 04.08.02

It seems that if `/heatingCircuits/hcX/suWiSwitchMode` is set to `off` or `forced`, parameter `/heatingCircuits/hc1/suWiThreshold` becomes unavailable. It's only available if `suWiSwitchMode` is set to `automatic`. Could you fix the integration so that it does not report an error?  

in log i see entries:
`ERROR (MainThread) [bosch_thermostat_client.helper] Can't update data for Summer Winter Threshold. Trying uri: /heatingCircuits/hc1/suWiThreshold. Error message: URI /heatingCircuits/hc1/suWiThreshold doesn not exist: 404, message='Not Found', url=URL('http://192.168.x.x/heatingCircuits/hc1/suWiThreshold')`

**Comment by pszafer** [comment]
you can disable error logs within Home Assistant according to your needs:
```
logger:
  bosch_thermostat_client.helper: fatal
```

**Comment by pswid** [comment]
Ok, but what if someone would like to catch all, not only fatal errors? Besides, availability of `suWiThreshold` only in `auto` mode has sense and doesn't mean that something is wrong. So, why treat this as an error?

**Comment by pszafer** [comment]
you're talking from perspective of only one URI and your knowledge that this URI can throw 404.
I can't write different code for each URI, for me it would be much harder to help other people if I omit logging for some URI's.
If you have an idea how to implement that so everybody can gain something, you're welcome to make PR so I can take a look at it.

**Comment by pswid** [comment]
I understand your point of view, but if certain URI can return a 404 and it doesn't mean error/problem, maybe instead of creating separate routines for each URI, just add to existing code a list of exceptions for which errors/warnings will not be reported?
BTW, apart from `suWiThreshold` error, I also noticed (logged as warning):

```
Logger: bosch_thermostat_client.schedule.ivt_schedule
Source: /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/schedule/ivt_schedule.py:98
First occurred: 07:09:24 (119 occurrences)
Last logged: 09:09:32

URI for Active Program A doesn't exists. Maybe we can figure out how to work anyway
```

This warning occurs when `/heatingCircuits/hc1/operationMode` is set to `manual` (there is no warning if it's set to `auto`). Because, in that case `/heatingCircuits/hc1/activeSwitchProgram` also becomes unavailable (error 404).

**Comment by pszafer** [comment]
Fixed with https://github.com/bosch-thermostat/bosch-thermostat-client-python/commit/001a9e76503d06df44d4d07874abbf7803e52231
If you want you can disable `warning` and `info` level. Those levels should be used for troubleshooting anyway.
