### ISSUE TITLE
After upgrading to  v0.18.0.dev3_2 the intergration dosn't start anymore (KM200 with http)

### ISSUE THREAD

**Issue by Magic01** [bosch-thermostat/home-assistant-bosch-custom-component#163]
**Describe the bug**
After upgrading to  v0.18.0.dev3_2 the intergration dosn't start anymore (KM200 with http)

**To Reproduce**
Update to  v0.18.0.dev3_2 with a KM200 in http mode

**Expected behavior**
Should still work as bevore 

**Screenshots**

Logger: homeassistant.config_entries
Source: custom_components/bosch/__init__.py:309
Integration: Bosch thermostat (documentation, issues)
First occurred: 21:43:40 (1 occurrences)
Last logged: 21:43:40

Error setting up entry RC35 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch/__init__.py", line 145, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 238, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 309, in async_init_bosch
    supported_bosch = await self.gateway.get_capabilities()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 240, in get_capabilities
    if SELECT not in supported and self.switches.selects:
AttributeError: 'NoneType' object has no attribute 'selects'

**Version**
 Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/
-> Not avalable

**Comment by pszafer** [comment]
What firmware version do you have?

**Comment by Magic01** [comment]
KM200 is on 01.10.03

**Comment by dkalinai** [comment]
Have the very same issue unfortunately.

**Comment by pszafer** [comment]
Can you check dev5?

**Comment by Magic01** [comment]
Yes, thanks. It's working again here.
