### ISSUE TITLE
Recording Sensors not available

### ISSUE THREAD

**Issue by Schopenhauer178** [bosch-thermostat/home-assistant-bosch-custom-component#164]
**Describe the bug**
The following recording sensor show not available

Recording ractualCHPower
Nicht verfügbar
 
Recording ractualDHWPower
Nicht verfügbar
 
Recording ractualPower
Nicht verfügbar
  
Recording rsolarYield
Nicht verfügbar although it shows a positive number if there is a solar yield

Which logs do you need?

Best regards...

**Comment by pszafer** [comment]
Logs of component startup. Follow this https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#home-assistant-debugging-log and restart HA.

**Comment by Schopenhauer178** [comment]
I added the logs...
[Bosch Log.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8934235/Bosch.Log.zip)

**Comment by pszafer** [comment]
did you enable `bosch_thermostat_client: debug` ?

**Comment by Schopenhauer178** [comment]
I added to the following to the config and restarted. afterwards I opened system - logs and filtered for bosch....

logger:
  default: warning
  logs:
    frontend: debug
    homeassistant.components.frontend: debug
    custom_components.bosch: debug
    bosch_thermostat_http: debug

**Comment by pszafer** [comment]
replace bosch_thermostat_http with bosch_thermostat_client

**Comment by Schopenhauer178** [comment]
tried it but don't think it changed anything...

[Log Bosch.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/8943479/Log.Bosch.zip)

**Comment by Nakle** [comment]
Disabling and re-enabling 'Use new statistic API' fixed it for me, for a while.
![bilde](https://user-images.githubusercontent.com/3876702/176836867-44a30fe0-37ab-4c34-99a7-4dfd0c9e24f6.png)

**Comment by dannyk79** [comment]
I am facing the same problem. Seems that sensor data becomes unavailable and i have to restart the integration. I am not sure if the sensor data becomes unavailable only after the reset at midnight or during daytime also.

**Comment by pszafer** [comment]
try to enable debug log and maybe some of you can find something. Right now I don't have enough information to help you

**Comment by dannyk79** [comment]
Do you need additional information? seems this happens only every night at 00:00....

**Comment by pszafer** [comment]
should be fixed https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.2
