### ISSUE TITLE
Debug_scan fails if www directory is not present

### ISSUE THREAD

**Issue by daman7cz** [bosch-thermostat/home-assistant-bosch-custom-component#166]
**Describe the bug**
If www sub-directory is not present in config directory, debug_scan fails

**To Reproduce**
Remove www directory and try to run debug_scan

**Expected behavior**
During debug_scan initialize, when opening/appending /config/www/bosch_scan.json, please add check for www directory existence. If not existing, then create it.

**Screenshots**
n/a

**Version**
  - HA Core 2022.6.6
  - HA Bosch component version 0.18.0.dev5
  - Python Bosch HTTP client version?

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#bosch-system-scan-via-raw-scan
![image](https://user-images.githubusercontent.com/690510/174803745-b266d6fd-c13d-4f31-b549-dbcccb5de451.png)

Integration is not allowed to create dir for you.

**Comment by daman7cz** [comment]
It see now. It's a pitty.

Thank you
