### ISSUE TITLE
Please add UUID screenshot to debug_scan wiki page

### ISSUE THREAD

**Issue by daman7cz** [bosch-thermostat/home-assistant-bosch-custom-component#167]
**Is your feature request related to a problem? Please describe.**
After new Home Assistant core, UUID must be given manually. However the process of passing this string is not straightforward for people doing it for first tome.

**Describe the solution you'd like**
It would be better to update the wiki page https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices#start-the-bosch-thermostat-debug_scan to show where/how to do it. 

**Describe alternatives you've considered**
Otherwise people less skilled in Home Assistant will ask or might ask each one by one in discussion forum.

**Additional context**

Thank you.

**Comment by pszafer** [comment]
Done.
