### ISSUE TITLE
Energie sensor in m3 instead of kWh

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#169]
I'm using a CT200 and it works very good, thanks for all you've done !

I just discover the gas statistic sensor and put it in the energy dashboard and it works !

but the unit is kWh, it could be more useful to have it in m3 since the conversion between m3 and kWh change accross months (according to my gas provider)
For information EasyControl app displays information using m3 too

**Comment by pszafer** [comment]
maybe next month I can try to implement it. Unfortunately bosch gives kWh so it would be another hack...

**Comment by doudz** [comment]
Looks like Bosch easycontrol  app use a fixed factor to convert kWh to M3 : 8.125
Anyone could confirm ?

**Comment by doudz** [comment]
According to my gas provider , in May I have used 22m3 , converted to 240.9kWh (factor is 10.95)

but the Bosch app reports 30.02 m3 and 243.88kWh

Who's right?

**Comment by pszafer** [comment]
AFAIK In Poland Easycontrol uses `0.1231` factor -> kWh * 0.1231 = m³

**Comment by doudz** [comment]
It's the same 1/0.1231 = 8.1234 so near what I found

**Comment by dannyk79** [comment]
The value depends on the gas you use. Different gas has different compression and energy values. Also it depens if you have L or H-Gas L-Gas is nearly 8-9 kwH/m3 and H-Gas is nearly 12 kwH/m3. I created a sensor for that: 

`  
sensor:
  - platform: integration
    source: sensor.recording_ractualpower
    name: energy_spent
    unique_id: "energy_spent"
    round: 2
    method: left

- sensor:
      - name: "Gas consumption"
        unique_id: "gas_consumption"
        device_class: "gas"
        state_class: "total_increasing"
        unit_of_measurement: "m³"
        state: >
          {% set kwh = states('sensor.energy_spent') | float %}
          {% set condition_value = 0.9421 | float %}
          {% set calorific_value = 11.369 | float %}

          {{ ( kwh/(condition_value * calorific_value) ) | round(1) }}`

**Comment by istvanSA** [comment]
Is there any update possible on this i'm running into the exact same issue

**Comment by Mrtony94** [comment]
Hi!, some update about this implementation?

**Comment by pszafer** [comment]
I have much troubles implementing it, it doesn't work as expected. I doubt I'd have time in near future to make this work.
Use template sensor as above or use kWh...

**Comment by doudz** [comment]
I think you can drop this function, it's not very useful
for me you can close this issue
