### ISSUE TITLE
"external"-state with new API

### ISSUE THREAD

**Issue by busaku** [bosch-thermostat/home-assistant-bosch-custom-component#170]
If i activate the new API in config, my record data will got weird data:

![image](https://user-images.githubusercontent.com/25269085/177278387-71734f13-5ea4-4ce7-8a19-bf82c5167056.png)

I cant import "old-Data" got an error.
![image](https://user-images.githubusercontent.com/25269085/177279004-df960ff4-5d8c-421b-b3a1-8d048fdd11d2.png)

**To Reproduce**
Just enable new API

**Expected behavior**
Got record-values

**Screenshots**
![image](https://user-images.githubusercontent.com/25269085/177278512-218178b8-36e4-4b83-8a7c-8e042a17023b.png)
![image](https://user-images.githubusercontent.com/25269085/177278541-2a5f3e80-a13a-418a-9c79-212346b49d5d.png)

Disabled new API:
![image](https://user-images.githubusercontent.com/25269085/177278626-80ec2fc7-ddad-49d4-bc64-1da1f472d5ed.png)

**Version**
  - HA version 2022.6.7
  - HA Bosch component version 0.18.0a
  - Python Bosch HTTP client version (?)

** Debug SCAN **
** IMPORTANT **
![image](https://user-images.githubusercontent.com/25269085/177278897-7c408946-c273-429c-8153-e81395d933f7.png)

**Comment by pszafer** [comment]
read https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support

**Comment by busaku** [comment]
Thanks,

but so i dont get (central heating data). Just:
![image](https://user-images.githubusercontent.com/25269085/177284059-c66eaa3c-e039-4ca7-8399-558983783b56.png)
(and these values are always the same)

and i cant import old history-data
![image](https://user-images.githubusercontent.com/25269085/177284227-43344b87-1501-4e40-8975-64664e9ca460.png)

**Comment by pszafer** [comment]
can you translate error from last screen?

**Comment by busaku** [comment]
Its like..

"Cant execute service bosch.move_old_statistic_data. Unknown error"

On Debug-Service i got error as seen in first post:
"Cant execute bosch.debug_scan. Need array index uuid. Got none"

:)

Thank you.

I have tried new installation of hacs-component, "reinstall" of integration in home assistant with new setup. got the same error.

**Comment by busaku** [comment]
Ah, in log-files i got:

  File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get
    check_loop(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(

if i try to import old stats.

and 2022-07-05 16:06:42 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['uuid']
2022-07-05 16:06:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140067235651344] Error handling message: required key not provided @ data['uuid']. Got None (invalid_format)

if i try to run debug scan

**Comment by busaku** [comment]
(I found the UUID on Buderus App <3)

[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9048651/bosch_scan.txt)

**Comment by pszafer** [comment]
Let me know if it works for you with the newest version.

**Comment by busaku** [comment]
With 12 days old 18.1 ? 
Nope, same error, recording CH power = unknown

**Comment by busaku** [comment]
Error still there with 0.18.2

**Comment by pszafer** [comment]
can you somehow turn on heating for at least 15 minutes? :) I think unknown is because of no heating during last month.

**Comment by busaku** [comment]
May i will try, atm its around 30° here ♨️

**Comment by busaku** [comment]
Runs around 25 minutes, still Unknown

**Comment by busaku** [comment]
I don't know if it's interesting, but in 0.18.3 the bug is thill sere ;)

**Comment by enjikaka** [comment]
I got it working here with new stats api when using the colon-name instead. But how do I rename the entity now? I don't see the colon-entities in the entities config screen?

**Comment by pszafer** [comment]
You can't rename it because those are not entities, those are entries in statistics table.
