### ISSUE TITLE
Doenst start von HA 2022.7.0

### ISSUE THREAD

**Issue by busaku** [bosch-thermostat/home-assistant-bosch-custom-component#172]
**Describe the bug**
Version 0.18.0a doesnt start on 2022.7.0

`Logger: homeassistant.setup
Source: setup.py:298
First occurred: 07:28:03 (1 occurrences)
Last logged: 07:28:03

Unable to prepare setup for platform bosch.sensor: Platform not found (cannot import name 'StatisticsMeta' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py)).`

**Comment by pszafer** [comment]
fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.1
