### ISSUE TITLE
Bosch heat pump CS7001iAW 9 ORE: wrong energy consumption values

### ISSUE THREAD

**Issue by elbielefeld22** [bosch-thermostat/home-assistant-bosch-custom-component#178]
Hello,

**Describe the bug**
Home Assistant shows wrong energy consumption values. It looks like the value is constantly counting up in the same speed but that can clearly not be the case.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/105170107/178160661-052a68c4-202c-4a12-a241-3ab74daa3a6d.png)

**Version**
  - HA version? 2022.7.2
  - HA Bosch component version? 0.18.1
  - Python Bosch HTTP client version? don't know

** Debug SCAN **
** IMPORTANT **
I don't know what uuid to put into the parameter. Where can i find this?

Thanks

**Comment by johannesMangler** [comment]
Hi el,
i do have the same setup and hardware. 
I start with the HA integration but can't connect till now.
What have you typed in for serial device / access token / password?
I tried several but nothing helped.

After connection I could have a look on the energy consumpion :P

**Comment by johannesMangler** [comment]
After using it a week now, on my side it also doen't work.  
"energy consumption" still shows 0 kWh while the water is heated every two days

@elbielefeld22 do you have a solution / work around?

**Comment by pszafer** [comment]
Enable recording sensor if you have those. Disable energy consumption, many people don't have this sensor.
UUID is uuid of your thermostat. It can be found as "Hardware" in Device info.

**Comment by elbielefeld22** [comment]
Hello,
I enabled the energy consumption sensor but still have wrong values:
![image](https://user-images.githubusercontent.com/105170107/180622284-8ca11a26-52a2-4379-ad05-acd416448480.png)

As you can see, the head pump was only running at the following time:
![image](https://user-images.githubusercontent.com/105170107/180622374-1b589bb9-5f6b-4ee5-abd8-0eb8ce100785.png)

Here's the scan file
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9174615/bosch_scan.json.txt)
