### ISSUE TITLE
Temperature Sensor

### ISSUE THREAD

**Issue by woempiej** [bosch-thermostat/home-assistant-bosch-custom-component#182]
Is there a way to use the current room temperature, as a temp sensor?

**Comment by przemoc86** [comment]
I've created new sensor

![image](https://user-images.githubusercontent.com/62384501/179374620-447e3c2c-aec8-4a8c-bfb1-aea6c9ca5260.png)
![image](https://user-images.githubusercontent.com/62384501/179374631-98ab880c-6108-44b3-b986-71146cc01036.png)

![image](https://user-images.githubusercontent.com/62384501/179374626-563094bc-863d-4ab0-bb2c-6f9924fb3cfa.png)

**Comment by woempiej** [comment]
Do I have to put this in the configuration.yaml?

**Comment by przemoc86** [comment]
Yes - and no ;)

The easiest way is to add it to configuration.yaml, but if You're planning to expand Your HA instance, best practice is to divide configuration yaml into pieces.
For example I have:
![image](https://user-images.githubusercontent.com/62384501/179394542-dea38018-664a-49d3-90b4-eb670940d646.png)

so to configuration.yaml 
you have to add
sensor: !include YOURFILENAME.yaml (YOURFILENAME you have to setup - I propose sensor, sensors, etc)

then in newly created file from File Editor, You are adding the code I've provided (don;t forget about correct line setup (via tabulators)

**Comment by woempiej** [comment]
Thank you for the instructions!

![afbeelding](https://user-images.githubusercontent.com/62903344/179398274-942ae092-67e7-41de-90cb-93e8deaed1c4.png)

It was a bit of a puzzel because I had a "sensor:" in the configuration.yaml for waste collection integration.
I copied that in the new "sensors.yaml" file where your template example is in, and deleted it from the configuration.yaml (Devide)
Then I add the sensor: !include

Great!
