### ISSUE TITLE
Update CT200 03.12.00

### ISSUE THREAD

**Issue by lbossle** [bosch-thermostat/home-assistant-bosch-custom-component#183]
**Describe the bug**
Controller updated to 03.12.00 and the integration stopped working.

> There are problems with config of your thermostat.
> You might have unsuporrted firmware version 03.12.00.
> You can create issue on Github, but first
> Go to Developer Tools/Service and create bosch.debug_scan.

I disabled auto updates now, unfortunately it was enabled by default.

**To Reproduce**
1. Update CT200 to firmware 03.12.00

**Version**
  - HA version? 2022.7.2
  - HA Bosch component version? 0.18.1

** Debug SCAN **
https://jsonblob.com/999051998343217152

**Comment by olesj33** [comment]
Same here, just stoppede working. Unsupported firmware.

**Comment by pszafer** [comment]
new version released https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.2
