### ISSUE TITLE
sensor.notifications switched to "unknown error" while an error occurs (I only have one example)

### ISSUE THREAD

**Issue by SmilyHM** [bosch-thermostat/home-assistant-bosch-custom-component#185]
**Describe the bug**
Sensor (sensor.notifications) shows "unknown error" instead of error
Sensor (sensor.health_status) shows "error" <-- that's fine of course

**To Reproduce**
get an error ;-)

**Expected behavior**
sensor.notification = _error-code_ (i.e. 6L 229 B or 6L-229-B or something like that)

**Screenshots**
Won't help i guess

**Version**
  - HA version 2022.07 or 2022.08 (it occures on August 1st)
  - HA Bosch component version v0.18.3
  - Python Bosch HTTP client version? Sorry, where to get version? But I would guess latest...

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
I'm running FHEM in parallel - I'm still in the transition period from FHEM to HA for the last devices. The message out of FHEM was:
"Time: 2022-08-01T20:26:15 -ErrorCode: 6L -AddCode: 229 -Category: B"

It means:
[EN] Flame failed during burner operation
[DE] Flamme während des Brennerbetriebes ausgefallen

I've got the "Error codes EMS control" from https://www.ersatzteile-koeln.de/buderus-fehlermeldung-ems-steuerung/index.php --> it's german only, but also includes informatio how to test / fix / cause.

But don't get me wrong - that would be great as additional information --> but I know this would be a feature-request. ;-)

**Comment by pszafer** [comment]
Attach your bosch scan. My component supports error codes but maybe there is something missing.
https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/aa36e80d9314c2adfca5f49827dea1624ef94eea/bosch_thermostat_client/db/errorcodes_ivt.json

**Comment by SmilyHM** [comment]
Hi @pszafer,

thanks for your quick reply! And I'm sorry for my delay with these answer! The 6L-error occures today again.

My Device is IVT / RC300 --> I found the error in errorcodes_**netfit**.json:

` "6L": {
        "229": {
            "description": "Insufficient ionization current was measured during burning."
        }`

In  errorcodes_**ivt**.json there is no "primary information" like '6L' only the "secondary information" (maybe not needet?). In this case the "unknown error" makes sense, cause there is no '229' entry.

This is the scan from a couple of minutes ago: [bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9402168/bosch_scan.txt)

Thanks and best regards
Sascha

**Comment by pszafer** [comment]
I don't have your scan with error visible, so feel free to attach new scan with notification present.
For now I merged ivt and nefit lists, so component search for all possible errors.
