### ISSUE TITLE
Cannot create IVT / XMPP Configuration

### ISSUE THREAD

**Issue by khaindar** [bosch-thermostat/home-assistant-bosch-custom-component#186]
I cannot create a working XMPP Configuration, as can be seen on the screenshot.
I can't change my Password to a short version, as the Buderus Site only accepts 10 characters with capital letters and special characters. 

**Screenshots**
![image](https://user-images.githubusercontent.com/98260404/183865131-114e663b-b733-4654-b8cd-43d0983a3188.png)
![image](https://user-images.githubusercontent.com/98260404/183865327-1811f17d-8381-412f-b9c3-ae4888fc3850.png)

  - HA version 2022.8.1
  - HA Bosch component version 0.18.3

bosch.debug_scan doens't work :/
![image](https://user-images.githubusercontent.com/98260404/183866199-b76a63a5-4181-47f7-a242-486f1d126aca.png)

Any ideas?

**Comment by pszafer** [comment]
it's not password to Buderus portal but to your device.

**Comment by khaindar** [comment]
![image](https://user-images.githubusercontent.com/98260404/183896919-bc16b4ea-b320-4ffd-9b98-11b0dfde8726.png)
?

**Comment by pszafer** [comment]
last one is password for Bosch device you set during initial setup.

**Comment by khaindar** [comment]
Initial Setup on the Buderus heater (RC310?)

**Comment by pszafer** [comment]
what app do you use?

**Comment by khaindar** [comment]
Oh man i deleted the MyBuderus App and connected the Heater again, set the Password and boom, it works. 
Sorry for the cicumstances!
