### ISSUE TITLE
Unknown device - Cannot connect to Bosch gateway

### ISSUE THREAD

**Issue by stefanoferrario** [bosch-thermostat/home-assistant-bosch-custom-component#188]
After successful configuration I have error "Cannot connect to Bosch gateway".
<img width="1136" alt="Schermata 2022-08-17 alle 18 31 00" src="https://user-images.githubusercontent.com/16150154/185194036-27c8c4c0-c5f3-448b-aad1-df6bb4e8697e.png">

<img width="619" alt="Schermata 2022-08-17 alle 18 37 45" src="https://user-images.githubusercontent.com/16150154/185195011-fc854540-15b1-4997-8802-94216926533c.png">

**Comment by pszafer** [comment]
Attach debug scan, write model of your device.

**Comment by sampl3x** [comment]
I got the exact same issue with my CT-200.

**Comment by thelix** [comment]
Same issue


2022-09-24 21:30:18.486 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-09-24 21:30:18.492 ERROR (MainThread) [custom_components.bosch] Your device is unknown null

**Comment by pszafer** [comment]
Let's close this thread. If you want help, make issue with some meaningful data, not same issue. There are a lot of CT200 around Europe, each one with different version of hardware, some can't be connected via XMPP, I can't help any of you with information `Same issue`. Read wiki, try to make scan, find out your hardware version, reach me on discord etc.
