### ISSUE TITLE
"BoschNumber is overriding deprecated methods on an instance of NumberEntity"

### ISSUE THREAD

**Issue by teaserrr** [bosch-thermostat/home-assistant-bosch-custom-component#189]
Just found this in my logging after HA update to 2022.08:

`2022-08-18 09:45:07.169 WARNING (MainThread) [homeassistant.components.number] custom_components.bosch.number::BoschNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

**Comment by pszafer** [comment]
Do you have the latest version of component?
