### ISSUE TITLE
Open Window Detection eTRV CT200 Bosch

### ISSUE THREAD

**Issue by AxDevl** [bosch-thermostat/home-assistant-bosch-custom-component#190]
In the newest update of the easycontrol app  3.14.0 released a surprising update on Open Window detection for systems that have the eTRV for radiators. I would love to see an entity that basically says if a window is opened or closed if possible! This will eliminate the use of have door/window sensors to turn down the temperature. 

Thanks! Here are some photos - 
![1DDDA2FC-BA1D-459F-B59F-B21702BDC9D5](https://user-images.githubusercontent.com/95246520/187069626-1a97ff45-4112-4a1a-b38b-dd24bb73c03a.jpeg)
![D649DAA2-AE0E-4EA4-AF07-65B2F9241E4D](https://user-images.githubusercontent.com/95246520/187069631-391b5084-f3fd-4432-be40-e3e2ce2f55fb.jpeg)

**Comment by pszafer** [comment]
Attach bosch scan
