### ISSUE TITLE
Add support for error notifications

### ISSUE THREAD

**Issue by gralin** [bosch-thermostat/home-assistant-bosch-custom-component#191]
**Is your feature request related to a problem? Please describe.**

Recently my CT200 controller started flashing with red color. Since I didn't see anything wrong in HA, I've checked the Bosch app. I noticed that there is an active issue with my heater which I should resolve - it suggests to call for assistance. I normally don't use this app as I have everthing I need inside HA, so it's easy to miss this important notification.

**Describe the solution you'd like**

Would be great if we could get information about heater active issues inside HA. I have attached the debug_scan where this error is listed. I think it would be enough to just have a Binary Sensor in HA which would signal that there is at least one active issue, which would suggest to check Bosch app for details.

```json
[
    {
      "id": "/notifications",
      "type": "errorList",
      "writeable": 0,
      "recordable": 0,
      "used": "true",
      "available": "true",
      "value": [
        {
          "act": "A",
          "dcd": "H01",
          "ccd": 5284,
          "orig": "8",
          "dlv": "8",
          "fc": "16",
          "t": "2022-08-18T05:58:39+02:00"
        }
      ]
    }
  ]
```

**Additional context**

[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9440321/bosch_scan.txt)

<img src="https://user-images.githubusercontent.com/3457048/187090633-d16276d1-f789-4e25-8f2e-aa30372c8564.jpg" width="250"> <img src="https://user-images.githubusercontent.com/3457048/187090635-b9099639-c70a-4362-a4ab-98aa36c9d92d.jpg" width="250"> <img src="https://user-images.githubusercontent.com/3457048/187090637-0ee24aec-d93d-4d3d-9b9d-439029924e22.jpg" width="250">

**Comment by pszafer** [comment]
I'd need list of all possible errors in the same scheme as: https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/db/errorcodes_ivt.json

**Comment by gralin** [comment]
@pszafer where did you get that list from? The error code 5284 on that list is exactly the same error code as I see in CT200. Maybe those two are shared cross devices??

**Comment by gralin** [comment]
I have provoked another error (by removint batteries from one of the thermostats). Unforunately I can't find it in the IVT error codes linked above...

![image](https://user-images.githubusercontent.com/3457048/187468574-343bedd1-0a03-487d-a1e7-d5853751a39e.png)

**Comment by pszafer** [comment]
I don't remember, it was long time ago when I get this list...

**Comment by gralin** [comment]
Technician is coming over to my house soon to do routine yearly checkup, I will ask if they have access to complete error code list or how to they obtain more information about it.

**Comment by pszafer** [comment]
Any update about error codes?

**Comment by gralin** [comment]
No luck with the technician. I've sent an email to Bosch but no reply so far. I will keep trying sending emails like Andy Dufresne in Shawshank Redemption 😆

**Comment by comtel2000** [comment]
@gralin you can extract the error codes from pdf manual to a csv or json as contribution for the component ;)

https://www.meinhausshop.de/media/pdf/meinhausshop-6720821143.pdf

**Comment by gralin** [comment]
@comtel2000 thanks for the link, I would be happy to contribute but I still didn't get my hand on the list of errors for CT200. This manual is for different controller. While it looks similar, it doesn't contain all errors that CT200 can report - see below example.

![187468574-343bedd1-0a03-487d-a1e7-d5853751a39e.png](https://user-images.githubusercontent.com/3457048/210524558-182d33eb-82ec-479e-ba0d-04db95bdb275.png)

**Comment by JohnB71** [comment]
There is an option to look for fault codes in another app, called 'Bosch EasyService'. This is an app intended for installers (paid version), but the part to search the fault is free. I have an android version, but I guess a Apple version should also be avalable. 
Go to the three bars at the top left, then select "search error." Here you can type the foult code and you will get a discription and suggestions how to solve the problem. 
Unfortunately you'll find not every error in the list, but I hope it can provide some additional information for you.

**Comment by ks-nss** [comment]
Found these Bosch thermostat errors [here](https://www.bosch-easycontrol.com/gb/en/easycontrol/faqs/#panel-uid-2142987-3-1)

    A84-1870: A low battery has been detected on one of the linked wireless devices. Battery replacement is required.
    A84-1876: The connection to the appliance has been lost. No communication to the appliance is possible.
    A84-1869: The connection to a wireless device has been lost. Devices cannot communicate.
    A84-1871: The valve adaption process needs to be started on one of the linked Radiator Thermostats.
    A84-1872: The valve adaption process failed on one of the linked Radiator Thermostats. Reason: Valve is too tight to operate. Check the mounting of the valve.
    A84-1873: The valve adaption process failed on one of the linked Radiator Thermostats. Reason: Valve operation range is too big. Check the mounting of the valve.
    A84-1874: The valve adaption process failed on one of the linked Radiator Thermostats. Reason: Valve operation range is too small. Check the mounting of the valve.
    A84-1879: The valve adaption process failed on one of the linked Radiator Thermostats. Reason unknown. Check the mounting of the valve.

**Comment by gralin** [comment]
@JohnB71 thanks for the hint about Bosch EasyService app. I've looked inside the APK and they have all the errors nicely structured there in JSON format for different languages: [errors.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10815867/errors.zip)

However they still don't have the EasyControl specific errors. Fortunately @ks-nss found them on the website. I wonder why those are not listed in the EasyService app.

@pszafer do you think we could use the enclosed errors codes? I can merge them with the ones @ks-nss found (I will try to do it for all the languages).

**Comment by gralin** [comment]
What do you think @pszafer about ☝️ ?

**Comment by masterx1981** [comment]
I'm interseted in this, as by now i can't detect a fault from ha.
Thanks!

**Comment by pszafer** [comment]
I'd need error list in English. @gralin are you able to provide such list?

now how to interpret those:
```json
{
          "act": "A",
          "dcd": "H01",
          "ccd": 5284,
          "orig": "8",
          "dlv": "8",
          "fc": "16",
          "t": "2022-08-18T05:58:39+02:00"
        }
```

Structure of JSON error file is:
- primary key is `dcd`
- secondary key is `ccd`
- `act key` is "failure type" key probably
- error class is probably "fc" key

**Comment by gralin** [comment]
@pszafer Here are the erors again, this time containing English version too. 
[errors.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/14813390/errors.zip)

**Comment by pszafer** [comment]
This is how it will look like
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/690510/43f49096-4487-4b58-918b-feecee8e0fdc)

first error as sensor state, next error as attribute.

**Comment by pszafer** [comment]
Ready to be used https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.25.0
Let me know if everything works.
