### ISSUE TITLE
Integration for Bosch CW400

### ISSUE THREAD

**Issue by tamasnyulas** [bosch-thermostat/home-assistant-bosch-custom-component#192]
**Is your feature request related to a problem? Please describe.**
When I try to integrate my Bosch CW400, I get the following error:
> This error originated from a custom integration.
>
> Logger: custom_components.bosch
> Source: custom_components/bosch/__init__.py:145
> Integration: Bosch thermostat (documentation, issues)
> First occurred: 11:51:46 (6 occurrences)
> Last logged: 11:54:27
>
> Your device is unknown null

**Describe the solution you'd like**
I'd like to connect my Bosch CW400 to Home Assistant.

**Describe alternatives you've considered**
Any suggestions how to get it integrated would be welcome.

**Comment by pszafer** [comment]
What app do you use to manage this device?
Can you try follow wiki and make Bosch scan so I'd know what device you have

**Comment by tamasnyulas** [comment]
I have "Bosch HomeCom Easy" v1.9.1 to control my device.
I've tried to follow the wiki instructions, but all I got was certificate verification failures. I assume, I'm either using the wrong parameters, or my device is simply not compatible to respond 🤷

**Comment by pszafer** [comment]
What firmware version do you have?

**Comment by tamasnyulas** [comment]
Software version: 04.08.02
Hardware Version: iCom_Low_NSC_v1

**Comment by pszafer** [comment]
Based on software version it should work. If you want PM me on discord and I can try check out if I can connect to your thermostat

**Comment by tamasnyulas** [comment]
That would be awesome. Where can I find your discord username?

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#first-config-help-needed

**Comment by tamasnyulas** [comment]
Thanks for @pszafer, my issue was that the "internet password" was unknown to me and no matter what password I was trying to use, the error messages during the integration didn't clarify that the issue was not that the device was unknown, but the password was incorrect.

I've ended up resetting the password on the thermostat wall panel and then re-registered the device with a new password. Then things started to work finally :)
