### ISSUE TITLE
Buderus KM200 - Unknown Error Occurred -what values in which field? 

### ISSUE THREAD

**Issue by mwalter665** [bosch-thermostat/home-assistant-bosch-custom-component#193]
I installed the KM200 and the Installation, but by adding the token and password it says unknown error occured, so what are the data for the fields because the logs says:

"_Logger: custom_components.bosch.config_flow
Source: custom_components/bosch/config_flow.py:143
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 11:43:42 (6 occurrences)
Last logged: 11:46:00

Error connecting Bosch at 10.0.0.47 - user intervention: authentication failed: authentication aborted by user_"

So you can see i added the IP 10.0.0.47 - and yes a give this IP every time to the mac adress.

the token is a Data field for the possword from the box. beetween every 4 digits is a hyphen like
AB12-C3DE-fg4h-5Ijk
what must be insert?

my personal password is the password i entered at the last field. is this right? 

I miss my "Username" or the "Loginname" from the KM 200 Box.

**Comment by mwalter665** [comment]
Sorry i read again and find the information to take IVT. so this was the first Mistake. And for all other - the token is without the hyphen

**Comment by Schampanja** [comment]
Hi i think i have the same Problem here?
At first, I do not know what kind of KM (50, 100, 200) i have. How can i find out?
I do know the IP (Hostname is TK-850-JH3E-NET) and i know the token (with the hyphen) from the sticker.
But what is the password? Is it the Bosch ID which i use on the Buderus App? Actually, it does not work.
Maybe someone cn help out with information.

THX a lot 

David
