### ISSUE TITLE
No current system status for IVT RC200 (Bosch heatpump)

### ISSUE THREAD

**Issue by 4timepi** [bosch-thermostat/home-assistant-bosch-custom-component#195]
Hi, I'm attach scan result of my device IVT RC200 (Bosch heatpump).
I'm not able to fetch any information about current status of water heater and pump itself / heating circuit.  Something similar to icons displayed directly on device screen (is water currently heating, is external aggregate working, is heating active). Is it possible to fetch it somehow for my device? Thanks

[bosch_ivt.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9568201/bosch_ivt.txt)

**Comment by 4timepi** [comment]
Yes, that's what I done. Anyway I had hopes for additional statuses possible to fetch from device.

**Comment by pszafer** [comment]
There are no text status in API. I think icon is displayed based on pump modulation
