### ISSUE TITLE
Buderus KM100 - Unknown Model

### ISSUE THREAD

**Issue by MarcelW85** [bosch-thermostat/home-assistant-bosch-custom-component#196]
Hi,

the adapter only shows me an unknown Model and no entities.
It's a Buderus KM100 from 2021.
It's configured as IVT - HTTP.

The debug scan deliveries many details.

What can i do next?

Thanks Marcel

[debug_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9574624/debug_scan.txt)

**Comment by pszafer** [comment]
I can add support for it, but you'd have only sensors as your device doesn't provide heatingCircuits or dhwCircuits

**Comment by pszafer** [comment]
I don't know what ioBroker shows. Scan is fetching data directly from your device, if it isn't present it won't be working.
I'll add your device to my todo list to add.

**Comment by Th0tti** [comment]
I also use the KM100. It would be very nice if you add the device.

**Comment by Th0tti** [comment]
When do you think about adding the Buderus KM 100?

**Comment by calle66** [comment]
I also use the KM200 and have the same problems that it cannot be integrated. Think if the KM100 is running, could I include the KM200 as well?
I would be very happy about an integration.

**Comment by pszafer** [comment]
@MarcelW85 seems something is wrong with your setup.
```
{
      "id": "/system/info",
      "type": "systeminfo",
      "recordable": 0,
      "writeable": 0,
      "values": [
        {
          "Tok": "8",
          "Id": "195", -> boiler
          "Ver": "03.07",
          "No": "303537303038303030303135363837333739303834393000000000"
        },
        {
          "Tok": "16",
          "Id": "0",
          "Ver": "NF00.00",
          "No": ""
        },
        {
          "Tok": "48",
          "Id": "164", -> solar
          "Ver": "NF25.06",
          "No": "323533303037393030303338373737333831313031313500FFFFFF"
        },
        {
          "Tok": "9",
          "Id": "224", -> bosch condens 9000i
          "Ver": "NF35.06",
          "No": "333135343336383332323130313037303030303033313838373337"
        }
      ]
    },
```

Tok: 16 means it is controller, but under id there is no indication what type of controller do you have.
I added bosch condens to list, so integration will appear for you in next version, but you should check your connections anyway.

**Comment by Th0tti** [comment]
It is a controller from Buderus (subsidiary of Bosch).  Behind my KM 100 is a Buderus GB 192 heater.

**Comment by pszafer** [comment]
Done in 0.19.2
