### ISSUE TITLE
missing property for bosch_thermostat_client.circuits.circuit

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#199]
**Describe the bug**
Logger: bosch_thermostat_client.circuits.circuit
Source: custom_components/bosch/water_heater.py:136
Integration: Bosch thermostat (documentation, issues)
First occurred: 14:39:50 (5 occurrences)
Last logged: 14:45:52

You wanted to set None, but it is not allowed dict_keys(['Off', 'high'])
 
smartcontrol has 3 options for water heating in app off/auto/on in the card for that instance I see off/performance/high usage
I cant select performance (which means in smartcontrol app auto option).

**To Reproduce**
tried to change entity state

**Expected behavior**
for central water heating my app has 3 options auto on and off entity shows 3 but one only matches state in app (2 works: on and high performance)

**Version**
  - HA version? 2022.9
  - HA Bosch component version? newset avaliable from hacs
  - Python Bosch HTTP client version? like above

** Debug SCAN **
** IMPORTANT **
doesn't work : NoURLAvailableError

**Comment by MG-Sky** [comment]
debug scan https://file.io/l0LbNK393ljJ

**Comment by Bigglesuk** [comment]
I've found the same problem with mine, but didn't realise (from the subject) it was the same issue until I did some further logging to get the error message.
[https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/203](url)

**Comment by pszafer** [comment]
Fixed in 0.19.2

**Comment by Bigglesuk** [comment]
I've tested and can now set the HW to Performance, looks good thanks @pszafer
