### ISSUE TITLE
add entity for "/dhwCircuits/dhw1/temperatureLevels/high"

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#203]
**Is your feature request related to a problem? Please describe.**
is it possible to add an entity for "/dhwCircuits/dhw1/temperatureLevels/high" it would be perfect to add a switch or input number to change (display) hot water temperature in the tank.

 the scan result:
"/dhwCircuits/dhw1/temperatureLevels/high",
      "type": "floatValue",
      "writeable": 1,
      "recordable": 0,
      "value": 49.0,
      "used": "false",
      "available": "false",
      "unitOfMeasure": "C",
      "minValue": 10.0,
      "maxValue": 80.0,
      "stepSize": 1.0
    },

**Describe alternatives you've considered**

**Additional context**

**Comment by pszafer** [comment]
You can manage dhw1/temperatureLevels in water_heater entity. I won't add second way to manage it as it could break water_heater entity and add unnecessary API calls.

**Comment by MG-Sky** [comment]
thanks, the problem with it is that you cannot get value/manage the temp of the tank if you have selected auto mode. I understand the value is displayed in water_heater.dhw1, right? so if I have "performance" mode I cannot get current setpoint of the water nor change it. btw. thanks for such component it's really gr8!
