### ISSUE TITLE
Switch hc1 / hcx to off from frontent or get real state on frontend

### ISSUE THREAD

**Issue by honikos** [bosch-thermostat/home-assistant-bosch-custom-component#204]
**Is your feature request related to a problem? Please describe.**
I use Bosch custom component v0.18.3
HTTP -> IVT 
Logamatic HMC300, Gateway iCom_Low_NSC_v1, firmware 04.08.02.

**Describe the solution you'd like**
The debug scan tells me I can't switch off hc1, despite it's now off. This was achieved with the remote-controll rc100 (Bosch). If I set RoomSetpoint lower than 5, the screen on rc100 allows me to switch off the hc1.
On lovelace I can't set temperature lower than 5.5 degree (also said in debug_scan).
```
{
      "id": "/heatingCircuits/hc1/currentRoomSetpoint",
      "type": "floatValue",
      "writeable": 0,
      "recordable": 0,
      "value": 0.0,
      "unitOfMeasure": "C",
      "state": [
        {
          "off": 0.0
        }
      ]
    }
```
With ems-esp it seems to be possible to switch off hc.
https://github.com/emsesp/EMS-ESP32/blob/main/src/devices/thermostat.h   (example rc100h)
Sometimes I have an update on Lovelace that the hc1 is off, but usually the frontend hc1 is on (heating) even it was turned off with rc100.

**Describe alternatives you've considered**
Is it possible to 
1. get the real state of hc1 to the frontend or 
2. even switch the rc100 or heatpump.hc from frontend?

**Additional context**
[bosch_debug_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9697144/bosch_debug_scan.json.txt)

debug_scan.json

**Comment by pszafer** [comment]
Now real state is displayed in frontend. I couldn't figure it out how to implement state off.
