### ISSUE TITLE
Optimisation for update in HA

### ISSUE THREAD

**Issue by AxDevl** [bosch-thermostat/home-assistant-bosch-custom-component#205]
Asked to make an issue for future update.

Hi, so little story. I've got a tablet mounted on a wall running the integration which is perfect.

I'm using mushroom climate cards for my config in a popup and I'm trying to make this as user friendly as possible, very bare minimals.

So when you change the temperature, the temperature changes straight away to bosch thermostats which is great. However, it takes about 30s to change in the HA system as it goes through again the thermostat refresh. 

Now lets imagine this, my parents who are extremely anti-tech, come up to the tablet, get the pop-up and changes the temperature and comes out the popup. Then lets say I come up and click the popup (less than 30s) and see the old temperature and want to set it (already set) to a higher temperature, and me thinking i set to my temperature however in this case it will be set to my parents temperature. 

I hope you understand it but basically is there a way to get the set temperature to stay in HA instead of every 30s for the thermostats to get the update.

**Comment by pszafer** [comment]
optimistic mode available in 0.19.x
