### ISSUE TITLE
Boost Mode for heating

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#206]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup the button and two other switches (numbers) for a Boost mode - i can only see it in the debug scan results as there is no any entities for following paths:

/heatingCircuits/hc1/boostTemperature
/heatingCircuits/hc1/boostZones
/heatingCircuits/hc1/boostShortcut
/heatingCircuits/hc1/boostMode
/heatingCircuits/hc1/boostDuration

i have seen the topic on similar topic but for a water heater.

**Describe the solution you'd like**
im wonder how i can setup custom entities for the services as i would like to have option to run boos mode to start heating radiators..

**Additional context**
[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9707371/bosch_scan.txt)

**Comment by pszafer** [comment]
boostTemperature, boostMode, boostDuration added in 0.19.x
