### ISSUE TITLE
Ct200 no havc mode off, only auto/heat

### ISSUE THREAD

**Issue by streetjumper16** [bosch-thermostat/home-assistant-bosch-custom-component#207]
Hello,

Is it possible to switch off the bosch thermostats via the ct 200?  This is possible with the bosch controller!

**Comment by pszafer** [comment]
If it's possible by device then make scan when thermostat is ON, then make scan when it is OFF and attach those scans

**Comment by streetjumper16** [comment]
The thermostat itself can switch off, but this cannot be done when connected to the Bosch CT200.  If I connect it to the Bosch Smart Home Controller it is possible.

**Comment by pszafer** [comment]
Don't repeat yourself, I need 2 scans as mentioned above

**Comment by webeling67** [comment]
I don't understand a HAVC mode. The Easycontrol app is showing a Lock of the smart thermostat to prevent children to play around with the setting. But it is not Heating Mode switch on smart thermostat on the radiator. CT200 itself has also no control like that in the device.

Or is this about the setting of the heating circuit and it's ability to  have a control based on outside temperature? There we have a Summer/Winter setting switch. But that is already a hierarchical setting.

**Comment by ivosas22** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Trace-File-of-Communication-with-Bosch-Device-(Dev-Raw-Scan)

Guide on how to make a scan, OP needs this to help you
