### ISSUE TITLE
Bosch Compress 7001i Firmware update no data with 04.08.03

### ISSUE THREAD

**Issue by rhehl** [bosch-thermostat/home-assistant-bosch-custom-component#208]
Today after getting a update of the "energy manager app", i got offered to do a firmware update to my HeatPump internet gateway.

From 04.08.02 to 04.08.03.

After restarting Homeassistant, i cannot see any data.

I deleted and did a fresh setup of the heatpump integration, connection is via IVT XAMPP.

After this the Devices count dropped from 6 to 1 without any entitys.

[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9710383/bosch_scan.json.txt)

**Comment by honikos** [comment]
Thanks for Information.
I have a Buderus heat pump. Technically it could be same as yours. And I think its only rebranded to Buderus.

With firmware 05.08.02 I use HTTP -> IVT   and not IVT XAMPP.
So maybe its worth a try. Don't forget reboot homeassistant after changing configuration.

**Comment by rhehl** [comment]
@honikos sry, but this rly doesn't help, in your other comment you sayd you have "04.08.02", like i had before update. And by Comparing your scan with mine i there we both have set the "/system/brand" value set to "unknown"

I would expect then if i can do a bus scan of the heatpump it's not a problem of which connection mode i use, especialy if the same method worked, before a small firmware patch.

**Comment by rhehl** [comment]
I get the error "You might have unsuporrted firmware version 04.08.03"
Looks like in the client lib the "040803.json" mapping for the new 04.08.03 Firmware is missing.
https://github.com/bosch-thermostat/bosch-thermostat-client-python/tree/dev/bosch_thermostat_client/db/nsc_icom_gateway

**Comment by rhehl** [comment]
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9731551/bosch_scan.json.txt)
Another scan, now while Heatpump is active

**Comment by pszafer** [comment]
04.08.03 should be supported in 0.19.2
