### ISSUE TITLE
Switch BoostMode no reaction.

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#211]
**Describe the bug**
Boost mode switch - no change , 
also is it possible to change BoostMode Temperature to be 0.5 step size not of 1C?

**To Reproduce**
when you toggle boostMode switch it backs to the OFF after 30seconds no logs no debug information
from Service call it works

**Version**
  - HA version? 2022.09
  - HA Bosch component version? 19.3
  - Python Bosch HTTP client version? no

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9745952/bosch_scan.json.txt)

**Comment by pszafer** [comment]
Need more logs. It's should be working...

**Comment by MG-Sky** [comment]
what kind of info do you need?

**Comment by pszafer** [comment]
logs what happened when you turned on switch

**Comment by MG-Sky** [comment]
ok dunno why but now it works :)
