### ISSUE TITLE
KM 100

### ISSUE THREAD

**Issue by Th0tti** [bosch-thermostat/home-assistant-bosch-custom-component#212]
`Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:238
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 15:15:27 (3 occurrences)
Last logged: 15:15:50

Your device is unknown null`

I use the KM 100. 

2022-10-10 15:16:57.817 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: null
2022-10-10 15:16:57.818 ERROR (MainThread) [custom_components.bosch] Your device is unknown null

**Comment by pszafer** [comment]
Provide Bosch scan

**Comment by Th0tti** [comment]
I cannot run the Bosch Debug Scan in Home Assistant. The service is not available. How can I create the log? Use Home Assistant OS.

**Comment by pszafer** [comment]
try to follow wiki: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Unsupported-firmware
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Run-lib-with-Docker

**Comment by Th0tti** [comment]
Unfortunately I can't run the debug mode.

`2022-10-10 22:38:14.668 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.19.3.
2022-10-10 22:38:14.669 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2022-10-10 22:38:14.669 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as http://192.168.178.31.
2022-10-10 22:38:14.670 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/uuid
2022-10-10 22:38:18.366 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Can't fetch data for update_info Cannot connect to host http:80 ssl:default [Name does not resolve]
2022-10-10 22:38:18.399 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: null
2022-10-10 22:38:18.400 ERROR (MainThread) [custom_components.bosch] Your device is unknown null`

I use the firmware 04.08. A Buderus heater GB192 is connected to my KM 100. I can access the heating in the app.

**Comment by MarcelW85** [comment]
> `Logger: custom_components.bosch Source: custom_components/bosch/**init**.py:238 Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues)) First occurred: 15:15:27 (3 occurrences) Last logged: 15:15:50
> 
> Your device is unknown null`
> 
> I use the KM 100.
> 
> 2022-10-10 15:16:57.817 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: null 2022-10-10 15:16:57.818 ERROR (MainThread) [custom_components.bosch] Your device is unknown null

KM100 was supportet but with the new uodate it isn't supportet anymore.

**Comment by pszafer** [comment]
Still need Bosch scan for this firmware

**Comment by Th0tti** [comment]
Is there anyone who can run the Bosch Debug Scan for km 100

**Comment by vytukas4** [comment]
Here it is
[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9996831/bosch_scan.json.zip)

**Comment by Th0tti** [comment]
Thanks. I hope there will be an update soon.

**Comment by Th0tti** [comment]
When do you think you will integrate the new firmware of the KM 100?

**Comment by Th0tti** [comment]
Thanks. I hope there will be an update soon.

**Comment by comtel2000** [comment]
I run Gb192i with RC300 and integrated KM100 (firmware 4.08.02) without issues.
Maybe it‘s related to the poor performance of the km100.
Just try to reset it via Buderus App (new password)

see: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/171#issuecomment-1176300533

**Comment by Th0tti** [comment]
> I run Gb192i with RC300 and integrated KM100 (firmware 4.08.02) without issues. Maybe it‘s related to the poor performance of the km100. Just try to reset it via Buderus App (new password)
> 
> see: [#171 (comment)](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/171#issuecomment-1176300533)

Did you select IVT as device type and then http IVT protocol?
What IP, access token and password did you take?

**Comment by comtel2000** [comment]
> Did you select IVT as device type and then http IVT protocol? What IP, access token and password did you take?

yes, IVT HTTP protocol and I don't think you will succeed with my KM 100 credentials ;) 

Choose the IP of your local KM100 + KM100 Gateway PWD or AccessToken + the a new generated Buderus App password

**Comment by Th0tti** [comment]
Did you enter the password from the sticker without the hyphens in the access token?

**Comment by comtel2000** [comment]
yes, choose the gateway pwd from sticker without dashes as token and a new generated Buderus App password as password

**Comment by T1mey** [comment]
I have the same problem with a Buderus Gb192i 

```
2023-01-02 11:57:12.886 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: null
2023-01-02 11:57:12.889 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
```

**Comment by Th0tti** [comment]
I've now tried again to add the integration.  I entered the correct address as the IP address.  As token I used the password without dashes.  I also changed the Buderus password (Bosch ID) from the app again.  I still get the message: unknown model.  I don't know anymore.

**Comment by comtel2000** [comment]
it's not your Bosch ID password

Here a detailed password reset procedure KM100/RC300(310):

- Go to RC3x0 -> Menu - Settings - Reset Internet Password
- Open Buderus App
- remove connected Heater, etc. if present
- Add new device by scan the 2D Code on the sticker
- Buderus app ask for a new password
- enter a new password (do not use special characters)
- use the new password for this integration

With my heater, these steps must be repeated after each power off/on restart of the heater (Gb192i/KM100 firmware 4.08.02)

**Comment by Th0tti** [comment]
Many Thanks.  The problem is solved.  It worked.
