### ISSUE TITLE
Add a control for switch between summer and winter

### ISSUE THREAD

**Issue by moustic999** [bosch-thermostat/home-assistant-bosch-custom-component#215]
**Is your feature request related to a problem? Please describe.**
The sensors for summer winter switch mode and summer winter mode are available, but there is no way to change this directly from home assistant.

**Describe the solution you'd like**
I would like to have an extra entity like a switch which would allow to change the switch mode from forced to temp threshold and a switch to change mode from summer to winter when mode is forced.

**Describe alternatives you've considered**
There is no alternative in home-assistant to control summer / winter mode.

**Additional context**

**Comment by pszafer** [comment]
Attach your scan, for many (most?) people suWiSwitch mode dissapeared from bosch API so it's not possible to add it to HA.

**Comment by moustic999** [comment]
Oh sorry, I was not aware that it disappeared for many people. I still have it.

I tried to change it via send_custom_put service but it does not make any changes....

service: bosch.send_custom_put
data:
  uuid: "xxxxxx"
  path: "/heatingCircuits/hc1/suWiSwitchMode"
  value: "off"

the value is currently set to forced, but the service call above does nothing. 
If I try with my own python call to this URI, it works.

What am I doing wrong ?

**Comment by moustic999** [comment]
I have debug for component set up. I can see update messages of sensors, but when I try to call the service. I don't see anything in logs.

**Comment by moustic999** [comment]
It seems to work, but with a delay, few hours after making test, my wife complained it was cold.... heating was in summer mode.... so it works with delay ;-)

**Comment by pszafer** [comment]
If there is few hours delay it most common device delay. Component would send put immediately.
