### ISSUE TITLE
Gas Consumption in Energy Panels integration

### ISSUE THREAD

**Issue by bruceasd** [bosch-thermostat/home-assistant-bosch-custom-component#216]
I'd like to add gas consumption in HomeAssistant Energy Panel (like in EasyControl App) but no sensor are available in energy panel.

https://www.home-assistant.io/more-info/statistics/

I don't know if it will be possible. Thanks.

**Comment by pszafer** [comment]
Follow wiki: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support
