### ISSUE TITLE
Sensor for current temp

### ISSUE THREAD

**Issue by bruceasd** [bosch-thermostat/home-assistant-bosch-custom-component#217]
Current thermostat temp is only available as a control. It is possible to add a sensor with current thermostat temp?
Thanks.

**Comment by bruceasd** [comment]
Thanks, it works,

**Comment by zbikmarc** [comment]
I am missing this sensor to. Provided solution is indeed simple but looks a bit hacky and I would expect such property to be available as native sensor.
