### ISSUE TITLE
.1 step in desidered temperature

### ISSUE THREAD

**Issue by bruceasd** [bosch-thermostat/home-assistant-bosch-custom-component#219]
It would be possible to set the desired temperature in .1 step and non in .5 steps?
Normally I set between 21.5 and 22 degrees and have few choices: 21.5 - 22.
Sometimes 21.5 is slightly cold and 22 too hot.
I wish I could set 21.5 - 21.6 - 21.7 .......

Thanks.

**Comment by pszafer** [comment]
Provide debug scan and information about device you have

**Comment by bruceasd** [comment]
[Logs.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9844940/Logs.zip)
I have a Bosch CT200.

**Comment by pszafer** [comment]
Minimal step is 0.5

**Comment by pszafer** [comment]
Fixed in 0.19.4

**Comment by bruceasd** [comment]
Thanks, but was fixed in 0.19.4? Minimal step is 0.5 or 0.1? How i can set 0.1 steps?

**Comment by pszafer** [comment]
It allows same step as your device. For Easy control is 0.5. 0.1 is impossible and truly measurements are not accurate enough for 0.1 step
