### ISSUE TITLE
Expose TRV offset values in HA - Feature request 

### ISSUE THREAD

**Issue by emasge** [bosch-thermostat/home-assistant-bosch-custom-component#220]
[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9897015/bosch_scan.txt)
Each TRV has a temperature offset that can adjust the main temperature reading. By exposing this values to HA we can create automations in HA to adjust the TRV temperature based on external sensor. 

   "id": "/devices/device2/etrv/offset",
      "type": "floatValue",
      "writeable": 1,
      "recordable": 0,
      "value": 0.0,
      "unitOfMeasure": "C",
      "minValue": -2.0,
      "maxValue": 2.0,
      "stepSize": 0.5
    },

**Comment by pszafer** [comment]
Do you know if `/devices/` can contain different devices than thermostatic ones?

**Comment by emasge** [comment]
As far as i know, no. CT200 dosent support external sensors or any other device types. Only thermostatic devices (TRV's)
