### ISSUE TITLE
No energy consumption via NewAPI

### ISSUE THREAD

**Issue by igieon** [bosch-thermostat/home-assistant-bosch-custom-component#223]
**Describe the bug**
I use version 0.19.3. I have running IVT by RC300 Firmware: 04.08.02.

I dont have any energy consumption in Homeassistant, but when i disable and enable integration the energy consuption for last days is populated. What can cause this or any help is needed to debug it ?

**Comment by pszafer** [comment]
I need bosch scan first

**Comment by igieon** [comment]
Here is the scan. But its not the problem with integration per se all other thing work and also energy statistics are populated after integration is disabled enabled. I am running home assiatan version: Home Assistant 2022.10.4
Frontend 20221010.0 - latest
[rawscan_953420077.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9868488/rawscan_953420077.zip)
I think this behaviour about not populating energy happens after i upgraded home assistant

**Comment by pszafer** [comment]
Do you have recording sensors enabled?

**Comment by dfarin** [comment]
Same here, v0.19.3 + Firmware: 04.08.02

Reload/restart doesnt help.
Sensors are activated (also try deactivate and activate again)

in Logs i just find warnings like this:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:122
First occurred: 25. Oktober 2022 um 12:12:58 (1 occurrences)
Last logged: 25. Oktober 2022 um 12:12:58

Detected integration that closes the Home Assistant aiohttp session. Please report issue to the custom integration author for bosch using this method at custom_components/bosch/__init__.py, line 471: await self.gateway.close(force=True)

Logger: homeassistant.components.energy.sensor
Source: components/energy/sensor.py:375
Integration: Energie (documentation, issues)
First occurred: 24. Oktober 2022 um 21:09:12 (2 occurrences)
Last logged: 24. Oktober 2022 um 21:09:12

Found unexpected state_class None for sensor.recording_ractualchpower
Found unexpected state_class None for sensor.recording_ractualdhwpower

**Comment by igieon** [comment]
On my side. I check date time on home assistant and i found that my date time was not precise. I am running in docker on nas and nas has it only 1 per week to sync with ntp and i have time skew few seconds now i synced it and energy stat is populated without need to disable/enable integration.
