### ISSUE TITLE
Update of link within Readme.md to Raw Debug Scan Wiki page

### ISSUE THREAD

**Issue by webeling67** [bosch-thermostat/home-assistant-bosch-custom-component#225]
**Describe the bug**
Renaming of Wiki page causes need to update Readme.md

**To Reproduce**
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Raw-Scan-for-the-Bosch-Devices leads to juimp page. 

**Expected behavior**
Direct connection to trace file page. New page at:

https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Trace-File-of-Communication-with-Bosch-Device-(Dev-Raw-Scan)

**Screenshots**

**Version**
Current Wiki  (30/10/22)

**Additional context**
Jump page created to allow people to find trace file page

**Comment by webeling67** [comment]
I am not used enough to gut to do the change and pull request.

**Comment by pszafer** [comment]
Fixed.
