### ISSUE TITLE
External communication Home Assistant Bosch CT200 Thermostat

### ISSUE THREAD

**Issue by MarkRoks** [bosch-thermostat/home-assistant-bosch-custom-component#227]
Hello,

I have the Bosch CT200 thermostat integration running within Home Assistant v2022.10.5. This works perfectly with the HA app. and HA dashboard.

It is possible to read/adjust the measured/desired temperatures, to which the thermostat reacts.

However, is this also possible externally, through an API or MQTT to HA? For MQTT, I don't see the thermostat integration available within HA, while MQTT is running within HA integrations. While other integrations are visible within MQTT, which also run within HA.

What is the interpretation of the required rules (API or MQTT) to get things working externally? I can't resolve the required information.

I have tried a HTTP request with an API, which works like this; **http://homeassistant:8123/api/states/climate.livingroom** where I'm sending the following JSON; **{"state":"heat","attributes":{"temperature":21}}**. HA is then a few minutes upset (no display in dashboard) and does not respond to anything. Am I doing something wrong within the API?

I like to hear it.

Regards,

**Comment by pszafer** [comment]
This integration doesn't communicate through mqtt.
It uses bosch xmpp api and provide states to HA.
