### ISSUE TITLE
Bosch integration not working after HA update 2022.11.2

### ISSUE THREAD

**Issue by M4v3r1cK87** [bosch-thermostat/home-assistant-bosch-custom-component#230]
**Describe the bug**
Bosch integration not working after HA update 2022.11.2

**Version**
  - HA version? 2022.11.2
  - HA Bosch component version? 0.19.4
  - Python Bosch HTTP client version?

**Comment by pszafer** [comment]
provide some logs

**Comment by M4v3r1cK87** [comment]
I've tried to reboot my HA system and now working, so I close this issue.
Thank you so much
