### ISSUE TITLE
Sensor returnTemperature is always 0

### ISSUE THREAD

**Issue by bruceasd** [bosch-thermostat/home-assistant-bosch-custom-component#231]
**Describe the bug**
Sensor returnTemperature is always 0

I would like to have the true value. Thank you.

**Version**
  - HA version? 2022.11.2
  - HA Bosch component version? v0.19.4
  - TC200

[new 1.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/9972294/new.1.zip)

**Comment by pszafer** [comment]
As you can see in the scan, value is 0 in it. It just display what your device is showing.
