### ISSUE TITLE
Missing statistic values

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#233]
I notice some statistic values are missing
I don't know why, is there a way to force reloading the values ?

![image](https://user-images.githubusercontent.com/1262548/202788545-35ab8c4d-126b-4aaa-bfb7-5f4ca07e23f0.png)

**Comment by pszafer** [comment]
I don't think so, you could try to remove 17th from database, it should try to fetch from last avaiable row till now.

**Comment by doudz** [comment]
I tried to delete entries since 2022-11-13 from the `statistics` table but it only reload the previous day
New entries appears just after deleting, I'm not sure the data are fetched from bosch
Any idea ?

**Comment by pszafer** [comment]
Have you stopped HA while modyfing database?

**Comment by doudz** [comment]
I tried both

**Comment by pszafer** [comment]
Check out statistic short table as well

**Comment by doudz** [comment]
there's no value in `statistic_short_term` for that metadata_id

**Comment by doudz** [comment]
`all_stats = (await self._bosch_object.fetch_all()).values() `doesn't work

https://github.com/bosch-thermostat/bosch-thermostat-client-python/issues/31

**Comment by igieon** [comment]
I have same problem with missing statistics. Here is before disabling :
![image](https://user-images.githubusercontent.com/1535798/202996143-b0b05c9d-2d0d-4a17-b9d9-b4efdbc306d1.png)
and here after disabling and then enabling it
![image](https://user-images.githubusercontent.com/1535798/202996295-8be1d3be-6408-42dc-bea8-65c53e2d25ba.png)
Statistics was fixed.
I have reported with #223 , i was thinking that by sync ntp time and date make it fixed but seems not or it was worked for while but as you see in graph its stopped worked probably same time delay will be good when this new api is used.

**Comment by igieon** [comment]
Ok i have found that i have time drift 5 seconds on my nas so probably check time config on your HA. I will see if this happens again meand time drifts

**Comment by doudz** [comment]
no time drift for me
```
timedatectl timesync-status
       Server: 91.189.94.4 (ntp.ubuntu.com)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 2
    Reference: 11FD22FD
    Precision: 1us (-23)
Root distance: 24.085ms (max: 5s)
       Offset: -63us
        Delay: 15.970ms
       Jitter: 276us
 Packet count: 89
    Frequency: -10,551ppm
```

**Comment by igieon** [comment]
@doudz if you disable and enble intragtion is consption populated ?

**Comment by doudz** [comment]
probably... but this time I removed manually all records in the statistics table for the right metadata_id and the component reload all data
