### ISSUE TITLE
Nefit EnviLine monoblock New Firmware Version 03.13.02

### ISSUE THREAD

**Issue by roykrikke** [bosch-thermostat/home-assistant-bosch-custom-component#235]
**Describe the bug**
I have a unknown firmware version and like to ask to add them, please find the raw scan attached.
It is a [Nefit EnviLine monoblock Heat Pump](https://www.nefit-bosch.nl/producten/warmtepompen/lucht-water-warmtepomp/enviline-all-electric-monoblock) with [EasyControl](https://www.nefit-bosch.nl/producten/thermostaten/easycontrol).

**Debug SCAN**
[logging.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10094889/logging.txt)

**Additional context**
I think it's super cool that integration is possible with HA. Thank you for making this possible, thank you for the effort.

**Comment by MG-Sky** [comment]
try restart ha or and integration. open Bosch application and see results

**Comment by roykrikke** [comment]
There are problems with config of your thermostat.
You might have unsupported firmware version 03.13.02.
You can create issue on Github, but first
Go to [Developer Tools/Service](http://springer.local.lan:8123/developer-tools/service) and create bosch.debug_scan.
[BoschGithub](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component)

**Comment by roykrikke** [comment]
> try restart ha or and integration. open Bosch application and see results

No luck.

**Comment by honikos** [comment]
https://github.com/ksya/ha-nefiteasy 

Are there firmeware updates?

**Comment by roykrikke** [comment]
> https://github.com/ksya/ha-nefiteasy
> 
> Are there firmeware updates?

Apparently

    {
      "id": "/gateway/versionFirmware",
      "type": "stringValue",
      "writeable": 0,
      "recordable": 0,
      "value": "03.13.02"
    },

**Comment by honikos** [comment]
>     Are there firmeware updates?

Apparently "03.13.02"

Did you install an app and check if there is an update?

**Comment by pszafer** [comment]
Fixed in 0.20.0
