### ISSUE TITLE
No module named 'aioxmpp'

### ISSUE THREAD

**Issue by FrederikVV** [bosch-thermostat/home-assistant-bosch-custom-component#238]
- Installed HA -> HARC
- When installing the "Bosch Thermostat" integration I receive the GUI err msg:"Config flow could not be loaded: {"message":"Invalid handler specified"}"
- home-assistant.log:
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration bosch: No module named 'aioxmpp'
- aioxmpp is installed (version: 0.13.2)
- Running OS: Ubuntu 22.04.1 LTS

**Comment by pszafer** [comment]
Can't help. You probably have something messed up with yout installation. If you need more guidance please join discord community.
