### ISSUE TITLE
Don't get proper response from setting temperature.

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#239]
This error originated from a custom integration.

Logger: bosch_thermostat_client.circuits.easycontrol.base
Source: custom_components/bosch/climate.py:116
Integration: Bosch thermostat (documentation, issues)
First occurred: 27 November 2022 at 20:54:06 (6 occurrences)
Last logged: 09:20:06

Don't get proper response from setting temperature.

**Comment by pszafer** [comment]
Open new issue and fill it with template. I don't have enough information here.
