### ISSUE TITLE
0.7.1 Name does not resolve

### ISSUE THREAD

**Issue by pszafer** [bosch-thermostat/home-assistant-bosch-custom-component#24]
Checked your 0.7.1. Work ok. Now I can change heating modes. It is great feature. Thanks a lot.
But now I can not change room temp via climate control in lovelace. When I try to do that, I have error:
`bosch_thermostat_http.exceptions.DeviceException: Cannot connect to host 192.168.1.32none:80 ssl:None [Name does not resolve]`

_Originally posted by @probecar in https://github.com/pszafer/home-assistant-bosch-custom-component/issues/11#issuecomment-585660797_

**Comment by pszafer** [comment]
@probecar test it: https://github.com/pszafer/home-assistant-bosch-custom-component/releases/tag/v0.7.2

**Comment by probecar** [comment]
tested:
error: Failed to call service climate/set_temperature. local variable 'target_uri' referenced before assignment
