### ISSUE TITLE
bosch sensor.energy_consumption 10 times to high

### ISSUE THREAD

**Issue by honikos** [bosch-thermostat/home-assistant-bosch-custom-component#242]
**Describe the bug**
Seem to have a format problem. According to sensor.energy_consumption my heatpump has an daily energy consumption > 100 kWh. Whereas between 10 and 25 is appropriate. (sensor sensor.recording_rconsumedenergy is ok)

**To Reproduce**
1. Go to 'sensor.energy_consumption' in bosch-custom-component integration
**Expected behavior**

A value 10 times smaller.

**Screenshots**
not necessary 

**Version**
  - Home Assistant 2022.11.4
  - Bosch custom component v0.19.4
  - HTTP -> IVT
  - RC300, Gateway iCom_Low_NSC_v1, firmware 04.08.02.
 

** Debug SCAN **
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10118119/bosch_scan.json.txt)

**Additional context**

**Comment by christian-nils** [comment]
Hi,

I have the same issue, here is a graph for yesterday's "sensor.energy_comsumption":

![image](https://user-images.githubusercontent.com/2658014/206121428-f7204583-5ae1-4a1e-9b79-0f9d5d54101d.png)

Which look like I consumed 2464 kWh. I consumed 64.82 kWh that day according to my energy meter.

My config is similar to OP:

    Home Assistant 2022.11.4
    Bosch custom component v0.19.4
    HTTP -> IVT
    RC300, Gateway iCom_Low_NSC_v1, firmware 04.08.02.

My debug scan is here -> http://jsonblob.com/1049957328480387072

BTW, what is the difference between _recording_rconsumedenergy_ and _energy_consumption_ ?

Thanks!

**Comment by honikos** [comment]
> BTW, what is the difference between recording_rconsumedenergy and energy_consumption ?
Should be the same. rconsumedenergy seems to be stored in RC300 components (recorder inside, pushes every hour to my device, in kWh, without summing up) whereas energy_consumption value is summing up the energy consumption (both power x time).

**Comment by pszafer** [comment]
`sensor.energy_consumption` is broken since 2 years, for some people it 10 times too high, for other 20x, for other too low.
That's the reason for recording sensors implemenation.
If you want to have entity state recording sensor will be 1 hour shifted as HA doesn't allow to give state from the last hour (data for last hour HH-01 is available from bosch at HH:05).
With NEW API option enabled you can have data only available in energy panel but those data won't be 1 hour shifted as component put those data directly into statistic database (kind of a hack)

**Comment by christian-nils** [comment]
Thanks for the answers, I believe I will keep using `recording_rconsumedenergy` since it seems to be working just fine :) I thank you @pszafer and all the contributors for this very useful HA integration. Have a great day.
C/N
