### ISSUE TITLE
sensor.recording_routputproduced  has no values

### ISSUE THREAD

**Issue by honikos** [bosch-thermostat/home-assistant-bosch-custom-component#243]
**Describe the bug**
For my understanding sensor.recording_routputproduced (recording sensor) records the energy output of my heatpump (eg. in 1 kWh out 3.5 kWh) ... hope I do not misinterpret it.

**To Reproduce**
see recording sensors in the integration

**Expected behavior**
fetch a value 

**Screenshots**
not necessary

**Version**
-  Home Assistant 2022.11.4
- Bosch custom component v0.19.4
-  HTTP -> IVT
- RC300, Gateway iCom_Low_NSC_v1, firmware 04.08.02.

** Debug SCAN **
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10118152/bosch_scan.json.txt)

**Additional context**
-

**Comment by martt1koo** [comment]
I have same issue with all 7 recording sensors. I can get other sensors like supply temperatures. Also recording sensors can be seen in Bosch EasyRemote app. 

IVT
iCom_Low_NSC_v1
Laiteohjelmisto: 04.08.02

Home Assistant 2022.7.5

**Comment by martt1koo** [comment]
Solved. Just had to untick Use new API from integration options.

![kuva](https://user-images.githubusercontent.com/97317605/206565075-8e4294f8-8692-4542-9977-a0c2b4e35a3f.png)

**Comment by pszafer** [comment]
With `New statistic API` data from recording sensors are available only in Energy dashboard.
Withouth New stats API data are available as regular sensor, but are 1 hour shifted. Read wiki for more info https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support

@honikos for output produced you have only zeros
![image](https://user-images.githubusercontent.com/690510/206573293-efc161d4-1711-4dd2-a2b1-ff78b9e8a093.png)

I'll reopen if you have any further questions
