### ISSUE TITLE
Connectivity error on IVT HTTP connection

### ISSUE THREAD

**Issue by maartenweyns** [bosch-thermostat/home-assistant-bosch-custom-component#244]
**Describe the bug**
Error on connection over HTTP:

```
Wrong IP or credentials at *** - Unable to decrypt: 'IVTEncryption' object has no attribute '_key'
```

**To Reproduce**
1. Try and connect via HTTP
2. View HA logs
3. See error

**Expected behavior**
Connection successful or log about wrong password

**Version**
  - HA version: 2022.11.5
  - HA Bosch component version: v0.19.4

**Comment by honikos** [comment]
Install an app on your smarthpne. Choose a password without special character.

**Comment by maartenweyns** [comment]
Yes, re-adding the system to the `myBuderus` app made me set a new password. That worked.
