### ISSUE TITLE
Only get a recordingCHpower value every second hour

### ISSUE THREAD

**Issue by busaku** [bosch-thermostat/home-assistant-bosch-custom-component#245]
**Describe the bug**
recordingCHpower only record every second hour. 

**To Reproduce**
I just go to my energy board

**Expected behavior**
Record every hour

**Screenshots**
![image](https://user-images.githubusercontent.com/25269085/205453601-24e29d96-5179-4901-aa3e-24bc2f92d465.png)

**Version**
  - HA version? 2022.11.2
  - HA Bosch component version? 0.19.4

** Debug SCAN **
** IMPORTANT **
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10147005/bosch_scan.json.txt)

**Comment by busaku** [comment]
![image](https://user-images.githubusercontent.com/25269085/206152428-c2213e58-f1be-464a-88fd-c58210af1dbd.png)

(more info)

**Comment by pszafer** [comment]
Are you able to install bosch lib manually so you could use bosch_cli ?

**Comment by busaku** [comment]
Works with 0.20 again

![image](https://user-images.githubusercontent.com/25269085/206904686-b5990264-e9de-45c8-b2d5-5e5d989c0480.png)

**Comment by busaku** [comment]
![image](https://user-images.githubusercontent.com/25269085/206912127-0a7c8a1e-a779-4b44-ba1c-0bd6fcdf6d5a.png)

Okay, didn't work again. Just todays Data until the Update are shown in energy-dashoard.

what should I do with bosch_cli @pszafer ?

**Comment by pszafer** [comment]
Do you have proper timezone set?

**Comment by busaku** [comment]
Debug-Scan 

`{
      "id": "/gateway/DateTime",
      "type": "stringValue",
      "writeable": 1,
      "recordable": 0,
      "value": "2022-12-12T11:13:27"
    },`

looks good. may one or two minutes incorrect

**Comment by pszafer** [comment]
System zone. One/two minutes shift for database is big issue.

**Comment by busaku** [comment]
HA runs on:
Synology -> VM -> HassIO -> BoschComponent

Checked every single time-settings
Syno fine, VM fine, HassIO fine, Heating fine (i have set the time).

Same issue

**Comment by busaku** [comment]
Issue still there

**Comment by pszafer** [comment]
It should be fixed in 0.21.0. Prerelease is ready to test it: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.0dev1

also, as it took some time to make a fix for me, I added service to manually download one day, so everybody can fix wrong data.
But if you want to fix, then fetch from the oldest day to the most recent day.
The data which is available from the past depends from bosch device, so for some users it is 30 days, for some even 90 days.

**Comment by busaku** [comment]
Looks good, thank you <3
