### ISSUE TITLE
Data missing after update to Home Assistant 2022.12

### ISSUE THREAD

**Issue by olli-dot-dev** [bosch-thermostat/home-assistant-bosch-custom-component#246]
**Describe the bug**
After updating to Home Assistant 2022.12 the integration seems not to be working anymore. 

**To Reproduce**
The sensors "recording..." all changed to state unknown. Seen with the following sensors:
 -  sensor.recording_ractualchpower
 - sensor.recording_ractualdhwpower
 - sensor.recording_ractualpower
 - sensor.recording_ractualtemp
 - sensor.recording_routdoor_t1
 - sensor.recording_rroomtemperature

Neither restarting Home Assistant nor reloading the integration manually did any help!

**Expected behavior**
The sensors used to provide values before updating Home Assistant to 2022.12

**Screenshots**
-

**Version**
 - Home Assistant 2022.12.0
 - Supervisor 2022.11.2
 - Operating System 9.3
 - Frontend 20221207.0 - latest
  - HA Bosch component version 1.28.4
  - Python Bosch HTTP client version?

** Debug SCAN **
** IMPORTANT **
Running debug scan doed not work:
"Fehler beim Aufrufen des Diensts bosch.debug_scan. required key not provided @ data['uuid']. Got None"

**Additional context**
`Logger: homeassistant.helpers.entity
Source: custom_components/bosch/sensor/recording.py:105
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 06:41:21 (828 occurrences)
Last logged: 07:49:51

Update for sensor.recording_ractualpower fails
Update for sensor.recording_ractualchpower fails
Update for sensor.recording_ractualdhwpower fails
Update for sensor.recording_rroomtemperature fails
Update for sensor.recording_ractualtemp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/bosch/sensor/recording.py", line 89, in async_update
    await self._insert_statistics()
  File "/config/custom_components/bosch/sensor/recording.py", line 105, in _insert_statistics
    last_stats = await get_instance(self.hass).async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: get_last_statistics() missing 1 required positional argument: 'types'`

**Comment by pszafer** [comment]
Check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.20.0dev1a

**Comment by wag-cz** [comment]
Hello, I've just tried v0.20.0dev1a on Home Assistant 2022.12.1 and it still doesn't work. It complains about date format now.

Logger: homeassistant.helpers.entity
Source: util/dt.py:188
First occurred: 12:35:07 (336 occurrences)
Last logged: 13:02:37

Update for sensor.bosch_recording_ractualpower fails
Update for sensor.bosch_recording_routdoor_t1 fails
Update for sensor.bosch_recording_ractualchpower fails
Update for sensor.bosch_recording_rsolaryield fails
Update for sensor.bosch_recording_ractualdhwpower fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/bosch/sensor/recording.py", line 89, in async_update
    await self._insert_statistics()
  File "/config/custom_components/bosch/sensor/recording.py", line 127, in _insert_statistics
    end_time = dt_util.as_local(dt_util.parse_datetime(end))
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 188, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not datetime.datetime

**Comment by pszafer** [comment]
Can you test dev2? https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.20.0dev2

**Comment by olli-dot-dev** [comment]
Values are back but seem to be wrong (like double the usage as usual)

**Comment by pszafer** [comment]
Send Bosch scan so we can check. I haven't touched code calculating values

**Comment by HoldorfNico** [comment]
I have exactly the same proplem and no solution. please follow up

**Comment by wag-cz** [comment]
> Can you test dev2? https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.20.0dev2

v0.20.0dev2 works correctly. Thank you for quick fix!

BTW Values are okay for my installation (KM200)

**Comment by doudz** [comment]
Same problem for me using v0.20.0  on HA 2022.12.1

```
2022-12-10 23:17:13.257 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.energy_central_heating fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/home/doudz/.homeassistant/custom_components/bosch/sensor/energy.py", line 90, in async_update
    await self._insert_statistics()
  File "/home/doudz/.homeassistant/custom_components/bosch/sensor/energy.py", line 128, in _insert_statistics
    last_stats = await get_instance(self.hass).async_add_executor_job(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: get_last_statistics() missing 1 required positional argument: 'types'
```

**Comment by pszafer** [comment]
@doudz can you check https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.20.1dev1

**Comment by doudz** [comment]
@pszafer it works ! thank :)

but like the last time, it has only reloaded data for yesterday, not for the previous day (data for 9 and 10th december were missing, 9th is still missing)

![image](https://user-images.githubusercontent.com/1262548/206891792-58eb7020-db04-4e4e-a3d3-87876678a0a8.png)

It would be cool to be able to load missing data since the last stats, not only the "last_entry" 

```

        if not last_stats:
            all_stats = (await self._bosch_object.fetch_all()).values()
            if not all_stats:
                return
            _sum = 0
        elif self.statistic_id in last_stats:
            self._bosch_object.clear_past_data(self._read_attr)
            last_stats_row = last_stats[self.statistic_id][0]
            end_time = datetime.datetime.strptime(
                last_stats_row["end"], "%Y-%m-%dT%H:%M:%S%z"
            )
            _sum = last_stats_row["sum"] or 0
            all_stats = self._bosch_object.last_entry.values()


```

**Comment by schraubgern** [comment]
After the last updates no statistics anymore: 
Home Assistant 2022.12.7 
Supervisor 2022.11.2 
Operating System 9.4 
Frontend 20221213.1 - latest 

Please have a look to other Issue report for this topic with actual debug_scan.

Thanks.

**Comment by pszafer** [comment]
@schraubgern do you use the latest version?

**Comment by ks-nss** [comment]
Running HA in Docker
Home Assistant 2023.2.2
Frontend 20230202.0 - latest

[results_1.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10819560/results_1.zip)

1) I might have a new firmware, there was an outage with Bosch a few days ago and there was new EasyControl App deployed.

2) If I look at the Gas consumption in the Energy dashboard for this week, with today being the 24th.
  24 = Today / So no data till end of day ?
  23 = blank
  22 = blank
  21 = 14.9 / 20.4
  20 = blank
  19 = 19.8 / 18.5

docker run test query --host=xxx --token=yyy --password=zzz --protocol XMPP --device=EASYCONTROL -p "/energy/history?entry=791.0"
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 4.8,
            "d": "23-02-2023",
            "eCH": 26.9,
            "eHW": 15.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}

entry=790
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 6.5,
            "d": "22-02-2023",
            "eCH": 20.4,
            "eHW": 16.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 4.8,
            "d": "23-02-2023",
            "eCH": 26.9,
            "eHW": 15.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}


entry=789
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 9.5,
            "d": "21-02-2023",
            "eCH": 14.9,
            "eHW": 20.4,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 6.5,
            "d": "22-02-2023",
            "eCH": 20.4,
            "eHW": 16.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 4.8,
            "d": "23-02-2023",
            "eCH": 26.9,
            "eHW": 15.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}

entry=788
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 11.2,
            "d": "20-02-2023",
            "eCH": 13.5,
            "eHW": 3.0,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 9.5,
            "d": "21-02-2023",
            "eCH": 14.9,
            "eHW": 20.4,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 6.5,
            "d": "22-02-2023",
            "eCH": 20.4,
            "eHW": 16.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 4.8,
            "d": "23-02-2023",
            "eCH": 26.9,
            "eHW": 15.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}

 
entry=787
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 7.2,
            "d": "19-02-2023",
            "eCH": 19.8,
            "eHW": 18.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 11.2,
            "d": "20-02-2023",
            "eCH": 13.5,
            "eHW": 3.0,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 9.5,
            "d": "21-02-2023",
            "eCH": 14.9,
            "eHW": 20.4,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 6.5,
            "d": "22-02-2023",
            "eCH": 20.4,
            "eHW": 16.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        },
        {
            "T": 4.8,
            "d": "23-02-2023",
            "eCH": 26.9,
            "eHW": 15.5,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}

**Comment by MG-Sky** [comment]
For me only yesterday is empty but this happened also  before I updated the app (SC) – the update of HA helped me to get back 3 from 4 missing days.

 

Ok. After I wrote above sentence, I have pulled  new HA image from docker

Didn’t help 13-02 and 23-02 are blank only. 

 

----

Michal

**Comment by MG-Sky** [comment]
edit, actually data loaded so only 13-02 is empty - can you try reinitialize (restart integration?)
