### ISSUE TITLE
Support for Bosch/IVT air to air heatpump

### ISSUE THREAD

**Issue by Magifi** [bosch-thermostat/home-assistant-bosch-custom-component#247]
Hi,

I have Bosch 8101i heatpump and I can control it through Homecom easy -app. The app itself is quite poor but better than nothing. I knew that this heatpump is not supported device with this integration but still I tried to connect with instructions given. It did go through IVT -config option but like I thought, I got error message: 

"There are problems with config of your thermostat.
Your device is unknown null.
You can create issue on Github, but first
Go to [Developer Tools/Service](http://192.168.0.17:8123/developer-tools/service) and create bosch.debug_scan.
[BoschGithub](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component)"

Any easy way to get this working with HA and Bosch custom component integration or should I just give up?

**Comment by arvids** [comment]
Did you try to follow the instructions and create a scan?

**Comment by Magifi** [comment]
> Did you try to follow the instructions and create a scan?

I tried to follow the instruction "Trace File of Communication with Bosch Device (Dev Raw Scan)" but I can't find "Bosch thermostat: debug_scan" from services. Perhaps because installation didn't go through.

**Comment by ckay111** [comment]
I am at this point too. Any help?

**Comment by robbedoes14** [comment]
I'm also at this point, anybody has some usefull tips ?

![image](https://user-images.githubusercontent.com/120013753/221550522-0e977d07-3442-4188-be8a-32aea377a4c9.png)

**Comment by pszafer** [comment]
Check out wiki and try to make bosch scan, so I can look at it.

**Comment by robbedoes14** [comment]
> Check out wiki and try to make bosch scan, so I can look at it.

ok, will do.........one thing is also some confusing to me. In the instructions the following is noted: 

"_For the IVT you must enter the IP-address of the gateway, the device access token and the password you defined in the EasyRemote app. Please find the IP address for your device in your network router._"

Questions = 
1) Do I have to enter the IP-adress of the gateway of my router ??
2) the IP-adress of the device is in my router a different one, then the one that is on the sticker of my IP-module. Which one should i enter?

**Comment by robbedoes14** [comment]
so what to fill:

![image](https://user-images.githubusercontent.com/120013753/223682207-08efe9e4-2b17-46df-a0d3-22f97c66cd9f.png)

**Comment by robbedoes14** [comment]
I use the Nefit ProControl app, and that is working all well

**Comment by pszafer** [comment]
ad 1. IP of your bosch KM200/KM100 or gateway you have.
ad 2. the one which it uses, sticker probably show default IP

**Comment by robbedoes14** [comment]
oke......I filled in the correct ip-adress (the one that is used by the IP-module (= same MAC-adress as on the sticker) and use the login name and password I used in the Nefit ProControl app.........error message: "_The IP adress or login name or password is wrong_".

So what to do now ? Because now I can't follow your wiki to trace file of communication with bosch device, because there is no device detected with your integration. I tried so many options, but I don't seem to get true....Any advice / help / suggestions ??

**Comment by pszafer** [comment]
try without HA https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-Run-lib-with-Docker

**Comment by robbedoes14** [comment]
Hi pszafer, thnx for the reply and the helping hand. But....the instructions and the needed handling is far too difficult for me. I'm not a programmer and don't understand programming language, and I'm more a noob in this world (I don't even know what "_Running lib_" is). I just run HA supervisor version on a Synology NAS, and this is way beyond. I like to learn but I think this is my endpoint here.......sorry.

**Comment by pszafer** [comment]
If anybody here feel so, you can contact me directly on Discord and I can check if it's possible to integrate this heat pump into HA.
For now I'm closing this issue. If there will be any news I'll inform here.

**Comment by robbedoes14** [comment]
> If anybody here feel so, you can contact me directly on Discord and I can check if it's possible to integrate this heat pump into HA. For now I'm closing this issue. If there will be any news I'll inform here.

And on which Discord-channel can I find you ? Some checking needed.
