### ISSUE TITLE
Junkers CT100 thermostat configuration

### ISSUE THREAD

**Issue by joanvaque** [bosch-thermostat/home-assistant-bosch-custom-component#25]
Hi everybody,

First of all, thank you very much for developing this custom component, and in second, I would like to apologize for my poor English level.

I would ask you about my HA installation, I’ve tried different ways to connect my Junkers CT100 without success, I know that your development is for Bosch thermostats, but Junkers CT100 is made from Bosch, because Bosch is the Main Company and they make different models as Bosch, Junkers and Buderus.

I’ve download your Github code from **https://github.com/pszafer/home-assistant-bosch-custom-component** and I’m trying to configure all in HA in order to obtain the must simple value of my thermostat, the temperature, I’ve copied your **bosch** folder in **custom_components** folder, and I’ve added on **configuration.yaml** the values that you refer.

Well, to be honest, I'm not sure if I've done the correct steps, I'm new in HA.

There are my steps:

1. I've downloaded your github component
2. I've copied the bosch folder with all your files in my custom_components HA installation
3. I've added in configuration.yaml what I've have described you (described below)
4. I've restarted my HA

bosch:
  address: 192.168.1.33
  password: 080xxxx
  access_token: 4eswvUxL5ssxxxx
  sensors:
      - return

But, unfortunately, nothing occurs, in Entities don't appear any Bosh entity, thanks in advance, and sorry for my ignorance.

Joan

**Comment by pszafer** [comment]
Delete config from tank file and try to follow this tutorial https://github.com/pszafer/home-assistant-bosch-custom-component/wiki/Integrations-config

**Comment by pszafer** [comment]
After checking out your device. Unfortunately CT100 is not supported for now.
It is cloud only device. I will check if I can add support for it somehow.

**Comment by joanvaque** [comment]
Hi Pawel, thank you very much for your response and for your investigation, I appreciate your attention with my intention of integrate a Junkers CT100 thermostate in HA, I’ll follow your progress with interest. Thanks in advance.

**Comment by pszafer** [comment]
Hi @joanvaque , can you test this release - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.8.4

**Comment by joanvaque** [comment]
Hi Pawel,

First of all, thank you very much for your dedication, I'm going to test it
and I'll give you feedback about it.

Thanks in advance.
Joan

**Comment by joanvaque** [comment]
Hi Pawel, I've updated my HomeAssistant version to 0.109.1, and I've added bosch folder on custom_components folder, and my question is, but, what I've to add on configuration.yaml ?

Thanks in advance.

**Comment by pszafer** [comment]
go to integration page and find `bosch`

**Comment by joanvaque** [comment]
Hi Pawel, I've added Bosch Integration, but don't appear anything on Entities Section, but on Registry appears this message:

Detalles de registro (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/bosch/__init__.py:166
First occurred: 17:29:14 (2 occurrences)
Last logged: 17:39:03

Error setting up entry Unknown for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/bosch/__init__.py", line 97, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 166, in async_init
    manufacturer=self.gateway.device_model,
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_client/gateway/nefit_gateway.py", line 44, in device_model
    return self._device.get(VALUE, "Unknown")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by joanvaque** [comment]
Hi Pawel, I've added Bosch Integration, but don't appear anything on
Entities Section, on Registry appears this message:

Detalles de registro (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/bosch/init.py:166
First occurred: 17:29:14 (2 occurrences)
Last logged: 17:39:03

Error setting up entry Unknown for bosch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in
async_setup
hass, self
File "/config/custom_components/bosch/init.py", line 97, in
async_setup_entry
return await gateway_entry.async_init()
File "/config/custom_components/bosch/init.py", line 166, in async_init
manufacturer=self.gateway.device_model,
File
"/usr/local/lib/python3.7/site-packages/bosch_thermostat_client/gateway/nefit_gateway.py",
line 44, in device_model
return self._device.get(VALUE, "Unknown")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pszafer** [comment]
Can you try now with version 0.8.6. There should be some error with your product id.
The best way to help you would be if you contact me on discord (read README how to login).

**Comment by joanvaque** [comment]
I've copied 0.8.6 version on custom_components folder, and I've integrated Bosch another time, but, there is the same problem.

I don't understand how can I contact whit you, I'm new on GitHub and I don't know what is discord, I'm sorry, in any case, I appreciate your help.

Detalles de registro (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/bosch/__init__.py:166
First occurred: 18:26:15 (1 occurrences)
Last logged: 18:26:15

Error setting up entry Unknown for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/bosch/__init__.py", line 97, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 166, in async_init
    manufacturer=self.gateway.device_model,
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_client/gateway/nefit_gateway.py", line 44, in device_model
    return self._device.get(VALUE, "Unknown")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by soflane** [comment]
Does it work now ?
i'm also interested bc I have the same device in the house I rent
