### ISSUE TITLE
Electric Grid Consumption

### ISSUE THREAD

**Issue by Schopenhauer178** [bosch-thermostat/home-assistant-bosch-custom-component#252]
Hi,

I discovered that my Bosch cw 100 controller also stores the electric grid consumption. It would be great to have that as an energy device, so that it can be tracked as a device in the energy board. It is the eltric energy, that is used e.g. for the pump.

I added the raw search and a screenshot of the controller screen. In the screen you can see total consumption and the share for heating or hot water.

Thanks a lot for this great integration!

Best

Sven

[Archiv.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10362531/Archiv.zip)

**Comment by Schopenhauer178** [comment]
Hi, just wanted to ask if you already had a chance to look at the issue? Best Sven

**Comment by pszafer** [comment]
Hi, did you try to enable new api and recording sensors: actualCHPower, actualDHWPower?

**Comment by Schopenhauer178** [comment]
Hi, I see figures for both sensors but do you have a description what they record?

Best Sven

**Comment by pszafer** [comment]
central heating power and domestic hot water power.

**Comment by Schopenhauer178** [comment]
I think we might misunderstand each other. I am searching for a sensor for the electric power. If the heater burns gas to make hot water there is gas consumption but also electric consumption for the circulation pump, Standby and so forth. I see the electric consumption on the heaters monitor and am now searching a corresponding sensor in home assistant.

**Comment by pszafer** [comment]
I don't see any data in your scan which show electric power usage, so it might not be available in API.

**Comment by Schopenhauer178** [comment]
Okay thank you for checking it! Best Sven
