### ISSUE TITLE
HA 2023.1?

### ISSUE THREAD

**Issue by gruessung** [bosch-thermostat/home-assistant-bosch-custom-component#254]
Is it possible to support HA 2023.01?

**Comment by pszafer** [comment]
it is supported

**Comment by gruessung** [comment]
Maybe it would be useful to change the release notes :)? 
![Screenshot_2023-01-10-20-59-34-45_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/433331/211659102-4dba3238-3fb7-4508-9a66-fd20bbdbbc85.jpg)

**Comment by pszafer** [comment]
Sure 😃

**Comment by gruessung** [comment]
Thank you :)
