### ISSUE TITLE
Reboot causes error

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#256]
After a reboot I got an error messages requesting to fill out an issue report.

For some reason it cannot find my bosch thermostat. 

I'm using HA 2023.2.3 supervised installment and the latest HACS installment of the bosch integration.

Please find attached the debug scan.
[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10721255/bosch_scan.json.zip)

Hope this helps.

**Comment by haaino** [comment]
A once again reboot resolved the temporary issue.

**Comment by pszafer** [comment]
It's your network problem probably.
