### ISSUE TITLE
no gas consumption in new hass

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#258]
**Describe the bug**
from 3 days I have no information of a gas consumption also in ha I see following warning
Sensor sensor.energy_central_heating has device class energy, state class None and unit kWh thus indicating it has a numeric value; however, it has the non-numeric value: external (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.energy_hot_water has device class energy, state class None and unit kWh thus indicating it has a numeric value; however, it has the non-numeric value: external (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by pszafer** [comment]
Anything in the logs?

**Comment by MG-Sky** [comment]
after update to newest stats are back only one day is empty, but can you fix the warnings about string value?Od: Pawel ***@***.***>Wysłano: sobota, 18 lutego 2023, 09:11Do: bosch-thermostat/home-assistant-bosch-custom-component ***@***.***>DW: MG-Sky ***@***.***>; Author ***@***.***>Temat: Re: [bosch-thermostat/home-assistant-bosch-custom-component] no gas consumption in new hass (Issue #258)
Anything in the logs?

**Comment by pszafer** [comment]
No, as this entity doesn't have a state, it can't be fixed right now

**Comment by pszafer** [comment]
In next version state if new api used will be `-7`, so HA won't warn in logs.
