### ISSUE TITLE
Add support for optimistic preset updates

### ISSUE THREAD

**Issue by roderik-maker** [bosch-thermostat/home-assistant-bosch-custom-component#259]
**Is your feature request related to a problem? Please describe.**
Changing the preset mode through the HA climate entity takes a while to update. (This causes some family members to keep pressing the button till the new preset state updates.)

**Describe the solution you'd like**
When optimistic mode is on: preset modes update optimistically (just like HVAC modes.)
Basically, add an "async_set_preset_mode" function to the climate entity that is used when  "_optimistic_mode=true"

**Comment by pszafer** [comment]
You haven't provided enough data. bosch scan, your system etc.
It doesn't work as easy as you'd think...
I tried that already, my component doesn't follow regular component update cycle, as I had to figure out upgrade of bosch state in separate API calls (when it wasn't available that easy in HA).
I support multiple device types.
Because of that, there are several possible scenarios of setting preset mode.
Bosch updates API within 1 minute. HA updates state maximum every 30 secs
- set preset mode X to Y
- set optimistic in HA,
- HA entity state update is called
- bosch return **old preset** and it's updated.

My attempt for optimistic update:
- set preset mode X to Y,
- save new state in bosch object,
- don't fetch new data from bosch api for next call
- in next update call fetch from bosch api.
- 
Unfortunately it doesn't work very well because for some people bosch API rejects setting preset mode **after** one minute.

**Comment by roderik-maker** [comment]
Thank you for the quick response and taking the time to explain what you have already tried and why it’s not as simple as I initially thought. 

I haven’t spent enough time looking at your code to fully understand how it works (was hoping to avoid that haha). It’s probably not this simple, but I was wondering if something like the following might work: 

Have the integration keep track of two internal variables: 
- A variable representing the preset.state shown/selected in home assistant: A
- A variable representing the most recently received preset.state from the Bosch API: B

When the User changes to a different preset in HA UI:
	update A
	Send Set to A command to Bosch API

When Bosch API sends update:
	If state B has changed:
		If new B != A:
			# User has made a change in the app, I would argue the Bosch app takes 
			# precedence so update the Home assistant state to the new state from API
			A = B
			Tell home assistant there has been a state change, send A
		Else:
			# Bosch has successfully updated, no further change is needed
			return
	Else:
		# B has not updated correctly so: 
		need to resend SET to A command to Bosch API

When Home assistant wants a state update:
	Tell home assistant the state is A

Sorry if this comes across as naive or if I misunderstood the problem (it’s already late here so I'm pretty tired).

I’ll also have a look myself and see if I can get something working, hopefully I’ll have time later this week. I’ll let you know if I manage to get anywhere useful. 

Oh and also thank you so much for all the time you have already invested into this integration, it has been really great being able to add climate controls to my HA UI.

**Comment by roderik-maker** [comment]
> You haven't provided enough data. bosch scan, your system etc. It doesn't work as easy as you'd think... I tried that already, my component doesn't follow regular component update cycle, as I had to figure out upgrade of bosch state in separate API calls (when it wasn't available that easy in HA). I support multiple device types. Because of that, there are several possible scenarios of setting preset mode. Bosch updates API within 1 minute. HA updates state maximum every 30 secs
> 
> * set preset mode X to Y
> * set optimistic in HA,
> * HA entity state update is called
> * bosch return **old preset** and it's updated.
> 
> My attempt for optimistic update:
> 
> * set preset mode X to Y,
> * save new state in bosch object,
> * don't fetch new data from bosch api for next call
> * in next update call fetch from bosch api.
> 
> Unfortunately it doesn't work very well because for some people bosch API rejects setting preset mode **after** one minute.


So something like this wouldn't work?

```
    async def async_set_preset_mode(self, preset_mode):
        """Set operation preset mode."""
        _LOGGER.debug(f"Setting operation preset mode {preset_mode}.")

        if self._optimistic_mode:
            _old_preset_mode = self._bosch_object.preset_mode
            self._preset_mode = preset_mode
            self.async_write_ha_state()
######################################## Added logic ########################################
        numberOfTries = 4
        for _ in range(numberOfTries)
            status = await self._bosch_object.set_ha_mode(preset_mode)
            if status > 0:
                return True
#############################################################################################
        if self._optimistic_mode:
            """If fail revert back to mode it was back then."""
            self._preset_mode = _old_preset_mode
            self.async_write_ha_state()
        return False
```

**Comment by pszafer** [comment]
this won't work.
- this loop could after several times lock your access to API for a few hours
- after second try you'd get empty response
- after third/fourth you might get 403 Forbidden
