### ISSUE TITLE
Energy can not be inserted into database with 2023.3

### ISSUE THREAD

**Issue by Tuningmormota** [bosch-thermostat/home-assistant-bosch-custom-component#260]
**Describe the bug**

The energy data is not visbile in the "energy" tab. in logfile there are error eintries.

Log Entry:
2023-03-03 15:12:18.561 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.energy_central_heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/bosch/sensor/energy.py", line 89, in async_update
    await self._insert_statistics()
  File "/config/custom_components/bosch/sensor/energy.py", line 151, in _insert_statistics
    if end_time and day_dt.date() <= end_time.date():
AttributeError: 'float' object has no attribute 'date'
2023-03-03 15:12:18.570 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.energy_hot_water fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/bosch/sensor/energy.py", line 89, in async_update
    await self._insert_statistics()
  File "/config/custom_components/bosch/sensor/energy.py", line 151, in _insert_statistics
    if end_time and day_dt.date() <= end_time.date():
AttributeError: 'float' object has no attribute 'date'

**To Reproduce**

Update home assistant docker image from 2023.2.5 to 2023.3
Then start it.

**Expected behavior**

After a day, the last day data is visible in the energy tab. (No error entries in log )

**Version**
  - HA version? 20233
  - HA Bosch component version? v0.20.2
  - Python Bosch HTTP client version? where to find it?

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

this service not executes in my instaes. 
Log: websocket_api script: Error executing script. Error for call_service at pos 1: Error rendering data template: Result is not a Dictionary

**Additional context**
[home-assistant_bosch_2023-03-03T14-12-45.551Z.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10883197/home-assistant_bosch_2023-03-03T14-12-45.551Z.log)

**Comment by MG-Sky** [comment]
in the file /custom_components/bosch/sensor/energy.py  replace line to            
 end_time = datetime.datetime.utcfromtimestamp(last_stats_row["end"])

look for last_stats_row["end"]

**Comment by wag-cz** [comment]
Code proposed by @MG-Sky doesn't work for me - leads to "TypeError: can't subtract offset-naive and offset-aware datetimes" as utcfromtimestamp method creates an datetime object without timezone information while today object has timezone info.

Below code works for me:
`end_time = datetime.datetime.fromtimestamp(last_stats_row["end"], tz=datetime.timezone.utc)`

It is necessary to update both /custom_components/bosch/sensor/energy.py as well as /custom_components/bosch/sensor/recording.py files.

**Comment by MG-Sky** [comment]
thanks I haven't check to recording as my energy stats are written   daily - 8ll change recorder too thanks!

**Comment by Tuningmormota** [comment]
Thanks for the solutions, it looks good again

**Comment by MG-Sky** [comment]
yes, but no data in database.

**Comment by Tuningmormota** [comment]
I have restarted both the server and my app on phone , and the data for the last two days are visible. I always had a 1 day delay in the data. I do not checked the database itself, but I think it
 Is fair to assume they had been read out form the database.  I have changed both of the files simultaneously, and also made a restart of ha server after that.

**Comment by erreesse** [comment]
@wag-cz please forgive me, i'm not a developer, i have not understand what line i had to modify.
can you help me? thanks in advance

**Comment by erreesse** [comment]
after some try&error , i replace:

end_time = last_stats_row["end"]

with:

end_time = datetime.datetime.fromtimestamp(last_stats_row["end"], tz=datetime.timezone.utc)

but i never see gas usage on "energy".
maybe i change the wrong line?

**Comment by pszafer** [comment]
Fixed in v0.21.0 https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.0
Let me know if there are any problems.

**Comment by pszafer** [comment]
@erreesse enable new API (follow wiki) and then add energy: statistic to your graph

**Comment by erreesse** [comment]
> @erreesse enable new API (follow wiki) and then add energy: statistic to your graph

i had to disable "use new statistic API" because , if "enabled" i got negative value in sensor.energy_central_heating

with  "use new statistic API" enabled, i hadn't "energy:" entity !

maybe i miss someting, i followed the "new api wiki" ( https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support ) , but in "configure" i had only 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/42069398/224005185-29c897aa-1836-4bb2-85ba-47d5771a9cb4.png">

i can't : "Enable Recording or Energy (depends of device you have) sensor you want to gather statistic."

**Comment by pszafer** [comment]
@erreesse that's how it is suppose to look. -17 it means it put data directly into statistics table in database.

**Comment by erreesse** [comment]
@pszafer ok. but in "energy dashboard" i see 0 in "gas" ,  i had changed the sensor, from "sensor.energy_central_heating" to "sensor:echenergy_central_heatingexternal"  , bit still 0 in the graph.

i don't have "energy:" or "energy."  to use

**Comment by erreesse** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/42069398/224022595-6942c0ab-cd2b-4bc7-acfc-27687dad752b.png">
