### ISSUE TITLE
Cannot connect to Bosch gateway

### ISSUE THREAD

**Issue by JaroNesvadba** [bosch-thermostat/home-assistant-bosch-custom-component#261]
**Describe the bug**
Today I received the CT200, installed it, and now I try to integrate it with my existing HA. Unfort, I am stuck, and the Bosch integration tile in HA that displays (I masked the SN):

```
Unknown model // Bosch thermostat // Initializing
 or sequentially:
Unknown model // Bosch thermostat // Retrying setup: ('Cannot connect to Bosch gateway, host %s with UUID: %s', '[xxxxxxxxx]', None)
```

**To Reproduce**
After adding the Bosch integration and finishing the set up. I choose the 'EasyControl' (bottom option) option during setup

**Expected behavior**
I would expect the device model to be found, and the device model to be displayed in the integration tile. And subsequently: the integration to complete successfully showing entities et cetera.

When I ran into this issue nad after reading I changed the device password, as well as the Bosch cloud account pw, but that did not help me.

**Screenshots**
![image](https://user-images.githubusercontent.com/33891202/223126448-b205279f-8207-413b-b350-0de78cfd2113.png)

and 

![image](https://user-images.githubusercontent.com/33891202/223130226-48f6752c-c03c-4725-83d1-c4ff23d116e1.png)

**Version**
  - HA version 2023.3.1
  - HA Bosch component version v0.20.2
  - Python version: 3.10.10

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

This service is not available for me in HA; I do not find this entry in the dropdown list.

**Additional context**

part of the error log:
```
[...]
2023-03-06 14:13:31.721 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2023-03-06 14:13:31.726 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2023-03-06 14:14:22.349 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2023-03-06 14:14:22.354 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2023-03-06 14:14:46.007 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2023-03-06 14:14:46.012 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2023-03-06 14:15:32.938 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2023-03-06 14:15:32.944 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
[...]
```

**Comment by filipkotian** [comment]
same problem here

**Comment by JaroNesvadba** [comment]
In addition, some more details on the device itself:

![image](https://user-images.githubusercontent.com/33891202/223366712-decdaeb4-967b-43dc-9f53-f91e1f5fdd3f.png)

**Comment by JaroNesvadba** [comment]
Also, I paid extra attention to the pw, and did a full 'reset' (uninstalling both thermostat (now cloud is also showing all details correctly) and HACS/HA integration) and re-did the whole thing. I hope pw is not / no longer the issue, as that would be a bit silly as a reason for the issue...

But again: to no avail, integration is still not showing the model nor any entity.

**Comment by pszafer** [comment]
hi, 03.02.00 is very old firmware. Maybe 4 years old, anyway Bosch changed xmpp servers for newer firmware and I support only this newer xmpp server. You should ask your technician for update of your device

**Comment by JaroNesvadba** [comment]
Understood, Pawel. 

Today, I spoke to Bosch in the Netherlands and they told me about the roll out of the new firmware, and that it will take a couple of weeks (not to overload their servers...) The devices 'connected the longest' are first served; that means that my device will be touched as one of the latest devices. 

They aim for last week of March for all devices to be updated to the latest firmware.

I now request for closure of this issue #261, awaiting the new firmware to be installed and I will then retry the HA integration. Patience is a virtue...

**Comment by ks-nss** [comment]
I am seeing the same error "Retrying setup: ('Cannot connect to Bosch gateway, host %s with UUID: %s', '101147738', None)"

I am running HA in docker, I did a fresh install of HA today, using the latest release of HA. 
My Firmware is 04.00.00

Here's some of the docker logs if they help...


homeassist-homeassist-1  | 2023-03-09 12:21:22.506 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.21.0.
homeassist-homeassist-1  | 2023-03-09 12:21:22.506 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
homeassist-homeassist-1  | 2023-03-09 12:21:22.510 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as XXXXXXX.
homeassist-homeassist-1  | 2023-03-09 12:21:22.510 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /gateway/uuid by 140105160153008
homeassist-homeassist-1  | 2023-03-09 12:21:23.126 DEBUG (MainThread) [bosch_thermostat_client.encryption.base] Unable to decrypt: b'\xb0\xd8!nL$R\xaaL\xc57\xfb\xc7\x89\xdaC\x98\x02\xac\xb97\xdf\xe71m\xb7\xfcI\xa34\xbe\xc7\x08Z\xdd\x18\x97\xcf\x0cZ\x87v\xdff\xd6\xca\x98}\x05\xc0\x97\xd4\r\x9b\xdfrf}\xe9F\xbc\x05\xc7\xbf\x1a\x190\xe3\x90\xd7\x06\xd8\xb7Q\xf6\xda\x16\xf7,\xf3\xed\xeb\x1cH\xe5\x0f\xaf\x0f\xb6*O\xcb\xe1\x9fV\xbd' with error: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
homeassist-homeassist-1  | 2023-03-09 12:21:23.127 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/uuid
homeassist-homeassist-1  | 2023-03-09 12:21:23.127 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /gateway/uuid: null
homeassist-homeassist-1  | 2023-03-09 12:21:23.127 DEBUG (MainThread) [bosch_thermostat_client.gateway.easycontrol] Can't fetch data for update_info Error requesting data from /gateway/uuid
homeassist-homeassist-1  | 2023-03-09 12:21:23.128 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /system/interfaces by 140105160153008
homeassist-homeassist-1  | 2023-03-09 12:21:23.239 DEBUG (MainThread) [bosch_thermostat_client.encryption.base] Unable to decrypt: b'\xea\x07\xa7\xa9\xbd\x9be:\xc3\x07\xfe\xef\x19\x14\xfdM\'n\x86\xb3\xdf\xf6\xe8\xea\x85\xe0\xa2<\x0b\xc5\xa5B\xd5\xe3\x81i\xb0\xb1s-\xd8bc\xb1\x06J\xcb\xd5\xc9B\xdf\xf9wn\t\xa4\xf9\x1d\xdc\xb7\x89\x14\x9e\xa7\xf0\xed2\xa5\xce\xb3\xd2{\xc0[/\xf7\xbf\xbe"\x19\x97A\xf8Pp\x14qVzr8D\xb4\xbc\xe8\x1c' with error: 'utf-8' codec can't decode byte 0xea in position 0: invalid continuation byte
homeassist-homeassist-1  | 2023-03-09 12:21:23.240 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
homeassist-homeassist-1  | 2023-03-09 12:21:23.240 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /system/interfaces: null
homeassist-homeassist-1  | 2023-03-09 12:21:23.240 DEBUG (MainThread) [bosch_thermostat_client.gateway.easycontrol] Can't fetch data for update_info Error requesting data from /system/interfaces
homeassist-homeassist-1  | 2023-03-09 12:21:23.240 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /gateway/versionFirmware by 140105160153008
homeassist-homeassist-1  | 2023-03-09 12:21:23.353 DEBUG (MainThread) [bosch_thermostat_client.encryption.base] Unable to decrypt: b'\xb0\xd8!nL$R\xaaL\xc57\xfb\xc7\x89\xdaC\xb4\xd4\x8f\x05U\x05S\x14\xb5\x9d \xaf\xc4\xfb\xbb\xad:\x19:\x1a\xa9\xdc\x89\xb9\x01\xc1\x0f\xa8\xc1\x1e\x0cz-\xd4\x1e!\x00\x99\xa2\xbb\x1f\x04\xec \xed\x1f\x96-\xa67\x824\x84\x96t\r\xfc\x8bA\xfee\xb2}P3\x159\x82\xf5\xe8\xb3\xcb\xaa\xb4~\xfd\x06w\xfe\xe7\x05.\xb2\xd4\x8f\xbe\xbbE\x9e9i\xfd#\xb4\x16>' with error: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
homeassist-homeassist-1  | 2023-03-09 12:21:23.353 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/versionFirmware
homeassist-homeassist-1  | 2023-03-09 12:21:23.354 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /gateway/versionFirmware: null
homeassist-homeassist-1  | 2023-03-09 12:21:23.354 DEBUG (MainThread) [bosch_thermostat_client.gateway.easycontrol] Can't fetch data for update_info Error requesting data from /gateway/versionFirmware
homeassist-homeassist-1  | 2023-03-09 12:21:23.354 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /gateway/productID by 140105160153008
homeassist-homeassist-1  | 2023-03-09 12:21:23.455 DEBUG (MainThread) [bosch_thermostat_client.encryption.base] Unable to decrypt: b"\xb0\xd8!nL$R\xaaL\xc57\xfb\xc7\x89\xdaC\xd9i\xd9\xa6Iv\xb6\x15\xa5\xf8?\xd7pr84'\x13r`q]HF64\x86\xba\xe6\xbc\x8a\x95\x89\x81H\xed\xf8\xde\x91Ip\x8dS\xddY%o\xdeZ\xef7\xb7\xef\x81r\xcd\xd3MJ\x9e\x89^*\x87\xd21\xee\x8fk\xb6\x9f2\xa5\xdb)\xfb\xf0\xa4\x12\xbb\xeb(\xe7\x19\xfd\xbb\xa9\x1b\x04?\x89\xc6WUa\xb8" with error: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
homeassist-homeassist-1  | 2023-03-09 12:21:23.456 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/productID
homeassist-homeassist-1  | 2023-03-09 12:21:23.456 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /gateway/productID: null
homeassist-homeassist-1  | 2023-03-09 12:21:23.456 DEBUG (MainThread) [bosch_thermostat_client.gateway.easycontrol] Can't fetch data for update_info Error requesting data from /gateway/productID
homeassist-homeassist-1  | 2023-03-09 12:21:23.456 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /gateway/DateTime by 140105160153008
homeassist-homeassist-1  | 2023-03-09 12:21:23.563 DEBUG (MainThread) [bosch_thermostat_client.encryption.base] Unable to decrypt: b'\xb0\xd8!nL$R\xaaL\xc57\xfb\xc7\x89\xdaCjA\x96\xf8\x06{?\x18\x85\xba\xaa\x19\n\xa3\xb6\x82\xdd\x1f\x1a\x9b2\x03Zq\xc2\xc2\x82\xff1\xcc\xd3%\x9d\x0cV\xb2\xe9*K7\x04\xb5]w_\xecd\xd8\xfa\xeb\xe1Y\x9ao\xb0\xd7\xacK\xf41\x9dm\x9a\x151c\xc8)\x7f+~\x1e\xderX~\xb7\xe5\x8e\x80\xb2\x91\x85>\x1c\xbf\xd3=5Ev_\r\x9ey\x91Z\x01\x94\xe4\xc9\\\x7fn\x14\x9f\x1eL\x8f\xea\x81\xed' with error: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
homeassist-homeassist-1  | 2023-03-09 12:21:23.564 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/DateTime
homeassist-homeassist-1  | 2023-03-09 12:21:23.564 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /gateway/DateTime: null
homeassist-homeassist-1  | 2023-03-09 12:21:23.564 DEBUG (MainThread) [bosch_thermostat_client.gateway.easycontrol] Can't fetch data for update_info Error requesting data from /gateway/DateTime
homeassist-homeassist-1  | 2023-03-09 12:21:23.565 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
homeassist-homeassist-1  | 2023-03-09 12:21:23.568 ERROR (MainThread) [custom_components.bosch] Your device is unknown null

**Comment by pszafer** [comment]
@ks-nss wrong password

**Comment by ks-nss** [comment]
Yes it was my password... How odd, I reset my password to 8 chars a while ago and was using the correct 8 char password.I tried logging out of the app and logging back in again but the 8 char password didn't work anymore, I still had my old password so I tried using that and was able to log in on the app and reset my password again to 8 chars. Wonder if BOSCH had to restore systems from backups after the issues they had recently.

**Comment by Stijnele** [comment]
Here a solution to remove the 8 character password. I don't know enough about programming to translate it for this application. 
  https://github.com/robertklep/bosch-xmpp/commit/0fe6b5fc293848b6e20bc845de04c0f4b02615fd

**Comment by JaroNesvadba** [comment]
Just a quick follow up: it turned out that my EasyControl device had a product defect; I cannot tell what exactly. Bosch helpdesk did the diagnosis remotely. They send me a new device, and after I received it, I could now update to v4 and also I can now connect the HA integration to the device. Tadaaaa!

Now all working as expected...
