### ISSUE TITLE
CT200 firmware 4.0.0 support

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#262]
Bosch has deployed firmware 4.0.0 for CT200 and now integration can't load.

Could you add support for this firmware ?

**Comment by bbartje** [comment]
Same request here

**Comment by bigdmo007** [comment]
Ditto

**Comment by JaroNesvadba** [comment]
Just out of curiosity: my CT200 device is on 03.02.00 as 'actuele firmwareversie'. I do not get the option to update. I bought the device last week and installed it yday. In the 'updates' section it does not show any newer version than 03.02.00. 

How often are updates pushed, I wonder?

**Comment by ivosas22** [comment]
Same here, mods are prob already working on it. Keep up the great work

**Comment by pszafer** [comment]
Fixed in v0.21.0 https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.0
Let me know if there are any problems.

**Comment by bigdmo007** [comment]
Thanks for fixing quickly
