### ISSUE TITLE
Firmware 4.0.0 support

### ISSUE THREAD

**Issue by roykrikke** [bosch-thermostat/home-assistant-bosch-custom-component#263]
Here's [the debug output](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10912359/bosch_scan.json.txt) 4.0.0 firmware.

**Comment by schraubgern** [comment]
New Firmware (4.0.0) from Bosch and Thermostat is not working anymore. Is it possible to prevent this Issue due self updating manifest? Attached you find my Debug Scan. Greetings.
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10921619/bosch_scan.zip)

**Comment by pszafer** [comment]
Fixed in v0.21.0 https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.0
Let me know if there are any problems.

**Comment by bigdmo007** [comment]
Thanks for fixing quickly
