### ISSUE TITLE
Debug scan failed to call service 

### ISSUE THREAD

**Issue by ivosas22** [bosch-thermostat/home-assistant-bosch-custom-component#264]
**Describe the bug**
Failed to call service, error rendering data template. result is not a dictionary

**Version**
  - HA version? 
(2023.2.5)
  - HA Bosch component version?
  4.0.0.
  - Python Bosch HTTP client version?
  v0.20.2

**Comment by gyraksi** [comment]
Did you try this in developer tools? Without uuid: I also had the same error message.
service: bosch.debug_scan
data:
  uuid: "123456789"

**Comment by ivosas22** [comment]
Yes I tried in developer tools. Using the serial number of the ct200 for the uuid. I tried changing the code, but nothing seems to fixSent from my iPhoneOn 8 Mar 2023, at 19:19, gyraksi ***@***.***> wrote:﻿
Did you try this in developer tools? Without uuid: I also had the same error message.
service: bosch.debug_scan
data:
uuid: "123456789"
