### ISSUE TITLE
v0.21.0 extrem high (no realistic) consumptoin

### ISSUE THREAD

**Issue by busaku** [bosch-thermostat/home-assistant-bosch-custom-component#267]
Over the day the gas-consumtion looks fine, but in the morning, the day before today looks like that:

![image](https://user-images.githubusercontent.com/25269085/224246126-6f9d0f15-1645-4701-96dd-44d7f9444597.png)
![image](https://user-images.githubusercontent.com/25269085/224246286-a61fbc34-5622-41c8-a210-ccac7f190fe9.png)
![image](https://user-images.githubusercontent.com/25269085/224246632-295269ef-7b70-4fd5-96d6-5f86e3a8136e.png)

Looks like thit happens ones a day.
Over the day the statistics looks good, and on the next day it will add some really high data.

HA Version 2023.3.1
Bosch-Custom-Component v0.21.0

**Comment by pszafer** [comment]
Provide bosch scan.

**Comment by busaku** [comment]
[debugscan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/10942216/debugscan.txt)

**Comment by busaku** [comment]
Oh, works in the other direction too ;) (negative numbers)
![image](https://user-images.githubusercontent.com/25269085/224552814-35d440a6-f1d2-45f7-827e-9c565601e2cc.png)

**Comment by pszafer** [comment]
can you check https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.1dev1 ?

**Comment by busaku** [comment]
![image](https://user-images.githubusercontent.com/25269085/224833812-46090a35-1948-4108-9393-43ecd3a30c3c.png)

installed, i will provide you feedback :)
thank you

**Comment by busaku** [comment]
![image](https://user-images.githubusercontent.com/25269085/224915275-0ac97a79-e08e-4a7f-b511-6805eaa5f164.png)
unfortunately doesn't look good :(

**Comment by pszafer** [comment]
Check v0.22.1 it should work. I'll reopen if problem still occurs
