### ISSUE TITLE
Setting temperature doesn't work with Program1/Program2

### ISSUE THREAD

**Issue by jlintula** [bosch-thermostat/home-assistant-bosch-custom-component#27]
I have a Bosch Compress 5000 LW ground-source heat pump equipped with a ProControl gateway.  This custom component can connect to the gateway with no problem, and I can access some of the data it provides (namely outdoors and water heater temperatures).

I'm trying to feed my indoor temperature sensors' temperature from Home Assistant to the heat pump so that it would adjust its heating accordingly. This works, but only partially. To actually be able to set the target temperature so that it has any meaning, the heat pump must not be in the "Optimized usage" aka HP_OPTIMIZED switch program, it must be in Program1 or Program2. As we discussed in Discord with pzsafer, the hvac_mode exposed to HA maps "auto" to HP_OPTIMIZED, "heat" to Program1 and "heat_cool" to Program2. 

With hvac_mode set to match Program1 or Program2, editing the temperature from HA gives this message to the logs:

```
2020-04-02 08:40:00 DEBUG (MainThread) [custom_components.bosch.climate] Setting target temperature 22.0.
2020-04-02 08:40:00 ERROR (MainThread) [bosch_thermostat_http.circuit] Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!
2020-04-02 08:40:00 DEBUG (SyncWorker_1) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-04-02 08:40:00 DEBUG (SyncWorker_1) [bosch_thermostat_http.circuit] Current temp of HC1 is {'value': 22.0, 'minValue': 10.0, 'maxValue': 35.0, 'unitOfMeasure': 'C'
}
```
Based on what I see, there's one workaround to make the temperature setting work for a while:
* Set hvac_mode to auto. In this mode, the component happily updates the temperature: ```2020-04-02 08:54:32 DEBUG (MainThread) [custom_components.bosch.climate] Setting target temperature 22.0.
2020-04-02 08:54:32 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending PUT request to /heatingCircuits/hc1/temperatureLevels/normal
2020-04-02 08:54:32 DEBUG (MainThread) [bosch_thermostat_http.circuit] Set temperature for hc1 with result True
2020-04-02 08:54:32 DEBUG (SyncWorker_7) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-04-02 08:54:32 DEBUG (SyncWorker_7) [bosch_thermostat_http.circuit] Current temp of HC1 is {'value': 23.5, 'minValue': 10.0, 'maxValue': 35.0, 'unitOfMeasure': 'C'}```
* In the HP_OPTIMIZED mode however, the heat pump does nothing with the set temperature.
* Now, if I set the heating program to Program1 or Program2 in the heat pump console, the values set in Home Assistant actually affect the heating.
* At some point in the future (might take hours and I'm not sure why), the component realizes the program is not at HP_OPTIMIZED and actually switches the program back, at which point the set temperature in HA does nothing again. I can set the hvac_mode back to heat_cool or heat, but then setting temperature stops working from HA.

Home Assistant version 0.107.7, HA Bosch component 0.7.2. 
Here's bosch_scan.json done when hvac_mode was set to heat_cool and setting temperature didn't work: https://jsonblob.com/6bf574c4-74a7-11ea-a7d0-03e648df9933

**Comment by jlintula** [comment]
I had some time in my lunch break to check what's happening, so I added some debug logging to beginning of set_temperature() in bosch_thermostat_http/circuit.py:
```
_LOGGER.debug(f"set_temperature() target_temp {target_temp} temperature {temperature} min_temp {self.min_temp} max_temp {self.max_temp} _temp.setpoint {self._temp_setpoint}")
_LOGGER.debug(f"op_mode_is_auto {self._op_mode.is_auto} target_uri {self.schedule.get_uri_setpoint_for_current_mode()} ")

```

When setting up temperature in Program1/Program2 (hvac_mode heat or heat_cool) I see this:

```
2020-04-02 12:03:41 DEBUG (MainThread) [bosch_thermostat_http.circuit] set_temperature() target_temp 22 temperature 23.5 min_temp 22.0 max_temp 22.0 _temp.setpoint None
2020-04-02 12:03:41 DEBUG (MainThread) [bosch_thermostat_http.circuit] op_mode_is_auto True target_uri /heatingCircuits/hc1/temperatureLevels/exception 
2020-04-02 12:03:41 ERROR (MainThread) [bosch_thermostat_http.circuit] Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!
```

And when in HP_OPTIMIZED mode I see this: 

```
2020-04-02 12:04:30 DEBUG (MainThread) [bosch_thermostat_http.circuit] set_temperature() target_temp 22.0 temperature 24.0 min_temp 10.0 max_temp 35.0 _temp.setpoint setpoint2
2020-04-02 12:04:30 DEBUG (MainThread) [bosch_thermostat_http.circuit] op_mode_is_auto False target_uri -1 
2020-04-02 12:04:30 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending PUT request to /heatingCircuits/hc1/temperatureLevels/normal
2020-04-02 12:04:30 DEBUG (MainThread) [bosch_thermostat_http.circuit] Set temperature for hc1 with result True
```

Seems like it's tripping to the temperature check in line 361. I bypassed it by hardcoding the values to `if 10 < temperature < 35 and target_temp != temperature:`. Seems like setting temperature works just fine in the Program1/Program2 modes. (It actually now changes the `/heatingCircuits/hc1/temperatureLevels/exception` temp instead of `/heatingCircuits/hc1/temperatureLevels/normal` like in auto mode, which isn't as convenient to me as I now I can't just feed the internal temperature sensor levels there to adjust the heating level, but it's not a big deal).

So looks to me that the in "non-auto" modes, min_temp and max_temp values are both set to what's at `/heatingCircuits/hc1/temperatureLevels/normal` (22.0 C for me), which doesn't seem right.

**Comment by pszafer** [comment]
In this situation URI `/exception` is correct.
Let's analyze it. As today is thursday let's analyze only this day.
```
{
      "id": "/heatingCircuits/hc1/switchPrograms/Program2",
      "maxNbOfSwitchPoints": 14,
      "maxNbOfSwitchPointsPerDay": 2,
      "setpointProperty": {
        "id": "/heatingCircuits/hc1/temperatureLevels",
        "uri": "http://THERMOSTAT/heatingCircuits/hc1/temperatureLevels"
      },
      "switchPointTimeRaster": 30,
      "switchPoints": [
        {
          "dayOfWeek": "We",
          "setpoint": "normal",
          "time": 1440
        },
        {
          "dayOfWeek": "Th",
          "setpoint": "exception",
          "time": 0
        },
        {
          "dayOfWeek": "Th",
          "setpoint": "normal",
          "time": 1440
        },
        {
          "dayOfWeek": "Fr",
          "setpoint": "exception",
          "time": 0
        },
      ],
      "type": "switchProgram",
      "writeable": 1
    },
```

Setpoint `normal` is enabled from Wednesday 24:00:00 (1440) to Thu 00:00:00 so 0 minutes.
Now at 00:00:00 you are enabling setpoint `exception` till Thursday 24:00:00.
So in practice you never have setpoint `normal` enabled in `Program2`.

There is some bug that it doesn't see MAX temp of exception properly:
```
{
      "id": "/heatingCircuits/hc1/temperatureLevels/exception",
      "maxValue": 30,
      "minValue": 10,
      "recordable": 0,
      "type": "floatValue",
      "unitOfMeasure": "C",
      "value": 22,
      "writeable": 1
    },
```

**Comment by jlintula** [comment]
Oh, you are absolutely right, I didn't realize it works that way in the component, it makes sense. 

I have indeed set the program to have the exception time enabled for whole week. This is because with this heat pump model, if the program is running in "normal" time (and not "exception" time), the normal and exception set temperatures have no effect at all (which is what happens in the auto/HP_OPTIMIZED mode too). So in order to be able to control the heat output from Home Assistant, it seems I need a program that is always in the "exception" time. In this situation it would be useful to be able to choose, if I want the temperature setting to affect the exception or normal temperature. In the end it doesn't matter greatly, as setting either can be used in an automation to achieve the same end result.

**Comment by pszafer** [comment]
I think for you fixing setting `exception` to properly recognize MIN-MAX threshold would be enough.

Bosch designed it in a way that
```
temperatureLevels/exception
```
is like out or no usage time or no home etc.

and 
```
temperatureLevels/normal
```
should be when people are home.

**Comment by jlintula** [comment]
I still have the temperature check bypassed in `circuit.py` and when I edit the program to be normal for the whole day today (Thursday), the component seems to edit the normal temperature correctly (it's reflected in the heat pump panel). However, it just does nothing -- the target water temperature for the heating circuit isn't affected by this, unlike when editing either of the temperatures (normal or exception) when the program is in the exception period.

So in this case just fixing the MIN-MAX threshold doesn't seem to work with this heat pump, unless there is some other option I should set somewhere.
