### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by MortenHannemose** [bosch-thermostat/home-assistant-bosch-custom-component#270]
**Describe the bug**
When adding the integration I get the message:
`Config flow could not be loaded: {"message":"Invalid handler specified"}`
Logger: homeassistant.config_entries
Source: config_entries.py:816

Error occurred loading configuration flow for integration bosch: cannot import name 'timestamp_to_datetime_or_none' from 'homeassistant.components.recorder.models' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/components/recorder/models.py)

**To Reproduce**
1. Install the bosch custom component via HACS
2. Add the Bosch sensor integration
3. See message `Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Expected behavior**
I expected the integration to be added. 

**Version**
  - HA version 2023.2.3
  - HA Bosch component v0.21.0
  - Python Bosch HTTP client version - not sure what this is.
  - HACS v1.31.0

**Additional context**
I have tried restarting, clearing the browser cache and using the `redownload` for the bosch custom component in HACS

**Comment by rabacen** [comment]
Same issue here:  Error    Config flow could not be loaded: {"message":"Invalid handler specified"} on HA 2023.2.0
upgrading HA to 2023.3.5 fixed the issue for me.

**Comment by MortenHannemose** [comment]
Thanks, upgrading homeassistant to 2023.3.5 also worked for me.
