### ISSUE TITLE
Support for Bosch Compress 7800i LW

### ISSUE THREAD

**Issue by yodasopa** [bosch-thermostat/home-assistant-bosch-custom-component#272]
Hi, is the 7800i LW supported?
I use the HomeCom Easy App to connect.
HomeCom Easy Softwareversion: 06.02.04
Hardwareversion: K30RF_v1

I tried the Easy Control and Easy Remote App, but can't connect to the Connect Key K30 RF.
If its not supported, do you plan to support the connect key / 7800i?

**Comment by pszafer** [comment]
I doubt it's possible, but you can try to check if your device is using XMPP protocol, to talk to bosch servers.
If true, then we can check if we can decode messages.

**Comment by pszafer** [comment]
I'll reopen if you gather some more information
