### ISSUE TITLE
solarYield recordings with RC300 results in kWh instead of Wh

### ISSUE THREAD

**Issue by Mahebla** [bosch-thermostat/home-assistant-bosch-custom-component#273]
**Problem**
After installing HA 2023.3.5 the energy dashboard shows the recording values of the solarYield in kWh instead of Wh.

**To Reproduce**
- Use new statistic API
- Take a look into an energy recording using "unitOfMeasure": "Wh" 
- Values shown in unit kWh instead of expected Wh.

**Expected behavior**
Values with unit Wh are shown in Wh.

**Screenshots**
![image](https://user-images.githubusercontent.com/29723571/226465890-5ad28a2f-18fc-4e89-b17f-9410440bacd7.png)

**Version**
  - HA version 2023.3.5
  - HA Bosch component version v0.21.0
  - Python Bosch HTTP client version?

** Debug SCAN **
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11023012/bosch_scan.json.txt)

**Additional context**
The data base entry for the statistic shows NULL, expected are Wh.
![image](https://user-images.githubusercontent.com/29723571/226466420-2e52e32d-c562-4cad-b3c0-2388e0e7b7a5.png)

**Comment by Mahebla** [comment]
I removed the high peak and with v0.22.0dev1 the general graph looks pretty good, but now all the values has kWh intead of Wh.
![image](https://user-images.githubusercontent.com/29723571/226751701-2f53a353-e262-4d02-ba19-43889d890145.png)

**Comment by Mahebla** [comment]
I have enabled the debug severity level and added also an additional log Information on recording.py line 78:
_LOGGER.debug("Update of sensor %s unit: bosch = %s rec = %s", self.unique_id, self._bosch_object.unit_of_measurement, self._unit_of_measurement) 

In the log
[error_log.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11058369/error_log.txt)
it's shown that the unit for the solarYield is added with none instead of Wh:
2023-03-24 05:17:59.471 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Update of sensor RecordingRecording rsolarYield917361676 unit: bosch = None rec = None

**Comment by Mahebla** [comment]
Hi, I have installed version 0.22.2 and still the solaryield has no unit:
![image](https://user-images.githubusercontent.com/29723571/230165578-0cea468b-9c5f-4761-ad2f-d2b480bd63fe.png)

[home-assistant_2023-04-05T17-51-48.697Z.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11161704/home-assistant_2023-04-05T17-51-48.697Z.log)

**Comment by pszafer** [comment]
Are you able to install bosch_cli on your PC? I'd need result of single day query

**Comment by Mahebla** [comment]
Hi pszafer,
I tried to use bosch-thermostat-client-python-0.22.2, 
but there are version conflicts visible when installing the requirements.txt: 
The user requested sortedcollections==2.1.0
aioxmpp 0.13.1 depends on sortedcollections~=1.0

**Comment by Mahebla** [comment]
In the meantime I was able to run the query:
```
bosch_cli query --config ./config.yml --debug --path /solarCircuits/sc1/solarYield --path /heatSources/actualCHPower --path /heatSources/actualDHWPower --path /heatSources/actualPower
```
results in
```
[
    {
        "id": "/solarCircuits/sc1/solarYield",
        "recordable": 1,
        "type": "floatValue",
        "unitOfMeasure": "Wh",
        "value": 143.2,
        "writeable": 0
    },
    {
        "id": "/heatSources/actualCHPower",
        "recordable": 1,
        "type": "floatValue",
        "unitOfMeasure": "kW",
        "value": 0.0,
        "writeable": 0
    },
    {
        "id": "/heatSources/actualDHWPower",
        "recordable": 1,
        "type": "floatValue",
        "unitOfMeasure": "kW",
        "value": 0.0,
        "writeable": 0
    },
    {
        "id": "/heatSources/actualPower",
        "recordable": 1,
        "type": "floatValue",
        "unitOfMeasure": "kW",
        "value": 0.0,
        "writeable": 0
    }
]
```

**Comment by pszafer** [comment]
Those values should be available as sensors in HA already, right?

**Comment by Mahebla** [comment]
Yes, each of the listed sensors is available as a recording sensor (I switched on the new recording API).
- All of these 4 recording sensors are available with values in the statistic db
- All 3 actual*Power sensors having the expected units (kWh). 
- The only problem is that the values of the solarYield have no unit and homeassistant chooses then kWh instead of Wh in the energy monitor.

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.1
