### ISSUE TITLE
CT200 energy values are negative

### ISSUE THREAD

**Issue by mcervar** [bosch-thermostat/home-assistant-bosch-custom-component#274]
Hi

After upgrading to https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.21.1dev1 
something changed with energy sensor, now new entities are created named:

- sensor.energy_energy_central_heating
- sensor.energy_energy_hot_water

Currently both are showing -17 kWh which is wrong.
I am using CT200
Home Assistant 2023.3.6
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

![image](https://user-images.githubusercontent.com/47822784/227167947-8af4db60-e688-427c-ba87-5fdb28fbb49e.png)

**Comment by fireraiserDE** [comment]
Yes, that's correct. It also appears that way in my setup.

**Comment by pszafer** [comment]
That's correct, this is info that new api and direct insertion into database is working
