### ISSUE TITLE
Support for passwords >8 characters

### ISSUE THREAD

**Issue by Stijnele** [bosch-thermostat/home-assistant-bosch-custom-component#275]
Currently Bosch is requiring new passwords to be longer than 8 characters. In the code below (in JS) you can find out how other users solve this. Can this be added to this software?
https://github.com/robertklep/bosch-xmpp/commit/0fe6b5fc293848b6e20bc845de04c0f4b02615fd

A different source for passwords longer than 8 characters is: https://github.com/marconfus/aionefit/blob/master/aionefit/__init__.py

**Comment by pszafer** [comment]
I use exactly same methods. Those aren't working for Easycontrol.
