### ISSUE TITLE
Every day update suggested and no energy recording

### ISSUE THREAD

**Issue by bruceasd** [bosch-thermostat/home-assistant-bosch-custom-component#276]
**Describe the bug**
Every day I recice this message:
Versione installata (Installed version) v0.22.0dev1
Ultima versione      (Last version)       v0.21.0

If i click "Update", i recive the error message "No update available"

In the energy panel i haven't gas consumption for some days.

If i run
service: bosch.fetch_recordings_sensor_range
data:
  uuid: "101XXXXXX"
  day: "2023-03-22"
  statistic_id: recording:recording_ractualchpowerexternal

I recive a green "OK" but energy data ar not displayed.

Thanks.
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11075643/bosch_scan.zip)

**Comment by pszafer** [comment]
Try 0.22.x. You have easycontrol so statistic id would be different.
