### ISSUE TITLE
Negative values in hot water energy statistics

### ISSUE THREAD

**Issue by fireraiserDE** [bosch-thermostat/home-assistant-bosch-custom-component#278]
Hi Pawel,

I've been an HA user since yesterday because Bosch will shut down the Home Connect Plus service.
All automations run perfectly in HA in connection with the CT 200 thermostat (and better).
So first of all, thank you for your commitment to making the Bosch custom component available!

The only issue I've found so far is with the energy sensor named:

    sensor.energy_hot_water

Only one bar with accumulated negative values appears in the energy statistics for Gas consumption.
The values for sensor.energy_central_heating are displayed correctly.
So I don't know if this has the same cause as described in issue [#271](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/271).

I'm using EasyControl CT 200
Home Assistant: 2023.3.6
Supervisor: 2023.03.3
Operating System: 9.5
Frontend: 20230309.1 - latest
home-assistant-bosch-custom-component: v0.21.0

![sensor-energy-hot-water](https://user-images.githubusercontent.com/26580830/229070552-a1072133-ff35-40d5-9410-154a58966087.png)

**Comment by pszafer** [comment]
Please, check v0.22.1 and let me know. I'll reopen if this still occur
