### ISSUE TITLE
HA 2023.3.6 Bosch integration is not properly loaded

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#281]
The latest release seems to fail with HA 2023.3.6. Is this expected?
[home-assistant_bosch_2023-04-03T13-00-46.261Z.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11138499/home-assistant_bosch_2023-04-03T13-00-46.261Z.log)

**Comment by pszafer** [comment]
Looks like wrong credentials 😞, I'll recheck but it's working for me fine

**Comment by pszafer** [comment]
I can't reproduce. Seems like bug in your network setup

**Comment by kkseem** [comment]
Same problem for me. After update on the new version, the integration could not be loaded any more.

**Comment by Michael6804** [comment]
Hello, since update 2023.06 the integration Bosch thermostat is no longer working, is there a solution? no more connection.
