### ISSUE TITLE
New version not providing entity 

### ISSUE THREAD

**Issue by ivosas22** [bosch-thermostat/home-assistant-bosch-custom-component#282]
New version completely broken. All entities no longer provided by the integration it says. Anybody else?

**Comment by MG-Sky** [comment]
i had to remove integration and start from scratch, new v. creates entities with _2 at the end

**Comment by mcervar** [comment]
Hi, for me all climates, all sensors, all devices are doubled :/

**Comment by MG-Sky** [comment]
remove the integration and import once again.

**Comment by mcervar** [comment]
Yes, full removal and adding it from start worked, but take a note that some entities like climates and energy are left and you need to remove them manually or you will still get duplicates

Or second approach is just upgrade, remove old entities, and rename new ones :)

**Comment by pszafer** [comment]
Unfortunately, I added `/devices` in Easycontrol and due to this enhancement I had to rename unique id's of all devices. Because of this HA thinks that this is new entities with `_2`. Remove and re-add might be necessary. I added note in release info
