### ISSUE TITLE
Bosch no longer working with HA 2023.04.01

### ISSUE THREAD

**Issue by Ahnl66** [bosch-thermostat/home-assistant-bosch-custom-component#285]
/After update to HA 2023.04.01 the integration shows no errors, but none of the sensors work.

easycontrol

UPDATE: turns out it was working but sensor names changed/duplicated (e.g. climate.living —> climate.living_2). So no issue, can be closed.
———

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:169 
Integration: Bosch thermostat (documentation, issues) 
First occurred: 09:22:51 (1 occurrences) 
Last logged: 09:22:51

Unloading Bosch module.

**Comment by pszafer** [comment]
Enable debug logs and provide more info

**Comment by Matthijsbr123** [comment]
For me the fix was to change the password in the EasyControl app under personal

**Comment by kirelam** [comment]
I did try to edit the password, what did not change the case. 
After that I removed the Bosch plugin and added it again. 

Tried to login with the used credentials, but now I get a "Unknown Error"

Debog log is not possible, cause there is no plugin yet.

![Screenshot 2023-04-11 125415](https://user-images.githubusercontent.com/37197122/231139713-126d1036-bd2e-49be-aa08-38650dbb7de7.jpg)

**Comment by honikos** [comment]
you should delete and readd the integration, not the plugin. Maybe therefore you use the old credentials.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.22.2
