### ISSUE TITLE
0.8.4 install problem on CAN

### ISSUE THREAD

**Issue by probecar** [bosch-thermostat/home-assistant-bosch-custom-component#29]
Hello,

Can not add integration IVT - HTTP
`Logger: custom_components.bosch.config_flow
Source: custom_components/bosch/config_flow.py:128
Integration: Bosch (documentation)
First occurred: 5:27:21 PM (4 occurrences)
Last logged: 5:31:38 PM

Error connecting Bosch at 192.168.1.32 - Expecting ',' delimiter: line 115 column 17 (char 3701)`

I have Buderus with CAN.

0.7.2 working ok.

Thank you.

**Comment by pszafer** [comment]
Delimeter error should be fixed in 0.8.6
if you have other issue with 0.8.6 please post new issue.
