### ISSUE TITLE
Add support for Bosch IP-Gateway for Bosch Climate control

### ISSUE THREAD

**Issue by supersej** [bosch-thermostat/home-assistant-bosch-custom-component#293]
Would it be possible to make this fine component include support for Bosch Climate control witch is controlable via their app named "Bosch HomeCom Easy" (Android / Ios app).
I am using the wifi module "IP-gateway G10 CL-1" which seems to have the same values as required for the Eeasycontrol part in the component.

It has a loginname, password with same length as mentioned in the documentation and I have tried with a fresh 8 character password for the Homecom app without special charactersa as mentioned in the documentation as a possible source of failure.

When trying to authenticate I get the following error
  Unknown error occurred
In the homeassistant log I get
  Error connecting Bosch at 1015xxxxx - user intervention: authentication failed: authentication aborted by user.
I get the same error if I try ex. IVT instead of Easycontrol.
I am not sure why it mentions "user intervention" cause every time I have tried I let it run until it fails.

I would really like to be able to include my climate heat pump via this component into Homeassistant to be able to monitor and control the temperatur like if it was a regular Bosch termostat.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/18198121/13977d91-db1e-41ca-b470-76facf218cdd)

**Comment by rhehl** [comment]
@supersej u should also blur the qr Code, he contains the blured informations like the password

**Comment by pszafer** [comment]
@supersej if you'd like me to check if it's possible to integrate this module, then come to discord and dm me with credentials.

Other way you can sniff module communication and check to what server does it connect.

**Comment by supersej** [comment]
> @supersej u should also blur the qr Code, he contains the blured informations like the password

Oh thanks. I did not know.

**Comment by diogotcorreia** [comment]
Hey
Has support for this device been added to this integration?
If not, have you figured out anything about the device?
