### ISSUE TITLE
Junkers Bosch Systemregler CW 400

### ISSUE THREAD

**Issue by schlaufon** [bosch-thermostat/home-assistant-bosch-custom-component#296]
![image](https://user-images.githubusercontent.com/126504679/235934416-084508ba-58db-4eb5-ba17-e91399df2153.png)

Is it possible to include the Bosch control unit CW400 into the code.
That unit is communicating via mblan-i and the BOSCH HomeCom iOS App.
Only in home assistant I have the missing data.

So far I am unable to receive data for the recording entities which are marked with an r.

**Comment by pszafer** [comment]
It won't work with my component unfortunately, it's different protocol

**Comment by martinsteinorth** [comment]
I just got the CW400 working, but with a very limited set of accessible data. I am using an MBLAN2 and have been able to connect via IVT HTTP. The component detects a "RC300/RC310/Nefit Moduline 3000" and I am able to control `climate.hc1` and `water_heater.dhw1`. 

I wonder if there is anything I can change or maybe even contribute to support more functionality, but I can open up another issue for that.

**Comment by martinsteinorth** [comment]
Nevermind, the sensors are available, they were just deactivated.

**Comment by iwannet** [comment]
@martinsteinorth How did you add the MBLAN2 to the CW 400 ? Because mine doesn't have it i think.

**Comment by martinsteinorth** [comment]
> @martinsteinorth How did you add the MBLAN2 to the CW 400 ? Because mine doesn't have it i think.

You can look up how to connect MBLAN2 to your gas boiler unit in the instructions. It is only a matter of connecting two wires to the gas boiler after removing some covers. In my case it is a Cerapur ZSB. The port is called EMS.

**Comment by iwannet** [comment]
I dont have an Mblan2, do i need to buy it seperatly ? Cuz its 300 euros

**Comment by schlaufon** [comment]
> I dont have an Mblan2, do i need to buy it seperatly ? Cuz its 300 euros

Are you sure you need a MBLAN2 ?
I think it depends on your boiler.
Mine is a Condens 9000i WM (BOSCH/Junkers) and only works with MBLANi (**i**, not 2)
Today I think Bosch also sells a WiFi- box solution only. MBLAN2 is an older model.

**Comment by martinsteinorth** [comment]
> I dont have an Mblan2, do i need to buy it seperatly ? Cuz its 300 euros

You need to check first which box is the right one for your boiler. There are MBLAN2 and MBLANi. MBLAN2 has been discontinued. You cannot and should not purchase it. You can get in contact with Bosch through this form and might be eligible to get a box shipped to you for free: https://www.bosch-homecomfort.com/de/de/wohngebaeude/no-menu/internet-gateway/ 
If you purchased your boiler in 2022 or later you should be eligible. Just choose "no voucher" and provide them with your boilers serial number and some additional information. Worked for me.
