### ISSUE TITLE
Exception in async_update when dispatching 'bosch_dhw_update': () 

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#297]
I just installed 2023.5. After this I received an error message which I think originated from this component:

---
Logger: homeassistant.util.logging
Source: util/logging.py:156
First occurred: 08:38:34 (1 occurrences)
Last logged: 08:38:34

Exception in async_update when dispatching 'bosch_dhw_update': () Traceback (most recent call last): File "/config/custom_components/bosch/water_heater.py", line 155, in async_update self._target_temperature = self._bosch_object.target_temperature File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/circuit.py", line 367, in target_temperature target_temp = self.schedule.get_temp_for_current_mode() File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/schedule/__init__.py", line 200, in get_temp_for_current_mode cache = self.get_temp_in_schedule() File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/schedule/__init__.py", line 265, in get_temp_in_schedule bosch_date = datetime.strptime(self._time[0:25], self._date_format) File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '2023-05-04T08:38:33' does not match format '%Y-%m-%dT%H:%M:%S%z'
-----

I wondered if this was a once off due to a network issue or something else?

best regards,
haaino

**Comment by pszafer** [comment]
Hi, sorry for late response.
Provide bosch scan and information about your device.
I will reopen issue when you provide those data
