### ISSUE TITLE
Bosch Easycontrol ct200 not working with firmware 4.0.0

### ISSUE THREAD

**Issue by francescoscanferla** [bosch-thermostat/home-assistant-bosch-custom-component#300]
**Describe the bug**
After updating firmware to version 4.0.0 the climate sensors are no longer present

**To Reproduce**
The Easycontrol has updated itself to the version 4.0.0

**Version**
  - Home Assistant 2023.5.0
  - Supervisor 2023.04.1
  - Operating System 10.1
  - HA Bosch component version 0.22.2

** Debug SCAN **
** IMPORTANT **
[bosch_scan.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11412959/bosch_scan.log)

**Comment by Bigglesuk** [comment]
I have no issues with this integration and my ct200 on version 4.0.0 and HA 2023.5.0.
