### ISSUE TITLE
No energy statistics after TC100 update 4.0.0 and HA update

### ISSUE THREAD

**Issue by rameister** [bosch-thermostat/home-assistant-bosch-custom-component#306]
Since 07.06.2023 I don't receive energy statistics anymore.

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

TC100.2 - EASYCONTROL for firmware 04.00.00
Please see the attached Bosch Debug log. I hope it helps.
[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/11801438/bosch_scan.json.zip)

<img width="499" alt="image" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/59337072/c750e708-ae9e-4b23-b006-96b255ea025f">

Please have a look to my Thermostat App where the Data from missing dates in this iPhone App still present as well.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/59337072/525bb7a0-a582-461f-b929-6f606bb067f1)

**Comment by HeGa59** [comment]
same here. No actualization of the recording-sensors!!

**Comment by pszafer** [comment]
can you try version v0.22.3dev1?
You'd need to enable `Use new statistic API` in integration option once again.

**Comment by rameister** [comment]
Yes, I have it done and waiting for new values in the energy Dashboard. The new statistic API in integration option has reaktivated as well.

**Comment by rameister** [comment]
Please have a look to my last bosch scan file attached.
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12015279/bosch_scan.zip)

**Comment by rameister** [comment]
Yes, I did it but there is no Energy is shown. Do you have any suggestion to solve this issue? I can test when you have a new Version of your scripts. Greetings.

**Comment by pszafer** [comment]
Recheck v0.23.1 and let me know

**Comment by rameister** [comment]
Thank you for the update, just put it in. No change occurred, now I have negative energy values.
![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/59337072/30ea0c0e-75b3-4298-aba4-344c6a0a20ce)

**Comment by rameister** [comment]
Attached a latest bosch_scan
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12094450/bosch_scan.zip)

**Comment by pszafer** [comment]
-17 it means it should work.
Now follow instructions: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support

**Comment by rameister** [comment]
I did this according to your instructions but no change occurred. What can I do I send the debug data again.
[home-assistant_2023-07-19T12-02-00.370Z.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12094995/home-assistant_2023-07-19T12-02-00.370Z.zip)

**Comment by rameister** [comment]
Today an update was available and so I made it to Release 04.02.01 as well. In my Buderus/Bosch App I can see the Energy Values but not in HA at the Energy Desk. The issue is still present.

**Comment by MG-Sky** [comment]
i have same issue, I've tried everything (re-enable etc..) values are not shown in energy statistics my energy sensors show with unknown state (ct200 - newest firmware/bosch component)

**Comment by fireraiserDE** [comment]
> i have same issue, I've tried everything (re-enable etc..) values are not shown in energy statistics my energy sensors show with unknown state (ct200 - newest firmware/bosch component) [scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12138973/scan.txt)

Yep, same here - status unknown.

**Comment by rameister** [comment]
Tody no values shown and no entyties shown. That's all in the bucket?

**Comment by Atraxmaster** [comment]
It doesn't work for me on ct200 either

**Comment by pszafer** [comment]
Please check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.3
I will reopen if problem'd still occur.

**Comment by fireraiserDE** [comment]
Hi Pawel,
there is a change, but it doesn't solve the problem.
There are now 4 entities, but two of them are no longer active:

![bosch_entities](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/26580830/98c94d4b-6832-40e6-a096-6eb3fc71c7ad)

And the two active Entities have a strange attitude towards precision:

![sensor_settings](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/26580830/60e19e85-84ab-40f8-aa17-b05ea25973f0)

**Comment by pszafer** [comment]
@fireraiserDE did you read wiki https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/New-API-support ?
It won't be visible in entity list, only in energy dashboard settings. -17 means it's working

**Comment by fireraiserDE** [comment]
@pszafer: new API is active but still there are several choices in the dashboard settings:

![Configure_gas_consumption](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/26580830/19f94bc7-3ff8-4715-b244-f8aaf0ced2f3)
