### ISSUE TITLE
IVT RC300/310 Bosch/Buderus

### ISSUE THREAD

**Issue by hipik634** [bosch-thermostat/home-assistant-bosch-custom-component#307]
Hi, 
with Home Assistant 2023.4.6

integration over HACS:

module:
IVT
od RC300
Firmware: 04.08.02

Missing pretty much all of the sensors. Only working thing is thermostat and hot water setup. All internal sensors report as missing. 

Is there something, I can do to pinpoint the issue?

**Comment by pszafer** [comment]
enable those you need, sensors are disabled by default
