### ISSUE TITLE
Firmware 4.2

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#309]
FYI. 

On 4-7-2023 I installed firmware version 4.2. After installation I get warnings in HA that the hacs bosch module does not recognize this firmware version.

However, it looks like the integration is still working fine.

**Comment by Barrie99** [comment]
Had the same issue yesterday, only my integration stopped working completely after a version upgrade. I bet this is only a matter of time for everyone.

Did a quick and dirty fix to get it up and running again. My installation is running from Docker, so some command might be different on other installations.

First, SSH into the docker.
> docker exec -t -i <docker id> /bin/bash

Then copy the version 4.0 json file to the new 4.2 release.
> cd /usr/local/lib/python3.11/site-packages/bosch_thermostat_client/db/easycontrol
> cp 040000.json 040200.json

Then edit the 040200.json file so the version number on the first line matches: "versionFirmware": "04.02.00",
> vi 040200.json

That's it, restart Home Assistant and you'll be up and running.

My 2 cents, hope it helps someone.

**Comment by thepasto** [comment]
@Barrie99 Thank you so much, it works like a charm!

**Comment by petrotti77** [comment]
Hi Barrie99, could you please explain how to do this procedure on home assistant without doker. I'm not very practical. Thank you

**Comment by Barrie99** [comment]
@petrotti77 I don't have any other installation handy, but I'm guessing it's more or less the same, taking into account that you're able to SSH into the docker container. (Even HAOS is running from a container)

The Portainer addon should be able to do just that.
https://community.home-assistant.io/t/home-assistant-community-add-on-portainer/68836

But I'm pretty sure there will be an official solution to this issue soon.

**Comment by petrotti77** [comment]
@Barrie99 I am not able to perform the changes you recommended due to my lack of experience. If you have any simpler solution to fix this CT200 firmware update issue I will be very grateful.

**Comment by jmlt** [comment]
> Had the same issue yesterday, only my integration stopped working completely after a version upgrade. I bet this is only a matter of time for everyone.
> 
> Did a quick and dirty fix to get it up and running again. My installation is running from Docker, so some commands might be different on other installations.
> 
> First, SSH into the docker.
> 
> > docker exec -t -i [docker id] /bin/bash
> 
> Then copy the version 4.0 json file to the new 4.2 release.
> 
> > cd /usr/local/lib/python3.11/site-packages/bosch_thermostat_client/db/easycontrol
> > cp 040000.json 040200.json
> 
> Then edit the 040200.json file so the version number on the first line matches: "versionFirmware": "04.02.00",
> 
> > vi 040200.json
> 
> That's it, restart Home Assistant and you'll be up and running.
> 
> My 2 cents, hope it helps someone.

thank you!

**Comment by bakboord4** [comment]
Bosch thermostat integration for my CT200 with firmware 04.02.00  completely removed and installed again as documented.
The integration is not working, no sensors  are visible and a debug-scan is not created.

Logged error message:
2023-07-09 22:42:37.406 ERROR (MainThread) [custom_components.bosch] You might have unsupported firmware version 04.02.00

System development is not my habitat. Docker and portainer is a bit too much for me. HA 2023.7.1 on a RPi4 is the configuration.
Is there a fix iunder construction? I would be very greatfull to hear. Thank you.

**Comment by janoschbatschi** [comment]
Same issue here. As far as I understand, a custom_component (HACS addon) is not running in a container itself. At least "docker ps" is only listing system-addons. 
And in the python-files I can't find where the HACS-addon is getting the firmware-version from. Maybe someone has an idea for a quick fix?

**Comment by suchosj** [comment]
> Had the same issue yesterday, only my integration stopped working completely after a version upgrade. I bet this is only a matter of time for everyone.
> 
> Did a quick and dirty fix to get it up and running again. My installation is running from Docker, so some commands might be different on other installations.
> 
> First, SSH into the docker.
> 
> > docker exec -t -i [docker id] /bin/bash
> 
> Then copy the version 4.0 json file to the new 4.2 release.
> 
> > cd /usr/local/lib/python3.11/site-packages/bosch_thermostat_client/db/easycontrol
> > cp 040000.json 040200.json
> 
> Then edit the 040200.json file so the version number on the first line matches: "versionFirmware": "04.02.00",
> 
> > vi 040200.json
> 
> That's it, restart Home Assistant and you'll be up and running.
> 
> My 2 cents, hope it helps someone.

Thanks a lot, it works. The only cons is, I now have CT200 devices duplicated: once working with fw version 04.02 and second not working with fw v. 04.00.

**Comment by Barrie99** [comment]
@suchosj I'm relatively sure your issue has nothing to do with the 040200.json file. (You could test by removing it)
The json only accepts the new firmware but does not duplicate entities or anything else in Home Assistant. Perhaps you tried reinstalling the complete custom component or tried something else prior to running this fix? That would explain.

For now, just disable the firmware updates on the thermostat. That prevents these things happening again :)

**Comment by petrotti77** [comment]
hello all, although I have updated the repisitory to v0.22.3dev1, the integration still doesn't work. I've tried uninstalling both the repository and the integration but nothing works. now it only sees the device but no sensors. do you have suckings? Thank you

**Comment by bruceasd** [comment]
> hello all, although I have updated the repisitory to v0.22.3dev1, the integration still doesn't work. 

+1

**Comment by PV-Web** [comment]
following this as my bosch thermostat also did an auto update to 4.02 and now the integration is no longer working

**Comment by gitioda** [comment]
following this as my bosch thermostat also did an auto update to 4.02 and now the integration is no longer working 😄

**Comment by TomDeSchutter** [comment]
following this as my bosch thermostat also did an auto update to 4.02 and now the integration is no longer working :smile:

**Comment by Raspyguy** [comment]
Same here.....integration is not working anymore after update to 4.02 👎

**Comment by fgraefen** [comment]
same here :(

**Comment by Jopy2104** [comment]
Same issue.

**Comment by andrewptw** [comment]
Same here.

**Comment by bakboord4** [comment]
@Barrie99. I did install Portainer. The gap between  Portainer opening screen and the fix instructions assumes a lot of extra knowledge I do not have.  
But before I maybe try it again, to me it is not clear the nature of this firmware problem. What is holding back to create a formal solution with a new integration release?  Thanks for your reaction.

**Comment by Barrie99** [comment]
> What is holding back to create a formal solution with a new integration release?

I have no clue. I'm just a user like you that managed to fix this issue on his Docker installation ;-)
I have nothing to do with Bosch or this integration.

That said, let me look into the HAOS installation, maybe I can make a step-by-step guide.

**Comment by bakboord4** [comment]
@Barrie99 if possible that would be very helpful. Available for testing if needed.

**Comment by Raspyguy** [comment]
@Barrie99, because i am not familiar with such deep programming i have not even try the portainer installation.
I really appreciate your efforts with this issue and it would be great if you can solve this four us, as users.
A few months ago i have had the same problem with the Bosch integration but after a HA update it solves itselfs🤔
In the meantime thx again👍

**Comment by Barrie99** [comment]
I wish I had better news but this is a tough nut to crack on HAOS, since I can't find an easy way to fully access the system. (Which makes sense since it's not meant to be fully open).

I'm new to Github, but I managed to fork the bosch-thermostat-client-python branch and added the 040200.json file. The Home Assistant integration uses this bosch-thermostat-client-python code, so hopefully the json will get incorporated into the main branch. If so, we probably don't need to do anything I suppose, except maybe reinstall the integration. I have no clue how this works, if it works or who has to accept or validate this change. So it might take months, it could take hours. Who knows.

So for Docker installations anyone can copy and edit the json file manually as described above. (It looks harder than it is) But for HAOS we appear to be stuck waiting for the developers to do something. As @Raspyguy said, these things usually fix themselves after some time.

**Comment by thepasto** [comment]
I think it should be reported [here](https://github.com/bosch-thermostat/bosch-thermostat-client-python/tree/dev/bosch_thermostat_client/db/easycontrol)

**Comment by gitioda** [comment]
@Barrie99   yes HA on raspberryPi

**Comment by TomDeSchutter** [comment]
> @andrewptw @Jopy2104 @fgraefen @Raspyguy @TomDeSchutter @gitioda @PV-Web
> 
> So you're all running the HAOS version of Home Assistant? Since the fix for this problem for Docker installations is in this thread. If HAOS: Has any of you tried Portainer or this method: https://community.home-assistant.io/t/protip-how-to-get-shell-in-actual-homeassistant-or-addon-container-when-using-hassio/48760
> 
> Let me know.

I went the quick and dirty path as well. Moved my installation to a docker based one. 
Was long overdue for me anyway. Your hack fixed my issues, thank you.

**Comment by Barrie99** [comment]
@TomDeSchutter No problem, happy to assist. I think you made a smart move. Was standing in your shoes a couple of weeks ago and haven't regretted moving to Docker for even one second.

**Comment by fgraefen** [comment]
I was also able to create the configuration file in the HA Dockeer container via the Advanced SSH & Web Terminal addon.

thanks for your support!

**Comment by gralin** [comment]
@pszafer it's this time of the year when Bosch releases new firmware and we need your assistance 🙏

**Comment by Barrie99** [comment]
@fgraefen It will most likely be overwritten. But chances are it will be overwritten by pretty much the same file, so you won't even notice.

**Comment by pszafer** [comment]
I'll be back home on Sunday, then I'll release new firmware. Sorry you have to wait but it's my vacation time ;)

**Comment by gitioda** [comment]
> I'll be back home on Sunday, then I'll release new firmware. Sorry you have to wait but it's my vacation time ;)

Don't be sorry, Many thanks in advance, take you time and enjoy your holliday !  😊

**Comment by gralin** [comment]
@pszafer here is my scan in case you need it. Thanks again for your continued support!
[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12080467/bosch_scan.txt)

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.1

**Comment by haaino** [comment]
Thank you the release @pszafer. It indeed resolves the issue!

**Comment by gitioda** [comment]
Thanks a lot @pszafer issue solved for me too  😀🙏

**Comment by petrotti77** [comment]
@pszafer Thank you so much for solving the problem. so far everything works fine.

**Comment by PV-Web** [comment]
@pszafer Thanks for the quick action. Seems to work great again. Keep up the good work!

**Comment by Jopy2104** [comment]
@pszafer Thanks for the fix. Works like a charm.

**Comment by pszafer** [comment]
@Raspyguy update via HACS

**Comment by Raspyguy** [comment]
Hi, its not visible in HACS?Verzonden vanaf Outlook voor Android

**Comment by Raspyguy** [comment]
@pszafer,Found it, update become visible after using the 3 dots 🙄Works perfectly 👍Many thanks for the solution!!Verzonden vanaf Outlook voor Android

**Comment by Raspyguy** [comment]
Hi there,Again after the bosch 04.02.01 update the integration isn't working anymore🥴Anybody familiar with it?Verzonden vanaf Outlook voor Android

**Comment by bakboord4** [comment]
@pszafer @Raspyguy 
The custom - component 0.23.1 installed three days ago and was working as expected. 
However, last night out of the blue the same error: 'You might have unsupported firmware version 04.02.01' came back in logging and on screen. 

Only difference is version level now 04.02.01 instead of .00. None of integration sensors are available anymore. 

Yesterday I upgraded HA to 2023.7.3. Reverted back to 7.2 but firmware error remains.
Enough information supplied for investigation and possible fix?

**Comment by pszafer** [comment]
I released 0.23.2 with the fix yesterday afternoon

**Comment by Jopy2104** [comment]
@pszafer does this fix also work with 04.02.00, so I can upgrade HA before the thermostat?

**Comment by pszafer** [comment]
@Jopy2104 yes
