### ISSUE TITLE
Old entity types

### ISSUE THREAD

**Issue by stefanlaheij** [bosch-thermostat/home-assistant-bosch-custom-component#31]
First of all thanks for the great work. It works perfectly with my Nefit Enviline (KM200).

At startup I get some messages since Home Assistant release version 0.110:
1. ClimateDevice is deprecated, modify BoschThermostat to extend ClimateEntity
2. WaterHeaterDevice is deprecated, modify BoschWaterHeater to extend WaterHeaterEntity
3. bosch: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

Best regards, Stefan

**Comment by pszafer** [comment]
thanks, I have everything ready to move on to newer version.
I will push it tomorrow I think.

**Comment by pszafer** [comment]
@stefanlaheij can you test this release https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.9.0 and let me know if it's working for you with 0.110.
If so I will publish it as 'official'.

**Comment by stefanlaheij** [comment]
I get this error at startup:

2020-06-02 08:57:03 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry RC300/RC310/Nefit Moduline 3000 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/bosch/__init__.py", line 90, in async_setup_entry
    protocol=entry.data[CONF_PROTOCOL],
KeyError: 'http_xmpp'

**Comment by stefanlaheij** [comment]
After removing the integration and creating it again it now works like it did before
