### ISSUE TITLE
cannot import name 'StatisticsRow'

### ISSUE THREAD

**Issue by redskull1986** [bosch-thermostat/home-assistant-bosch-custom-component#310]
After update of HA Bosch I got the following error:

Logger: homeassistant.setup
Source: setup.py:213
First occurred: 20:23:21 (1 occurrences)
Last logged: 20:23:21

Setup failed for custom integration bosch: Unable to import component: cannot import name 'StatisticsRow' from 'homeassistant.components.recorder.statistics' (/usr/src/homeassistant/homeassistant/components/recorder/statistics.py)

I tested Python 3.11.4 first then 3.10.12

**Version**
  - HA version: 2023.3.3
  - HA Bosch component version: 0.23.1
  - Python version: 3.10.12 & 3.11.4
  - device: CT200 newest update

** Debug SCAN **
Isn't possible

**Comment by pszafer** [comment]
Component is prepared to work with the newest HA. It won't work with such old version.
