### ISSUE TITLE
Recordings not updated. Only initial values are reported.

### ISSUE THREAD

**Issue by Scoperius** [bosch-thermostat/home-assistant-bosch-custom-component#312]
**Expected behavior**

Recordings are expected to be updated hourly. 

Last version... 

IVT local connection

**Comment by pszafer** [comment]
Please check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.3
I will reopen if problem'd still occur.

**Comment by Scoperius** [comment]
No change


------ Původní zpráva ------
Od "Pawel" ***@***.***>
Komu "bosch-thermostat/home-assistant-bosch-custom-component" 
***@***.***>
Kopie "Scoperius" ***@***.***>; "Author" 
***@***.***>
Datum 05.09.2023 8:48:33
Předmět Re: [bosch-thermostat/home-assistant-bosch-custom-component] 
Recordings not updated. Only initial values are reported. (Issue #312)

**Comment by pszafer** [comment]
Provide logs and more data.
