### ISSUE TITLE
new firmware 04.02.01 (CT200)

### ISSUE THREAD

**Issue by redskull1986** [bosch-thermostat/home-assistant-bosch-custom-component#313]
A new firmware is released.
04.02.0**1**

**Version**
  - HA version: 2023.7.2
  - HA Bosch component version: 0.23.1
  - Python: 3.11.4

** Debug SCAN **
isn't possible

**Comment by SteGe88** [comment]
Same problem over here…

**Comment by Raspyguy** [comment]
Same here.

**Comment by pszafer** [comment]
fixed in [v0.23.2](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.2)

**Comment by Raspyguy** [comment]
Great👍Everything works like charm.Thx for the fast solution!Verzonden vanaf Outlook voor Android

**Comment by bruceasd** [comment]
Thanks, now HA works, but CT 200, with new 04.02.01 firmware do not connect to internet. WiFi connection to routers is ok, but it can not comuniacte :-(
Do you have the same problem?

**Comment by redskull1986** [comment]
Bosch server was down, again. It work now.

**Comment by SteGe88** [comment]
Had the same issue and found this site from Bosch: https://www.nefit-bosch.nl/consument/na-je-aankoop/actuele-meldingen. Don’t know if there is an English version. But after a while it was working out of itself.
