### ISSUE TITLE
firmware version 04.02.01.

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#314]
New firmware update today, 22 July 2023. 

----

There are problems with config of your thermostat.
You might have unsupported firmware version 04.02.01.

----

From the version number and release notes, it seems like a small update.

I hope a, small, update can resolve this issue.

**Comment by pszafer** [comment]
fixed in [v0.23.2](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.2)
