### ISSUE TITLE
Buderus RC310

### ISSUE THREAD

**Issue by FloCodeRian** [bosch-thermostat/home-assistant-bosch-custom-component#316]
**Describe the bug**
I have problems connecting my new Buderus thermostat. 
Is there a way to get this “ password you defined in the EasyRemote app “ 
Without the Bosch App. 
Seems like the Buderus app doesn’t support this Passwort?

**Comment by zbikmarc** [comment]
You can use Buderus App. I have this exact thermostat and I was able to connect it to home assistant.

**Comment by FloCodeRian** [comment]
Thank you for your reply! Did you use Buderus App „MyBuderus“ or „MyDevice“ ? Am 05.08.2023 um 16:27 schrieb Marcin Żbik ***@***.***>:﻿
You can use Buderus App. I have this exact thermostat and I was able to connect it to home assistant.

**Comment by zbikmarc** [comment]
> Thank you for your reply! Did you use Buderus App „MyBuderus“ or „MyDevice“ ? Am 05.08.2023 um 16:27 schrieb Marcin Żbik ***@***.***>:﻿ You can use Buderus App. I have this exact thermostat and I was able to connect it to home assistant. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

It was MyDevice
