### ISSUE TITLE
Support Bosch Compress 7800i that uses Bosch HomeCom Easy?

### ISSUE THREAD

**Issue by douglas2** [bosch-thermostat/home-assistant-bosch-custom-component#317]
Hi,

I am wondering if there is any plans to add support for **Bosch Compress 7800i LWM 12** that uses the **Bosch HomeCom Easy** app?

Thanks!

**Comment by fir3drag0n** [comment]
Same, only that I do have the Condens 5300i W and HomeCom Easy App as well!

**Comment by pszafer** [comment]
No, afaik it's different protocol. My integration doesn't support it.
