### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by stefanlaheij** [bosch-thermostat/home-assistant-bosch-custom-component#32]
Hi @pszafer,

Is it an idea to publish this component in HACS? (https://hacs.xyz/)
I think it makes your component more widely known and used.
Also it makes it a lot easier to do upgrades :)

Best regards, Stefan

**Comment by pszafer** [comment]
I will try to do it next week if latest release is working for you all.

**Comment by pszafer** [comment]
Should be finally added to HACS soon: https://github.com/hacs/default/pull/766
