### ISSUE TITLE
Energy Stats aren't updating on CT200 fw 04.02.01

### ISSUE THREAD

**Issue by ANeed2Py** [bosch-thermostat/home-assistant-bosch-custom-component#320]
**Describe the bug**

The daily energy stats are not updating for me and I also can't manually update them from the provided fetch service.

**Version**
  - HA version? HAOS 2023.9.1
  - HA Bosch component version? v0.23.4
  - EasyControl CT200 v04.02.01

If i go back to v0.23.2 I can get it to work again. (sort of 🙂)

With v0.23.2 installed I have to:

Edit the energy.py sensor code to match the attributes I get for the hot water & heating.
Looking in my BoschSCAN I see that my attributes for the above are gHw and gCh respectively.

    {
      "id": "/energy/history?entry=346.0",
      "type": "energyRecordings",
      "writeable": 0,
      "recordable": 0,
      "used": "true",
      "available": "true",
      "value": [
        {
          "d": "09-09-2023",
          "T": 22.3,
          "gCh": 0.0,
          "gHw": 1.8
        }
      ]
    },

If I change the energy.py code to those, it works. (kind of 🙂)

    
    EnergySensors = [
    {"name": "energy temperature", "attr": "T", "unitOfMeasure": TEMP_CELSIUS},
    {
        "name": "energy central heating",
        "attr": "gCh",
        "unitOfMeasure": ENERGY_KILO_WATT_HOUR,
    },
    {"name": "energy hot water", "attr": "gHw", "unitOfMeasure": ENERGY_KILO_WATT_HOUR},
    

It will download the stats as it should and update them if I use the fetch service but for some other reason (bug?) the first hour of the previous day slowly increment all day until the next day is downloaded at 00:06. (Then the cycle repeats)

I would then manually adjust the statistics and that fixes it but this has to be done every day.

I tried the latest version v0.23.4 but it won't download any stats at all.
If i change the energy.py to reflect my attributes for hotwater & heating it doesn't help either.

Any ideas?

I've gone back to v0.23.2 current and editing the stats everyday but I can upgrade to the latest version if you need me to try anything out?

**Comment by pszafer** [comment]
Since 0.23 attributes are dynamically checked, so you probably have 0.22 installed.

**Comment by Tothdav** [comment]
Hi!

Same happens in my environment. Debug scan shows the following, which seems ok for me from hot water point of view:

`{
      "id": "/energy/history?entry=347.0",
      "type": "energyRecordings",
      "writeable": 0,
      "recordable": 0,
      "used": "true",
      "available": "true",
      "value": [
        {
          "d": "10-09-2023",
          "T": 21.6,
          "gCh": 0.0,
          "gHw": 4.1
        }
      ]
    },`

But the energy sensors reports -17 kWh for both heating and hot water:

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11217258/035644ec-2bc7-4ad4-a0c5-9ee6299ac52c)

I have the v0.23.4 installed.
(however the log tells this:
2023-09-10 08:18:54.957 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.23.2.)

Please let me know if I can send more more details or logs!

**Comment by davee640** [comment]
Hello, 
I have the same result.
Please help 
![IMG_0103](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/132099064/73e20adf-c803-4111-8295-73f7a5a8944c)

**Comment by Tothdav** [comment]
I have done the steps from the wiki more times (also with deleting the integration completely and install it again), but it does not work at all for me. Every other sensor works well.

The only case is when I could fetch the energy data when I **disabled** the new statistics API:
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11217258/65ffb686-5b96-40f2-b082-c559ad8f7772)

Also I recognized when I deleted the integration that the created energy stats remain in the Statistics view under the Developer Tools.
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11217258/d482dd66-ffc2-4870-b5cf-ea7c5946fe14)

Can be the problem when I install it again, that the integration cannot create the new stats due to the remained ones? Do you have any other suggestion what should I try?

**Comment by Kaacz** [comment]
@pszafer How to set external sensors from New API  in widget?

**Comment by pszafer** [comment]
@Kaacz you can just use those only https://www.home-assistant.io/dashboards/energy/

**Comment by Kaacz** [comment]
OK, thanks for info. I don't want to use energy dashboard, then I was set all energy* entities as disabled. 
And I hope this setting turns off unwanted periodic energy data collection. 
I solved it by collecting data externally once a day to InfluxDB (I have better graphs in Grafana). 
And I added these items in the DB as a sensor.
