### ISSUE TITLE
Energy statistics for some days are not fetched/stored

### ISSUE THREAD

**Issue by mcervar** [bosch-thermostat/home-assistant-bosch-custom-component#321]
Describe the bug

The daily energy stats are not always updating for me but I can manually fetch recordings (via service) for central heating or hot water and then it shows properly in energy dashboard.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/47822784/ca3ef7fd-f066-49ac-8692-dd355c540559)

Sometimes, on random, statistics for some days are not registered/fetched.
Also if I restart the integration, statistics are fetched and stored properly.

It can be solved by creating automation for fetching recordings daily, but it would be better if possible to find the reason behind this behavior.

Version
Home Assistant 2023.8.4
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230802.1 - latest

HA Bosch component version v0.23.4
EasyControl CT200 v04.02.01

**Comment by mcervar** [comment]
Simple automation which seems to work to fetch data and fill the gaps nightly

`alias: Fetch Bosch gas consumption from yesterday
description: ""
trigger:
  - platform: time
    at: "04:00:00"
condition: []
action:
  - service: bosch.fetch_recordings_sensor_range
    data:
      uuid: "UUID-OF-YOU-CT200"
      statistic_id: sensor.energy_hot_water
      day: >
        {{ (as_timestamp(now()) - 24*3600) | timestamp_custom("%Y-%m-%d", True)
        }}
  - service: bosch.fetch_recordings_sensor_range
    data:
      uuid: "UUID-OF-YOU-CT200"
      statistic_id: sensor.energy_central_heating
      day: >
        {{ (as_timestamp(now()) - 24*3600) | timestamp_custom("%Y-%m-%d", True)
        }}
mode: single
`

**Comment by Kaacz** [comment]
Hi, thanks for script, i hope that solve my problem with non-working data fetch with old API at all (for widget).
Please, where I find uuid? I see only device_id. 
PS: to author - will be good to have ability to switch off useless hourly! fetching for easycontrol CT200.

**Comment by mcervar** [comment]
Hi

For UUID, go to Setting -> Integration -> Bosch Thermostat -> Devices -> Select device which represents your radiator valve, for example for me it is Living Room -> Under Device Info there is Hardware

**Comment by Kaacz** [comment]
Ah, sorry, as an IT person I know the standard UUID format, many alphanumeric characters with dashes. :)
In this case, "Hardware" is simply the serial number of the CT200. OK, I'll run your script with s/n as uuid.
Thanks.

**Comment by Kaacz** [comment]
Not working as legacy fetch. Only integration reload "some" working...
Nevermind, for my "yesterday" dashboard widget I was use my external fetched influxdb data as new input sensor for HA. 
Now I need only one: how stop useless and unnecessary every-hour-fetch one/per/day data from CT200. @pszafer 
PS: But still I want send many thanks for this integration. I look forward for sponsoring, but in first I must create some knd of virtual pay card for this. 
Github: It is shamed if only direct payment card use is only one method to use ... :(

**Comment by pszafer** [comment]
Fetching of stats should be fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
Let me know.
Automation does change too, now you can choose `device` from the list and integration would find connected UUID itself.

I'll close issue now and reopen if you report that problem somehow still occurs.
