### ISSUE TITLE
Low battery device reported as Heating in Home Assistant

### ISSUE THREAD

**Issue by cyberden** [bosch-thermostat/home-assistant-bosch-custom-component#322]
**Describe the bug**
It seems that using the connected bosch valvles, when they run low on battery, the status is reported as "Heating" by default even though it is currently idle.

**To Reproduce**
Have a valve low on battery, it is always in the "heating" status.
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/7973581/499dc157-6e58-4b90-ac18-55f5209d03c7)

**Expected behavior**
If possible, keep the correct operation status or report the battery status.

** Debug SCAN **
** IMPORTANT **
this zone is reporting as Heating :
`{
      "id": "/zones/zn3/status",
      "type": "stringValue",
      "writeable": 0,
      "recordable": 0,
      "value": "low battery"
    },`

This other zone is reported as idle (as it should be) :
`{
      "id": "/zones/zn2/status",
      "type": "stringValue",
      "writeable": 0,
      "recordable": 0,
      "value": "idle"
    },`

**Additional context**
I'm not sure if it can be done since the api does not report heating or idle, just "low battery" so...

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
