### ISSUE TITLE
Summer/Winter Switchpoint

### ISSUE THREAD

**Issue by nibblerrick** [bosch-thermostat/home-assistant-bosch-custom-component#33]
At least my Unit has Summer/Winter switchpoints, so at some level of outdoortemperature the heating turns off (or the heatingcircuit).
Even though you define thresholds the it doesn't switch at these thresholds of the outdoortemperature on and off, instead it does some debouncing and things.

So my question is if it would be possible to have these status-sensors in HA so I can use it so switch some thermostats.

The corresponding data seems to be in

```
        {
            "id": "/heatingCircuits/hc4/suWiSwitchMode",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 1,
            "value": "active",
            "allowedValues": [
                "off",
                "active"
            ]
        },
```
a fulll scan of my system is in #10 

Don't know if it's doable, but as I got my outdoortemperature (still thanks for that!) I thought I'll ask.

**Comment by pszafer** [comment]
I could add some service to change `suWiSwitchMode` and add logic as follows:

```
if `suWiSwitchMode` == `active` and `outdoortemperature > suWiThreshold`:
   show HC as off.
```

**Comment by nibblerrick** [comment]
That's not better than what I do at the moment.

But I thought sthe suWuSwitchMode shows if it's in summer or wintermode, but you are right, that's only if the mode itselt is activated.

I just saw that at the moment I have `current_temperature: null` as attribute, maybe I can use that. But I don't know how it behaves, I restarted HA today when summermode was active. I'll see what it shows tonight and tomorrow, then it should have switched to winter and summer once.
If that doesn't help maybe the pumpmodulation of the different heatcircuits could be used. If the pumpModulation is >0 then the circuit should be active, I think. pumpModulation is only as RC35 Sensor in the actual code, but not for the different heatcircuits, right?

```
        {
            "id": "/heatingCircuits/hc2/pumpModulation",
            "type": "floatValue",
            "writeable": 0,
            "recordable": 1,
            "value": 100.0,
            "unitOfMeasure": "%",
            "minValue": 0.0,
            "maxValue": 100.0
        },
```

**Comment by pszafer** [comment]
can you explain what you want to achieve?
do you want to turn on heating or just know what mode is thermostat on?

**Comment by nibblerrick** [comment]
E.g. the thermostat in the bathroom has a sensor in the floor, so the floor can be nice and warm. This is more than the average roomtemperature. So when it's in summermode it would try to heat gives power to the valves.
Therefore I want to put the thermostat to a targettemperature low enough so it won't try to heat.

My first idea: take the threshold which is set in the RC35 and switch the thermostat with the outdooretemperature. But then I noticed the threshold set in the RC35 is not a direct threshold.
6 weeks ago the heatingcircuit switched off about 3 hours after the outdooretemperature was above the threshold and switched on again about half an hour it has fallen below the threshold.
Now it switches the heatingcircuit off about an hour after going above the threshold and back on 3 1/2 hours after falling below.
So there is some magic/computing/debuncing/whatever going on in the RC35 based on the temperaturecurve over the day or something.
What I like to have is something which tells me if the heatingcircuit is on or off.
One thing which indicates the circuit is on is if the circulationpump of the circuit is running. If there are other parameters indicating this - I don't know. Therefore I want to observer if current_temperature  is usable.
To answer your question: I want to know if the heatingcircuit is on and switch the roomthermostat accordingly. But I don't want to switch heating in the RC35 on or off.
Have I managed to explain it a little bit? Otherwise I'll try again.

**Comment by pszafer** [comment]
I think I understand. Can you make new scan tomorrow when day operation mode should be active?

**Comment by nibblerrick** [comment]
I made three scans: one when winter-mode is active, one when winter-mode is active but hotwater is generated (hot-water priority is enabled, so it shuts the heatingcircuits off to generate hotwater quicker) and one in summer-mode.
What I found: winter-mode and winter-mode with hot-water there is a difference in

```
            "id": "/heatingCircuits/hc2/currentOpModeInfo",
            "recordable": 0,
            "type": "hcmodelist",
            "values": [
                {
                    "auto": "**on**",
                    "floordrying": "off",
                    "holiday": "off",
                    "manual": "off"
                }
           "id": "/heatingCircuits/hc2/currentOpModeInfo",
            "recordable": 0,
            "type": "hcmodelist",
            "values": [
                {
                    "auto": "**off**",
                    "floordrying": "off",
                    "holiday": "off",
                    "manual": "off"
                }
```
and in

```
        {
            "id": "/heatingCircuits/hc2/pumpModulation",
            "maxValue": 100.0,
            "minValue": 0.0,
            "recordable": 1,
            "type": "floatValue",
            "unitOfMeasure": "%",
            "value": **100.0**,
            "writeable": 0
        },
        {
            "id": "/heatingCircuits/hc2/pumpModulation",
            "maxValue": 100.0,
            "minValue": 0.0,
            "recordable": 1,
            "type": "floatValue",
            "unitOfMeasure": "%",
            "value": **0.0**,
            "writeable": 0
        },
```
But when I compare winter and summer-mode the only difference is in `pumpModulation`, but `currentOpModeInfo` stays the same.
As far as I can see the only real indication if the heatingcircuit is running is the `pumpModulation` > 0.
The `current_temperature`-attribute in HA shows here always `null`.
[bosch-scan-summer.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/4710499/bosch-scan-summer.json.txt)
[bosch-scan-winter.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/4710501/bosch-scan-winter.json.txt)
[bosch-scan-winter_hwactive.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/4710503/bosch-scan-winter_hwactive.json.txt)

**Comment by pszafer** [comment]
in EMS bus there is:
```
 {
            "allowedValues": [
                "off",
                "forced",
                "cooling"
            ],
            "id": "/heatingCircuits/hc1/currentSuWiMode",
            "recordable": 0,
            "type": "stringValue",
            "value": "forced",
            "writeable": 0
        }
```

in CAN bus I think the best would be to check manually `outdoor temperature > suwiswitchmode  and suwi is active`.
I can also add extra sensor with pumpModulation to each HC.

I'm not eager to set HC on off if `pumpModulation == 0`, because I think bosch can sometimes turn off pump when HC is in auto mode and then component would lie about status.

what do you think?

**Comment by nibblerrick** [comment]
The problem is checking `outdoor temperature > suwiswitchmode and suwi is active` doesn't work as I said because the RC35 does some magic. At the moment I am doing that and it doesn't work so well.
A sensor for `pumpModulation` would be fine for me if that's possible.
I think setting the HC to off if `pumpModulation == 0`  isn't a good way, too.
So a sensor with the `pumpModulation` would be the best I think.

**Comment by nibblerrick** [comment]
Thanks for the update! With 9.1 here is what happens:
PumpModulation is availible, however it seems shifted:
when pump hc2 switches on hc3-pumpmodulations gets updated.
on hc3 hc4-pump and on hc4 hc2-pump gets updated
On startup I get this warning:
```
Logger: bosch_thermostat_client.helper
Source: custom_components/bosch/__init__.py:253
First occurred: 9:12:36 (5 occurrences)
Last logged: 9:16:39

Can't update data for controlType. Trying uri: /heatingCircuits/hc2/controlType. Error message: URI /heatingCircuits/hc2/controlType doesn not exist: 403, message='Forbidden', url='http://10.134.49.84/heatingCircuits/hc2/controlType
```

I tried to make a scan, so it might be helps debugging, but when I try to make a scan now I get this:

```
Logger: bosch_thermostat_client.encryption.base_encryption
Source: custom_components/bosch/__init__.py:284
First occurred: 9:17:27 (1 occurrences)
Last logged: 9:17:27

Unable to decrypt: b'\xee\x1b\xf5~%\xae\x9f\x89\xa4P\r\xbe\xc6a\xce:\xf7\xd2\x90\xca\x1d\xe5-\xffs\xf1\xb3\xc62p<\xe9\xd7/\\\x0c\x02`g\x19\xaa\xc9tN\xcd\x8f\xed\x0b\x9e)\x7f\xa2H\xfbP\x03L\xb7>\xdd{\x01\x08SGh\xeb\x12\x16\xc6\xa4\x1e\x80\xf8\x81\xdb\x8b\xd3\x00\x89.\xf4\x89+\x96s\xbdo\x7fLq\xde\x8b\xc8*\xcdT\xfb9\xe7\xe6\xac\x17\x04\xd6\xdfj\xfc\x02\xb3\xc8\xe7\xf3-\xe1V/\xd7jQ.\xba\x15j\xe3G\xb8pwV\x8f\xed\xdf\xd4^U>\xf8\xd2\xfb =\xb0\x95\x0e=\x0b\xc5\xc7V\xbb\xb08;\x91\xe9v\xa3"\x91\xf2P\xa9M\xdd\x03<\x034\x88!\xf9\x19>zgf\xadkE\x82I\xdb\xb0B\x1f\x04l\xc7\xcfA\xf3\xf8\xf4\xf5`N\xbf\x03\xcb7\xaa\xd1\xe1Zn\x13\x05' with error: 'utf-8' codec can't decode byte 0xee in position 0: invalid continuation byte
```

Does this help?

**Comment by nibblerrick** [comment]
Even with the switchpoint shifted on my system, as long as I know it it's easy to integrate and works very well for me, thank you again for integrating that.
Would be fine by me to close the issue therefore.

**Comment by pszafer** [comment]
can you open new issue for this shifted problem and explain it? am I understand correctly that if hcX turns on then you see hcX+1 updated as on? and hcX is still off?

**Comment by nibblerrick** [comment]
Hi, kind of. I'll try to gather a new log file and describe the issue best as possible at the weekend.
