### ISSUE TITLE
Question about sensor.actual_power

### ISSUE THREAD

**Issue by gmed-ed** [bosch-thermostat/home-assistant-bosch-custom-component#330]
Just to prevent missunderstandigs:

sensor.acutal_power provides information about power according to gas-burner modulation.

We`ve got an Buderus GB162-15 with a minimum power of 2,4kW up to 14,4kW max.
Sensor shows 100kW max?!

Is this sensor just related to sensor.actual_modulation?
If possible, where could i place min-max values of the burner to get accurate measurements?

If it's not possible i'm going to create a helper-entity to calculate values baseg on sensor.acutal_power.

**Comment by zbikmarc** [comment]
> Is this sensor just related to sensor.actual_modulation?

I am pretty sure it is not. I have Buderus GB072-24 and I can see up to 15kW (last days). While actual modulation, presented in %, has exactly same shape but between 0 and 100%+

This might be due to how your boiler reports data.

**Comment by gmed-ed** [comment]
Hi, as you can see,
our GB162 shows 100kW max, but has just 15kW !?

![Bildschirmfoto_2023-10-20_11-17-40](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/43848352/bdd8956a-7bcf-477b-8403-879a9b86448b)

Maybe you're right and GB172 Software is showing correct values?

I created a template to recalculate down from 100kW to 15kW.
But those values do not correspondent to our gas-meter values...

**Comment by pszafer** [comment]
Those sensor are inaccurate and often report garbage.
Use new statistic API and then you'd get past data in Energy dashboard (see wiki for more info)
Bosch API returns data live, but somehow after an hour these data are recalculated into something very different (and closer to truth).
