### ISSUE TITLE
Entity sensor.ecus_avg_outdoor_temperature is using state class 'total' which is impossible

### ISSUE THREAD

**Issue by ngosang** [bosch-thermostat/home-assistant-bosch-custom-component#333]
**Describe the bug**
I see this message in Home Assistant:
> 3-10-11 14:08:42.271 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ecus_avg_outdoor_temperature (<class 'custom_components.bosch.sensor.energy.EnergySensor'>) is using state class 'total' which is impossible considering device class ('temperature') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues

**To Reproduce**
1. Configure Junkers CT100 with NEFIT (other metrics are working fine from here)

**Expected behavior**
No warning log

**Version**
  - HA version? 2023.10.1
  - HA Bosch component version? 0.23.4

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/commit/e5967066caa58622bb0ccf13c4795bde1503ea63

**Comment by ngosang** [comment]
@pszafer could you publish a release with the latest commits?
