### ISSUE TITLE
Can't install integration -- "message":"Invalid handler specified"

### ISSUE THREAD

**Issue by chodenthalgithub** [bosch-thermostat/home-assistant-bosch-custom-component#336]
Hi, i installed Bosch thermostat over HACS. 
But if I want to add the Integration in Home Assistant, I get the error: 

Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

(In English: Config flow could not be loaded: {"message":"Invalid handler specified"} )

I have Version: Home Assistant 2023.9.3
Installed as Docker on Linux. 

What can I do, to fit that?
Regards

**Comment by MisterAG** [comment]
Hi, 

I have the same issue.  Running version Home Assistant 2023.11.0.dev20231022 on raspberry pi 4 in a dockercontainer.
Any solution to this?

Best regards,
Jan

**Comment by pszafer** [comment]
Can you enable debug logs of the component and provide more info?

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1

**Comment by chodenthalgithub** [comment]
Sorry, I have updated home assistant to the latest stable version and get already the error message. 
I can't enable debug mode, because I can't install the integration. I get the error message during the installation of the integration. 
Regards
Christian
