### ISSUE TITLE
"Can't update data for Hotwater temp" nore "actualPower"

### ISSUE THREAD

**Issue by rikardkjell** [bosch-thermostat/home-assistant-bosch-custom-component#337]
**Describe the bug**
Felet härrör från en anpassad integration.

Logger: bosch_thermostat_client.sensors.sensor
Source: custom_components/bosch/__init__.py:398
Integration: Bosch thermostat (documentation, issues)
First occurred: 16 oktober 2023 kl. 13:25:23 (2323 occurrences)
Last logged: 08:45:49

Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url=URL('http://192.168.xx.xx/system/sensors/temperatures/hotWater_t2')
Can't update data for Actual Power. Trying uri: /heatSources/actualPower. Error message: URI /heatSources/actualPower doesn not exist: 404, message='Not Found', url=URL('http://192.168.xx.xx/heatSources/actualPower')
Can't update data for supplyTemperatureSetpoint. Trying uri: /heatingCircuits/hc1/supplyTemperatureSetpoint. Error message: Connection timed out for /heatingCircuits/hc1/supplyTemperatureSetpoint.

**To Reproduce**
N/A

**Expected behavior**
Expected the hot water temperature to be fetched

**Screenshots**
N/A

**Version**
  - HA 2023.10.3
  - Bosch custom component v0.23.4
  - Python Bosch HTTP client version? Don't know where to find

** Debug SCAN **
** IMPORTANT **
http://jsonblob.com/1163741258253721600

**Additional context**

**Comment by kodsama** [comment]
I have the same on my side.
Could this be related to #289 ?

**Comment by pszafer** [comment]
Your device doesn't provide such values as you can see:

```
{
      "id": "/system/sensors/temperatures",
      "type": "refEnum",
      "references": [
        {
          "id": "/system/sensors/temperatures/outdoor_t1",
          "uri": "http://THERMOSTAT/system/sensors/temperatures/outdoor_t1"
        },
        {
          "id": "/system/sensors/temperatures/supply_t1_setpoint",
          "uri": "http://THERMOSTAT/system/sensors/temperatures/supply_t1_setpoint"
        },
        {
          "id": "/system/sensors/temperatures/supply_t1",
          "uri": "http://THERMOSTAT/system/sensors/temperatures/supply_t1"
        },
        {
          "id": "/system/sensors/temperatures/return",
          "uri": "http://THERMOSTAT/system/sensors/temperatures/return"
        },
        {
          "id": "/system/sensors/temperatures/switch",
          "uri": "http://THERMOSTAT/system/sensors/temperatures/switch"
        }
      ]
    }, 
```

Same in `"id": "/heatSources",`, no actualPower.
So you have to disable those sensors.

**Comment by rikardkjell** [comment]
Ok, thank you very much. I'll  disable them.
