### ISSUE TITLE
Changed name of sensors in the Utilities section

### ISSUE THREAD

**Issue by jwmaas** [bosch-thermostat/home-assistant-bosch-custom-component#340]
The sensors in the Utilities documentation have been renamed:
Changed "sensor:ehwenergy_hot_waterexternal" into "energy:ehwenergy_hot_waterexternal"
Changed "sensor:echenergy_central_heatingexternal" into "energy:echenergy_central_heatingexternal"

**Comment by pszafer** [comment]
What is the problem here?

**Comment by jwmaas** [comment]
"sensor:ehwenergy_hot_waterexternal" and "sensor:echenergy_central_heatingexternal" do not exist, and therefore the listed queries did not work. With with the edited names "energy:..." the queries work

**Comment by pszafer** [comment]
Are you talking about screenshot in the wiki page?

**Comment by jwmaas** [comment]
I am talking about the wiki page text and query in the utility meter section.
