### ISSUE TITLE
Buderus KM 200; recording new statistics, Energy Gas: incorrect first value and missing value for the last hour

### ISSUE THREAD

**Issue by HeGa59** [bosch-thermostat/home-assistant-bosch-custom-component#341]
**Describe the bug**
  Energy representation is incorrect for the first value (both screenshots) and the last hour is missing (screenshot October 30, 2023). This is also the case in version 0.23. The absence of the last hour is also in all previous days!

**To Reproduce**
Buderus KM 200, Mode HTTP, recording new statistics

**Screenshots**
<img width="1205" alt="Gasverbrauch 20231031" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11235285/3deb75f2-51a1-4c0c-98d2-196aaf2c0528">

<img width="1198" alt="Gasverbrauch20231030" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11235285/28a5d7e5-dbab-499e-a707-442868d99d5d">

**Version**
  - HA version?
    Home Assistant 2023.10.5 
    Supervisor 2023.10.1
    Operating System 11.1
    Frontend 20231005.0 - latest 
  - HA Bosch component version?
       0.24.0-dev.2 and also 0.23.4
  - Python Bosch HTTP client version?
       bosch-thermostat-client==0.23.2
** Debug SCAN **
[bosch_scan.json](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13219907/bosch_scan.json)

** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/
   http://jsonblob.com/1168971594906591232

**Comment by HeGa59** [comment]
I'm one step further. The last step on the day "Appending day to statistic table with id: recording: ractualpowerexternal" is at 11:06 p.m., the next one at 1:06 a.m. This means that the calculation at 00:06 is missing!
[Log Bosch.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13256005/Log.Bosch.txt)

**Comment by HeGa59** [comment]
Hello pszafer, I think I found the error in the “recording.py” script: Line 97:
      "start_time=start, stop_time=start + timedelta(hours=26)"
change the value from 26 to 25, then the first value is correct and the last value also appears. If you agree, please change the next version and close this issue

**Comment by HeGa59** [comment]
The historical values are now all ok, but on the current day I have the error described again after an hour. There may be another problem on line 200. The value 25 seems to be necessary there too.

**Comment by tl2909** [comment]
Thanks for bringing this up - same issue here with the same setup (Buderus KM 200, Mode HTTP, recording new statistics)

Core 2023.11.1
Frontend 20231030.1
Bosch Integration: v23.4

![Unbenannt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/71659726/770e645b-8b3e-47f5-a5cd-4c481fa4dc97)

**Comment by FC-Rene** [comment]
Hello, I have the same issue. The value between 0:00 - 01:00 increases throughout the day:

<img width="207" alt="ha_energy_gas" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/113801570/e482bd46-2608-4df5-b059-b9de78f6b65b">

It doesn't happen every day, currently only every other day. But I'm not sure yet, as I've only been using it for five days.

Using new statistic API
RC300 (I think)
IVT / HTTP

Core: 2023.11.2
Frontend: 20231030.2
Bosch Integration: v0.23.4 (I think)

Other questions: Is there a way to rename the recording stats for the energy dashboard and store a static price?

**Comment by pszafer** [comment]
@FC-Rene about other questions both answers are no.

**Comment by birefringence** [comment]
What is happening is that the "sum" column in the database increases to much. I observed this

1. on the first day after turning on the heating.
2. after being on vacation for a few days and the system being in vacation mode (effectively not heating)

Note how the sum in the third row suddenly jumps inexplicably:

```
328175|||||||1.0|1901.0|68|1703279160.87331|1703275200.0|
328237|||||||1.0|1902.0|68|1703282760.83316|1703278800.0|
333175|||||||5.0|2141.0|68|1703574362.77258|1703570400.0|
333236|||||||2.0|2143.0|68|1703577960.77433|1703574000.0|
```

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
