### ISSUE TITLE
CT200: Possibility to control which Rooms getting boosted

### ISSUE THREAD

**Issue by Simi791** [bosch-thermostat/home-assistant-bosch-custom-component#342]
**Is your feature request related to a problem? Please describe.**
The integration already offers the option of switching on the boost and setting the duration and desired temperature. However, there is currently no way to configure which heating circuits or devices the boost is applied to. It looks like the rooms that were last selected in the Easycontrol-App are being used. Sometimes the selection seems to be random. 

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/138227370/a2b625dd-c088-4798-a3c9-f2ae0ce71778)

**Describe the solution you'd like**
It would be great if there was a way to select which rooms the boost should be applied to (like in the Easycontrol-App).

**Describe alternatives you've considered**
Alternatively, it would also be possible to always apply the boost to all rooms.

**Comment by masterx1981** [comment]
I'm trying to do this using a special program for every zone (all the radiators have it's own easy control valve), then via home assistant set this program using a scene.

**Comment by pszafer** [comment]
Boost is for whole heating circuit. There might be some boost info in `/zones` make multiple bosch scans.
Before boost and after boost, after changing zone settings and before. Maybe then we can figure out how it works.

I'll close issue now and reopen if you come back with data (too many users just ask for something without giving any details so I have too many issues open).

**Comment by Simi791** [comment]
The raw scan was helpful in understanding how it works. The heating circuit has a parameter called boostZones, with which the zones that should be boosted can be parameterized. To meet my requirement, the integration would need to provide this list and make it selectable under Boost. This is also exactly the list that can be modified in the Easycontrol-App.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/138227370/08cd75b7-d0bf-4e9b-9d75-6736a828e3d6)

![Screenshot_2024-03-11-16-46-13-365_com bosch tt bosch controlng](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/138227370/8af583c0-1642-49c7-9aea-57e9324d5ac3)

If needed, I'm also happy to provide the complete scan
