### ISSUE TITLE
Can't update data for Hotwater temp.

### ISSUE THREAD

**Issue by tonypapa55** [bosch-thermostat/home-assistant-bosch-custom-component#343]
Logger: bosch_thermostat_client.sensors.sensor
Source: custom_components/bosch/__init__.py:402
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 07:08:33 (1129 occurrences)
Last logged: 13:23:28

Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url=URL('http://192.168.1.200/system/sensors/temperatures/hotWater_t2')
Can't update data for Actual Power. Trying uri: /heatSources/actualPower. Error message: URI /heatSources/actualPower doesn not exist: 404, message='Not Found', url=URL('http://192.168.1.200/heatSources/actualPower')
Can't update data for System pressure. Trying uri: /heatSources/systemPressure. Error message: URI /heatSources/systemPressure doesn not exist: 404, message='Not Found', url=URL('http://192.168.1.200/heatSources/systemPressure')
Can't update data for pumpModulation. Trying uri: /solarCircuits/sc1/pumpModulation. Error message: Connection timed out for /solarCircuits/sc1/pumpModulation.

**Comment by pszafer** [comment]
Gateway returns 404. It's not issue with integration.
