### ISSUE TITLE
AttributeError: 'BoschWaterHeater' object has no attribute 'async_turn_on'

### ISSUE THREAD

**Issue by MortenHannemose** [bosch-thermostat/home-assistant-bosch-custom-component#345]
**Describe the bug**
I cannot turn water heater on from a scene.

**To Reproduce**
1. Create a scene that changes "operation" of water heater from "eco" to "on"
2. Activate the scene
3. See error

**Expected behavior**
I expected water heater to turn on

**Screenshots**
```
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 830, in _handle_entity_call
    partial(getattr(entity, func), **data)  # type: ignore[arg-type]
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschWaterHeater' object has no attribute 'async_turn_on'
```

**Version**
  - HA 2023.4.6
  - HA Bosch component version: v0.21.0

**Additional context**
A scene to turn the water heater from "on" to "eco" works. I am able to turn it from "eco" to "on" through the GUI.

**Comment by MortenHannemose** [comment]
I just updated to the latest version (v0.23.4) and get a NotImplementedError. I guess this means it's a known issue?

```
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/components/water_heater/__init__.py", line 314, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/data/data/com.termux/files/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/components/water_heater/__init__.py", line 310, in turn_on
    raise NotImplementedError()
NotImplementedError
```

**Comment by pszafer** [comment]
Please attach bosch scan
I'll close issue now and reopen if you come back with data (too many users just ask for something without giving any details so I have too many issues open).

**Comment by MortenHannemose** [comment]
Thank you so much for the work you do! I have attached a scan here: 
[rawscan.json](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13858751/rawscan.json)

**Comment by MortenHannemose** [comment]
My dashboard looks like yours. 
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11504118/2e477944-e9fa-4bad-9513-904c52ad9aad)
I'm trying to change the mode from "eco" to "on", with a scene. If I do it from the dashboard, it works fine, but when I activate my scene I get the error.

**Comment by pszafer** [comment]
Show me this scene. For me it seems you're not trying to change mode, but you're trying to turn on heater. It's weird that scene allows it anyway.

**Comment by MortenHannemose** [comment]
This is a screenshot of the scene. I'm not sure if there is a better way of sharing it. 
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/11504118/a6c6367c-1919-4133-8804-c09bbe52c567)

**Comment by MortenHannemose** [comment]
And, if I make a scene setting the mode to "eco" it is able to change mode from "on"->"eco" as expected.
It is only when I try to change the mode to "on" that there is an issue.

**Comment by pszafer** [comment]
Copy and paste code of the scene from scenes.yaml file.

**Comment by MortenHannemose** [comment]
```
- id: '1699710055925'
  name: 'Varm'
  entities:
    water_heater.dhw1:
      min_temp: 40
      max_temp: 55
      operation_list:
      - 'on'
      - eco
      - high_demand
      current_temperature: 53
      temperature: 42
      operation_mode: 'on'
      setpoint: low
      switchPoint:
      bosch_state: ACTIVE
      target_temp_step: 1
      friendly_name: dhw1
      supported_features: 3
      state: 'on'
    switch.charge:
      friendly_name: charge
      state: 'off'
  metadata: {}
```

**Comment by pszafer** [comment]
remove `state: 'on'` line from scene, maybe this would help.
