### ISSUE TITLE
energy consumption adds some (huge) amount every hour

### ISSUE THREAD

**Issue by CanisLupus-42** [bosch-thermostat/home-assistant-bosch-custom-component#346]
**Describe the bug**
The 'energy consumption' sensor steadily increases, when the the burner is active (as expected) . But every hour it jumps up by a huge amount, even if the burner is not in use. This amount added hourly seems to be increasing over time, but I can't figure out by how much or on which basis.
The problem seems to have been around since I integrated the heating in HA 6 weeks ago. I just started looking at the energy values a few days ago and therefore noticed it.

**Expected behavior**
I cleaned up the data and eliminated all the hourly additions. The resulting values seem valid and roughly match the gas meter. In conclusion: The expected behavior would be a realistic counter, without the unexplicable hourly additions.

**Screenshots**

sensor.energy_consumption over the last 24 hours, the hourly jumps are clearly visible:
![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/88034398/ed6dc572-100a-4788-80cb-3013dc53c430)

sensor.energy_consumption in the long run. As the hourly steps are increasing, there is an exponential growth over time:
![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/88034398/48d8860f-777a-40a5-aaf2-108cc57fe141)

Corrected graph, by deleting the hourly increases:
![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/88034398/814b782c-1d9d-4382-996a-04e42a9077ec)

**Version**
  - HA version: 2023.11.2 (but the problem seems to be )
  - HA Bosch component version: v0.23.4
  - Python Bosch HTTP client version: ?
  
**Additional context**
I integrated the heating system based on a 'GB212-15 H IP' and a 'RC-310' localy via HTTP.

**Comment by honikos** [comment]
This is a known issue. My is about, if not exactly, 10 times to high (Bosch/Buderus heat pump).
A template sensor should fix it (divided by 10).
![energy 2023-12-05 08-56-01](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/34808551/daf5c46f-4105-4182-a43e-aab71355b8c1)
