### ISSUE TITLE
Support for MB LAN2 with CerapurComfort-Eco ZSBE 28-3 A 23

### ISSUE THREAD

**Issue by Skirf** [bosch-thermostat/home-assistant-bosch-custom-component#347]
Is there a chance of getting my combination to work? Additionally i use a FW200.

Thanks!

**Comment by pszafer** [comment]
Make scan with MB LAN2 and attach it here. I'll reopen if you'll give some more info with files needed.

**Comment by Skirf** [comment]
Hi there,

 

which scan do you want me to do? I’m relatively new to the topic.

 

Thanks!

 

Von: Pawel ***@***.***> 
Gesendet: Montag, 8. Januar 2024 08:08
An: bosch-thermostat/home-assistant-bosch-custom-component ***@***.***>
Cc: Skirf ***@***.***>; Author ***@***.***>
Betreff: Re: [bosch-thermostat/home-assistant-bosch-custom-component] Support for MB LAN2 with CerapurComfort-Eco ZSBE 28-3 A 23 (Issue #347)

 

Make scan with MB LAN2 and attach it here. I'll reopen if you'll give some more info with files needed.
