### ISSUE TITLE
CT200 eTrv Open Window Detection as sensors 

### ISSUE THREAD

**Issue by Tuningmormota** [bosch-thermostat/home-assistant-bosch-custom-component#348]
It would be great if the "openWindowDetection" values would be represented as sensor to zones (or devices). 
I would like to use this information to a window reminder if a window is kept open too long.

The data is altready available in the bosch.scan file.

[bosch_scan.json](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13474343/bosch_scan.json)

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1

**Comment by Tuningmormota** [comment]
Thank you for the feature. The new sensor is visble, but nearly all sensor has a value of "False". Later in the night I may be able to create a proper issue ticket with all the data and log files.

![Screenshot_20240108_131621_Home Assistant](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/100776613/53bfdb48-ed1b-4ffc-989b-c911f8bea0bd)
