### ISSUE TITLE
Your device is  null

### ISSUE THREAD

**Issue by hcm183** [bosch-thermostat/home-assistant-bosch-custom-component#349]
The Bosch Integration is broken. 
Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.1
Frontend
20231030.2

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:297
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
Your device is unknown null

Do not have any idea, whats wrong or how to fix.

HELP!

**Comment by pszafer** [comment]
What have you done? Did you succeed?

**Comment by hcm183** [comment]
rejoiced too soon; it's broken again

Am 6. Dezember 2023 22:14:24 MEZ schrieb Pawel ***@***.***>:
