### ISSUE TITLE
 Installation failed, not possible

### ISSUE THREAD

**Issue by tempo3** [bosch-thermostat/home-assistant-bosch-custom-component#35]
Hello, I tried to install the integration as described here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component

At the integration page, I selected Bosch, For a few seconds a window shows a search but after a few moments it goes back to the selection of the integration w/o any further step...
Any help is highly appreciated.

BTW Info: The buderus custom component is not longer active in the config. This component was running w/o any problem over the last month, only several sensors were missing.

Setup:
Home Assistant 0.113.0

Protokolldetails ( ERROR )
Logger: homeassistant.config_entries
Source: config_entries.py:521
First occurred: 12:46:59 (3 occurrences)
Last logged: 13:00:03
Cannot find integration bosch

**Comment by pszafer** [comment]
do you run Home Assistant OS or some Debian/Ubuntu etc?

**Comment by tempo3** [comment]
Thx for your quick response. Its Debian 10 (buster)

**Comment by pszafer** [comment]
pypi can't install libxml on debian.
you have to install it using apt-get 
I think this should be enough:
```
apt-get install libxml2-dev libxslt-dev python-dev
```

source: https://stackoverflow.com/questions/5178416/libxml-install-error-using-pip

**Comment by tempo3** [comment]
thx, for the hint. did it. but now, the Bosch integration is not in list of integrations...? any idea?

**Comment by pszafer** [comment]
do you have it installed as venv? maybe install this package manually and then check HA.

**Comment by tempo3** [comment]
thx, no not as venv. Its a regular debian ...

**Comment by pszafer** [comment]
maybe try cleaning cache in browser.

**Comment by tempo3** [comment]
Thx, it works with the manual installation.
