### ISSUE TITLE
Lots of measurements dissapeared

### ISSUE THREAD

**Issue by kodsama** [bosch-thermostat/home-assistant-bosch-custom-component#350]
**Describe the bug**
A lot of measurements are not available since the new API was released (0.22 if I recognize).
I barely can see the heating and hot water now, all measurements sensors are present in the addon but marked as disabled and not getting any data anymore.

The scan of my heat pump does show a lot of them though. Is this related to a firmware upgrade? Downgrading the addon does not fix the problem as I run into a bug to add the heatpump then. 

**To Reproduce**
1. Add the bosch add-on, follow steps to add the heat pump (AirX in my case)
2. Check sensors, lots of them are displayed but disabled by default
3. Activating/deactivating new statistics API does not fix the problem

**Expected behavior**
More sensors should return data. Before 0.22.2 I could see the modulation %, energy usage, target setpoint tempeerature, etc. Now all these are still present but do not return anything.

**Screenshots**
<img width="998" alt="image" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/4998141/5584ce18-47ad-484c-b00a-51f79b2fc418">
<img width="1037" alt="image" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/4998141/ee7f51ae-426d-47d1-9a2c-adfa56dfb6c3">

**Version**
  - HA version? 2023.11.3
  - HA Bosch component version? 0.23.4

**Debug SCAN**

https://pastebin.com/mmT3368H

**Additional context**
This does not seem to be related to HA but to the new statistics API as this is when I noticed the problem appeared. Switching on or off the statistics API did not solve the problem.
This is still the same as in #292, fix of #289 did not fix it

**Comment by Marc911H** [comment]
Hello,

I have the same problem. I only see thermostats for heater and hot water.
I have a KM200 V2 & rc310

**Comment by pszafer** [comment]
Yes, a lot of sensors are disabled by default. It is by design. Enable those you need. Too many people locked themselves somehow. It might be connected with too many API calls.
