### ISSUE TITLE
IVT - Invalid Start bite - Unable to integrate.

### ISSUE THREAD

**Issue by IkaSGC** [bosch-thermostat/home-assistant-bosch-custom-component#351]
**Describe the bug**
It is not possible to integrate the device. An error pops up that the IP address or password is wrong.

**To Reproduce**
IVT --> HTTP --> Enter data --> ERROR

**Expected behavior**
Don't get an error.

**Screenshots**

![ScreenHunter_01 Dec  03 19 14](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/7561343/e62f31c4-71c6-47a2-bcf4-a5a410b01071)
![ScreenHunter_02 Dec  03 19 18](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/7561343/895a72e6-9623-4fee-9161-661e559e4842)

**Version**
  - HA version? - Latest
  - HA Bosch component version? - Latest
  - Python Bosch HTTP client version? - Dont Know

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`

Not Found

**Additional context**

**Comment by IkaSGC** [comment]
I changed the password, just numbers and letters in lower case, I can log into the app but not here. The next question is what, see screen, is the token.

![20231018_095744](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/7561343/0290b675-0109-4337-84c3-4aaa209ab502)

I've tried the top long number with and without dashes, but it doesn't work.

**Comment by hcm183** [comment]
The same here! App works, HA don't. The update of today changes - nothing! Not able to integrate; "device is null" 😩

**Comment by hcm183** [comment]
Added the device several times. Now it is on HA available. But only two entities: dhw1 and hc1.

**Comment by IkaSGC** [comment]
Ok, its working...... Password must be the same as PWD into your mobile app (logicaly) and that TOKEN is "Password" from that sticker from LAN module. 

Token is in format "xxxx-xxxx-xxxx-xxxx" WITH !!! dashes...

**Comment by honikos** [comment]
Strange ... my Token is without dashes.
@hcm183   try to remove the Bosch Thermostat integration, then restart ha and do a fresh install.

**Comment by hcm183** [comment]
New installation did it! Don't know how. But only success is important😁.
Thanks for the Support!
HCM

Am 4. Dezember 2023 20:41:58 MEZ schrieb honikos ***@***.***>:
