### ISSUE TITLE
[CT200] Couldn't find device model. Got product ID: None

### ISSUE THREAD

**Issue by bramvdpol** [bosch-thermostat/home-assistant-bosch-custom-component#353]
**Describe the bug**
Plugin does not initialize. Logging shows: `Couldn't find device model. Got product ID: None`. See attached log file for details.

**To Reproduce**
1) Add CT200 thermostat using 0.23.2 plugin

**Expected behavior**
Thermostat shows up

**Screenshots**
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/15914261/c67807d2-12b4-4200-aae6-4cb7b79be314)

**Version**
  - HA version? 2023.11.3
  - HA Bosch component version? 0.23.2
  - Python Bosch HTTP client version? Don't know how to check

** Debug SCAN **
Does not work, probably because the thermostat will not in itialize

**Additional context**
 Interestingly the thermostat worked ok for a long time. Then at some point only the water temperature and modulation were still accesible but all thermostats disappeared. After trying to configure the thermostat again the CT200 will no longer initialize in home assistent. 

If there is anything else I can try to narrow down what is going wrong please let me know :). I could probably figure out how to use bosch-thermostat-client if that is required?

[CT200 log.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13605049/CT200.log.txt)

**Comment by pszafer** [comment]
Should be fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
