### ISSUE TITLE
Unknown model; integration of an device don't work

### ISSUE THREAD

**Issue by hcm183** [bosch-thermostat/home-assistant-bosch-custom-component#354]
**Describe the bug**
Bosch intergration newly don't work. Add a device fails "unknown model"

**Version**
Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231030.2
** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/  
There is no such scan.

**Additional context**
The Integration worked, after an update in HA it was broken. After an update of the integration it worked again. Now after an other update of HA, it's broken again.

**Comment by chrisdevh** [comment]
Hi @hcm183 : I think you discoverd the same bug as in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/332?

**Comment by cengizsek** [comment]
hi
I installed the integration for the first time and it didn't work. (12-23 with last update)

**Comment by pszafer** [comment]
For some users changing password multiple times worked. For most times it was user fault to get put wrong password (singleid password instead of device password). You can try `bosch_cli` to get scan, if that works then it's bug in integration.

**Comment by cengizsek** [comment]
I changed my password many times but it didn't work.
