### ISSUE TITLE
Setting temperature

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#355]
Hi,

I'm probably doing something wrong in my script, but I'm getting the following error message in my logfile:

----
This error originated from a custom integration.

Logger: bosch_thermostat_client.circuits.easycontrol.base
Source: custom_components/bosch/climate.py:116
Integration: Bosch thermostat (documentation, issues)
First occurred: 10:17:23 (4 occurrences)
Last logged: 13:45:24

Don't get proper response from setting temperature.

---

I use the following code:

----

**service: climate.set_temperature
data:
  hvac_mode: heat
  temperature: 17.5
target:
  entity_id: climate.kantoor_haaino**

----

The good news is that the automation does work. 

Hope someone point me out to my obvious mistake.

**Comment by pszafer** [comment]
Turn on debug logs and come back with result or come to discord to discuss it further. I'll reopen issue if got more data.
