### ISSUE TITLE
Recording consumed power adds wrong data in dB

### ISSUE THREAD

**Issue by WeirdSience** [bosch-thermostat/home-assistant-bosch-custom-component#356]
**Describe the bug**
Using the recording:rconsumedenergyexternal for statistics it has now started to add a lot of consumed kWh every day at 00:00:00.
Some days the statistics says the IVT unit has consumed more energy then the entire house.

**To Reproduce**
1. Go to development tools and statistics
2. Click on recording:rconsumedenergyexternal
3. Scroll down to time stamp 00:00:00 for any day
4. See error as integrations add a lot of kWh at this particular time

**Expected behavior**
Integrations should not add extra kWh

**Screenshots**

**Version**
  - Core:2023.11.23
  - Supervisor: 2023.11.06
  - OS:11.2
  - HA Bosch component version: v.0.23.4
  - Python Bosch HTTP client version?
![20231205](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/94736569/cbd8769f-6512-4e39-8088-b4c68039c3fc)
![20231206](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/94736569/e6fd18cc-b12c-45c2-b5dd-343d1f998554)

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
Is this a error where integrations adds to many kWh every day at 00:00:00.

**Comment by WeirdSience** [comment]
EDIT: Debug SCAN doesn´t seem to be working, see attachment
![Debug](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/94736569/fb686577-b2e6-4a1e-a8a6-801ab09de94e)

**Comment by honikos** [comment]
Core 2023.12.3
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2


Debug SCAN works.

![bosch_debug_scan_ha](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/34808551/3d36eb0a-72ad-4749-a2c7-90b20063f4ca)

> Some days the statistics says the IVT unit has consumed more energy then the entire house.

This is normal (bug). Bosch doesn't open their API. Some value are 10 to 20 times to high.

**Comment by WeirdSience** [comment]
Yes, you are right. There is a debug file stores and when I look at it, the data from the log doesn´t match the values stored in Home assistant database therefore I believe it´s a bug in the integration. 
Example, data from 23/12/23 at 00:00:00. Value in debug file is 1kWh if I assume "y"/"c" = 1 and recording i home assistant dB shows 9 kWh. 
![Debug_2](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/94736569/af8e962e-5e42-4005-a787-9e529eb4ff8c)

**Comment by pszafer** [comment]
yes, I have problem with finding last value in database. I plan to work on it during Christmas holiday. Please follow this issue https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/294
If you're willing to help with fixing algorithm it would be much appreciated.

**Comment by WeirdSience** [comment]
Thank you, I hope you solve it. Sorry for not contributing but this is out of my skill level :)
Marry Christmas
