### ISSUE TITLE
Add Easy ontrol app features

### ISSUE THREAD

**Issue by S-360** [bosch-thermostat/home-assistant-bosch-custom-component#357]
This a feature request for some of the settings that are available in the Easycontrol app(Android) right side
![Screenshot_20231211_232357_EasyControl](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/66750273/d6becc1a-24ba-405e-aebb-94c6bc552a48)
 pop out panel(see pic)

-Away
-Child-Lock
-Advance
-Boost

I'm alway using boost to increase/decrease the heating for a few hours or advance to skip to the next preset.

Would be great if these were available through Homes Assistant and being able to see and control the state from the dashboard.

My thermostat is the Bosch EasyControl CT200.

Thanks

Update...

I have now managed to get the "Boost" and "Away" functions by enabling the following entities

for Boost enable the following entities;
- switch.boost
- number.boost_duration
- number.boost_temperature
- sensor.hc1_boost_remaining_time

For away anable the following entities;
- binary_sensor.autoawayenabled
- switch.away_mode
- number.away_mode_temp

There doesn't seem to be any entity to enable the "Advance" feature from the app?

**Comment by pszafer** [comment]
I don't know what is advanced feature. Provide bosch scan and analyze what would you like to have.

I'll close issue now and reopen if you come back with data (too many users just ask for something without giving any details so I have too many issues open).
