### ISSUE TITLE
[CT200] Bosch Easycontrol ct200 not working

### ISSUE THREAD

**Issue by Ri-De-Ru** [bosch-thermostat/home-assistant-bosch-custom-component#358]
**Describe the bug**
Updated HA and Bosch component to versions below and the integration stopped working.

**To Reproduce**
Update from early 2023 HA & Bosch component version to version below. Reconfiguring component didn't resolve the issue.

**Screenshots**
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/22764374/0a4bbdbb-d5b8-42d1-8b75-9908c352a2a0)

**Version**
Home Assistant 2023.12.1
HA Bosch component version 0.23.4
EasyControl 4.8.1

** Debug SCAN **
** IMPORTANT **
[home-assistant_bosch_2023-12-13T07-28-03.215Z.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13657682/home-assistant_bosch_2023-12-13T07-28-03.215Z.log)

**Comment by vrengad** [comment]
Getting the same error when trying [to connect Bosch Easy Control to Home assistant with following resource
](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Installation-Guide)

**Comment by GlosVaper** [comment]
Also same issue;
2023-12-29 23:18:30.788 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.23.2.
2023-12-29 23:18:30.788 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2023-12-29 23:18:30.790 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as xxxxxxx.
2023-12-29 23:18:34.230 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None

**Comment by pszafer** [comment]
It should be fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
I'll close issue now and reopen if you report back that issue still occurs.

**Comment by vrengad** [comment]
I get the following error eventhough i am entering the right credentials

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:306
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 11:10:01 AM (21 occurrences)
Last logged: 11:28:09 AM

You might need to check your password.

**Comment by pszafer** [comment]
Enable debug logs and paste whole error, because imo it's different one.

**Comment by vrengad** [comment]
i have following errors and warnings after i turned on the log.
Log details (WARNING)
This error originated from a custom integration.
Logger: bosch_thermostat_client.connectors.xmpp
Source: custom_components/bosch/__init__.py:299
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 1:21:08 PM (10 occurrences)
Last logged: 1:21:29 PM

Can't decrypt for /gateway/uuid
Can't decrypt for /system/interfaces
Can't decrypt for /gateway/versionFirmware
Can't decrypt for /gateway/productID
Can't decrypt for /gateway/DateTime

Log details (ERROR)
This error originated from a custom integration.
Logger: bosch_thermostat_client.gateway.easycontrol
Source: custom_components/bosch/__init__.py:299
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 1:21:09 PM (2 occurrences)
Last logged: 1:21:29 PM

Couldn't find device model. Got product ID: None

Log details (ERROR)
This error originated from a custom integration.
Logger: bosch_thermostat_client.gateway.easycontrol
Source: custom_components/bosch/__init__.py:299
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 1:21:09 PM (2 occurrences)
Last logged: 1:21:29 PM

Couldn't find device model. Got product ID: None

Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:306
Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
First occurred: 1:21:09 PM (2 occurrences)
Last logged: 1:21:29 PM

You might need to check your password.

**Comment by vrengad** [comment]
i also don't see the bosch_scan.json under my www dir as per following instructions in services.yaml
![Screen Shot 2024-01-08 at 1 30 08 PM](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/154575720/689f9088-82ea-4b95-8e92-df4cfd41e3b8)


Run raw scan for Bosch. It will be available as bosch_scan.json in your www dir of Home Assistant. You can check url of the file in logs after it. It doesn't matter which entity you choose. It makes scan for whole your setup. Typically it is https://ha/local/bosch_scan.json?vX . 
    There will be notification in HA with url of the scan. It takes several minutes to finish. Be patient!
    Choose any entity or device of your bosch inegration, it will find UUID and make scan for your whole Bosch setup. You don't need to choose water heater and climate separately!

**Comment by pszafer** [comment]
Probably you need to change your device password. (it's not single key/bosch id password)

**Comment by Ri-De-Ru** [comment]
> It should be fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1 I'll close issue now and reopen if you report back that issue still occurs.

I will test this tonight, but does this update also require HA 2024.1 or newer?

**Comment by pszafer** [comment]
yes, you'd need the latest HA

**Comment by vrengad** [comment]
Thanks I realised i had a different password for the device and a different one for the single. Tried logging in with the device password and it connected!!. Thank you

**Comment by mgambrill82** [comment]
Hi. I have the same issue but don't have a different password. I don't fancy resetting my ct200 and 3 room thermostats. Is there another way I can get this working?
