### ISSUE TITLE
2024.1 deprication for SUPPORT_*

### ISSUE THREAD

**Issue by ChristophCaina** [bosch-thermostat/home-assistant-bosch-custom-component#360]
**Describe the bug**

2024.1 will throw a deprication warning for the CLIMATE.SUPPORT_* components.

```
from homeassistant.components.climate.const import (
    CURRENT_HVAC_HEAT,
    CURRENT_HVAC_IDLE,
    SUPPORT_PRESET_MODE,
    SUPPORT_TARGET_TEMPERATURE,
)
```
The SUPPORT_* should be replaced with `ClimateEntityFeature`

https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

** Debug SCAN **
** IMPORTANT **

**Additional context**

**Comment by pszafer** [comment]
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
