### ISSUE TITLE
consumed energy from net provider

### ISSUE THREAD

**Issue by cyberoner1** [bosch-thermostat/home-assistant-bosch-custom-component#361]
I thinking about moving from Iobroker to Home Assistant and I am testing my Bosch Heatpump CS7001 with Home Assistant.

One of my most important topic is the consumed energy of my heatpump. In Iobroker I am able to get the hourly value which is written to my influxdb with "ems-esp.0.recordings.heatSources.total.energyMonitoring.consumedEnergy._Hours"

I don´t have an EMS-ESP I am just unsing the km200 interface of this module. Now I have compared the energy which I get from the Add-On and the only value I am able to get is "energy consumption". But this value is not the value of the consumption from net (the kw/h I have to pay for). This value is the indicator how much energy the heatpump produced. Like 1kw/h input = 4 kw/h output.

Is there any way to get the consumed energy from net added

**Comment by pszafer** [comment]
Attach bosch scan.

**Comment by pszafer** [comment]
I'll close issue now and reopen if you come back with data (too many users just ask for something without giving any details so I have too many issues open).

**Comment by cyberoner1** [comment]
Hi, 
I created the scan 
[bosch_scan.json](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/13936876/bosch_scan.json)

there is the section recordings/heatSources/total/energyMonitoring

as it is not possible to get the actual energy measure (as I know only per hour) is it possible to write recordings into a database or similiar?
