### ISSUE TITLE
sensor.hc2_actual_supply_temperature_for_hc entity not avalible

### ISSUE THREAD

**Issue by matejgordon** [bosch-thermostat/home-assistant-bosch-custom-component#365]
Hello, yesterday, I found that the sensor.hc2_actual_supply_temperature_for_hc entity is not avalible.
I'm not sure, if it's after the update or not, but I guess it is.

Log for detail:

  Logger: bosch_thermostat_client.sensors.sensor
  Source: custom_components/bosch/__init__.py:398
  Integration: Bosch thermostat ([documentation](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component), [issues](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues))
  First occurred: 22:12:41 (263 occurrences)
  Last logged: 22:49:37

    Can't update data for Actual supply temperature for HC. Trying uri: /heatingCircuits/hc2/actualSupplyTemperature. Error message: URI /heatingCircuits/hc2/actualSupplyTemperature doesn not exist: 404, message='Not Found', url=URL('http://10.0.0.39/heatingCircuits/hc2/actualSupplyTemperature')
    Can't update data for Hotwater temp. Trying uri: /system/sensors/temperatures/hotWater_t2. Error message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url=URL('http://10.0.0.39/system/sensors/temperatures/hotWater_t2')
    Can't update data for Chimney temp. Trying uri: /system/sensors/temperatures/chimney. Error message: URI /system/sensors/temperatures/chimney doesn not exist: 404, message='Not Found', url=URL('http://10.0.0.39/system/sensors/temperatures/chimney')
    Can't update data for Actual Power. Trying uri: /heatSources/actualPower. Error message: URI /heatSources/actualPower doesn not exist: 404, message='Not Found', url=URL('http://10.0.0.39/heatSources/actualPower')
    Can't update data for System pressure. Trying uri: /heatSources/systemPressure. Error message: URI /heatSources/systemPressure doesn not exist: 404, message='Not Found', url=URL('http://10.0.0.39/heatSources/systemPressure')

**Comment by pszafer** [comment]
It gives you 404 Error, so it's not connected to your installation
