### ISSUE TITLE
CT 200 entities not available after update(s)

### ISSUE THREAD

**Issue by lutze22arcorde** [bosch-thermostat/home-assistant-bosch-custom-component#366]
All entities are not available after HA or/and component update.

Version:
HA Core 2024.1.1
HA Supervisor 2023.12.0
HA Operating System 11.3
HA Frontend 20240104.0

Bosch Smart Home Controller (SHC) 0.4.78

Debug SCAN
http://jsonblob.com/1193087081009504256

**Comment by pszafer** [comment]
It should be fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.1
