### ISSUE TITLE
Update v0.24.1

### ISSUE THREAD

**Issue by marekvich** [bosch-thermostat/home-assistant-bosch-custom-component#367]
After this new update v0.24.1 all sensors are False.

![Snímek obrazovky 2024-01-08 094350](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/101363770/f1045344-e4da-40ae-bf6c-057f223f4bd2)
![Snímek obrazovky 2024-01-08 094506](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/101363770/85aee629-d194-4bec-909c-083656fe4b0a)

**Comment by honikos** [comment]
same here

Logger: homeassistant.util.logging
Source: util/logging.py:102
First occurred: 09:14:59 (15 occurrences)
Last logged: 09:28:53

Exception in async_update when dispatching 'bosch_sensor_update': () Traceback (most recent call last): File "/config/custom_components/bosch/sensor/base.py", line 120, in async_update self._state = None if self._attr_state_class == "measurement" else self._bosch_object.state ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter return getattr(o, private_attr_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'

**Version**
  - HA version
     Core 2024.1.2
     Supervisor 2023.12.0
     Operating System 11.3 
  - 0.24.1 
  - IVT von RC300
RC300/RC310/Nefit Moduline 3000
Firmware: 04.08.02

**Comment by MajorTomD** [comment]
Same here! Most sensores shows 'false'.

**Comment by pszafer** [comment]
Fixed regression in v0.24.2
