### ISSUE TITLE
 'ENERGY_KILO_WATT_HOUR' is not defined (CT200)

### ISSUE THREAD

**Issue by MG-Sky** [bosch-thermostat/home-assistant-bosch-custom-component#368]
**Describe the bug**

Exception in async_update when dispatching 'bosch_energy_update': () Traceback (most recent call last): File "/config/custom_components/bosch/sensor/energy.py", line 125, in async_update self._unit_of_measurement == ENERGY_KILO_WATT_HOUR ^^^^^^^^^^^^^^^^^^^^^ NameError: name 'ENERGY_KILO_WATT_HOUR' is not defined

**To Reproduce**
When installed new version and restarted the HA in logs (CT200): 
debug:
http://jsonblob.com/1193909031390797824

**Version**
  - HA version? 2024.1.2
  - HA Bosch component version? 0.24.3

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**

**Comment by pszafer** [comment]
thanks for nice report!, fixed it https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.4
