### ISSUE TITLE
No longer getting values from KM200

### ISSUE THREAD

**Issue by basjes1977** [bosch-thermostat/home-assistant-bosch-custom-component#37]
**Describe the bug**
Since today I can no longer use the Bosch custom component. I can no longer see any values from the sensors and/or change settings. I tried removing and reinstalling the Bosch integration. 

I can still ping the device on it's fixed ip address and it is still online according to the Nefit ProControl IOS app which I can use to 
 control and monitor it

**To Reproduce**
1. try a debug scan
2. check the log file

**Expected behavior**
A normal functioning component,
**Screenshots**

**Version**
  - HA version:
arch | x86_64
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.0-10-amd64
python_version | 3.8.3
supervisor | 235
timezone | Europe/Amsterdam
version | 0.114.3
virtualenv | false

  - HA Bosch component version?
  The same as here on GitHub 
  - Python Bosch HTTP client version?
  The same as here on GitHub 

** Debug SCAN **
** IMPORTANT **
Debug scan does not work, I don not get a download
there is however a log entry:
"Home Assistant log tells me :"Detected use of deprecated `base_url` property, use `homeassistant.helpers.network.get_url` method instead. Please report issue to the custom component author for bosch using this method at custom_components/bosch/__init__.py, line 286: url = "{}{}".format(self.hass.config.api.base_url, "/local/bosch_scan.json")""

and right before this log entry: 
"Logger: bosch_thermostat_client.encryption.base_encryption
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py:77
First occurred: 21:21:19 (1 occurrences)
Last logged: 21:21:19

Unable to decrypt: b'\x9e\xa8*\xc7\x85lx\xae\x91{\x0f\x84\xc6\xfa\x01\xab\x04\xb9a\xf49\x94\xbb\xe6\xf8\xee/\xdc\xafx\xa5a\xacLH\xe4\xcc\x97\x03\x9e\xf7:\xdczo\x92?/\xbe\x16\xa4\xc1\xe5$\xfb\xbf\xcd\x8d\xb8\xb4B\xcf\xc8\xaf\x07H\xbf.\xb7\xd7.\xe7\xb0\xe0\xe3\xeb\xfbJAcj\xa1\n\xf6jZ:\xcc\xc9\x89\xd7o>\xbd\xf4\xeb\xefK\xe49\xa6\xd9\xd4\xcanQZ\xd2\x9aO:\xab\xf3\xef\x90\xed\x91\x83\x03)y\x05.\xdf\xd9<w\xa9\x96\xfb\xa3\xd7gt\xc5\xdc;g`\xe2\xf4\xa4\x01\x0bus:\x15\xa4mH5\x84n6A\x07`tr<\xf9$\xafL\x01\x0f\x87\xa7i\xe3\x9e\x03\xb8\x03\x99\x9c\xd4\xd6\x1c.\xc6\x05tP\xef\xbe\xac\xc1\x8a-\xd5\xa9\xe5vb\x9f\xae\xf9\\\xe5\x92\xc9\xe9\xe3\xd6=`\xc8\xfa\xe2\x14H\xc7\x0c\xa7\xa2K\x9a$\xc7\x1dO\xcb' with error: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte"

**Additional context**

**Comment by pszafer** [comment]
can you try to disconnect km200 module for 10 seconds to restart it.

**Comment by basjes1977** [comment]
Hi, is should have written it in my bug report ...
I tried restarting several times. (power off and on aftwer a few seconds) I tried disconnecting the lan cable as well. I restarted it again just now. Sadly without result.

**Comment by pszafer** [comment]
I will remove deprecated base_url tomorrow.
You can try to fetch download link manually - `http://YOURHAURL/local/bosch_scan.json`

**Comment by basjes1977** [comment]
I managed to get the json with your help. Here you go: https://jsonblob.com/fdaab456-e70f-11ea-bdf5-35dcaa18e398.

And thanks for your help so far ;)

**Comment by pszafer** [comment]
bosch updated firmware in your KM200. I have to study it and update lib to work with it...

**Comment by basjes1977** [comment]
Oh wow, I did not know ota firmware updates were possible.
Anything I can do to help?

**Comment by pszafer** [comment]
you are only one who has this version, so test new release, please
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.9.2

**Comment by basjes1977** [comment]
I will let you know. Thanks for quick help

**Comment by basjes1977** [comment]
I will close the issue as it is resolved. Thanks again for the quick solution

**Comment by pszafer** [comment]
great!
