### ISSUE TITLE
Firmware 04.02.02

### ISSUE THREAD

**Issue by Homeuser2631** [bosch-thermostat/home-assistant-bosch-custom-component#370]
New firmware update today, 13 januari 2024

There are problems with config of your thermostat.
You might have unsupported firmware version 04.02.02.

From the version number and release notes, it seems like a small update.

I hope a, small, update can resolve this issue.

**Comment by ronline23** [comment]
Well, same here. CT200 FW update leads to:

024-01-13 10:28:40.576 ERROR (MainThread) [custom_components.bosch] You might have unsupported firmware version 04.02.02

**Comment by kornelmGH** [comment]
Same issue on both the latest core and on 2024.1.3 as well. 

2024-01-13 12:11:47.945 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.24.1.
2024-01-13 12:11:47.946 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2024-01-13 12:11:47.958 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 111111111.
2024-01-13 12:11:49.627 ERROR (MainThread) [custom_components.bosch] You might have unsupported firmware version 04.02.02

**Comment by honikos** [comment]
> 2024-01-13 12:11:47.958 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 111111111
This should be the wrong ID -  11111111111
look into the wiki

**Comment by kornelmGH** [comment]
> > 2024-01-13 12:11:47.958 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 111111111
> > This should be the wrong ID -  11111111111
> > look into the wiki
thanks! it was "masked" by me, that is not the real one :)

**Comment by bas0008** [comment]
Connexion impossible chez moi également pour mon ct200 depuis aujourd'hui

**Comment by Andy20234** [comment]
> New firmware update today, 13 januari 2024
> 
> There are problems with config of your thermostat. You might have unsupported firmware version 04.02.02.
> 
> From the version number and release notes, it seems like a small update.
> 
> I hope a, small, update can resolve this issue.

same problem here

**Comment by Andy20234** [comment]
cant do anything until new update

**Comment by pszafer** [comment]
fixed https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.24.5

**Comment by dtcu8ey6p41w** [comment]
thanks a lot for the fast update!

**Comment by Homeuser2631** [comment]
Pszafer thank you very much for the fast update!

**Comment by andyp2234** [comment]
Problem with home assistant showing wrong temperature
