### ISSUE TITLE
Return temperature sensor always showing as 0.0 degrees

### ISSUE THREAD

**Issue by Ciaccona** [bosch-thermostat/home-assistant-bosch-custom-component#371]
**Describe the bug**
sensor.return_temperature is always showing at 0.0 degrees, even when the boiler has been running for many hours. 
Other sensors, including sensor.actual_supply_temperature, sensor.actual_modulation, and sensor.hc1_supply_temperature_setpoint appear to function correctly. 

Additionally, I can see that the sensor is being called. Logs show:
"DEBUG (MainThread) [custom_components.bosch.sensor.base] Update of sensor SensorsReturn temperature101477814 called."

**To Reproduce**
1. Go to Developer Tools
2. Find sensor.return_temperature
3. View the state of this sensor

**Expected behavior**
I would expect that sensor.return_temperature shows a value above 0.0 degrees when the boiler is running. 

**Screenshots**
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/9163438/f7ec6b85-764d-437f-a640-8e4c85786204)

**Version**
  - HA version: 2024.1.3
  - HA Bosch component version: v0.24.4

** Debug SCAN **
http://jsonblob.com/1196047054991646720

**Comment by pszafer** [comment]
Please provide bosch scan

**Comment by Ciaccona** [comment]
> Please provide bosch scan

http://jsonblob.com/1196047054991646720

Thanks

**Comment by pszafer** [comment]
you can look in scan that you don't have return temperature sensor connected to your installation.

**Comment by Ciaccona** [comment]
> you can look in scan that you don't have return temperature sensor connected to your installation.

Thanks. Can I just check - does this mean it's likely that the actual Bosch thermostat itself hasn't been connected to the boiler correctly, therefore it is unable to read the return temperature?
