### ISSUE TITLE
New firmware

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#372]
Last night my Bosch thermostat received an update. 

---

This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:302
Integration: Bosch thermostat (documentation, issues)
First occurred: 11:12:50 (2 occurrences)
Last logged: 11:14:30

You might have unsupported firmware version 04.02.02

---

Hope this helps to add a new supported firmware version.

**Comment by johndfoss** [comment]
Same here

**Comment by THW30** [comment]
i have the same problem

**Comment by Nordcamper** [comment]
i have the same problem

**Comment by Didel** [comment]
I am receiving the same warning (having a CT200 thermostat), but for version `04.02.01`. So it looks like Bosch firmware >= `04.02.00` is not supported in the current (‘0.24.4`) version of this component.

**Comment by haaino** [comment]
Thank you for the update. This fixes the issue ☺️

**Comment by Didel** [comment]
Thanks for the quick fix, can indeed confirm this is resolved with `0.24.5` 👍🏻
