### ISSUE TITLE
Recent CT200 firmware broke integration

### ISSUE THREAD

**Issue by whiteduck22** [bosch-thermostat/home-assistant-bosch-custom-component#373]
Since Bosch released a new firmware I now get this notification

Bosch info
There are problems with config of your thermostat.
You might have unsupported firmware version 04.02.02.

I think this is probably a generic issue but happy to get more debug if needed.

Thanks a lot for doing what you do!

Best wishes
Ian

**Comment by pszafer** [comment]
update component to the newest version

**Comment by whiteduck22** [comment]
Thank you so much @pszafer !  Tested and working!
