### ISSUE TITLE
Special chars in password not supported

### ISSUE THREAD

**Issue by MisterAG** [bosch-thermostat/home-assistant-bosch-custom-component#378]
**Describe the bug**
I have the latest version of HA and the bosch-thermostat integration. With the following Hardware:
IVT_MBLAN
by iCom_Low_v1
Connected via [MBLAN Controller]
Firmware: 01.10.03

When I tried to install the integration at first it failed since I had a special character in my password (the "&" char). 
I could login to the easycontrol app with the password containing "&" but not for the integration. Changing the password and removing the special chars from the password fixed the issue with bosch-thermostat.

**To Reproduce**
Add special char to password and login will fail in bosch-thermostat

**Expected behavior**
I should be able to login.

**Comment by pszafer** [comment]
It's known issue. Password length shouldn't exceed 9 chars and have special characters in it.
As it's reverse engineering I'm not able to fix it.
