### ISSUE TITLE
Control device with activeSwitchProgram

### ISSUE THREAD

**Issue by JakobTewes** [bosch-thermostat/home-assistant-bosch-custom-component#38]
**Description**
My Buderus heater is not controlled via a room thermostat - in fact my RC35 is mounted to the boiler itself. 
The heating behaviour is controlled via outside temperature and via separate thermostats mounted to radiators.
Sometimes I´m out of town, activate a lower temperature profile and disable water heating. For ease of use
I use customised heating profiles. There are two custom profiles, that I´ve configured accordingly:
When I´m present, I use
`/heatingCircuits/hc1/activeSwitchProgram/Eigen1`
When away, I activate
`/heatingCircuits/hc1/activeSwitchProgram/Eigen2`

**Feature Request**
As I found no convenient solution for chaning the "activeSwitchProgram" via for example CURL, 
I´d love having an "input_select" way of switching the SwitchProgram. There are some different
profiles, that can be picked:

_Eigen1|Eigen2|Familie|Morgen|Abend|Vormittag|Nachmittag|Mittag|Single|Senioren_

Most of them are predefined settings, but _Eigen1_ and _Eigen2_ can be customized.

Manual [Operating Instructions Logamatic EMS](https://www.bosch-climate.us/files/201001222102130.6720640226_RC35_Operating.pdf) describes profiles on page 32 to 34.

Lookup/Description for profiles:

    Familie -> family
    Purpose: Default program

    Eigen1 -> costom1
    Purpose: Custom profile 1

    Eigen2 -> costom1
    Purpose: Custom profile 2

    Morgen -> early morning
    Purpose: Early shift work

    Abend -> evening
    Purpose: Late shift work

    Vormittag -> morning
    Purpose: Part-time work, mornings only

    Nachmittag -> afternoon
    Purpose: Part-time work, afternoons only

    Mittag -> midday
    Purpose: At home at midday

    Single -> single
    Purpose: Single person

    Senioren -> senior citizens
    Purpose: Senior citizens

**Closing words**
Hope, I described it comprehensible :-). 

Thanks and regards,

Jakob

**Comment by pszafer** [comment]
I think it's great idea. I need yours debug scan to check if it's possible to automate.
Currently there is so many devices I cannot depend on manual as each region has different `SwitchProgram`.

**Comment by JakobTewes** [comment]
nice, @pszafer. Did the debug scan, but oops :-):

`2020-11-28 13:53:38 ERROR (MainThread) [bosch_thermostat_client.encryption.base_encryption] Unable to decrypt: b'{"id":"/heatSources/flameCurrent","type":"floatValue","writeable":0,"recordable":1,"value":5.7,"unitOfMeasure":"\xb5A"}\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' with error: 'utf-8' codec can't decode byte 0xb5 in position 112: invalid start byte
2020-11-28 13:53:47 WARNING (MainThread) [homeassistant.components.apple_tv.media_player] A <class 'TypeError'> error occurred: 'noop' object is not iterable
2020-11-28 13:53:49 ERROR (MainThread) [bosch_thermostat_client.encryption.base_encryption] Unable to decrypt: b'{"id":"/system/appliance/flameCurrent","type":"floatValue","writeable":0,"recordable":1,"value":5.6,"unitOfMeasure":"\xb5A"}\x00\x00\x00\x00\x00\x00\x00' with error: 'utf-8' codec can't decode byte 0xb5 in position 117: invalid start byte
2020-11-28 13:53:54 ERROR (MainThread) [bosch_thermostat_client.encryption.base_encryption] Unable to decrypt: b'{\x89\x13\xde\x94\x18\xc6\xb9\xbdb\tco\x17:F\x01\r\xa8\x83\xdbZ\n\xcc\x8d\\\xb6\x1c\x04S\xc1\xfer:?\xfd\xb8\x93\xf9\x8f\xb0a\xb3DK\x8e\x9f\x7fh\xbe\xd1o\x9d\x14\x05U(.F\x8ck\x82\xb2\t2u\x18z\xb1y\x8aXb\x89R\xf5\x85\xda\x8ecuX\xba3\xb0;\xa3\xb7C"\xdd\x0f\xbad\x10\xca_\x17?\x10?\xd9\x9c\xbc%\xc9SM\x06\x10?\xe1\xc3\xdf;i\xd3\x8d\xd4a\x14\xaeugF\x9cXE:\x1fG\x84\x12qj\x15\xad\xf2W\xcb\xae\xffNZ&\x149C\xc2\x18\xeaG\x1cW\xf4#<\x7f\xfc"uD\xab\x83v4\x9e\x1b\xe1\x84\xf7\x03&\x13\x12\x9d\x9f\x0c\xd4\xb7\xa9\xd5O\x99r\xadi\x87F\xa2u\xba\xd2\xbf\x86$\x86\x83u\xf0Y\r\xec\xeb\xe1i\x7f' with error: 'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte`

**Comment by pszafer** [comment]
those errors are normal, some uris are cannot be decoded for some reason...
it should pass anyway and provide you url to download bosch scan.

**Comment by JakobTewes** [comment]
Had to recheck the procedure of downloading Debug Logs. URL is not provided after calling, but file is created :-).

https://pastebin.com/HmCeEUXu

**Comment by JakobTewes** [comment]
@pszafer, did I get that right: They really translate the REST (?) Endpoints? :-)
Do you need more information?

Regards,

Jakob

**Comment by pszafer** [comment]
it's not translating as I think they differ accoring to country but in Poland values are in English...
```
{
            "id": "/dhwCircuits/dhw1/activeSwitchProgram",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 1,
            "value": "Eigen1",
            "allowedValues": [
                "Eigen1",
                "Heizkreis"
            ]
        },
```

allowedValues are different in each region.


anyway, I have different idea.

for climate I'd like to add PRESET as input to select activeSwitchMode
https://developers.home-assistant.io/docs/core/entity/climate/#presets

Water heater doesn't have presets for now so I wouldn't add this option for it.

What do you think? Wouldn't it be better?

**Comment by JakobTewes** [comment]
ah funny...are the possible values „Eigen1“ and „Heizkreis“ the ones, that your polish localized gateway offer? That would suggest, that Bosch always uses the german term for the different modes. 

The values, you’ve posted came from the water heater, while I was referencing „hc1“. Setting „Heizkreis“ will tie the water heater to hc1 schedule, while „Eigen1“ lets one create a custom schedule.

Using PRESET sounds like the perfect candidate for that implementation. As I see, it makes sense, implementing it for hcN and dwhN as both support own switchPrograms. I think, that using custom values (instead of the ones pre-implemented „ECO“, „AWAY“ etc.) makes sense, as switchProgram reperesents a whole schedule. Maybe something like „schedule_family“, „schedule_custom1“ for hc and „schedule_custom1“, „schedule_hc1“ for dwh?

**Comment by pszafer** [comment]
in Polish they made 2 very sophisticated values: [ "1", "2" ] ;)

**Comment by JakobTewes** [comment]
please no close

**Comment by pszafer** [comment]
I remember about this. just don't have enough time lately.
when I fix all xmpp issues in this lib then I will try to add this presets.

**Comment by JT089** [comment]
thx for providing update @pszafer!

**Comment by pszafer** [comment]
Check out pre-release version: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.10.3
I added support for presets.
Let me know if this fullfil your needs.

**Comment by JakobTewes** [comment]
Tried and works like a charm ;-). TVM @moustic999!
Side question...why did you integrate the HVAC Mode switch?

Big thanks and regards 

Jakob

**Comment by pszafer** [comment]
cool,
HVAC mode was first in HA UI and it was designed for operation mode so it was pretty natural choice
