### ISSUE TITLE
Cannot create a Bosch Debug Scan anymore

### ISSUE THREAD

**Issue by rameister** [bosch-thermostat/home-assistant-bosch-custom-component#383]
**Describe the bug**
When I do a Bosch Debug Scan a message is shown: Dieser Dienst erfordert ein Ziel, definiere bitte eine Ziel-Entity_ID, Device_ID oder Area_ID unter Target: oder Data:

**To Reproduce**
1. Go to 'Developer Tools, and fill in the Bosch ID'
2. Click on 'Dienst ausführen'
3. Scroll down to ''
4. See error: Dieser Dienst erfordert ein Ziel, definiere bitte eine Ziel-Entity_ID, Device_ID oder Area_ID unter Target: oder Data:

**Version**
  - HA version? 2024.1.5
  - HA Bosch component version? TC100.2 / Easycontrol Firmware: 04.02.03
  - Python Bosch HTTP client version? 

**** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/**

**Additional context**
See above that is not working anymore. Please have a look to my parameters, the uuid is not really my id because of security:
**service: bosch.debug_scan
data:
. .uuid: "123456789"**

**Comment by rameister** [comment]
Please look to issue written by hardysim, he is not able to make a Debugscan too.

**Comment by haaino** [comment]
When I select the entity through the user interface instead of the uuid, I can make a debug scan.

**Comment by hardysim** [comment]
I'm still unable to run a debug scan (see [my issue](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/380#:~:text=HTTP%20client%20version%3F-,Debug%20SCAN,-I%20cannot%20create)) even when selecting my entity via the chips.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/3737512/0a50b342-98cc-4c34-ac68-dc06264005db)

**Comment by pszafer** [comment]
Do you have `www` folder?
