### ISSUE TITLE
unknown error occurred

### ISSUE THREAD

**Issue by Koralci** [bosch-thermostat/home-assistant-bosch-custom-component#386]
**Describe the bug**
Entering the IP-address of the wi-fi modul on IVT Air X 90 (2023 model), the device access token and the password defined in the Anywhere II app does not working. I always get "unknown error occurred"

**To Reproduce**

**Expected behavior**
Access to the integration

**Screenshots**

**Version**
  - HA version? Latest
  - HA Bosch component version? Latest
  - Python Bosch HTTP client version? Do not know

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `<img width="1062" alt="Snímek obrazovky 2024-02-05 v 17 25 17" src="https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/128385553/e8b0888f-51c9-4bf0-ba31-c753e5f909d1">`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**

**Comment by pszafer** [comment]
Sorry, it's probably too new to work with this component...

**Comment by Koralci** [comment]
Hi,
it probably works with a different protocol, discussion below. Is there any chance in the future that this could be functional?
Thanks, Martin

https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/335

**Comment by pszafer** [comment]
If somebody will find method for decrypt and encrypt I'd be happy to add it to my component.
I won't work on decrypting this stuff, as this is too much work for me and I don't have enough time.
