### ISSUE TITLE
Total working time is wrong interpreted by HA

### ISSUE THREAD

**Issue by Novae7** [bosch-thermostat/home-assistant-bosch-custom-component#389]
**Describe the bug**
The Total working time is a "date" in HA, and not a "duration/minutes" 
The Value is interpreted as date, bit its just a "minutes" value, so HomeAssistant does crazy stuff ;)

**Screenshots**
![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/2822685/419a6d25-18cd-48f3-84be-a08312507b18)

![grafik](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/2822685/ba6a6d03-8858-4207-a515-8f395622eec7)

**Version**
  - 2024.2.1
  - 0.24.6

**Comment by Novae7** [comment]
bosch_scan.json ->
http://jsonblob.com/1207378766170284032

**Comment by pszafer** [comment]
fixed in dev version https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.25.0-dev.6

I will release stable, when I got confirmation that everything is working.
