### ISSUE TITLE
Unknown model

### ISSUE THREAD

**Issue by dsoveen** [bosch-thermostat/home-assistant-bosch-custom-component#390]
**Describe the bug**
No readings from any sensor after enabling them. Integration has "Unknown model" as an entry, but with 19 devices and 110 entities

**To Reproduce**
1. Add integration
2. Add Easycontrol thermostate using ID and password
3. Enable some entities
4. No statistics found
5. StateExtra attribute of all entities have state "Waiting to fetch data"

**Expected behavior**
Sensors have live and historic readings

**Screenshots**

**Version**
  - HA version: 2024.2.1
  - HA Bosch component version: ?
  - Python Bosch HTTP client version: ?

** Debug SCAN **
http://jsonblob.com/1207735498050494464

**Additional context**
![Screenshot 2024-02-15 at 18 03 18](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/46262982/539c20de-157f-4a9e-b95d-10c6c7df0644)
![Screenshot 2024-02-15 at 18 03 05](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/46262982/797f6b2d-79a1-44a8-94e5-74e7ee569e47)
![Screenshot 2024-02-15 at 18 02 45](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/46262982/5a578114-d7b0-44d7-88d9-5f7774bbf4c6)

**Comment by dsoveen** [comment]
I now see that 2024.2 is not supported for this integration, is that the issue I am dealing with?

**Comment by JakobTewes** [comment]
And is there an ETA on when to expect support for 2024.02?

**Comment by pszafer** [comment]
I have surgery this week and I don't know how long my rehabilitation gonna take. During this time I can't work unfortunately, so I guess it will be shipped around end of March if nobody else makes PR to library.

**Comment by JakobTewes** [comment]
Oh…wishing you all the best for the surgery and a fast and good recovery! Things can wait!

**Comment by pszafer** [comment]
Please, test new release and let me know if it is working https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.25.0-dev.3
I wasn't able to test everything, so I really want your feedback

**Comment by dsoveen** [comment]
Thanks for your work. I hope you are well. I am a bit of a noob with git and HA but I will give it a try

**Comment by dsoveen** [comment]
I found the Beta button in HACS...... I have now downloaded this version and restarted HA. Unfortunately I am getting the same results. 
Log reports an error:


```
2024-03-12 17:14:41.097 ERROR (MainThread) [homeassistant.components.switch] Error while setting up bosch platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/bosch/switch.py", line 34, in async_setup_entry
BoschSwitch(
File "/config/custom_components/bosch/switch.py", line 102, in __init__
self._attr_unique_id = self._domain_name + self._name + self._uuid
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```
Thanks again for your help

**Comment by mpdenver** [comment]
I'm getting an "Unknown model" result for

- Logamatic Ems plus
- Logamatic MC110, 
- RC310 Buderus

I tried all sorts of combinations in the for adding the integration but no devices can be found. The system is connected to the internet with IP though and accessible via "MyBuderus" App.
I'm aware that the documentation only mentions compatibility with RC300, but was hopeful it would work nonetheless. Any thoughts?
Happy Sunday :)

**Comment by dsoveen** [comment]
I have deleted and reinstalled the integration and that solved the issues for me. I then updated the integration using hacs to 0.25.0 (from 0.25.0-dev3). Sensors still work! The issue can be closed as far as I am concerned. Thanks again.
