### ISSUE TITLE
Integration not loading on startup: Can't find your fw version.

### ISSUE THREAD

**Issue by JakobTewes** [bosch-thermostat/home-assistant-bosch-custom-component#392]
**Describe the bug**
The integration no longer loads for me on startup, as the firmware version is not recognised. I got a KM200 Gateway.

**Version**
  - HA version is 2024.2.2
  - HA Bosch component version is current
  - Python Bosch HTTP client version is bundled

** Log info **
`2024-02-18 18:56:37.630 ERROR (MainThread) [bosch_thermostat_client.db] Can't find your fw version.`
`2024-02-18 18:56:37.631 ERROR (MainThread) [custom_components.bosch] You might have unsupported firmware version None`

**Comment by JakobTewes** [comment]
reloading the integration leads to working component ;-)

**Comment by tempo3** [comment]
same here

**Comment by mpdenver** [comment]
Same here

**Comment by JakobTewes** [comment]
Fixed with 2024.2.3 ;-)
