### ISSUE TITLE
Device is unknown Null

### ISSUE THREAD

**Issue by schlaufon** [bosch-thermostat/home-assistant-bosch-custom-component#393]
Hi,
I am getting this message, no parametres are shown:

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/126504679/5bdb819d-1f4b-48ee-80a2-06f808345726)

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/126504679/ea3fd80e-0cd0-4502-9b97-45bddd15be58)

What to do?

My system:

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/126504679/837e2e4e-c590-4fb6-a3a7-fe4ec28e5745)

Until recently (ay 2 weeks ago, everything (almost ;-) was working.

[
![bild](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/126504679/e2aef314-4d1c-499a-aa33-f33c7e98a01b)
](url)

**Comment by pszafer** [comment]
It seems like your thermostat is not available in Bosch cloud

**Comment by laolaxyz** [comment]
t will only work with at least Home Assistant 2023.7 and maximum 2024.1 and Python >=3.11. It won't work with Home Assistant 2024.2 installed on HAOS which delivers Python 3.12.
