### ISSUE TITLE
Statistics for the 23rd hour are always missing

### ISSUE THREAD

**Issue by zaupav** [bosch-thermostat/home-assistant-bosch-custom-component#394]
**Describe the bug**
I use Stats ractualCHPower and Stats ractualDHWPower for the Energy dashboard. For the whole day the values are displayed correctly, but for the last hour of the day (23rd) the values are always missing.

**To Reproduce**
1. Go to 'Energy dashboard'
2. Click on ''
3. Scroll down to 'GAS consumption'
4. See error 'there is no value for 23rd hour'

**Expected behavior**
I expect values for all hours of the day.

**Screenshots**
Screenshots for 26.2.2024, 25.2.2024, 24.5.2024.

**Version**
  - HA version? 2024.1.6
  - HA Bosch component version? 0.24.6
  - Python Bosch HTTP client version? 0.24.6

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
![Screenshot 2024-02-27 161036](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/103241577/7e18a579-72fd-4ef6-afba-bc181958fecc)
![Screenshot 2024-02-27 161056](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/103241577/cfda2e17-124d-4f16-b8d3-8f4dedfa4cd2)
![Screenshot 2024-02-27 161110](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/103241577/3e032994-7a34-4268-aa07-ae9d6d0b9ed6)
[bosch_scan.json](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/14421860/bosch_scan.json)

**Comment by pszafer** [comment]
Show screenshot from `2024-2-26`

**Comment by zaupav** [comment]
![Screenshot 2024-03-08 182834](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/103241577/f048b868-3224-463e-a8af-b3c767e9a75b)

**Comment by zaupav** [comment]
This is the explanation
2024-03-08 00:06:00.001 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /recordings/heatSources/actualCHPower?interval=2024-03-08
Correctly should be called
2024-03-08 00:06:00.001 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /recordings/heatSources/actualCHPower?interval=2024-03-07
To retrieve the values for the last hour of the previous day

**Comment by pszafer** [comment]
can you find logs with line such as:
```
Last row of statistic %s found %s, missing %s with current sum 
```

**Comment by zaupav** [comment]
There is nothing like that in the log.

**Comment by zaupav** [comment]
You can see the log file from 2024-03-07 08:21:14.500 to 2024-03-08 08:47:00.820.
[home-assistant_bosch_2024-03-08T07-47-19.209Z.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/14542296/home-assistant_bosch_2024-03-08T07-47-19.209Z.zip)

**Comment by pszafer** [comment]
should be fixed in dev version https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.25.0-dev.6

I will release stable, when I got confirmation that everything is working.
I'm struggling with these past data for a long time now, let me know if dev version is ok.

**Comment by zaupav** [comment]
I can confirm that everything is working. Thank you for your support.
![Screenshot 2024-04-01 155305](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/103241577/185be187-9a95-4bcf-a947-44742c8c37f1)
