### ISSUE TITLE
Using slower stringprep, consider compiling the faster cython/libidn one

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#399]
Hi,

Just installed .25 on my ha 2024.3.3. 
Thank you for all the great work! Highly appreciated!

I got the following msg

------

This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/bosch/__init__.py:12
integration: Bosch thermostat (documentation, issues)
First occurred: 19:18:43 (1 occurrences)
Last logged: 19:18:43

Using slower stringprep, consider compiling the faster cython/libidn one.

----

Is this relevant?

**Comment by pszafer** [comment]
I can't do anything about it. You can ask HAOS devs to provide better cython/libidn, but it's nothing to worry about
