### ISSUE TITLE
Bosch CT200 new Firmware v5.00.01 is incompatible

### ISSUE THREAD

**Issue by nevada750club** [bosch-thermostat/home-assistant-bosch-custom-component#402]
**Describe the bug**
- This is the HA message: "There are problems with config of your thermostat. You might have unsupported firmware version 05.00.01."

**To Reproduce**
- Auto update the thermostat

**Expected behavior**
- Interface the HA with my thermostat with new Firmware

**Version**
Core: 2024.4.3
Supervisor: 2024.04.0
Operating System: 12.2
Frontend: 20240404.2

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
- Sorry but the `bosch.debug_scan` service not found because all entities are unavailable

**Additional context**
- until this morning everything was working fine, then the Thermostat updated itself and now HA no longer detects the components

**Comment by rameister** [comment]
Hello, for my Thermostat TC100.2 I have the same behavior and the bosch.debug_scan service not found anymore in the Service entries. All this is happened while updating the new Bosch Firmware Update to v5.00.01.

**Comment by gralin** [comment]
@pszafer already knows about this issue and it's just a matter of time until we get a fix. I have provided him the diff between scan with old firmware and scan with new firmware, but for archive purposes I include it here too: 
[changes.patch](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/15012756/changes.patch)

**Comment by nevada750club** [comment]
I confirm that everything works well, thank you.

**Comment by cream68** [comment]
After updating today I tried it again today:


Quelle: custom_components/bosch/config_flow.py:172
Wrong IP or credentials at 192.168.0.77 - Unable to decrypt: 'utf-8' codec can't decode byte 0x91 in position 0: invalid start byte
