### ISSUE TITLE
Detected that custom integration 'bosch' accesses hass.helpers.dispatcher

### ISSUE THREAD

**Issue by haaino** [bosch-thermostat/home-assistant-bosch-custom-component#409]
Hi,

I just installed HA 2024.5. In the log messages I saw these 2 remarks:

------

- Detected that custom integration 'bosch' accesses hass.helpers.dispatcher. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from dispatcher directly at custom_components/bosch/__init__.py, line 247: self.hass.helpers.dispatcher.async_dispatcher_connect(, please create a bug report at https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues

- Detected that custom integration 'bosch' calls async_create_task from a thread at custom_components/bosch/__init__.py, line 293: self.hass.async_create_task(self.recording_sensors_update()), please report it to the author of the 'bosch' custom integration

-----

Hopefully this means something to someone.

Best regards,
Haaino

**Comment by Joker1300** [comment]
Hi, 
I have the same LOG since update to HA 2024.5.
The gas consumption in the energy dashboard has not been recorded since then.

Best regards,
Joachim

**Comment by frankschultehoeppe** [comment]
Kann die Probleme mit dem Gasverbrauch im Energie-Dashboard bestätigen.
Beste Grüße 
Frank

**Comment by Kaufi206** [comment]
Same here. No gas consumption after the HA 2024.5 Update. Then i deleted the integration and after that i wanted to reinstall it, but i got the error message: wrong IP address or password. I checked both but they didn't changed.

**Comment by tvc-dps** [comment]
have the same error records and energy consumption not displayed - unknown, no option of m3, but just display J and Wh options

**Comment by tvc-dps** [comment]
There couple of functions should be rewritten to support 2024.5.2 version specifically
async_write_ha_state -> schedule_update_ha_state , reference https://github.com/tefinger/hass-brematic/pull/15

and not sure, but to support python 3.12
async_create_task  -> asyncio.run_coroutine_threadsafe, async method for python 3.12
