### ISSUE TITLE
Exception in get_signals when dispatching 'bosch_signal': 

### ISSUE THREAD

**Issue by bakboord4** [bosch-thermostat/home-assistant-bosch-custom-component#410]
**Describe the bug**
For me total unclear what the cause is of this error. And unclear what the effects (if any) are. This report is fulfilling a request: please report to the author...

Logger: homeassistant.util.logging
Bron: util/logging.py:98
Eerst voorgekomen: 04:15:32 (1 gebeurtenissen)
Laatst gelogd: 04:15:32

Exception in get_signals when dispatching 'bosch_signal': () Traceback (most recent call last): File "/config/custom_components/bosch/__init__.py", line 293, in get_signals self.hass.async_create_task(self.recording_sensors_update()) File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task self.verify_event_loop_thread("async_create_task") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'bosch' calls async_create_task from a thread at custom_components/bosch/__init__.py, line 293: self.hass.async_create_task(self.recording_sensors_update()). Please report it to the author of the 'bosch' custom integration.

**Expected behavior**
No error message.

**Version**
  - HA version: 2024.5.0
  - HA Bosch component version: v0.25.1
  - Python Bosch HTTP client version .....

**Comment by tvc-dps** [comment]
it is duplicate of https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/409

**Comment by bakboord4** [comment]
Thanks for the solution.
