### ISSUE TITLE
Non-thread-safe operations

### ISSUE THREAD

**Issue by RobertAmour** [bosch-thermostat/home-assistant-bosch-custom-component#412]
**Describe the bug**
The Bosch integration is performing non-thread-safe operations.  In my case this caused the upgrade to Core 2024.05.00 to stall for many hours before completing

**To Reproduce**
Reported here https://github.com/home-assistant/core/issues/116565#issuecomment-2093977654

**Version**
Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0
HACS 1.34.0
Bosch Thermostat Integration v0.25.1

** Debug SCAN **
http://jsonblob.com/1236195526252027904

**Additional context**

**Comment by pszafer** [comment]
Fixed in v0.26.0
