### ISSUE TITLE
Energy stats recorder not working after update 2024.5.2

### ISSUE THREAD

**Issue by Dejmal69** [bosch-thermostat/home-assistant-bosch-custom-component#417]
**Describe the bug**
Stats are empty since the update.
recording:rconsumedenergyexternal
recording:reheaterexternal
recording:rcompressorexternal
recording:routputproducedexternal

**To Reproduce**

**Expected behavior**

**Screenshots**
![Snímek obrazovky_2024-05-21_10-20-38](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/115118155/9f93b60f-a484-419e-9963-bf9c644787a5)

**Version**
  - HA version 2024.5.2
  - HA Bosch component version latest
  - Python Bosch HTTP client version?

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**

**Comment by pszafer** [comment]
Stats are not working in 2024.5. You'd have to wait till June as I don't have time right now :(

**Comment by Dejmal69** [comment]
Ok Thanks for Your great work. I will wait.

**Comment by CaseyRo** [comment]
I'm patient @pszafer ! thank you so much for taking care of this :-)

**Comment by Atraxmaster** [comment]
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/126868541/073db3bf-0f69-44cc-8daf-d38312c4c4a4)
Change __init__.py 2 place and restat HA. Work for me

**Comment by pszafer** [comment]
Hi, @alaraun made a fix for us!
Let's test it with https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.25.2

I'll reopen if it won't work.
