### ISSUE TITLE
dhw1 has 0 temperature after update to v 0.9.9

### ISSUE THREAD

**Issue by Trefex** [bosch-thermostat/home-assistant-bosch-custom-component#42]
HA version 0.116.4

![image](https://user-images.githubusercontent.com/2877665/101990584-f4d90380-3ca7-11eb-9f93-8344d8a299c8.png)

**Comment by Trefex** [comment]
[bosch_scan (1).zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5683493/bosch_scan.1.zip)

**Comment by Trefex** [comment]
Before upgrading I once tried "extra hot water" but I cancelled that. I hope it is not related.

**Comment by pszafer** [comment]
shoule be fixed by 0.9.10. Let me know. Closing for now.
