### ISSUE TITLE
NAT problem ?? What port is needed ? 

### ISSUE THREAD

**Issue by IkaSGC** [bosch-thermostat/home-assistant-bosch-custom-component#421]
**Describe the bug**

I don't know if it's a bug, but I can't get the device to connect. If I enable http or port 80 or 8080, it doesn't work. It is an IVT heat pump. The problem is surely only in the NAT settings, if I connect the IVT directly, it will connect. But unfortunately I need to have the IVT connected behind the router, as the IP module is a piece of junk and can't work with my network elements (Unifi) for more than 24h.

**To Reproduce**
Set it behind router and enable NAT rules, but http not working

**Version**
Everything is latest... Problem is not in version

Device cant inicialize in HA.
![ScreenHunter_14 Jun  10 17 41](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/7561343/45977af6-c059-417f-b6ae-765049b3afa2)

**Comment by pszafer** [comment]
Do you connect locally or through XMPP?

**Comment by IkaSGC** [comment]
I try it localy over HTTP....

**Comment by rickk88** [comment]
Might want to make sure your IVT picks up the new IP and has port 80 enabled, try to set up a laptop/computer behind the same router and see if you can connect to port 80 on the device to ensure your NAT rule is pointing at the correct IP and your IVT is aware of a new subnet. Port 80 should be enough for HTTP connectivity. I had the issue my device needed to be power cycled before it updated the IP and allowed port 80 again.

**Comment by IkaSGC** [comment]
I'll try again. I already tried port 80, but it didn't work. The module has an IP address, it's given by mDHCP. The IVT IP module itself has no configuration options.
