### ISSUE TITLE
Support for Bosch Tronic water heater series

### ISSUE THREAD

**Issue by tomekszy** [bosch-thermostat/home-assistant-bosch-custom-component#434]
**Is your feature request related to a problem? Please describe.**
Integration does not find Bosch Tronic water heater, which is visible in HomeCon app

**Describe the solution you'd like**
It will be good to add support for those water heaters

**Describe alternatives you've considered**
I tried to found other custom components for this, but failed, as there are not many

**Additional context**
I can expose my own water heater to external network if it will help to develop this integration

**Comment by pszafer** [comment]
probably different protocol than older devices
