### ISSUE TITLE
Please add support for the Bosch MR100i RF

### ISSUE THREAD

**Issue by ldfandian** [bosch-thermostat/home-assistant-bosch-custom-component#435]
**Is your feature request related to a problem? Please describe.**
Please add support for the Bosch MR100i RF at https://www.bosch-homecomfort.cn/product/mr100.html

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pszafer** [comment]
Sorry, it's probably home connect, different protocol. Without technical data I'm unable to even process this request
