### ISSUE TITLE
Firmware 05.02.00 on CT200

### ISSUE THREAD

**Issue by bcoddens** [bosch-thermostat/home-assistant-bosch-custom-component#437]
Thermostat got a update to version 05.00.01 and the integration does not work anymore.
You can find the debug scan here:

http://jsonblob.com/1283143134916501504

Thanks for all the work on this integration!

**Comment by pszafer** [comment]
fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.26.2
