### ISSUE TITLE
Cant start component: Unable to decrypt

### ISSUE THREAD

**Issue by bartoszx** [bosch-thermostat/home-assistant-bosch-custom-component#44]
Hello

I've been trying to start component  since 2 months. I thought that I have problem with HA version and waited for updates. Then I've tried to fresh install and still same problem.
Today I tried https://github.com/stefanlaheij/ha-buderus/ to ensure that I face same problem but it works.
This is step by step what I did:

Buderus with km200v2
HA version Version 2020.12.6.

- I cloned files to custom_component
- configuration->integrations->add integration->bosch
- choose device ->  ivtt->http
- provide with IP, access token (works with  ha-buderus) and password (which I use in buderus mobile app to login)
- after submit I got "Unknown error occurred"

And my logs shows:

`
Logger: bosch_thermostat_client.encryption.base_encryption
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py:77
First occurred: 8:40:05 AM (14 occurrences)
Last logged: 8:40:17 AM

    Unable to decrypt: b'\x94J\x8e\xcfy\x08\x07\xfd\x15\x1e5\xfc\xf6|\xe8\x93\x8d<\x02\xe9&\x9b*;\xa0\xd0H\x18\xb5\x1c\x91\xdc\xdc\x87E\xc1\x99\x9e\xcd\x97F\xc1\xfd\xff\xd2\xfa\x99\x05t\xd5)y\xdd\xd6\xcf\xd5\x89(\xbcNa\xaeR\x92g\xf5N.\x93\xb0\x07J\xfb\x0b!\xfde\xf0\xe2\xb4\x14\x99\x976\xa7&wll\x08\xe2\xb5\xfds\x01\xb7\x08\xa9\x85\x14\x06.\x91=\x1b+\t\x9b\x8e6\xa4\xce' with error: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte
    Unable to decrypt: b"\x86\x06\\\x9e\x81\xc7t\xcfwD4\\+\xdc\x99C\xbdw\xa5I<w.!\x00\x07\xbd\x9c`\xb7\x86\x81\x9aC\x807\x9a\x1a\xb7)\x84%\xf1P:\xf6\xbf\xa6\x15\x00\xd3Yw\xf4\x8d\x8aN\xe5\xbf\xe5S}LViN\xd2j)\xe59\xa4D\xc1\xff\xf8=[\xe3\xb9\xfdX\xc3\xe5\xd7I\xb1\x8a\xd4(\xc1\x87\x1f\x88\xbb\xee\x93\xd3&t\x87l\x1b\x1c\xa0B\x16!\x0e\xab\xb0p5\xad\xa9\xcb\xd1\xcd\xdeI\xa3\xdd$\n\xc6\xb5\xaa\x83#\xdd$wT\x8a'\xec\x82a\xcaw\xe4\x07\x9aZ\xffm\xdd\x95\xcc]\xe7I\xb4<\xdf\xbd\x90\xc2\x8bO\x17\xc1\x9a{\xa3E\x06\xe77\x9cW<0\xc6\x82<\xdfi\xcb\xad%\xf2e\xe4D\x14:65\xc0\x90*;s'\xe0U\xbe3\xa6\x02*,E\x01\x04\xb7\xe6\x126\xa6\x03\xb5n\x01b\x8c\x02xX\xa2\xd3\xd4`\n4r\x08k\x8f\\\x9b\xdd\xf6G{N&\xb31\x9f\xd8\x8d\x9a\xafJ;]n\xd9\x97\xe2\xff\x95$.\x9fiyD\xe5\xc4\x1e\xc1\x12\x02fu\xcf\xef\xa0\xa6" with error: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
    Unable to decrypt: b'\x94W^$Ah\xca\x03\x86s,N\x0f/@\x95D\x1e\x9f\xbd\x81n\x10\xd9\x8f\xb8\xf1)eAM[\xa4<\xec9W\xc8sr\xef*z\xae4[\x1a\xdd\xd6K\x184=\x17`Q\xa8\xd3\x17\tm.v\xb0\x83\xfaM\x1a"uAj\x83`\x82\xfb\xe3\xe8\x85_\xe4GeT\x7f\\\xd9\xc7LJ\x96iG\x83\x01\x81\xab\x9e99W$\xab\xa8\x1c>\x8e\xaeO\x00R\x92\x05\xba\xe6^\xb2\xd4\xe5\x08\x06\x18?\xb1Z\xf8pyS\n\x90mN6\x9e\xa8\xec\xf0f\xdct\x82\xab\x07\xe8]x\x976\x07\xee\xbcmFR2\xa7,;m7\xc6\xab\x9b\xb7K\x88\xe3\x90\x0e\xc6\x1a\x1f\x98\xdb^\xc0W]\xd6z\xa0\xd2\x17\xfd\x0b?\xc2z&\x98\xc6\xaeu\xcf\xcb\x99E\x10n\x7f\x8bMt\x8a\xac\x16\xb1\rp\xaa\xfe\xe4\xfd\xff\xb7:\xba\x88\xea\x9c\x95\xaa\x93\xcf\xbf\xa8\x03\xd4\x1a\xe5\n-A\x7f\xf9\xdb\xda-\xa1\x1bxspz\xfb\xe5ST\xa4\x7fgv\xb9\xc3L\x9c\xd6\xaa\xfff\xbb\xbe\xfa\xe1{z\xd9\x1c~\xef&\x90\xe1@\x97.\xa4YI\xa0n\xc6f\xfc4$\xf07\xae\x8d\xff\xf4\xfa;8u\x8cv\x8e\xd2\x8e{\x16\xe3\xc21\xde\x84\xb7\xa0\xb1^\x1bQ4\xc2ko>>\x1e\xc9{\xca\xc6I\xa9\x87\xac\xee\xfe\xb6\xb7\xbd9J\x8b"gM\xea\x95#E\xca\xa6*\xc4W\x9d\xf4,$\xd2\x9c\xb9c\x17\x06\x8c5\x06t\xab\t\x83}t\xac\x1f\xe2\xa9\x84\xff\xbc\x8f\xf880\x8e\x1e\xd2\xf5d\x8f\xba\x15}\xc9\xd2\x07\xcc\x9f\x8d\x08H\x8d\xad\x03\rOJ\xa2\x1f8 \x80$\xcdz\xb0\xbc\xe5YO\xf3W7\xd08\x1c{\x89\xde\x0b\x818y\x18\xcbJ\xf2\xd8\xcfW\xfa,[\x07\x88_\xf8\x9a\xc6\xd1~6$\xfcD\xc3\xdc\\\x86"h\xa4\x8bIf\x8a\x8e"\xf9\xfa\x84jr"\xb9bM\x82\x8d\xd6H\xb8\x8f\xf7\xbeo\xb4\xa8qM\xbb\xbd\x82\x0f\xdf\xab0\x91\xdcv\xe5\x1a\xcdZH[D\xb1\x1c\xb0\xf1V&\xcd\x82\x9b\xc7\xca\xe1\xa0#\xf3\xefB\xef\x03f\xfe\xda\xd3R\x8c\xdd\xaeA\xc7#\x00\x02B\xce\xa2\xfb\r[7\xbf\xcd\x0e\xfd+\xb7\xabm\x93\xe0M:R\x9f\x88\x14(k\xce\xa2\x0c\xf2\xe4\xe4f\x94T\x98\xf3\xef\xd4\xa1\x1a>K~\xd5\xc5u\xc8>\xe7\xe0p\x0c\xe3\x18"\x91\xc0\x0c*$o\x94\x06_\xfa?uW\x11\xb9O\x04%\x8f}\xcf[\x83\xb5h\xe8\xea\x001H2\xc3\xb3l1\x9d=7\xb80$\xc3\xe6lL8\xeb \x1f3\x18\xdd*^\xf4aO\x85aY&\xf9\xfdKA\xb8\xa7\x9dIc\x9a\xb9B5\\\x94\x15^R\xb5vSh\xf0\x12\x8eY=\xd6(\xb2\x1f\xd2\xe6\x06\x94x\x89\xe5\x03hIt\xd1\xebEZ\\\x00~\xd7\xed"\xf5' with error: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte
    Unable to decrypt: b'\xcc\xe7Ze^\xe4 \xa2/\xb7\x170\x02qM\xe9\x83\\\x1f\xde\xd9uZ\xa5nS8\xa0\x9f\xa4\x91m\xdch\x8a\x83M8\x97\x01\\`\x1f\x8dJ\x03AB\x8f\x90\xc4\xc7\xe3`\xe0\x03\x94\xe7\x88\xec\xe9\x08\'fh\x8c\x7f\x0e\xc2\xf9\xc2\xc0\xc2\xb3\x94\xccW$"jA"&"\xd1\x8e\x8e\xa7-b^\x02\t\x9a\xf0B\xb0#@r\x89\xc8S\xf8\x15-\xa2k\xc5X(\x1b\xe7\x8d\xbdk\xec\xea<\xd9\xfc\xe6"9\x1c\x86\xe4\x0e,\xefEGY\x10\xb8\x1c\x94c\x92\xed\xcexO3' with error: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
    Unable to decrypt: b'\x94J\x8e\xcfy\x08\x07\xfd\x15\x1e5\xfc\xf6|\xe8\x93\xa5\xf5\xea\xdc4\x0bb\xcd\xd9i\xc2\xf9>\x84\xb5\xc2p~\x05\x8f\x950_\x90\xa7k\xc6\xb7J\x1b\xcc\xdc\xae\x8f\x82\x03g\x9d\x9c\xd3IFa\xdf\xfc\x86c\xeb5\x03\x0cLl\xd8\xa5Rf\xff\xdcc\x85\x84\xee\x83L\x96F6\xf3\xbf\x16X\\\x1f\xe8\xcbB\xc3\xbc\xfeZ\xe4\x18\xcd=.+W\xb3\x94\x86\xca\x1bC\x10\xb5' with error: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte

`

**Comment by pszafer** [comment]
in ha-buderus you put generated password.
in this integration access token is device password/what's on the sticker of your device.

**Comment by bartoszx** [comment]
Pawel

Thanks a lot. Works great.
