### ISSUE TITLE
How to see (or change) password for existing integration?

### ISSUE THREAD

**Issue by markusschloesser** [bosch-thermostat/home-assistant-bosch-custom-component#443]
Hi (sorry, cannot access Discord),
I've been using your integration successfully for a couple of years, so thank you for that! :-)
How do I access the current password for my km200 (IVT)? Or change it? 
Thanks!

**Comment by honikos** [comment]
by using the app (easy controll, Bosch device, Buderus ... ??)

**Comment by markusschloesser** [comment]
No, I mean the saved credentials in HA

**Comment by honikos** [comment]
Deactivate HA custom component for Bosch thermostats, erase, restart HA, reinstall.

**Comment by honikos** [comment]
You can not change the original km200 credentials. See wiki [configuration-of-an-ivt-device](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Installation-Guide#configuration-of-an-ivt-device).
Do not know where in database the password is stored. Anyway it should be stored encrypted, so you can not use it directly.
Best way is to change the password by app installation or change password with app, as I mentioned before.
