### ISSUE TITLE
Decryption problem for Compress 7000 with new firmware 04.07.05 

### ISSUE THREAD

**Issue by Heli4ce** [bosch-thermostat/home-assistant-bosch-custom-component#45]
**Describe the bug**
Component can't communicate with heatpump
I have tried to reinstall component and HA, without success.
I was not able to run debugscan but did the best I could, see below...
I suspect the new firmware in the heatpump is the problem.
What steps are neccesary to support this?

```(venv) ajn@ubuntu:~/Projects/bosch-thermostat-client-python$ bosch_scan --host x.x.x.x --token xxxx --password xxxx --protocol HTTP --device IVT
ERROR:bosch_thermostat_client.gateway.base_gateway:You might have unsuporrted firmware version 04.07.05
INFO:bosch_thermostat_client.bosch_rawscan_cli:Successfully connected to gateway. Found UUID: xxxxxx
ERROR:bosch_thermostat_client.encryption.base_encryption:Unable to decrypt: b"\xf8\xa9\xfc\x99\\\th\xdb\xa1\xb5\x81A\xdep\x9e\xac\xd8\x90\\6*AQ\xe6_\t]oR\xaa\x1f+Yp\xe1\xb0\xa3`\xec\xa8\x0ca\x06zXN\xff\xbbn$\xd9\xf8S\x8e-\x89\x8bo\xa3\xd5'\x10\x83\xedn\xf9s\xcd\xff\xf9\xc0\xdd\xe5 84\xec\xe8\xd5\xa5\x86)W2\x04\x9f\x94f\x90\xbf\xc0\x8a\xb2[\xa5\xc4\xbf8\xa6\xc2\x84\xba\x15\xa6\xc3!\xb8\xb5\x10\xe1#\xc7W,\x82\x0e{\x80[S\xc7Zcgo\xdcB\xd0\xd9\xea\xba#\xf72\x9d\x03\xda\xe4\x95\xbe\xf3#\xe7\xec\x88\xcd\xa9p\xc5\xc4\xf6\xa5\xdb\xe7:\xf2\xc3^\x94I\xfb\x90\xf9\xd5\x03\xfc\x15\xe3\x15\xdev\xc4\xeeP\x14\xae\x00\xae\xf4\xba,%\x99\x16v%F\xb9\x8c\x88\xd4q\xe6n#L\x14]X\xaa\xd7\x9en`\xab!{)w\xd9\xafo\x8a\xa7\xb3\xe0\xe4\x85\xe2Bx\xa0\xc3\xa1" with error: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
INFO:bosch_thermostat_client.bosch_rawscan_cli:Successfully saved result to file: rawscan.json
(venv) ajn@ubuntu:~/Projects/bosch-thermostat-client-python$ 
```

What can I do to help?

[rawscan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5694214/rawscan.zip)

**Comment by pszafer** [comment]
rawscan is enough. I will add it.
I had only scan of 04.07.05 for RC300 till now, now I can add Compress as well.

**Comment by Heli4ce** [comment]
Many thanks, brilliant work

**Comment by pszafer** [comment]
new version released. test it and let me know

**Comment by Heli4ce** [comment]
Great!
Now it works like before the firmware update.

I have this:
Can't update data. Error: URI /heatSources/sensors/collectorInTemp doesn not exist: 403, message='Forbidden', url=URL('http://x.x.x.x/heatSources/sensors/collectorInTemp')

and this:
Can't update data. Error: URI /heatSources/energyMonitoring/startDateTime doesn not exist: 500, message='Internal Server Error', url=URL('http://x.x.x.x/heatSources/energyMonitoring/startDateTime')

and this:
Can't update data. Error: URI /heatSources/systemPressure doesn not exist: 404, message='Not Found', url=URL('http://192.168.70.25/heatSources/systemPressure')

I think it was like that before, but is it excpected behaviour?

**Comment by pszafer** [comment]
it's probably just your installation which lacks those sensors or there is something bad with Compress  device schema. what do you think @slovdahl ?

**Comment by slovdahl** [comment]
Hmm, good question. It looks my Compress 7001i is still running 04.07.03. I'll get back to this whenever my pump updates itself 🙂
