### ISSUE TITLE
Entities sometimes completely stop updating (issue wip)

### ISSUE THREAD

**Issue by warior456** [bosch-thermostat/home-assistant-bosch-custom-component#451]
**Describe the bug**
Sometimes seemingly at random all entities stop updating

**To Reproduce**
1. Wait until entities stop updating
2. Entities stop updating
3. Can be fixed by reloading the integration but i have no idea what the cause is

**Expected behavior**
Entities keep updating and don't randomly stop without recovering 

**Screenshots**
![Screenshot_20241102_104208_Home Assistant.jpg](https://github.com/user-attachments/assets/b246084b-4af6-4f99-8628-ed08a63f1457)
After reloading entities start updating again

**Version**
  - HA version: 2024.10.4
  - HA Bosch component version: 0.26.3
  - Python Bosch HTTP client version: wip

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
Bosch model: wip

**Comment by josemiguel-alvarez** [comment]
This has been happening to me. I have a CT 200.
