### ISSUE TITLE
Connect to IVT Geo 516 with Bosch IPI-100 module

### ISSUE THREAD

**Issue by minovap** [bosch-thermostat/home-assistant-bosch-custom-component#46]
I am able to connect with the Bosch EasyRemote app which probably means that my heater is compatible with this component, but I can’t seem to get the credentials right.

I have tried the command line interface to the python library in the dependencies, but I can not connect that way either.

Please see the attached image to see what the credentials label on my heater looks like.

Is my heater compatible? If so, which credentials am I supposed to use?

thanks!
![C7BC1360-13CE-4977-9B7F-40A8FF933FF3](https://user-images.githubusercontent.com/49623957/102686384-bbdce980-41e7-11eb-8149-15cadc9abaf8.jpeg)

**Comment by pszafer** [comment]
hi,
so I think it's not supported, but if you can connect with it, then I can add support for it.
just need bosch scan of it.

you can try doing it with Home Assistant, maybe it will work, to do so:
- add integration bosch
  - choose device type: IVT
  - protocol - HTTP
    - IP address: ip address
    - accesstoken -> this is `passwort` from sticker
    - password -> this is password you set up when connecting with app
If it will go through then in Developer Tools -> Services choose `bosch.debug_scan`

if it won't go through then follow this instructions: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Run-Bosch-Scan-from-Command-Line

**Comment by minovap** [comment]
Thank you for the prompt reply!

I managed to sign in with the help of your credentials clarification 👍 

Please see the screenshot from the setup process. I guess it is fully compatible?

<img width="584" alt="Screenshot 2020-12-19 at 11 51 57" src="https://user-images.githubusercontent.com/49623957/102687683-129af100-41f1-11eb-96f8-a14f368d435e.png">

**Comment by pszafer** [comment]
yes, seems it's Compress, so yes. it should be fully supported, but you can always check it out and report some problems or what is missing.

**Comment by minovap** [comment]
Ok. I will try out the sensors and report any issues. Thank you very much!

**Comment by pszafer** [comment]
just little note. it's pretty slow as I cut out number of queries to gateway. it takes about 1,5 minutes to apply any changes eg. you change temperature in water heater.
- temperature is send to gateway
- it's cached in Home Assistant,
- after about minute component is checking if gateway successfully applied this temperature.

most of the time it's not a problem but have this in mind.

**Comment by minovap** [comment]
Slow update speeds on this kind of systems should not be an issue. I don't need faster updates, but I am a little curious - is this data polling implemented on the actual IP-module on the local network? Sound like the kind of limits you would expect from online apis, not on a machine running locally.

I have a wireless temperature sensor that came with the heater and helps the heater adjust to the temperature in the house. It is available on the /heatingCircuits/hc1/roomtemperature endpoint. Would it be possible to add support for it?

    {
      "id": "/heatingCircuits/hc1/roomtemperature",
      "type": "floatValue",
      "writeable": 0,
      "recordable": 1,
      "value": 18.9,
      "unitOfMeasure": "C",
      "state": [
        {
          "open": -3276.8
        },
        {
          "short": 3276.7
        }
      ]
    },

**Comment by pszafer** [comment]
Create new issue with this request and I'm gonna need your bosch scan as well attached to it (best in some json upload website)
