### ISSUE TITLE
Add support for room temperature sensor

### ISSUE THREAD

**Issue by minovap** [bosch-thermostat/home-assistant-bosch-custom-component#47]
I have a IVT Geo 516 which is not officially supported by your component, but that I got working with your help in another issue entry (thanks!). There is a wireless temperature sensor that came with the heater and helps the heater adjust to the temperature in the house. It is available on the /heatingCircuits/hc1/roomtemperature endpoint. Would it be possible to add support for it?

Here is my Bosch-dump:
https://jsonblob.com/0383cc7d-4317-11eb-9756-9b0ca7c0cb6d

This is the sensor I would like to read into HA:

    {
      "id": "/heatingCircuits/hc1/roomtemperature",
      "type": "floatValue",
      "writeable": 0,
      "recordable": 1,
      "value": 18.9,
      "unitOfMeasure": "C",
      "state": [
        {
          "open": -3276.8
        },
        {
          "short": 3276.7
        }
      ]
    },

**Comment by minovap** [comment]
From what I can tell you create a Bosch gateway:

        import bosch_thermostat_client as bosch

        self._update_lock = asyncio.Lock()
        BoschGateway = bosch.gateway_chooser(device_type=self._device_type)

And then call the get_circuits() method and iterate through the response, adding the sensors:

        circuits = data[GATEWAY].get_circuits(circ_type)
        for circuit in circuits:
            for sensor in circuit.sensors:

The `/heatingCircuits/hc1/pumpModulation` endpoint gets added correctly, but not the `/heatingCircuits/hc1/roomtemperature` endpoint. So it seems like the bosch_thermostat_client library doesn't pickup roomtemperature, or am I missing something?

**Comment by minovap** [comment]
I managed to find and edit `nsc_icom_gateway.json` and added three sensors that gets picked up when calling `get_circuits()`:

`
{'_connector': <bosch_thermostat_client.connectors.http.HttpConnector object at 0x7f9b37d5ca30>,

	 '_data': {'roomtemperature': {'result': {},

	                               'type': 'regular',

	                               'uri': '/heatingCircuits/hc1/roomtemperature'}},

	 '_extra_message': 'Waiting to fetch data',

	 '_main_data': {'id': 'roomtemperature',

	                'name': 'Current Room Temperature',

	                'path': '/heatingCircuits/hc1/roomtemperature'},

	 '_state': False,

	 '_type': 'sensor',

	 '_update_initialized': False}

	<bosch_thermostat_client.sensors.Sensor object at 0x7f9b37d863d0>

	{'_connector': <bosch_thermostat_client.connectors.http.HttpConnector object at 0x7f9b37d5ca30>,

	 '_data': {'heatCurveMin': {'result': {},

	                            'type': 'regular',

	                            'uri': '/heatingCircuits/hc1/heatCurveMin'}},

	 '_extra_message': 'Waiting to fetch data',

	 '_main_data': {'id': 'heatCurveMin',

	                'name': 'Heat Curve Min',

	                'path': '/heatingCircuits/hc1/heatCurveMin'},

	 '_state': False,

	 '_type': 'sensor',

	 '_update_initialized': False}

	<bosch_thermostat_client.sensors.Sensor object at 0x7f9b37d86040>

	{'_connector': <bosch_thermostat_client.connectors.http.HttpConnector object at 0x7f9b37d5ca30>,

	 '_data': {'heatCurveMax': {'result': {},

	                            'type': 'regular',

	                            'uri': '/heatingCircuits/hc1/heatCurveMax'}},

	 '_extra_message': 'Waiting to fetch data',

	 '_main_data': {'id': 'heatCurveMax',

	                'name': 'Heat Curve Min',

	                'path': '/heatingCircuits/hc1/heatCurveMax'},

	 '_state': False,

	 '_type': 'sensor',

	 '_update_initialized': False}
`

However only heatCurveMin got picked up and added into HA. Although it is giving -1 as value. I don't know if the endpoint is properly supported by the heaters gateway - maybe that can the cause of this. However `roomtemperature` which is most important for me is being correctly dumed with a correct value to the `bosch.json` so I assume it should be possible to add and read properly.

**Comment by minovap** [comment]
An update on heatCurveMin:

  Can't update data. Error: URI /heatingCircuits/hc1/heatCurveMin doesn not exist: 403, message='Forbidden', url=URL('http://192.168.86.47/heatingCircuits/hc1/heatCurveMin')

**Comment by pszafer** [comment]
@minovap you can add it same as https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/cf268303880d0c1ba32b69416234a16d1ef69963/bosch_thermostat_client/db/rc300.json#L42-L46

Most compress users don't have roomtemp sensor so I just need check if adding it won't break something for others.

about 403, don't ask me what the reason they are blocking it for you. it's every half a year bosch is blocking something and after another update it is unlocked again...

**Comment by pszafer** [comment]
It's added with 0.9.12.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.9.12
