### ISSUE TITLE
Retrieving the magic key

### ISSUE THREAD

**Issue by tonsmets** [bosch-thermostat/home-assistant-bosch-custom-component#48]
Hi,

I want to use this integration with my EasyControl CT200. It seems some kind of magic key is missing to get going with this. I just tried decompiling the Android version of the Bosch EasyControl app. I found some strings and auth_config json data that might be the key to getting this working.

I have no idea if I can simply share this without legal consequences?

Kind regards,
Ton

**Comment by pszafer** [comment]
you can use lib and try it out here: https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/encryption/nefit_encryption.py

you can come to discord and PM me later, we can figure out something.

you can also try to check if it's not same useless data as here: https://github.com/robertklep/bosch-xmpp/issues/4

**Comment by lennvilardi** [comment]
I think he found the magic key check https://github.com/robertklep/bosch-xmpp/blob/6368b4ac3dbe563da70391c94945884fe0ea611f/lib/ivt-client.js#L4
