### ISSUE TITLE
Bosch 7001i (IVT) via http not all entities available

### ISSUE THREAD

**Issue by cubedube** [bosch-thermostat/home-assistant-bosch-custom-component#50]
Hello,

I have a brandnew Bosch 7001i Ground Heating Pump installed and connected it with the built in  Ethernet Connector.
As i understand this product is from IVT but sold under Bosch - right?
Runnung Home Assistant on a Pi 4 on the latest Version with the Bosch Custom Component on 9.11.

I get some Datas out but not consumed KW/h, Start Time, circuit Pump Modulation and all the Collector Data. Can someone help me? is there something wrong configured or is that model not completely supported?

Sensor Data
![image](https://user-images.githubusercontent.com/71415843/103488438-d381b800-4e0c-11eb-88c4-daa68728e1d3.png)

HW Data
![image](https://user-images.githubusercontent.com/71415843/103488485-2fe4d780-4e0d-11eb-9273-9b63a532b76a.png)

HC Data
![image](https://user-images.githubusercontent.com/71415843/103488506-59056800-4e0d-11eb-9f17-8937616b928e.png)

here the debug log
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5762256/bosch_scan.zip)

**Comment by cubedube** [comment]
Btw i forgot the HA Core logs - it seems that these data could not be found - i think they are there but probably reachable under different names?

![image](https://user-images.githubusercontent.com/71415843/103488640-8bfc2b80-4e0e-11eb-8066-1a82ba8dad6b.png)

**Comment by pszafer** [comment]
Ok. I don't have compress to test, so it's someone else work to add support for it.
in your situation:
- collector temp in/out, start time, system pressure - don't have permission to access it. Nothing to do with it, as it is Bosch decision to don't give access to this sensor. Might be accessible via XMPP...
- return temp - there is no such sensor in your setup
- DHW charge seems correct - you can make service to start it so you can heat water for 60 minutes interval in your case
- DHW working time - don't know why value is 0, but it displayed as bosch gives it to us.
- energy consumption / water flow as well I think -> this is the problem. it's not implemented properly yet. It seems that there are some uri's in bosch such as yours where you need to pass interval query param like `?interval=2020-12-23`
I haven't had time to work on it, there are some users, who wanted to do it, but so far I don't have any PR which adding this feature.

**Comment by cubedube** [comment]
Hi,

Thank you so much for the fast and proper response. i mean its already some information i get - but once you start you always want more :)
I will get in touche with bosch - who knows if a firmware update will be comming somewhen if that is even a option from bosch. i would let you know here if i find more information.

**Comment by pszafer** [comment]
I doubt bosch would help you. better come to discord and you can get in touch with guys who are already tried to make sense of it.
