### ISSUE TITLE
water_heater stopped working (RC300 / 04.07.05 / IVT / http)

### ISSUE THREAD

**Issue by der-optimist** [bosch-thermostat/home-assistant-bosch-custom-component#51]
**Describe the bug**
Some entities never worked (like energy consuption and heat pump modulation), but water_heater used to work. I was the target temperature that is set in the heat pump and I saw the current water temperature. But suddenly, it stopped showing these values. 
This happened approximately 36 hours after the last (automatic) restart of the heat pump (2020-12-15 02:46. Last received value is from 2020-12-16 13:00)
I think the values are available in the debug scan. But I don't understand why the component doesn't get the values.

**To Reproduce**
Don't know, sorry.

**Expected behavior**
See temperature values in HA.

**Screenshots**
![image](https://user-images.githubusercontent.com/45357614/103631180-f31afc80-4f42-11eb-9db7-5e3409768249.png)

![image](https://user-images.githubusercontent.com/45357614/103631287-134abb80-4f43-11eb-901f-903de3ad1716.png)

![image](https://user-images.githubusercontent.com/45357614/103631352-28bfe580-4f43-11eb-9502-2cdb234edd86.png)

![image](https://user-images.githubusercontent.com/45357614/103631421-3ecda600-4f43-11eb-80c5-9ffe28d2b0ce.png)
![image](https://user-images.githubusercontent.com/45357614/103631477-4f7e1c00-4f43-11eb-8f21-f0dd51ca38bc.png)

I deactivated the entities that did not work.

**Version**
  - HA version: 2020.12.0
  - HA Bosch component version: v0.9.11
  - Python Bosch HTTP client version: ?

** Debug SCAN **
https://jsonblob.com/7a6a702c-4f3c-11eb-bace-c1b413863bd1

**Additional context**
Thank you for your work on this component!

**Comment by der-optimist** [comment]
UPDATE: I just saw, that 2020-12-16 is the day I updated this component (time: 14:25) => so I think, the issue is related to the update

**Comment by pszafer** [comment]
can you paste screenshot from dhw1/water_heater Developer tools -> States? like this:
![image](https://user-images.githubusercontent.com/690510/103638413-2bbfd380-4f4d-11eb-989a-b768d036419a.png)

And maybe select somehow what is not working or/and what are real values from thermostat.

**Comment by der-optimist** [comment]
![image](https://user-images.githubusercontent.com/45357614/103646861-a8a57a00-4f5a-11eb-9244-1008fdb0c0a2.png)

Current Temp at the time of the debug scan was 43.9 C
I use profile "high" so it showed 43C as a setpoint until the update. The thermostat shows setpoint 55C, but I think this is the point where that water heater stops heating (and 43 is the point where it starts heating).

**Comment by pszafer** [comment]
Should be fixed with 0.9.12.
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.9.12

If issue still persist we can reopen.

**Comment by der-optimist** [comment]
It's working again, thank you very much!
