### ISSUE TITLE
Would you like me to add more GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [bosch-thermostat/home-assistant-bosch-custom-component#52]
**Is your feature request related to a problem? Please describe.**
If you want, I can add some advanced CI to your repo.

**Describe the solution you'd like**
Let me know if you want a PR.

**Describe alternatives you've considered**
- Do you want to enable auto-formatting whenever pushed?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Additional context**

**Comment by pszafer** [comment]
Sure. Make PR for it. 
- Autoformatting with black is ok.
- It can be packaged.
