### ISSUE TITLE
Support to CT100 FW 02.18.02

### ISSUE THREAD

**Issue by marcomsousa** [bosch-thermostat/home-assistant-bosch-custom-component#54]
[bosch_thermostat_client.gateway.base_gateway] You might have unsuporrted firmware version 02.18.02

Please support to CT100 FW 02.18.02

[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5791553/bosch_scan.zip)

**Comment by marcomsousa** [comment]
[https://github.com/bosch-thermostat/bosch-thermostat-client-python/pull/9](url)

**Comment by pszafer** [comment]
Will be added in next version
