### ISSUE TITLE
Bosch 7001/IVT Auxilary Heat On/Off Status

### ISSUE THREAD

**Issue by cubedube** [bosch-thermostat/home-assistant-bosch-custom-component#55]
Hi,

Is it possible to get displayed the status of the Auxilary Heating?
I assume that would be the sensor *Flamestatus" which in my case is constantly "Off".
I did the bosch scann on the entity "flamestatus" if that information is helpful.
Let me know if i can provide more information...
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5824047/bosch_scan.zip)

**Comment by pszafer** [comment]
Please, make new scan with latest lib/component version
