### ISSUE TITLE
Intergation of Buderus TC100

### ISSUE THREAD

**Issue by Lacoste2403** [bosch-thermostat/home-assistant-bosch-custom-component#56]
HA version: 0.117.6
Firmware TC100 = 03.04.01

I can not mount my TC 100, after entering the correct serial number and code, PW always comes "Unknown Error"

Idea what it is...external service is active....

thank you

Lars

**Comment by pszafer** [comment]
your firmware version seems outdated. can you try update it?
if it is impossible to update then I need bosch scan of your device

**Comment by Lacoste2403** [comment]
i have updated "HA", unfortunately no success...i provide scan...thanks

**Comment by pszafer** [comment]
sorry, misundrestanding, I meant firmware of TC100 module.

**Comment by Lacoste2403** [comment]
no problem...unfortunately I can not update my TC 100. Buderus app says that there is no newer update 

Model: logamatic tc100.2
Firmware 03.04.01

**Comment by pszafer** [comment]
please update component to 0.10.0 version, readd device and check out if you can run bosch_scan from developer tools -> services.

**Comment by pszafer** [comment]
I see that TC100 is connecting to same XMPP server as CT200.
Unfortunately there is different encryption and different magic key. Closing this till somebody discover magic.
