### ISSUE TITLE
CT100 v02.21.00 - no devices

### ISSUE THREAD

**Issue by Den-Olli** [bosch-thermostat/home-assistant-bosch-custom-component#57]
The installation didn't give any errors and connecting to my CT100 works, but the devices are not added.
The bosh service is also not available, so I can't access the log

**Comment by pszafer** [comment]
Find some logs, without logs I can't even tell what's not working.
provide: HA version, python version

**Comment by Den-Olli** [comment]
HA version: core-2021.2.3
Python version: 3.8.7

I just found something in the general log, but the bosch.debug_scan isn't available in the services

Logger: homeassistant.config_entries
Source: custom_components/bosch/__init__.py:171
First occurred: 12:28:51 PM (1 occurrences)
Last logged: 12:28:51 PM

Error setting up entry Unknown for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bosch/__init__.py", line 102, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 171, in async_init
    manufacturer=self.gateway.device_model,
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/gateway/nefit_gateway.py", line 46, in device_model
    return self._device.get(VALUE, "Unknown")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pszafer** [comment]
what country are you from? I will try to make 'better' log tomorrow, so we can try to fix this.

**Comment by Den-Olli** [comment]
I'm from Belgium
take your time, it's not super urgent :)

**Comment by GH2user** [comment]
> HA version: core-2021.2.3
> Python version: 3.8.7
> 
> I just found something in the general log, but the bosch.debug_scan isn't available in the services
> 
> Logger: homeassistant.config_entries
> Source: custom_components/bosch/**init**.py:171
> First occurred: 12:28:51 PM (1 occurrences)
> Last logged: 12:28:51 PM
> 
> Error setting up entry Unknown for bosch
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
> result = await component.async_setup_entry(hass, self) # type: ignore
> File "/config/custom_components/bosch/**init**.py", line 102, in async_setup_entry
> return await gateway_entry.async_init()
> File "/config/custom_components/bosch/**init**.py", line 171, in async_init
> manufacturer=self.gateway.device_model,
> File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/gateway/nefit_gateway.py", line 46, in device_model
> return self._device.get(VALUE, "Unknown")
> AttributeError: 'NoneType' object has no attribute 'get'

I have exactly the same result in the log.
Running HASSOS 5.11, HAcore 2021.2.3, Supervisor 2021.02.11
I have a Nefit Easy and living in the Netherlands

**Comment by pszafer** [comment]
With new version 0.10.0 you both can make bosch_scan.
Provide me your bosch_scans so I can try to add this device to this component.

**Comment by GH2user** [comment]
That indeed did make things work better;
- got a device showing now and was able to run the bosch.debug_scan
- device info:   Nefit, by Unknown, Firmware: 02:21;00
Debug scan attached as txt-file as didn't allow uploading json.

[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6038290/bosch_scan.txt)

**Comment by pszafer** [comment]
thanks! I will check it tomorrow and try to fix errors.

**Comment by Den-Olli** [comment]
I have also 1 unknown device now and was able to run the debug scan
[bosh_scan-DenOlli.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6042384/bosh_scan-DenOlli.txt)

**Comment by pszafer** [comment]
can you both provide some information about this devices (photo of the sticker maybe)?
I see that @GH2user has Buderus branded CT100
and @Den-Olli Junkers CT100 Belgium?

**Comment by Den-Olli** [comment]
I think that Junkers CT100, Buderus CT100 and Bosh CT100 are al the same device
![IMG_20210225_122244464](https://user-images.githubusercontent.com/14292392/109146714-7519eb80-7764-11eb-99a2-ea7294895ed0.jpg)
![Screenshot_20210225-122211](https://user-images.githubusercontent.com/14292392/109146722-777c4580-7764-11eb-9e74-b2dcfb147c42.png)

**Comment by GH2user** [comment]
I have the Nefit version, [https://professioneel.nefit-bosch.nl/consument/service/easy/easy](url)

![nefit_easy2](https://user-images.githubusercontent.com/59734822/109186238-01da9e80-7791-11eb-8269-4d6f835fc39c.jpg)
![nefit_easy](https://user-images.githubusercontent.com/59734822/109186250-0606bc00-7791-11eb-9af6-37d6353574b6.jpg)

**Comment by pszafer** [comment]
you can both check 0.10.1.

**Comment by GH2user** [comment]
0.10.1 gives me 3 devices and 5 entities

bosch sensors with outdoor_temperature, flow_control, system_pressure, actual_power
buderus ct100 with nothing
heating circuit hc1  with climate.hc1, 

the climate.hc1 gives me the set temperature and the current temperature.
all sensors when enabled give a meaningful value except the actual_power which is 0
have to check if this will only increase when heating as it is not at the moment.

Looking good sofar I would say!
Thanks for the quick action @pszafer

**Comment by Hendrikdenhond** [comment]
Following this post because i also could non integrate a bosch/junkers CT100 thermostat.
Installed version 0.10.1 and a device (junkers CT100) appeared in the integration, but no entities.
attached the bosch_scan.json as a zip.

Keep u the good work, really appreciating it !!!

[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6047664/bosch_scan.zip)

**Comment by Hendrikdenhond** [comment]
looks like i have unsupported firmware:

found this in HA notfications:

Bosch info
There are problems with config of your thermostat.
You might have unsuporrted firmware version 02.22.00.
You can create issue on Github, but first
Go to Developer Tools/Service and create bosch.debug_scan.
BoschGithub

**Comment by ktfzone** [comment]
My Bosch CT100 in Romania was broken as well with the latest release, I get Your device is unknown null.

**Comment by pszafer** [comment]
please, everybody, make new issue and attach new scan.
You have new firmware (I guess they released update... ) and devices from different countries.
I don't know why they brand devices for different countries and gives different model numbers but they do.
