### ISSUE TITLE
Problem starting the component

### ISSUE THREAD

**Issue by kamikazaaa** [bosch-thermostat/home-assistant-bosch-custom-component#6]
Hello, 

Thank you very much for developping this custom component.

Unforunately, I cannot start the component after installing it following the instructions. I've tried many times for several weeks now but the component doesn't seem to retrieve the data from my Buderus KM200. Please note that I've installed and used the "ha-buderus" (https://github.com/stefanlaheij/ha-buderus/) component before without a problem. I've uninstalled it before using your component.

This is the error I mostly get:

Error setting up entry for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 153, in async_setup
    hass, self)
  File "/config/custom_components/bosch/__init__.py", line 91, in async_setup_entry
    "sensors", uuid, bosch_sensors(current_firmware), gateway))
  File "/config/custom_components/bosch/__init__.py", line 172, in initialize_component
    components[FIRMWARE_VERSION])
TypeError: 'NoneType' object is not subscriptable

When I look at the full Home assistant log, the component seems to be communicating with the KM200 but it doesn't retrieve the data:

2019-07-19 22:20:06 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /gateway/versionFirmware from gateway: {"id":"/gateway/versionFirmware","type":"stringValue","writeable":0,"recordable":0,"value":"01.10.03"}
2019-07-19 22:20:06 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /gateway/versionHardware
2019-07-19 22:20:08 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /gateway/versionHardware from gateway: {"id":"/gateway/versionHardware","type":"stringValue","writeable":0,"recordable":0,"value":"iCom_Low_v1"}
2019-07-19 22:20:08 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /system/brand
2019-07-19 22:20:09 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /system/brand from gateway: {"id":"/system/brand","type":"stringValue","writeable":0,"recordable":0,"value":"Buderus"}
2019-07-19 22:20:09 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /system/systemType
2019-07-19 22:20:10 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /system/systemType from gateway: {"id":"/system/systemType","type":"stringValue","writeable":0,"recordable":0,"value":"CoreIcomGw"}
2019-07-19 22:20:10 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /heatingCircuits
2019-07-19 22:20:12 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /heatingCircuits from gateway: {"id":"/heatingCircuits","type":"refEnum","references":[{"id":"/heatingCircuits/hc1","uri":"http://192.*/heatingCircuits/hc1"},{"id":"/heatingCircuits/hc2","uri":"http://192.*/heatingCircuits/hc2"}]}
2019-07-19 22:20:12 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /heatingCircuits/hc1
2019-07-19 22:20:15 DEBUG (MainThread) [bosch_thermostat_http.gateway] Retrieved data for path /heatingCircuits/hc1 from gateway: {"id":"/heatingCircuits/hc1","type":"refEnum","references":[{"id":"/heatingCircuits/hc1/currentRoomSetpoint","uri":"http://192.*/heatingCircuits/hc1/currentRoomSetpoint"},{"id":"/heatingCircuits/hc1/actualSupplyTemperature","uri":"http://12.*/heatingCircuits/hc1/actualSupplyTemperature"},{"id":"/heatingCircuits/hc1/actualSupplyTempSetpoint","uri":"http:///heatingCircuits/hc1/actualSupplyTempSetpoint"},{"id":"/heatingCircuits/hc1/operationMode","uri":"http://*/heatingCircuits/hc1/operationMode"},{"id":"/heatingCircuits/hc1/temperatureRoomSetpoint","uri":"http://*/heatingCircuits/hc1/temperatureRoomSetpoint"},{"id":"/heatingCircuits/hc1/roomtemperature","uri":"http://*/heatingCircuits/hc1/roomtemperature"},{"id":"/heatingCircuits/hc1/manualRoomSetpoint","uri":"http://*/heatingCircuits/hc1/manualRoomSetpoint"},{"id":"/heatingCircuits/hc1/designTemp","uri":"http://*/heatingCircuits/hc1/designTemp"},{"id":"/heatingCircuits/hc1/currentOpModeInfo","uri":"http://*/heatingCircuits/hc1/currentOpModeInfo"},{"id":"/heatingCircuits/hc1/heatCurveMax","uri":"http://*/heatingCircuits/hc1/heatCurveMax"},

**Comment by pszafer** [comment]
Do you use HA 0.96 already?
It seems something is going wrong with checking sensors in your installation. I don't know why yet unfortunately...

**Comment by kamikazaaa** [comment]
Thanks for your fast reply.
Yes I use 0.96.1. But I had the same issues with older versions of HA and your component.

**Comment by kamikazaaa** [comment]
For your information, I use my KM200 on a Buderus GB162 with the RC35. The firmware is 01.10.03, which is the latest for this constellation.

**Comment by moustic999** [comment]
that's a pretty common installation. I'm curious what is happening.
Can you provide the output of rawscan ?

it is strange, version of the gateway have been updated by buderus few months ago  : here is the latest version : 
/gateway/versionFirmware
{'id': '/gateway/versionFirmware', 'type': 'stringValue', 'writeable': 0, 'recordable': 0, 'value': '04.06.07'}
/gateway/versionHardware
{'id': '/gateway/versionHardware', 'type': 'stringValue', 'writeable': 0, 'recordable': 0, 'value': 'iCom_Low_NSC_v1'}

**Comment by kamikazaaa** [comment]
What do you mean by rawscan? Inside of Home assistant?

About the firmware, it's the latest version which has been installed automatically. I don't know how to "force" a firmware update. Somebody said on a forum that this is the latest for RC35, the other would be only for RC300. But I'm not sure about that.

**Comment by pszafer** [comment]
@kamikazaaa your version of firmware is not supported by us, because we never saw such version.
In our knowledge current version for KM200 is '04.06.07'.

But let's try to integrate your setup as well.
I released new version: https://github.com/pszafer/home-assistant-bosch-custom-component/releases/tag/v0.3-alpha which shouldn't throw errors even if it is not compatible with library.

Delete integration first.
Remember to go to `~/.homeassistant/.storage` (or your storage dir) and look for:
- bosch -> delete this file
- you might check if there is anything related to bosch in files: core.config_entries, core.device_registry, core.entity_registry

If you succeed with installation then go to Develop tools -> Services -> choose bosch.debug_scan.

Provide us file which will be created.

**Comment by kamikazaaa** [comment]
Thanks for your efforts!

I managed to install the integration and it's recognised by Home Assistant without the sensors. 

Here is the Debug file:

[bosch_scan.zip](https://github.com/pszafer/home-assistant-bosch-custom-component/files/3418251/bosch_scan.zip)

**Comment by pszafer** [comment]
@kamikazaaa how old is your installation?

It seems that your scheme is very old and strange.
```
 {
            "id": "/gateway/uuid",
            "type": "stringValue",
            "writeable": 0,
            "recordable": 0,
            "value": -1,
            "allowedValues": -1
}
```

Your installation is missing:
```
"id": "/gateway/update"
```
I see that for sure many functions won't be working properly for you (water_heater probably).

My idea is to disconnect KM200, reset it and then connect it for a while without connecting to rest of the system. But I don't know if it wouldn't break something...

Also I could try to implement your scheme in library, but it gonna take a while and without any guarantee as I don't have access to this module.

**Comment by kamikazaaa** [comment]
The Gb162 and RC35 are from 2010. The KM200 v2 is from 2018.

I will try to reset it and disconnect it from the system, maybe it will update the firmware.

Has anybody tested your integration with the RC35?

**Comment by pszafer** [comment]
We don't have enough feedback back for now, so cannot say what KM* is connected with for different user.
I'm going to prepare lib to be more flexible for older firmware, but it's gonna take some time...

**Comment by kamikazaaa** [comment]
I contacted Bosch/Buderus about the firmware. Unfortunately, they confirmed that the latest firmware for the RC35 is 01.10.03.
The firmware 04.06.07 is only for the RC300 and RC310.
So I would be very grateful for a version of the integration which is compatible with the other firmware.

**Comment by pszafer** [comment]
Ok, I will update with you when I have something ready to test. I guess you will have to wait 2 weeks as I will be pretty busy next week.

**Comment by moustic999** [comment]
Do you have some knowledge in python ?
Can you try using the lib directly ? It would be very helpfull to have a list of all endpoints available on your system. once I have this, we could find a way to make the HA plugin working for you, as much as possibe with what we have .

**Comment by kamikazaaa** [comment]
@pszafer thank you very much. No problem, take your time.

@moustic999 I had started to learn Python but my knowledge is very limited. But this motivates me to take it up again. Maybe I will need a little help..

**Comment by pszafer** [comment]
@kamikazaaa can you try to install this release:
https://github.com/pszafer/home-assistant-bosch-custom-component/releases/tag/v0.4-alpha
You'd have ~/.homeassistant/.storage/bosch file there and you can customize URL's to your needs, but I tried to prepare it for your installation already.

**Comment by kamikazaaa** [comment]
@pszafer, I've tested the new release and I see some improvements. I now have the following sensors:

![Screenshot_20190813-220452_Chrome](https://user-images.githubusercontent.com/52717349/63230407-7b90e400-c20c-11e9-9d45-6625cdfd1eee.jpg)


The Water Heater and the thermostats of my 2 heating circuits are also available, but I cannot change the operating modes.

**Comment by pszafer** [comment]
Can you try now with new version?
I'm trying to adjust component for software version which most people have and yours. Pretty hard as you have different modes from us, but hopefully I'm getting closer.
Waiting for your feedback.

**Comment by kamikazaaa** [comment]
Thank you, I really appreciate your efforts.
I've tested the new version, I see some differences. I now see the "Target temperature" in the Water Heater:

![image](https://user-images.githubusercontent.com/52717349/63807377-dff32800-c91d-11e9-87e8-dbb16ca20eb2.png)


But if I try to change it, I get an error:

![image](https://user-images.githubusercontent.com/52717349/63807300-b3d7a700-c91d-11e9-8ff1-4484138599c0.png)

Operation only shows "off" but cannot be changed:

![image](https://user-images.githubusercontent.com/52717349/63807515-25aff080-c91e-11e9-96f8-98bb2b208edb.png)

For the heating circuits, it now shows "auto" in "Operation", and I successfully changed it :

![image](https://user-images.githubusercontent.com/52717349/63807630-690a5f00-c91e-11e9-949a-4eb1acd8a06f.png)

But I can only change it to auto, not back to "off".

 I haven't tried yet to use the lib directly in Python, due to limited time. Do you think I could help you by trying it, like moustic999 suggested?

**Comment by pszafer** [comment]
@kamikazaaa about set temperature I'll check that.
About operation mode, this bug suppose to happen in this version.
Just explain to me how night and day operation modes are working in your installation.

Why I'm asking...
I have such modes in climate component:
```
HVAC_MODES = [
    HVAC_MODE_OFF,
    HVAC_MODE_HEAT,
    HVAC_MODE_COOL,
    HVAC_MODE_HEAT_COOL,
    HVAC_MODE_AUTO,
    HVAC_MODE_DRY,
    HVAC_MODE_FAN_ONLY,
]
```

and I have no idea which mode is going where in your setup.
night and day is just heat or night is off and day is heat?

**Comment by kamikazaaa** [comment]
Actually, night and day are both different heating modes, but with different temperatures. Day is heating at the "normal" set room temperature, and night is a reduced mode where the system operates at the set night room temperature.
But since the HVAC_MODES don't have such modes, I would suggest that day is heat and night is off.

**Comment by pszafer** [comment]
Can you send me rawscan while your thermostat is in auto mode?
If possible try to reach me on discord. Then I guess we could figure out how to test new releases faster.

**Comment by kamikazaaa** [comment]
@pszafer here is the new rawscan with everything on auto:
[bosch_scan.zip](https://github.com/pszafer/home-assistant-bosch-custom-component/files/3571141/bosch_scan.zip)

ok what is your tag? I can also contact you on your gmail if you prefer.

**Comment by pszafer** [comment]
Same as here. pszafer or pszafer@gmail.com

**Comment by moustic999** [comment]
@kamikazaaa I checked our debug scan.
The RC35 is pretty common, but a bit older, It is possible to have all working fine in HA, but we need to make few debugging/experimentation

Is possible for you to install the python lib and python itself on a pc to make few experimentations ?

I would like to make sure of what you can do on the RC35.
How do you use it. When you are in auto mode. temperature are set via the calendar which swich between night / day. is That right ?

At any moment, in auto mode can you override the target temp ? or you need to switch to manual ?

**Comment by kamikazaaa** [comment]
Hi @moustic999, sorry for the late answer. I'm also in contact with pszafer and am trying to provide some infos.

About your questions:
So normally, the system is in auto mode. The program/schedule can be changed via the RC35 or the app. The schedule defines the time where it switches between the day and night temperature.

Yes, I can change the target temp in any mode, day, night or auto. This is possible via RC35 or in the app. When it is in auto mode, this change affects the actual mode it is in according to the schedule. For example : the system is in auto mode, at 15:00 it is day mode according to the schedule. When I change the temp from 22 to 23, this will also directly affect the day temperature. When I change to day mode after this change, the temp will stay at 23.
