### ISSUE TITLE
Bosch CT100 Romania : Unknown model

### ISSUE THREAD

**Issue by ktfzone** [bosch-thermostat/home-assistant-bosch-custom-component#60]
My Bosch CT100 is no longer recognizable . 

  - HA version 5.12
  - HA Bosch component version? latest, I assume v0.10.1
  - Python Bosch HTTP client version?  I didn't even had it installed until now, I found it but no details on how to install it. Any help here would be highly appreciated :)
  

Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

bosch.debug_scan not available in the list of services sadly.

[bosch.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6049881/bosch.txt)

Software version 02.22.00
hardware version 4

**Comment by pszafer** [comment]
@ktfzone there is no Home Assistant 5.12.

Can you remove your device and add it again?
From logs you attached it seems that some data like password, access token might be wrong.

If it still fails try to install lib in your computer and create scan:
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/VENV-setup
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Rawscan-directly-from-LIB

(+ windows help - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-environment-setup#windows-setup-using-windows-subsystem-linux )

**Comment by pszafer** [comment]
@ktfzone test out pre-release v0.10.2

**Comment by pszafer** [comment]
From software version I can see now that you have CT100.2. It won't work with this lib unfortunately.
