### ISSUE TITLE
Bosch Compress 7000 New FW 04.07.06

### ISSUE THREAD

**Issue by Heli4ce** [bosch-thermostat/home-assistant-bosch-custom-component#63]
**Describe the bug**
Integration stopped working after FW-update, I think I managed to get a rawscan...
Does this help?

[rawscan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6157474/rawscan.zip)

**Comment by pszafer** [comment]
fixed in: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.11.4

**Comment by Mektrik1** [comment]
Hi

i have a question where do i find the serial number of my Bosch Compress AW7000i
so i can get it intregret in Home assistant

**Comment by pszafer** [comment]
@Mektrik1 what devices do you own? do you have rc300?

**Comment by philsson** [comment]
I'm stealing this thread a bit. Looking into buying a pump called `Bosch Compress 7000i AW 7`. Any ideas if this will be compatible with this integration?

**Comment by pszafer** [comment]
it depends what control panel would you have. Newer versions works with Home Connect cloud and it wouldn't work with this integration.
If I were you I'd try to make EMS-Esp device and control heating with that as it doesn't need cloud service.
