### ISSUE TITLE
Bosch CT200 easycontrol problem

### ISSUE THREAD

**Issue by Lipek1991** [bosch-thermostat/home-assistant-bosch-custom-component#68]
Hello,

I can't connect my ct200 thermostat
log:

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:241
Integration: Bosch thermostat (documentation, issues)
First occurred: 19:49:14 (1 occurrences)
Last logged: 19:49:14

Cannot connect to Bosch gateway, host xxxxxxxx with UUID: None

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:239
Integration: Bosch thermostat (documentation, issues)
First occurred: 19:49:14 (1 occurrences)
Last logged: 19:49:14

Your device is unknown null

Logger: bosch_thermostat_client.gateway.easycontrol_gateway
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/gateway/easycontrol_gateway.py:100
First occurred: 19:49:13 (2 occurrences)
Last logged: 19:49:14

Couldn't find device model. Got product ID: None

Logger: bosch_thermostat_client.encryption.base_encryption
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py:77
First occurred: 19:49:12 (10 occurrences)
Last logged: 19:49:14

Unable to decrypt: b'\xb2\x84\xb6P\x89r\x8fM\xe8\x12\r\xb8\xb4\x00p@\xc8\xff\x1f\x11\xbd\xa9t\xc3\xf8^\xe5gB\xd1\xcc\x8emW\xd7\x03f\xf5!\x19\xea\xdc\x05\xcf\xb7R`9\xa79\x04\x12@,\xce\xed\xd2\x9e\xd6\x00-\x85\x1cO\xa2\xc9\xd4\x7f7|E\xce\xef\xdf{-\x07{\x8de,\xdbV+\xb8W\x1b\xb5\x0b\xd7\x9f\xc2{\x0fh\xdd' with error: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbS]Y\xe8x\xd2\xab\xd5}#\x882\xc5\xd9\xecT\x8b\x02\xf4\xac\xf9\xba\x11\x81\xa3\x82Ll\x98\x9fer\x803\xb6F\xda\xce(\x0c\x1aKrAa\x03\xba\x01K\xfd\xf0\xbaq\x9642\xd7\x04\xc9\xe8)\xfb\x7f\x8aT~a\x88|I9Y\xfao\r\xed\x94Z\xfb+\xfe\x82H\x80w\xc8\xe1\xa6\xfan\x82Ay]j\xe0' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bb\n&|d\xb7)0Z>^\\\xe18\xdc/J\xac\xee5r0\x1e\x08\xd7\xd0V\xe2\x1cm\x1a\xb9\xf7\xef\xf7\xc2O\xc7\x0f7\xa9\xa2U3\xa3\x12\xf8\xa2\xe9\xc9s\xc6\x1a\xdf\xba\x1dA&\xfb\xd1\x13\xaa\xebK\x9fM\xfe\xe1\xa4\xc0wz2\x0b\xc2\xc3\xde(\xda\n\xc5\x0f\x8d2xf\xed\x00\t\x9a>Q}{\xff\x1c#' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbH_f.G\xedK\xcd\x8e2\x80j\t%{\xf5\xb1uTm\xfd<\xd0\xeb\x8e=\xdc\x7f\x01\x8fE\'\xd7\x01\x90H\x84\x83Sy\xe7\xf5er\xb4\xd7)\x13\xff\xca\xc32\x0b\x86\xe7\xe2\x9cJ\x9b-bj\xdc\t\xa1V"@y\xe2#\xe8j2Ow\xf7\xfe\xcbx\xc4\xef\x89\x9b\x8e}\x8c\x1e0[\x86?\xe2\x06\x11\xdf\xab\x89\xa3\xcd!\x98lDM\x0e\xacDjr\x97I' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbH_f.G\xedK\xcd\x8e2\x80j\t%{\xf5\xb1uTm\xfd<\xd0\xeb\x8e=\xdc\x7f\x01\x8fE\'\xd7\x01\x90H\x84\x83Sy\xe7\xf5er\xb4\xd7)\x13\xff\xca\xc32\x0b\x86\xe7\xe2\x9cJ\x9b-bj\xdc\t\xa1V"@y\xe2#\xe8j2Ow\xf7\xfe\xcbxe\xb68\xd0\x7f\xaa\xea\xfe_O7\x8aN\x19\x17\xdc\xab\x89\xa3\xcd!\x98lDM\x0e\xacDjr\x97I' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

![bosch](https://user-images.githubusercontent.com/82958204/115769257-a224fc00-a3ab-11eb-9c93-533a91c8c4c1.png)

**Comment by pszafer** [comment]
your password is wrong

**Comment by Lipek1991** [comment]
I checked the password for the application bosch easycontrol and it's correct.
Maybe i'm doing something wrong. Please see the screenshots


![2021-04-22_211838](https://user-images.githubusercontent.com/82958204/115774128-7c025a80-a3b1-11eb-87e6-4ecf542d2360.png)
![2021-04-22_211850](https://user-images.githubusercontent.com/82958204/115774138-7e64b480-a3b1-11eb-82f7-3bf57db2c5fc.png)
![2021-04-22_212407](https://user-images.githubusercontent.com/82958204/115774142-802e7800-a3b1-11eb-9ec2-d923c0e78222.png)
![2021-04-22_212417](https://user-images.githubusercontent.com/82958204/115774144-815fa500-a3b1-11eb-9f7f-faecfda3a177.png)

**Comment by pszafer** [comment]
looks good but unfortunately decrypting bug is telling that something is wrong with password or access key.

**Comment by Lipek1991** [comment]
I reset my password, the problem is the same. 
Any other solutions?

**Comment by pszafer** [comment]
Unfortunately I don't know. Only thing I can offer is that you can PM me on our discord server https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#first-config-help-needed and I can check if I can connect to your device. It's up to you.

**Comment by pszafer** [comment]
Problem was with input password. User need to find/change password in EasyControlApp -> Settings -> User settings -> Change password.
Do not change password to bosch identity portal (it's wrong password).

**Comment by janoschbatschi** [comment]
Hey Pawal! 
Unfortunately, I'm facing exactly the same issue. Changed the password in the app and tried several times. Do you have any idea what could cause the problem?
<img width="813" alt="Bildschirmfoto 2021-09-13 um 11 43 29" src="https://user-images.githubusercontent.com/2529951/133062289-dc1079ed-ae9b-486d-bd41-b02087d6d6c5.png">

**Comment by pszafer** [comment]
hey, you probably need to open Bosch app, update your thermostat somehow and install pre-release 0.14.x as Bosch is rolling new firmware which moves you to the new server.

**Comment by janoschbatschi** [comment]
thank you pawel - that was the missing link!
