### ISSUE TITLE
Missing % unit for humidity sensor

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#73]
![image](https://user-images.githubusercontent.com/1262548/116745616-a1b7e100-a9fb-11eb-8c5d-b0d3f721337b.png)

Using CT200, indoor humidity has no unit, it should be %
```
2021-04-30 21:33:07 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsIndoor humidity101027819 called.
2021-04-30 21:33:07 DEBUG (MainThread) [custom_components.bosch.sensor] Bosch units {'value': 36.9, 'minValue': 0.0, 'maxValue': 100.0, 'unitOfMeasure': '', 'writeable': 0}
```

**Comment by doudz** [comment]
file:///home/doudz/.homeassistant/www/bosch_scan.zip
-34:-78:63:64

Attached bosch debug scan

**Comment by pszafer** [comment]
I can't reproduce. this is what I have using your scan:
![image](https://user-images.githubusercontent.com/690510/116788020-afc33b80-aaa7-11eb-8909-6ddb1188f7d4.png)

![image](https://user-images.githubusercontent.com/690510/116788057-de411680-aaa7-11eb-984e-82ea94ecdd16.png)

**Comment by doudz** [comment]
I agree it's strange, I put a debug line in get_units function inside async_update and it show that unitOfMeasure is empty

```
    async def async_update(self):
        """Update state of device."""
        _LOGGER.debug("Update of sensor %s called.", self.unique_id)
        data = self._bosch_object.get_property(self._attr_uri)

        def get_units():
            _LOGGER.debug("Bosch units %s", data) 
```


```
2021-04-30 21:33:07 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsIndoor humidity101027819 called.
2021-04-30 21:33:07 DEBUG (MainThread) [custom_components.bosch.sensor] Bosch units {'value': 36.9, 'minValue': 0.0, 'maxValue': 100.0, 'unitOfMeasure': '', 'writeable': 0}

```

**Comment by pszafer** [comment]
2 ideas, you might try to disable unbase64 function for json https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/7aeeb5812daf1632b0a84b0f8823dba5b3121ef0/bosch_thermostat_client/encryption/base_encryption.py#L27

or check if '%' is returned with get function https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/7aeeb5812daf1632b0a84b0f8823dba5b3121ef0/bosch_thermostat_client/connectors/xmpp.py#L78

**Comment by doudz** [comment]
Removing unbase64 works !
![image](https://user-images.githubusercontent.com/1262548/116791503-12720280-aabb-11eb-8256-c004b715424b.png)

**Comment by pszafer** [comment]
I will work on fix this

**Comment by doudz** [comment]
Here is my fix :

```
def isBase64(sb):
    try:
        if isinstance(sb, str):
            # If there's any unicode here, an exception will be thrown and the function will return false
            sb_bytes = bytes(sb, 'ascii')
        elif isinstance(sb, bytes):
            sb_bytes = sb
        else:
            raise ValueError("Argument must be string or bytes")
        return base64.b64encode(base64.b64decode(sb_bytes)) == sb_bytes
    except Exception:
        return False
                
def check_base64(s):
    if not isBase64(s):
        return s
    try:
        return base64.b64decode(s).decode("utf-8")
    except Exception:
        return s
```

**Comment by pszafer** [comment]
do you use last version of component? I rechecked and I fixed it already before.
I unbase64 only `value` key:
```
        object_type = dct.get(TYPE, None)
        if object_type and VALUE in dct:
            if object_type == STRING_VALUE:
                dct[VALUE] = check_base64(dct[VALUE])
            elif object_type == FLOAT_VALUE:
                dct[VALUE] = float(dct[VALUE])
        return dct
```

**Comment by doudz** [comment]
Yes, you're right, my fault, I was stuck with 0.12.1dev2 now it works good with 0.12.1dev8
