### ISSUE TITLE
Configure Bosch CT200 in HA

### ISSUE THREAD

**Issue by M4v3r1cK87** [bosch-thermostat/home-assistant-bosch-custom-component#76]
Hello,
I've installed your repository into my HA HACS integrations.

When I try to install the integration, HA ask me the Serial Number of Device, the Access Token and the Password.

I think know how to recover the serial number, but the Password and Access Token? 

The password is refered to the bosch profile used to register the termostat, or is the password used to create the Bosch Developer Portal?
The Access Token is the bearer token released when I register the termostat into the Bosch Developer Portal?

Thank you very much

Best Regards,
Valerio

**Comment by pszafer** [comment]
1. For now only beta version works ok with CT200, so need to install it.
2. Then choose device type Easycontrol.
3. Here is info how to configure - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Integrations-config

**Comment by M4v3r1cK87** [comment]
Yeah... it's working...

Thank you so much, very very thanks for all the developer group.

Best Regards,
Valerio

**Comment by Parogers90** [comment]
> 1. For now only beta version works ok with CT200, so need to install it.
> 
>     2. Then choose device type Easycontrol.
> 
>     3. Here is info how to configure - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Integrations-config

Link does not work.

**Comment by Moxy113** [comment]
Dear all,

For me the link also does not work. Does anybody have additional information?
