### ISSUE TITLE
KM200 CAN Sensor and DHW not received data after upgrade to 0.12.2

### ISSUE THREAD

**Issue by probecar** [bosch-thermostat/home-assistant-bosch-custom-component#78]
Hello,

I have Buderus KM200 v2 with CAN setup.

After upgrade to 0.12.2 version stop working sensors, HC and DWH.

In logs:
`
Logger: homeassistant.core
Source: core.py:1370
First occurred: 6:07:00 PM (1 occurrences)
Last logged: 6:07:00 PM

Unable to remove unknown service bosch/update_thermostat
`

The old version of your component not working for me since HA 6.0 version and last core.

**Version**
  - HA OS 6.0, core-2021.6.4, supervisor-2021.06.0 
  - HA Bosch component version?
  - Python 3.8.9

Thank you.
![1111](https://user-images.githubusercontent.com/57137520/121812979-bfbb6700-cc72-11eb-8584-4029cba632ad.png)
![2222](https://user-images.githubusercontent.com/57137520/121813007-df528f80-cc72-11eb-9e6f-d0d38b868c69.png)
![3333](https://user-images.githubusercontent.com/57137520/121813089-3bb5af00-cc73-11eb-8144-9535a901cfdd.png)

**Comment by pszafer** [comment]
Provide logs, there is nothing here which helps find the problem

**Comment by probecar** [comment]
I found workaround for this case. To install old version of your component on new HA, need to change manifest file.
I will try to install 0.12.2 and provide logs.

**Comment by JakobTewes** [comment]
Same problem here. Please see log attached[
[bosch_scan.json.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6724748/bosch_scan.json.txt)
](url)

**Comment by pszafer** [comment]
there are no logs here, only bosch scan attached

**Comment by JakobTewes** [comment]
eh...sorry. how can i extract?

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#debugging
find some logs

**Comment by JakobTewes** [comment]
kay. activated debug logging. 
[home-assistant.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6725624/home-assistant.log)

**Comment by pszafer** [comment]
did you enable debug logs for lib as well? `bosch_thermostat_client: debug `? there is no logs of parsing message from your device

**Comment by JakobTewes** [comment]
had those two active
`custom_components.bosch: debug`
`bosch_thermostat_http: debug`
activating the named now
`bosch_thermostat_client: debug`

**Comment by JakobTewes** [comment]
not that much more, i guess
[home-assistant.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6726538/home-assistant.log)

**Comment by JakobTewes** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/22556179/123652640-c1695b00-d82c-11eb-999d-fbba8ffc58c2.png">

**Comment by pszafer** [comment]
this is not error from this component

**Comment by JakobTewes** [comment]
sry. was homeconnect.

**Comment by JakobTewes** [comment]
maybe condition comes up because of the units recently switched to summer mode?

**Comment by pszafer** [comment]
I found reason for that, tomorrow I will try to fix it.

**Comment by JakobTewes** [comment]
Praise, praise, praise! You're great, @pszafer!

Another big thanks in advance :-)

Jakob

**Comment by pszafer** [comment]
@JakobTewes can you check if this fixes your issue - https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.12.3

**Comment by probecar** [comment]
I will check and let you know. Thank you.

**Comment by JakobTewes** [comment]
@pszafer, was on a business trip this days - sorry. tried and worked like a champ! 

Thank you so much

Jakob
