### ISSUE TITLE
IVT Geo 500 sensors unavailable

### ISSUE THREAD

**Issue by vdg1** [bosch-thermostat/home-assistant-bosch-custom-component#79]
**Describe the bug**
Hi,
I recently installed an IVT Geo500 heat pump and now I want to integrate it into Home Assistant. I have added the integration and that worked without problems. The unit is detected, however only a little number of the entities is actually available.

**To Reproduce**
Install integration and configure IVT account data using XMPP.

**Expected behavior**
Following entities are available:
- Charge switch
- dhw1
- hc1

Unavailable entities (which are expected to be available):
- all sensors, e.g. outdoor_temperature, return_temp, switch_temp, ...

**Screenshots**
![image](https://user-images.githubusercontent.com/2090293/124188074-0d333300-dabf-11eb-9ba0-75d77b1478a6.png)

**Version**
  - HA version: 2021.6.0
  - HA Bosch component version: 0.12.2
  - Python Bosch HTTP client version? Where do I find that?

** Debug SCAN **
[debug scan](https://jsonblob.com/cd758e32-daae-11eb-b281-a1b2e1bf3bf7)

[home-assistant.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6750738/home-assistant.log)

**Comment by deric** [comment]
@vdg1 Many sensors are disabled by default. It would be nice to have some preset for device type, like *Heat pump*, *Remote controller*, etc.

Just go to *Sensors*, click on *Enable entity* and confirm by hitting *Update*
![Screenshot_20210702_100313](https://user-images.githubusercontent.com/138573/124242148-b9573700-db1c-11eb-9d39-74415817235a.png)

Depending on your installation you should be able to see temperatures, modulation, etc.

**Comment by pszafer** [comment]
Upgrade component to latest version 0.12.3 (just published) as I fixed some issue with loading entities if charge switch was unavailable for some reason.
As @deric said if you want sensor to be fetched just enable it, most are disabled by default so you enable only those you need and integration won't hang your device

**Comment by vdg1** [comment]
Thanks @pszafer , @deric - that did the trick!
Do you have any information/experience how many sensors I can enable until my heat pump explodes?

**Comment by deric** [comment]
@vdg1 Feel free to enable all of them, but depending on your setup (solar panels, pool, secondary heating circuit) some data won't be available and home assistant will either return unknown value or throw errors into logs.

**Comment by vdg1** [comment]
@deric ok, thanks.

**Comment by pszafer** [comment]
@vdg1 it won't explode :)
for some users enabling more than 10 sensors caused device disconnection for hour or two.
That's the reason I don't enable all sensors by default.
