### ISSUE TITLE
Enable long-term statistics to integrate into new Homeassistant energy monitoring

### ISSUE THREAD

**Issue by philippreissing** [bosch-thermostat/home-assistant-bosch-custom-component#84]
Hi,

Home assistant recently introduced energy management capabilities (https://www.home-assistant.io/docs/energy). Would be great to be able to monitor the consumption of my heat pump in there, but the sensor doesn't show up in the panel. 

Apparently the integration needs to support these long-term statistics for the sensors in order to integrate into the energy monitoring:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Is that something that you are considering? Personally, I would need it for the "recording_rconsumedenergy" sensor, but I guess it would also make sense for other sensors.

Thanks,
Philip

**Comment by pszafer** [comment]
Yes, I want to add as much statistic as possible. Gas and electric if possible, but I'm struggling with reinterpreting this sensor data.
Maybe you can help me. This is what I have in RC300:
![20210828_193452](https://user-images.githubusercontent.com/690510/131226484-b4885b7e-3063-4b33-9ca4-12714603c74d.jpg)

It shows thas heater used 22kWh in last 24h.
I want to find it in recording data but can't get such sum in the end...
For temperature I see that algorithm is working.
My data: http://jsonblob.com/881234108333858816

Maybe you can try to check if algorithm for recording sensor for energy is working good for you.

**Comment by philippreissing** [comment]
I‘m not able to find daily energy consumption directly on the control panel of the heat pump. It only shows me the consumption since beginning. 

However, I’m able to reconcile the sensor data in HA with the Bosch app (yellow line is total consumption). 
![819511EC-6C72-41AC-A3FD-D4C36400B4A9](https://user-images.githubusercontent.com/69255136/131228433-d8eea9b1-507d-4504-92b0-530b484046ed.png)
![F81C200A-E93A-4B88-A1EC-99DB9B0CB2A8](https://user-images.githubusercontent.com/69255136/131228435-63e25c65-013f-448e-9e46-5803421eb74d.png)

Total daily consumption should then be 3 kWh. However, this will be inaccurate to a certain extent, because it only seems to record full kWh per hour. 
Not sure if we can maybe get better data with the daily recording sensor. With that I’m at least able to see fractions of kWh in the app. 
![1D43AE2C-D696-4B7B-B114-A0044807052D](https://user-images.githubusercontent.com/69255136/131228502-d375d88e-3239-4332-8893-ee3f684b285b.png)

**Comment by philippreissing** [comment]
If someone has a similar requirement, I was able to convert the recording sensor into a proper measurement for HA energy monitoring using the following configuration in home assistant configuration.yaml:
```
sensor:
  - platform: integration
    source: sensor.recording_rconsumedenergy
    name: _heizung_energy_int2_
    round: 2
    method: left
    unit: kWh
```

It uses the [Riemann sum integration](https://www.home-assistant.io/integrations/integration/) to sum the hourly measurements of kWh.
This is the recording sensor (sensor.recording_rconsumedenergy)
![image](https://user-images.githubusercontent.com/69255136/132203046-0747f8bb-56fe-4447-bd07-8d5dc8c6c52d.png)
The problem with it is that it has hourly consumption and it not steadily increasing. In the example above, it consumed 2 kWhs for 1 hour and then another 4 kWh for 1 hour. In total that would be 6.
The integration does just that calculation:
![image](https://user-images.githubusercontent.com/69255136/132203348-0e3c1e66-8226-48e0-ba77-c986631755dd.png)
You can see that the sensor here increased first by 2 kWh and then by another 4.

Would still be great to have a sensor like this in the standard integration if possible.

**Comment by pszafer** [comment]
Can you attach your current bosch scan and info what installation do you have? electrical heat pump or gas?
0.14 is pre-released and there recording sensors will be working in different way.

**Comment by philippreissing** [comment]
I've attached my scan. I'm using an eletrical heat pump, a Bosch Compress 7400i.
How will the sensors change in 0.14?
[bosch_scan.json (2).txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7115864/bosch_scan.json.2.txt)

**Comment by pszafer** [comment]
ok, so that is the reason why you have data in this uri :)
I've rewritten it almost from scratch... so I'm trying to describe it here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Recording-sensors---Energy-history

I update data for compress every hour HH:05, I put last_reset attribute at HH-1:00. And gather data exactly from this hour, so it should visible better on graphs (if last_reset attribute is working properly).
Now I'm trying to recognize if device is gas or electrical so for electrical it'd be easy just add device type `DEVICE_CLASS_ENERGY`, for gas I'd need to convert kWh -> m³ to get something visible in HA.

**Comment by philippreissing** [comment]
I think the last_reset attribute was removed again in the last release of HA (https://github.com/home-assistant/core/pull/54755) and they have added the total_increasing state_class, which handles resetting automatically.
You can see the details here: https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-total_increasing

I think to support energy monitoring, I think it would be easiest if you just summed up the recording values continuously. Maybe in a new sensor value for backwards-compatibility. Home assistant will then handle calculating the daily/monthly differences to show it correctly in the energy monitoring.
This is basically what I'm doing now with the additional integration sensor.

**Comment by pszafer** [comment]
I know. `last_reset` attribute might come back to HA, but in little different way. Most integration used `last_reset` wrong and that's why it was removed.

I tried to put sum data into HA and it wasn't working for me, at least in the summer time (so we are using gas only for water heating).
There are many problems:
- what if HA is off for more than 1 hour,
- how to handle sensors for users for whom energy statistics are updated once a day, HA wants update `total_increasing` sensor every hour,

I see that `last_reset` is still used https://github.com/home-assistant/core/blob/b99a22cd4d6660b1f7dd6c1d5bf2d80311c448f5/homeassistant/components/sensor/recorder.py#L403-L406 and I'm trying to put data into it, but it's not working very well for me.

**Comment by philippreissing** [comment]
> what if HA is off for more than 1 hour,
Yeah, then that data would be lost, but I'm not sure if that is really a huge problem. Then one day would be distorted in statistics, but sensor-wise you could even start from 0 again if I understand the [manual ](https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-total_increasing) correctly.

> how to handle sensors for users for whom energy statistics are updated once a day, HA wants update total_increasing sensor every hour,
I think in this case you just leave it at a static value, i.e. you keep it constant throughout the day.
