### ISSUE TITLE
Wrong unit of heating_energy_consumption

### ISSUE THREAD

**Issue by fuslwusl** [bosch-thermostat/home-assistant-bosch-custom-component#86]
The value of sensor.heating_energy_consumption is delivered as 28.128.234,0 kWh but the correct value seems to be 28.128.234,0 Wh because I don't have a powerplant :)

It would be great to get the value as 28.128,2 kWh.

Here is my debug_scan:
https://jsonblob.com/883296294244990976

**Comment by pszafer** [comment]
I'm trying to investigate this sensor whole week and I can't.
In my place I have more logical value:
```
{
    "id": "/heatSources/energyMonitoring/consumption",
    "maxValue": 135780000.0,
    "minValue": 0.0,
    "recordable": 0,
    "type": "floatValue",
    "unitOfMeasure": "kWh",
    "value": 20052.7,
    "writeable": 1
}
```

anyway I wanted to convert this value to m³ so it can be added to Energy dashboard,
but values are inconsistent across different users.
In Nefit app correction factor value is `0,12307692`

**Comment by pszafer** [comment]
During this weekend I made measurements for KM200, comparing with physical gas meter.
```
{
    "id": "/heatSources/energyMonitoring/correctionFactor",
    "maxValue": 1.3,
    "minValue": 0.7,
    "recordable": 0,
    "type": "floatValue",
    "unitOfMeasure": " ",
    "value": 0.8,
    "writeable": 1
}
```
During this weekend I used `2,87m³`. It showed as `2,2 kWh` in Buderus heater.
So it looks like for me that `1m³ = 0,77kWh`.
Anyway in the end I don't understand why your usage is so high.
Can you look at Used Energy in RC300 what is it showing for you?

**Comment by fuslwusl** [comment]
RC300 does not have any menu item for energy statistics - only RC310 does.

**Comment by pszafer** [comment]
In this case I'd use template sensor and customize to have proper value, but it's worth checking if this sensor is accurate for you.
In your scan I see some values which I might be wrong. Do you have hot water set to 75C?

**Comment by fuslwusl** [comment]
The Buderus App shows a total gas consumption of about 8533 kWh for the complete year 2021.
On 3rd sept. solar yield was 17,9 kWh.

**Comment by fuslwusl** [comment]
the hotwater temp in the 1000 l buffer tank is 75C and will be mixed down to 60C. Setting is 50C for hotwater in RC300.

**Comment by fuslwusl** [comment]
You can close this issue if the info i provided does not help finding a solution.

**Comment by pszafer** [comment]
Closing. Maybe we can figure it out in the future, why for some people values are too high.
