### ISSUE TITLE
Home Assistant Energy Management Gas Consumption

### ISSUE THREAD

**Issue by Rasenkantenstein** [bosch-thermostat/home-assistant-bosch-custom-component#88]
Since 2021.9 there's a new feature in Home Assistant (Gas Consumption config for energy management):
<img width="330" alt="image" src="https://user-images.githubusercontent.com/6643712/134815016-546ed4ef-1f54-4c28-b168-cf13b47a2bc7.png">
On a glance a user can now see all entities using energy and thus be able to calculate usage and approximate the cost.

I would like to add my Buderus device (which is integrated in this wonderful component). 
However, by default the gas consumption is not showing up in the configuration:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/6643712/134815092-8360b333-cd06-4b7a-aeda-16b3247c70cb.png">

Was someone already able to set it up? Is there maybe a way to publish a little guide in the wiki?

**Comment by pszafer** [comment]
What device do you have?
Attach Bosch scan so I can see your setup.
For KM200 energy consumption is given in kWh and I don't know how to calculate kWh to m3 so it will be visible in gas usage. For me I have template sensor which multiplies kWh x0.77 and returns m3 because this is correction factor for me.

For CT200 I have no idea what is unit which is returned im history entries. It might be m3 or kWh but somebody with device would need to find out it.

**Comment by Rasenkantenstein** [comment]
[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7231921/bosch_scan.json.zip)

**Comment by Rasenkantenstein** [comment]
OK, so the energy management needs a sensor with a measurement in m3. 
Something like this. Doesn't work though.
`
template:
  - sensor:
      - name: "Gas consumption"
        unique_id: "gas_consumption"
        device_class: "gas"
        unit_of_measurement: "m³"
        state: >
          {% set kwh = states('sensor.energy_consumption') | float %}
          {% set z_value = 0.9645 | float %}
          {% set heating_value = 11.3040 | float %}

          {{ ( kwh/(z_value*heating_value) ) | round(1) }}
`

However, it produces the correct value:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/6643712/134819675-cb593160-0d22-4f4c-aa13-f95bd622b6b0.png">

**Comment by pszafer** [comment]
you need `state_class: total_measurement`

**Comment by Rasenkantenstein** [comment]
@pszafer Thank you! I am able to display the value in Home Assistant Energy Management now. 
However, the value is much too high. 

The  sensor.energy_consumption captured more than 1000kWh per day:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/6643712/134937024-aab8618d-f663-4e2e-8996-60e17a659a1f.png">
This is far too much. According to the Buderus App the correct value would be 12.6kWh. I feel I capture the wrong sensor.
I suppose the sensor.actual_power is fitting better. Can I also use this for the template?

**Comment by pszafer** [comment]
Somebody already had similar problem, maybe try:
`{{ ( (kwh*0.01)/(z_value*heating_value) ) | round(1) }}`

**Comment by Rasenkantenstein** [comment]
Ok, I think I was able to get meaningful results:
Like described [here](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/84) I was able to get the Integral working:
```
- platform: integration
  source: sensor.recording_ractualpower
  method: left
  unit: kWh
  name: energy_spent
  round: 2
```
with this in place I was able to set up a sensor to measure the cubic meters required for the new Energy Management Dashboard:

```
template:
  - sensor:
      - name: "Gas consumption"
        unique_id: "gas_consumption"
        device_class: "gas"
        state_class: "total_increasing"
        unit_of_measurement: "m³"
        state: >
          {% set kwh = states('sensor.energy_spent') | float %}
          {% set condition_value = 0.9645 | float %}
          {% set calorific_value = 11.3040 | float %}

          {{ ( kwh/(condition_value * calorific_value) ) | round(1) }}
```

Maybe this could work out of the box with this integration? The condition value and the calorific value are printed on my gas invoice here in Germany. How about other countries? Could this be a configuration parameter for the component?

**Comment by pszafer** [comment]
That's very interesting, but can you check in longer period if those value are valid. What is condition value?
I have only calorific value, but as I tried to implement it it does not make any sense...
In my region we got most gas from Russia and some from other sources, not sure really, but in the end calorific_value can change from month to month. I asked users from southern Poland and they had different calorific value every month!
Similar situation is in Sweden as I was informed.

I doubt that Bosch/Buderus knows what is your `calorific_value` and I think module is calculating it already from m³ to kWh and correction factor is this:
```
{
            "id": "/heatSources/energyMonitoring/correctionFactor",
            "type": "floatValue",
            "writeable": 1,
            "recordable": 0,
            "value": 1.0,
            "unitOfMeasure": " ",
            "minValue": 0.7,
            "maxValue": 1.3
        },
```

**Comment by Rasenkantenstein** [comment]
I'll check over the long run. Bosch/Buderus don't know the calorific value of course. Our local gas supplier knows. An average of this value is calculated and displayed on the invoice: 
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/6643712/135752078-24ee53da-7442-4083-b0f7-9e1ebb0b6dc9.png">

It also changes over time. Z-Zahl is the equal of the condition value. And Brennwert is the calorific value. The condition value seems to be a German thing (https://de.wikipedia.org/wiki/Zustandszahl) as wikipedia doesn't provide information in any other language.

**Comment by pszafer** [comment]
I'm pretty sure that you can't take any values from your gas bill, `Gas Company kWh != Buderus kWh`

**Comment by markunca** [comment]
> Ok, I think I was able to get meaningful results: Like described [here](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/84) I was able to get the Integral working:
> 
> ```
> - platform: integration
>   source: sensor.recording_ractualpower
>   method: left
>   unit: kWh
>   name: energy_spent
>   round: 2
> ```
> 
> with this in place I was able to set up a sensor to measure the cubic meters required for the new Energy Management Dashboard:
> 
> ```
> template:
>   - sensor:
>       - name: "Gas consumption"
>         unique_id: "gas_consumption"
>         device_class: "gas"
>         state_class: "total_increasing"
>         unit_of_measurement: "m³"
>         state: >
>           {% set kwh = states('sensor.energy_spent') | float %}
>           {% set condition_value = 0.9645 | float %}
>           {% set calorific_value = 11.3040 | float %}
> 
>           {{ ( kwh/(condition_value * calorific_value) ) | round(1) }}
> ```
> 
> Maybe this could work out of the box with this integration? The condition value and the calorific value are printed on my gas invoice here in Germany. How about other countries? Could this be a configuration parameter for the component?

Which sensor for energy_spent you actually using? In my CT200 integration I see only sensor.energy_central_heating, sensor.energy_hot_water, sensor.energy_temperature

**Comment by pszafer** [comment]
@markunca @Rasenkantenstein has KM200 gateway so different device and different sensors.
For CT200 I don't have yet ideal solution. Those sensors are one day shifted as CT200 only gives data from one day before.

**Comment by markunca** [comment]
If there is no sensor with actual consumption, does it make sense to still use one day old data and then change these selected data by cron in statistic database to have there data at least for long term monitoring?

**Comment by pszafer** [comment]
There is new API available which seems to be almost perfect for this usage https://github.com/home-assistant/core/pull/56607
but I can't figure it out yet, how to put those stats propely.
