### ISSUE TITLE
Turn on/off the heating

### ISSUE THREAD

**Issue by Ekkib** [bosch-thermostat/home-assistant-bosch-custom-component#91]
I have a Buderus Logamax plus GB 172-24 K. It is controlled by an RC310 and a RC200. The burner controller is a BC25. The heating can be turned off/on directly at the BC25 controller. 

It would be very nice, if this switching could be done directly with the Home Assistant integration. 

Debugscan attached
[bosch_scan.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7250249/bosch_scan.json.zip)
.

**Comment by pszafer** [comment]
can you make 2 scans, one when burner is `ON`, second when burner is `OFF`.
Currently I don't see any switch to toggle burner

**Comment by Ekkib** [comment]
Thanks for the good suggestion ! I attach the two files. Unfortunately only the timestamp and some temperatures seem to be different, when I compared them. It seems, the scan leaves out some variables of the burner controller BC25. The addresses of these devices are listed in the Bosch scan.  "id": "/system/info", "type": "systeminfo", ... . The system consists of BC25, RC310, RC200, KM200, 2 times MM100.
The two scans :

[bosch_scan_heating_off_2021_10_03.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7274252/bosch_scan_heating_off_2021_10_03.json.zip)

[bosch_scan_heating_on_2021_10_03.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7274253/bosch_scan_heating_on_2021_10_03.json.zip)

**Comment by pszafer** [comment]
Yes, `/system/info` is just information what is connected to bus. I don't think so you can turn off burner from this API.

**Comment by Ekkib** [comment]
So I need to better understand, how I can get access to BC25 to turn off the burner. In the meantime I will find other ways to reach my goals. 

Please leave this topic open, in case it is of interest for others. Or somebody already knows, how to access the on/off of the BC25, ;-) .
