### ISSUE TITLE
Install IVT Vent 202

### ISSUE THREAD

**Issue by schononas** [bosch-thermostat/home-assistant-bosch-custom-component#93]
**Describe the bug**
I'm trying to install a IVT Vent 202 which I have installed a IP-module in. But there is a problem when Im installing it in HA.

**To Reproduce**
Install integration and configure IVT account data using XMPP. (tried HTTP as well)

**Expected behavior**
The installation to go thru without error. 

**Screenshots**

![image](https://user-images.githubusercontent.com/23654695/135620414-424989bc-963c-4337-a223-a241709eac92.png)

![image](https://user-images.githubusercontent.com/23654695/135620540-dec415b6-8941-4c15-85e7-e72b50e08129.png)

**Version**
  - HA version 2021.9.7
  - HA Bosch component version v0.15.1
  - Python Bosch HTTP client version?

** Debug SCAN **
http://jsonblob.com/893474473148432384

**Additional context**
Log when I did the Debug scan
![image](https://user-images.githubusercontent.com/23654695/135619631-82dace9b-9f4d-47c0-b19b-d909e60ea863.png)

**HA Log message**

This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:246
Integration: Bosch thermostat (documentation, issues)
First occurred: 14:22:48 (1 occurrences)
Last logged: 14:22:48

Cannot connect to Bosch gateway, host 855362261 with UUID: None

This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:244
Integration: Bosch thermostat (documentation, issues)
First occurred: 14:22:48 (1 occurrences)
Last logged: 14:22:48

Your device is unknown null

Logger: bosch_thermostat_client.gateway.ivt_gateway
Source: /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/ivt_gateway.py:98
First occurred: 14:22:47 (2 occurrences)
Last logged: 14:22:48

I cannot find supported device. Your devices: null

**Comment by pszafer** [comment]
scan is empty. What IP module do you have? What app do you use to control it?

**Comment by schononas** [comment]
I'm using this IP-module https://jsenergi.com/koppla-upp-din-varmepump/ivt-franluftsvarmepump/ip-modul-rego-2000-ivt-geo-ivt-vent.html

And the app that I'm using is IVT Anywhere.

**Comment by pszafer** [comment]
I think this one uses different protocol. Maybe you are able to sniff to what server module is connecting and if it uses xmpp as protocol (port 5222).

**Comment by schononas** [comment]
Haven't done it before but I'll give it a try. Are you using Wireshark when sniffing?

**Comment by schononas** [comment]
Have bout an EMS gateway because I couldn't connect to the gateway
