### ISSUE TITLE
Additional information on IVT

### ISSUE THREAD

**Issue by prj** [bosch-thermostat/home-assistant-bosch-custom-component#99]
Hello,

I reversed the EasyRemote app and there's a whole additional root path that is not used in the component right now. In case of my pump it shows a lot of useful data.
```
{
    "id": "/systemStates",
    "references": [
        {
            "id": "/systemStates/compressor",
            "uri": "http://192.168.1.45/systemStates/compressor"
        },
        {
            "id": "/systemStates/additionalHeater",
            "uri": "http://192.168.1.45/systemStates/additionalHeater"
        },
        {
            "id": "/systemStates/summaryAlarm",
            "uri": "http://192.168.1.45/systemStates/summaryAlarm"
        },
        {
            "id": "/systemStates/CompressorMotorProtection",
            "uri": "http://192.168.1.45/systemStates/CompressorMotorProtection"
        },
        {
            "id": "/systemStates/ColdCarrierPumpMotorProtection",
            "uri": "http://192.168.1.45/systemStates/ColdCarrierPumpMotorProtection"
        },
        {
            "id": "/systemStates/alarmPowerSupply",
            "uri": "http://192.168.1.45/systemStates/alarmPowerSupply"
        },
        {
            "id": "/systemStates/lowPressureState",
            "uri": "http://192.168.1.45/systemStates/lowPressureState"
        },
        {
            "id": "/systemStates/highPressureState",
            "uri": "http://192.168.1.45/systemStates/highPressureState"
        }
    ],
    "type": "refEnum"
}
```

There's also "/application".

I modified the __init__.py file in const folder, added these two into ROOTS, and ran the scan, but this did not add them to the scan.
Probably I am missing something...

**Comment by prj** [comment]
Tried creating a custom json db file, but that does not seem to work either. I can't even figure out from where the entities get populated, guess will need to wait for some input from your side.

**Comment by prj** [comment]
So many bugs :(

I adjusted the custom_initialize functionality so that it actually checks for the custom db. This was before nested into if's so that this would never happen.

Now I get this error:
```
2021-10-17 22:13:21 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry iCom_low_CAN_v1 CAN for bosch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/bosch/__init__.py", line 124, in async_setup_entry
return await gateway_entry.async_init()
File "/config/custom_components/bosch/__init__.py", line 206, in async_init
if await self.async_init_bosch():
File "/config/custom_components/bosch/__init__.py", line 271, in async_init_bosch
self.gateway.custom_initialize(custom_db)
File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 96, in custom_initialize
initial_db = get_initial_db()
TypeError: get_initial_db() missing 1 required positional argument: 'device_type'
```

This is because of a bug here in thhermostat client:
```
    def custom_initialize(self, extra_db):
        "Custom initialization of component"
        if self._firmware_version:
            self._db = get_custom_db(self._firmware_version, extra_db)
            initial_db = get_initial_db()
            initial_db.pop(MODELS, None)
            self._db.update(initial_db)
            self._initialized = True
```
You are supposed to call get_initial_db() with device type as argument apparently.

I learned enough that I can hack the main module in the home assistant through the terminal, but I have no idea what to do with the dependency or where it is stored... Or how to even get into some kind of development mode.

Otherwise I could test this and submit a PR.

**Comment by pszafer** [comment]
I abandoned idea of `custom_initialize` while ago... My idea was that anybody could add their device info and work on it. Eventually it was a nightmare, because there are too many depends in Bosch devices. Eg If you have DHW in follow ch mode, then if you change mode in HC, you are switching mode in DHW and user'd need to understand those processes to create proper db.

In 0.16.1 I added those URI's you are talking about so you can scan it.

**Comment by pszafer** [comment]
About development. It'd be great if you can contribute!
This is wiki I created https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Dev-environment-setup and https://developers.home-assistant.io/docs/api_lib_index/#trying-your-library-inside-home-assistant
For simple things I use my simulator https://github.com/bosch-thermostat/bosch_thermostat_http_simulator so I can test it on different devices

**Comment by prj** [comment]
So, even running a scan:
```
Download json file and attach it somewhere. The json file is stored under /www/bosch_scan.json. Please make sure the www folder exists prior to running the scan
```
What is "/www". Should it be typed into a browser? Should it be in the file system root? It certainly is not in the file system root and in the browser it gives a 404.

I'll check out the git and run it manually from my PC, but the instructions could really be at least a little bit clear.

**Comment by prj** [comment]
[rawscan_757210046.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7360888/rawscan_757210046.zip)

Here's the rawscan. None of the new paths are there, as I expected, because I did the same modification to roots as you and it did absolutely nothing. If I set it to debug mode it does not print anything useful.
Here's manual query of the relevant two entries for at least systemStates. These should be added to 010701.json, I guess I will figure out how to do that...

```
{
    "id": "/systemStates",
    "references": [
        {
            "id": "/systemStates/compressor",
            "uri": "http://192.168.1.45/systemStates/compressor"
        },
        {
            "id": "/systemStates/additionalHeater",
            "uri": "http://192.168.1.45/systemStates/additionalHeater"
        },
        {
            "id": "/systemStates/summaryAlarm",
            "uri": "http://192.168.1.45/systemStates/summaryAlarm"
        },
        {
            "id": "/systemStates/CompressorMotorProtection",
            "uri": "http://192.168.1.45/systemStates/CompressorMotorProtection"
        },
        {
            "id": "/systemStates/ColdCarrierPumpMotorProtection",
            "uri": "http://192.168.1.45/systemStates/ColdCarrierPumpMotorProtection"
        },
        {
            "id": "/systemStates/alarmPowerSupply",
            "uri": "http://192.168.1.45/systemStates/alarmPowerSupply"
        },
        {
            "id": "/systemStates/lowPressureState",
            "uri": "http://192.168.1.45/systemStates/lowPressureState"
        },
        {
            "id": "/systemStates/highPressureState",
            "uri": "http://192.168.1.45/systemStates/highPressureState"
        }
    ],
    "type": "refEnum"
}
```

Compressor:
```
{
    "allowedValues": [
        "ON",
        "OFF"
    ],
    "id": "/systemStates/compressor",
    "recordable": 0,
    "type": "stringValue",
    "value": "ON",
    "writeable": 0
}
```

```
{
    "id": "/systemStates/additionalHeater",
    "recordable": 0,
    "type": "floatValue",
    "unitOfMeasure": "%",
    "value": 0,
    "writeable": 0
}
```

**Comment by pszafer** [comment]
Don't try to do development in Docker or your stable HA instance. Install it on your PC and then run lib locally.
It's easier and faster.

Scan you sent is not made by 0.16.1 version of lib. In 0.16.1 if something is not visible then I print:
```
{
        "/systemStates": "not found"
},
```

**Comment by prj** [comment]
Editing the sensors like this could be useful in the db I think?
```
    "sensors": {
        "outdoor_t1": {
            "id": "/system/sensors/outdoorTemperatures/t1",
            "name": "Outdoor temperature"
        },
        "compressor": {
            "id": "/systemStates/compressor",
            "name": "Compressor"
        },
        "additional_heater": {
            "id": "/systemStates/additionalHeater",
            "name": "Additional heater"
        }
    }
```

Also maybe the extradhw could be explored a little. If it is possible to not only read but actually enable it for X hours, that would be pretty useful. One could write a script that monitors the current electricity price and if it is lower than a pre-set amount during night, one could activate the extradhw for that duration, so you pre-heat the water for morning to 65C for "free".

**Comment by pszafer** [comment]
I can add those sensor for you.
for turning on/off based on electricity is pretty simple. you can create template sensor with price of electricity and automation based on low price.

**Comment by pszafer** [comment]
ok, I will try to add it tomorrow.

about REST sensor, I'd use Node Red for this purpose. It can be made with simple javascript in a few steps and put into HA. In HA you'd need REST sensor and template sensor to extract proper key from json you fetched and you're limited in REST to 255 chars.

**Comment by prj** [comment]
I need to enable them separately as number.charge_duration and number.stop_temp.
I removed and re-added the device and now they showed up, or maybe they were showing before but the "number" threw me off.
